# Supplemental Reading {.unnumbered}

## Chapter 1: Employment as a Socio-Legal Relationship

## Chapter 2: Labor Organizing & Concerted Activity

- Brandon Magner, [Whither the Wagner Act: On the Waning View of Labor Law and Leviathan](https://scholarship.kentlaw.iit.edu/erepj/vol27/iss1/1/), 27 Employee Rights & Employment Policy Journal 1 (2024)

## Chapter 3: Establishing an Employment Relationship

## Chapter 4: Scope & Limits of Employer Control

### EEO Laws

- Keith Cunningham-Parmeter, [Discrimination by Algorithm: Employer Accountability for Biased Customer Reviews](https://www.uclalawreview.org/discrimination-by-algorithm-employer-accountability-for-biased-customer-reviews/), 20 UCLA Law Review 92 (2023)

- Robert Belton, [How Griggs Came to Be](https://muse.jhu.edu/article/875392/pdf), Journal of Supreme Court History (2014)

### Employee Speech and Political Activity

- [Most Doxxing Campaigns Only Last a Few Days. But the Effects Can be Felt for Months](https://www.npr.org/2024/04/11/1231084790/israel-kidnapped-posters-tore-down-doxxed), NPR Morning Edition (April 11, 2024).

- Charlotte Garden, [Was it Something I Said? Legal Protections for Employee Speech](https://www.epi.org/unequalpower/publications/free-speech-in-the-workplace/), Economic Policy Institute (May 2022)

- Alexander Hertel-Fernandez, [How Employers Recruits Their Workers into Politics--And Why Political Scientists Should Care](https://www.cambridge.org/core/journals/perspectives-on-politics/article/how-employers-recruit-their-workers-into-politicsand-why-political-scientists-should-care/778AD469C15C4100DB0C29DB8C858C4B), Perspectives on Politics (2016)

## Chapter 5: Confidentiality & Loyalty

### Noncompete Agreements 

- Alan B. Krueger & Eric A. Posner, [A Proposal for Protecting Low-Income Workers from Monopsony and Collusion](https://www.hamiltonproject.org/assets/files/protecting_low_income_workers_from_monopsony_collusion_krueger_posner_pp.pdf), The Hamilton Project (2018)

## Chapter 6: Wages & Hours

### Wage & Hour Enforcement 

[Employers Steal Billions from Workers' Paychecks Each Year](https://www.epi.org/publication/employers-steal-billions-from-workers-paychecks-each-year/), Economic Policy Institute (2017)

### Effect of Minimum Wage 

- [Most minimum wage studies have found little or no job loss](https://www.epi.org/blog/most-minimum-wage-studies-have-found-little-or-no-job-loss/), Economic Policy Institute (September 9, 2024)
- [How Increasing the Federal Minimum Wage Could Affect Employment and Family Income](https://www.cbo.gov/publication/55681), Congressional Budget Office (January 30, 2024)
- José Azar, et al, [Minimum Wage Employment Effects and Labor Market Concentration](https://www.restud.com/1511-2/), Review of Economic Studies (September 4, 2023)
- Jesse Wursten and Michael Reich, [Small Businesses and the Minimum Wage](https://irle.berkeley.edu/publications/working-papers/small-businesses-and-the-minimum-wage/), University of California, Berkeley, Institute for Research on Labor & Employment (March 7, 2023)

## Chapter 7: Employee Health & Safety

## Chapter 8: Terminating Employment

### Unemployment Compensation 

- Flannery O'Rourke, [Workers Denied: How to Diagnose and Prevent Improper Unemployment Insurance Denials](https://www.nelp.org/insights-research/workers-denied-how-to-diagnose-and-prevent-improper-unemployment-insurance-denials/), National Employment Law Project (July 2025)