# Sources {.unnumbered}

::: {.references}

## Cases

Adair v. United States, 208 US 161 (U.S. 1908)

Arku v. Wells Fargo Bank, Nat. Association, 621 F. Supp. 3d 602 (W.D.N.C. 2022)

Austin Maintenance v. Crowder Construction, 742 S.E.2d 535 (N.C. Ct. App. 2012)

Brunner v. Al Attar, 786 SW 2d 784 (Tex. App. 1990)

Cloutier v. Costco Wholesale Corp., 390 F. 3d 126 (1st Cir. 2004)

Coman v. Thomas Mfg. Co., Inc., 381 SE 2d 445 (Supreme Court 1989)

Commonwealth v. Hunt (Mass. 1842)

Commonwealth v. Pullis (Phila. 1806), 3 Doc. His. of Am. Ind. Soc. 59 (2d ed. Commons 1910)

Coppage v. Kansas, 236 US 1 (U.S. 1915)

Dalton v. Camp, 353 N.C. 647 (N.C. 2001)

Desai v. Charter Communications, LLC, 381 F. Supp. 3d 774 (W.D. Ky. 2019)

Duplex Printing Press Co. v. Deering, 254 US 443 (U.S. 1921)

Eastex, Inc. v. NLRB, 437 US 556 (U.S. 1978)

Ehling v. Monmouth-Ocean Hosp. Service Corp., 961 F. Supp. 2d 659 (D.N.J. 2013)

Food Lion, Inc. v. Capital Cities/ABC, Inc., 951 F. Supp. 1224 (M.D.N.C. 1996)

Food Lion, Inc. v. Capital Cities/ABC, Inc., 194 F.3d 505 (4th Circuit 1999)

Franklin v. Vertex Global Solutions, Inc., 20 Civ. 10495 (KPF) (S.D.N.Y. February 9, 2022)

Friel v. Angell Care Inc., 440 SE 2d 111 (N.C. App. 1994)

Haskins v. Royster, 70 N.C. 600 (N.C. 1874)

Hogan v. Forsyth Country Club Co., 340 SE 2d 116 (N.C. App. 1986)

Jespersen v. Harrah’s Operating Co., Inc., 444 F. 3d 1104 (9th Cir. 2006)

Johnson v. Nat’l Collegiate Athletic Ass’n, 108 F. 4th 163 (3rd Cir. 2024)

Johnson v. Nat’l Collegiate Athletic Ass’n, 561 F. Supp.3d 490 (E.D. Pa. 2021)

Kadlec Medical v. Lakeview Anesthesia Associates, 527 F. 3d 412 (5th Cir. 2008)

Karraker v. Rent-A-Center, Inc., 411 F. 3d 831 (7th Cir. 2005)

Keith v. Health-Pro Home Care Services, 873 SE 2d 567 (N.C. 2022)

K-Mart Corp. Store No. 7441 v. Trotti, 677 SW 2d 632 (Tex. App. 1984)

Lawlor v. Loewe, 235 US 522 (U.S. 1915)

Lemmerman v. A.T. Williams Oil Co., 350 SE 2d 83 (N.C. 1986)

Lochner v. New York, 198 US 45 (U.S. 1905)

Loewe v. Lawlor, 208 US 274 (U.S. 1908)

Mexican Radio Corp. v. NLRB, 789 Fed.Appx. 261 (2d Cir. 2019)

Miklin Enterprises, Inc. v. NLRB, 861 F3d 812 (8th Circuit 2016)

NLRB v. City Disposal Systems, Inc., 465 U.S. 822 (U.S. 1984)

NLRB v. Electrical Workers, 346 U.S. 464 (U.S. 1953)

NLRB v. Town & Country Elec., Inc., 516 U.S. 85 (U.S. 1995)

NLRB v. Washington Aluminum Co., 370 U.S. 9 (U.S. 1962)

People for Ethical Treatment of Animals v. North Carolina Farm Bureau Federation, 60 F.4th 815 (4th Cir. 2023)

Pham v. Aeva Specialty Pharmacy, Civil Action No. 21-cv-00703-NYW-STV (D. Colo. December 8, 2022)

Pollock v. Williams, 322 US 4 (U.S. 1944)

Razak v. Uber Technologies, Inc., 951 F. 3d 137 (3rd Cir. 2020)

Ries v. Mcdonald’s Usa, Llc, Case No. 1:20-cv-2 (W.D. Mich. December 6, 2021)

Rulon-Miller v. International Bus. Machines Corp., 162 Cal. App. 3d 241 (Cal. App. 1984)

San Diego Building Trades Council v. Garmon, 359 U.S. 236 (U.S. 1959)

Scudder v Woodbridge, 1 Ga. 195 (Georgia 1846)

Skagerberg v. Blandin Paper Co., 266 N.W. 872 (Minn. 1936)

Smith v. Manheim Remarketing, Inc., No. 5:19-CV-00086-KDB-DSC (W.D.N.C. November 26, 2019)

Starbucks Corp., Case 14--CA--295813 (NLRB Div. of Judges September 21, 2023)

State v. Wal-Mart Stores, 207 AD 2d 150 (N.Y. App. Div., 3rd Dept. 1995)

Stengart v. Loving Care Agency, 990 A. 2d 650 (N.J. 2010)

Stericycle, Inc., 04-CA-137660, 04-CA-145466, 04-CA-158277 04-CA-160621 (NLRB August 2, 2023)

The Boeing Company, 365 N.L.R.B. No. 154 (N.L.R.B. 2017)

Three D, LLC d/b/a Triple Play Sports Bar and Grille v. NLRB, 629 Fed. App’x 33 (2d Cir. 2015)

Triple Play Sports Bar & Grille, 361 N.L.R.B. No. 31 (N.L.R.B. 2014)

Truitt v. Salisbury Bank and Trust Co., 52 F. 4th 80 (2nd Cir. 2022)

## Statutes

### Federal

Clayton Antitrust Act, 15 U.S. Code § 17 (1914)

Sherman Antitrust Act, 15 U.S. Code § 1 (1890)

National Labor Relations Act, 29 U.S. Code § 151 et seq. (1935)

Norris-LaGuardia Act, 29 U.S. Code § 101 et seq. (1932)

### State

Discrimination Against the Engagement in Certain Activities, NY Labor Law § 201-d

Employer Use of Social Media, Cal. Labor Code § 980

Immunity from Civil Liability for Employers Disclosing Information, N.C.G.S. § 1-539.12

Lawful Use of Lawful Products, N.C.G.S. § 95-28.2

NC Property Protection Act, N.C. Gen. Stat. § 99A-2

Trapped at Work Act, NY Labor Law, Art. 37, §§ 1050 et seq

### Other 

Ordinance of Labourers, 23 Edw. 3 cc. 1-8 (1349)

Statute of Labourers, 25 Edw. 3 Stat. 1 (1351)

## Regulatory Materials

U.S. Dept. of Labor, Employee or Independent Contractor Classification Under the Fair Labor Standards Act, 89 FR § 1638 (Final Rule 2024)

## Books, Articles, & Other Publications

::: {#refs}

::



:::