# Syllabus {.unnumbered}

[{{< bi download >}}]({{< var syllabus-download >}} "Download Syllabus")

::: {.syllabus-header}

## {{< var subject >}} {.unnumbered}

{{< var institution >}}

{{< var term >}}

{{< var room >}}

{{< var meets >}}

[{{< var repo-name >}}]({{< var repo-url >}})

### Professor

{{< var author >}}

{{< var phone >}}

[{{< var email >}}](mailto:{{< var email >}})

Office hours: [[calendly.com/emfink]({{< var appointments >}})]{.mono-font-smaller}

:::

::: {.syllabus}

## Description {.unnumbered}

This course surveys federal and state laws governing employment, in both the individual and organized labor settings. Topics to be covered include establishing an employment relationship; recruitment & hiring; the scope and limits of supervisory control; confidentiality & competition; wages & hours; employee health & safety; and termination of employment. 

After completing the course, you should be able to recognize and diagnose legal issues arising in the employment context, analyze those issues under the applicable law, and help clients avoid legal problems or pursue remedies when they arise. Simulation problems, including in-class discussion and take-home assignments, provide an opportunity to develop practical skills for representing clients in employment matters.

## Course Materials {.unnumbered}

### Required

Employment Law: An Open-Source Casebook (version 4.1, December 2025). Available on the course website: [emfink.net/EmploymentLaw](http://www.emfink.net/EmploymentLaw).  

Rachel Arnow-Richman & Nantiya Ruan, Developing Professional Skills: Workplace Law (West Academic 2017) ("Workbook"). 

### Suggested

Ann Hodges & Rafael Gely, Principles of Employment Law (West Academic 2016). Digital version available at no cost through the [West Academic Online Study Aids Collection](https://subscription.westacademic.com/).

## Policies {.unnumbered}

### Grading

Your final grade for this course will be based on two group assignments (20% each), one individual writing assignment (30%), and class participation (30%). There will be no final exam.

The group assignments will be based on problems from the Developing Professional Skills workbook. Each group will be responsible for two problems during the term, as indicated in the Schedule and Assignments section of the syllabus. I will provide further information about each assignment before the due dates. 

The individual writing assignment will be based on a problem that I will provide in the last week of class. The due date for this assignment will be March 21 (last day of Winter Term exam period). 

### Attendance

Elon Law School has adopted the following attendance policy for all courses:

> The Law School administers a policy that a student maintain regular and punctual class attendance in all courses in which the student is registered, including externships, clinical courses, or simulation courses. Faculty members will give students written notice of their attendance policies before or during the first week of class. These policies may include, but are not limited to: treating late arrivals, early departures, and/or lack of preparation as absences  imposing grade or point reductions for absences, including assigning a failing grade or involuntarily withdrawing a student from the class  and any other policies that a professor deems appropriate to create a rigorous and professional classroom environment.
>  
> In case of illness or emergency, students may contact the Office of Student and Professional Life, which will then notify the student’s instructors. A student may notify the faculty member directly of a planned absence and should refer to individual faculty members regarding any policy that may apply. In the case of prolonged illness or incapacity, the student should contact the [Office of Student Life](https://www.elon.edu/u/law/students/).

You should let me know (in advance if feasible) if you are unable to attend class, will arrive late, or must leave early. I do not require an explanation of the reason, nor do I require a doctor's note or other documentation.

### Disability Accommodations

For disability accommodation requests, contact the [Elon Disability Services Office](https://www.elon.edu/u/academics/koenigsberger-learning-center/disabilities-resources/homepage/graduate-student-resources/).

### Honor Code

The Law School [honor code](https://www.elon.edu/u/law/students/honor-code/) applies to all activities related to your law school study, including conduct during class and examinations.

## Schedule & Assignments {.unnumbered}

(_Note:_ This class will not meet on Monday, January 19th)

### 1\. Foundations of Employment Law

#### January 5 & 7

Employment as a Socio-Legal Relationship, _Casebook_ Chap. 1

#### January 12

Labor Organizing & Collective Bargaining, _Casebook_ Chap. 2

### 2\. Establishing an Employment Relationship

#### January 14 

Identifying Employees, _Casebook_ Chap. 3, § 1-3

#### January 21 

Identifying Employers, _Casebook_ Chap. 3, § 4

#### January 26 

Recruitment & Hiring, _Casebook_ Chap. 4

### 3\.Scope & Limits of Employer Control

#### January 28

Privacy, Autonomy, & Dignity, _Casebook_ Chap. 5, § 1

#### February 2

Protected Concerted Activity, _Casebook_ Chap. 5, § 2

#### February 4 

Control Outside Work, _Casebook_ Chap. 5, § 3

### 4\. Employee Duties to Employers

#### February 9

Confidentiality, _Casebook_ Chap. 6, § 1

#### February 11 

Loyalty, _Casebook_ Chap. 6, § 2

#### February 16

Competition, _Casebook_ Chap. 6, § 2 

### 5\. Wages & Hours

#### February 18

Minimum Wage, Overtime, & Wage Payments, _Casebook_ Chap. 7

### 6\. Employee Health & Safety

#### February 23

Medical Leave & Disability Discrimination, _Casebook_ Chap. 8, §§ 1 & 2

#### February 25

OSHA & Workers' Compensation, _Casebook_ Chap. 9, §§ 3 & 4

### 7\. Terminating Employment

#### March 2

Contractual Exceptions to the At-Will Presumption, _Casebook_ Chap. 10, § 1

#### March 4

Tort & Statutory Claims for Wrongful Termination, _Casebook_ Chap. 10, §§ 2 & 3

#### March 9 

Unemployment Compensation, _Casebook_ Chap. 10, § 4

#### March 11 

##### Make-up Class (if needed)

:::