**295 F.Supp.2d 465 (2003)**

### Steven WIEGAND, Plaintiff,  
v.  
MOTIVA ENTERPRISES, LLC, and Starstaff, Inc., Defendants.

[No. CIV. 02-3979(JBS).](https://scholar.google.com/scholar?scidkt=1297669258135162046&as_sdt=2&hl=en)

**United States District Court, D. New Jersey.**

December 16, 2003.

[466](https://scholar.google.com/scholar_case?case=3111564132816580498&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34#p466)[\*466](https://scholar.google.com/scholar_case?case=3111564132816580498&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34#p466) Samuel J. Myles, Holston, MacDonald, Uzdavinis & Ziegler, P.C., Woodbury, NJ, for Plaintiff.

Jeffrey W. Moryan, Camille V. Otero, Connell Foley, LLP, Roseland, NJ, for Defendants.

## _OPINION_

SIMANDLE, District Judge.

On November 20, 2001, two newspapers ran articles which stated that plaintiff Steven Wiegand was operating a "mail order neo-Nazi skinhead music company" and that he was a "personal friend and supporter" of Katja Lane, the purported wife of Aryan Nation leader David Lane. Plaintiff immediately brought the articles to the attention of his supervisor at the Texaco gas station where he had worked without incident since 1994, which was operated by defendants Motiva Enterprises and Starstaff, Inc. The defendants' resulting investigation uncovered that plaintiff was operating a website which plaintiff admits "sells underground music and records" that are "racist and/or offensive to some people," such as swastika flags, music advertised as "the most popular and funniest Nigger-hatin' songs ever written" and t-shirts with sayings like "Skinheads" and "Blue-Eyed Devil." Defendants then told plaintiff that his employment was terminated because his operation of the website violated the company's "core value" of "respect for all people."

Plaintiff filed the present lawsuit on May 28, 2002, raising claims solely under New Jersey law, asserting (1) that defendants wrongfully terminated him because they discharged him "in violation of a clear mandate of public policy," namely his exercise [467](https://scholar.google.com/scholar_case?case=3111564132816580498&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34#p467)[\*467](https://scholar.google.com/scholar_case?case=3111564132816580498&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34#p467) of his Constitutional right to free speech, (2) that defendants breached a provision in his employee handbook when they fired him, and (3) that defendants are liable for damages under a theory of promissory estoppel because he relied on a statement from his supervisor regarding future employment. Presently before the Court are the parties' cross-motions for summary judgment as to all claims. The Court finds that summary judgment must be granted in favor of defendants as to Counts I and II because (1) defendants did not violate a clear mandate of public policy when they terminated plaintiff's employment because of his commercial hate speech, and (2) defendants are not liable for breach of contract based on the employee handbook because it clearly provided that it did not create a contractual relationship between the parties. The Court further finds that summary judgment must be denied as to the promissory estoppel claim in Count III because questions of fact remain about whether plaintiff reasonably relied on a promise for continued employment.

## I. BACKGROUND

## A. Plaintiff's Employment with Defendants

On August 4, 1994, defendant Starstaff hired plaintiff Steven Wiegand to work as a clerk for defendant Motiva Enterprises in the convenience store at a Texaco gasoline station in Maple Shade, New Jersey. (Otero Aff., Ex. B, Wiegand Vol. I Dep. at 31:18-22.) Plaintiff received a Starstaff Employee Handbook and, on August 4, 1994, signed to indicate his agreement the terms of the handbook and with his status as an at-will employee. (Otero Aff., Ex. U.)<sup><a href="https://scholar.google.com/scholar_case?case=3111564132816580498&amp;q=wiegand+v+motiva+enterprises+llc&amp;hl=en&amp;as_sdt=6,34#[1]" name="r[1]">[1]</a></sup> Plaintiff had a "good" employment record and was promoted to assistant store manager and then to store manager by October 1996. (Defs.' Facts ¶ 8; Pl.'s Facts ¶¶ 2-4; Otero Aff., Ex. G, Jantorno Dep. at 7:12-22; _id.,_ Ex. H, Sanders Dep. at 7:14-21; Pl.'s Ex. D, Winfrey Dep. at 16:12-13.) In July 2001, defendants issued a revised handbook, called the SORO<sup><a href="https://scholar.google.com/scholar_case?case=3111564132816580498&amp;q=wiegand+v+motiva+enterprises+llc&amp;hl=en&amp;as_sdt=6,34#[2]" name="r[2]">[2]</a></sup> Employee Resource Guide, which again indicated the at-will status of plaintiff's employment. (Otero Aff., Ex. C.)<sup><a href="https://scholar.google.com/scholar_case?case=3111564132816580498&amp;q=wiegand+v+motiva+enterprises+llc&amp;hl=en&amp;as_sdt=6,34#[3]" name="r[3]">[3]</a></sup> The July [468](https://scholar.google.com/scholar_case?case=3111564132816580498&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34#p468)[\*468](https://scholar.google.com/scholar_case?case=3111564132816580498&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34#p468) 2001 Guide also included certain guidelines for "the behavior expected of every employee." (Otero Aff., Ex. C at 2.) Employees were informed that defendants were "committed to the\[\] highest principle of ethics and conduct" so that all employees were required to "value and respect all people, demonstrate integrity, focus on customers, aspire to excellence and act for the greater whole," and "respect all applicable laws and avoid situations in which their personal interest conflicts with the interest of the Company." (_Id._ at 2, 29).<sup><a href="https://scholar.google.com/scholar_case?case=3111564132816580498&amp;q=wiegand+v+motiva+enterprises+llc&amp;hl=en&amp;as_sdt=6,34#[4]" name="r[4]">[4]</a></sup> In a separate "Code of Conduct" referenced within the handbook, defendants provided that "disciplinary action, including discharge, may be taken ... against employees who authorize or participate in actions which violate the law, the Code of Conduct or Company policy statements in such a manner as to impugn or seriously embarrass the Company or other employees publicly." (Otero Aff., Ex. D at 4.)

## B. The Newspaper Articles

Sometime in 1999, plaintiff told his immediate supervisor, Motiva sales consultant Charles Sanders, that "he sold CDs and flags on the Internet" and that "some were not mainstream." (Otero Aff., Ex. H, Sanders Dep. at 10:5-18.) Sanders testified that he was "not really sure what" plaintiff meant by "not mainstream," but that he never looked into it because he was concerned about plaintiff's work at the station and "didn't care" about what plaintiff was doing in his free time. (_Id._ at 10:19-12:13:3.)<sup><a href="https://scholar.google.com/scholar_case?case=3111564132816580498&amp;q=wiegand+v+motiva+enterprises+llc&amp;hl=en&amp;as_sdt=6,34#[5]" name="r[5]">[5]</a></sup>

Sanders' interest in plaintiff's side business changed, though, on November 20, 2001, when plaintiff called Sanders "very upset saying that there was ... an article printed about him ... He wanted to know was he going to be fired for this or what would happen to him." (Otero Aff., Ex. H, Sanders Dep. at 15:16-22.) The article entitled "Racist Business Moves to Maple Shade" appeared in the Courier-Post and the Burlington County Times, and reported [469](https://scholar.google.com/scholar_case?case=3111564132816580498&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34#p469)[\*469](https://scholar.google.com/scholar_case?case=3111564132816580498&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34#p469) that a "white supremacist publishing and Internet operation based in northern Idaho" called "14 Word Press" had been sold to "Steve Wiegand in Maple Shade." (Otero Aff., Ex. F; Pl.'s Ex. F.) According to the articles, Katja Lane, purported to be the wife of Aryan Nation leader David Lane, had operated the 14 Word Press site to allow "David Lane to propagandize and recruit new racists while behind bars for life in the nation's most secure federal penitentiary," but could no longer handle the work involved. (_Id._) The articles explained that she decided to turn over the business to plaintiff because "\[h\]e has been a personal friend and supporter for many years, as well as successfully running his own music distribution company." (_Id._) Plaintiff's company, called Micetrap Distribution, was described by the article as a "mail order neo-Nazi skinhead music company" that is "among the top 10 distributors of hate music \[and\] which frequently attracts young recruits to the racist movement." (_Id._) The articles did not make any reference to plaintiff's employment at Texaco. (_Id._)<sup><a href="https://scholar.google.com/scholar_case?case=3111564132816580498&amp;q=wiegand+v+motiva+enterprises+llc&amp;hl=en&amp;as_sdt=6,34#[6]" name="r[6]">[6]</a></sup>

Sanders said that plaintiff was clearly concerned about the articles and asked him, "Am I going to get fired or is there anything I can do?" (Otero Aff., Ex. H, Sanders Dep. at 15:24-16:2.) Sanders testified that he told plaintiff that he did not know what would happen, and that he needed to talk about it with Joseph Jantorno, sales manager for New Jersey and Pennsylvania SOROs. (_Id._ at 16:3-5.)

Sanders called plaintiff "within the next day or two" and told him that it would not hurt, and "might help if he got \[the business\] out of his name." (_Id._ at 16:3-5; Otero Aff., Ex. B, Wiegand Vol I Dep. at 84:20-85:11.) Plaintiff asserts that Sanders actually promised him that he would not be fired if he (1) prevented any other articles from printing, (2) took the 14 Word Press business out of his name, and (3) complied with the company's internal investigation. (Pl.'s Ex. H, Wiegand Cert. ¶ 12.) Sanders testified that plaintiff at "first said he couldn't \[take it out of his name\] because he had sunk too much money into it," but that he called back a "day or two later ... and said that he decided he was going to take it out of his name because his mother was being harassed ... for what he was doing." (_Id._ at 16:5-10.) Plaintiff dissolved his registration of the 14 Word Press name and sent the remaining 14 Word Press inventory "to a guy in California named John Something," because he thought that Sanders meant [470](https://scholar.google.com/scholar_case?case=3111564132816580498&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34#p470)[\*470](https://scholar.google.com/scholar_case?case=3111564132816580498&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34#p470) that "as long as I got \[14 Word Press\] out of my name" and "no more articles were printed ... everything would be fine \[and\] I would go back to work." (Otero Aff., Ex. B, Wiegand Vol. I Dep. at 85:16-86:3; 116:1-9.)

Meanwhile, Sanders had called sales manager Jantorno to tell him that there was an article in the newspaper "about Steve being involved with some type of, I will call it white supremist group." (Otero Aff., Ex. G, Jantorno Dep. at 4:15-5:7, 21:9-10; _id.,_ Ex. H, Sanders Dep. at 17:2-10.) Jantorno testified that his first question was whether "he's actually the principle" of the company and "deeply involved," rather than "a friend or \[just\] fooling around with it." (_Id.,_ Ex. G, Jantorno Dep. at 23:1-13.) Jantorno thought that "if he's a principle in the company we are going to have a problem ... if not, he's going to have to explain himself and why he's in the company." (_Id._) He thought that "\[if\] he was a principle in that type of company ... and did distribute the type of material as described to me, it would fly in the face of what this company in this country is all about." (_Id._ at 24:13-18.)

Jantorno asked Sanders to talk to plaintiff again to verify whether "any part of the article that was mentioned \[was\] true." (_Id._ at 27:12-14.) Sanders called Jantorno a "day or two later" and confirmed that plaintiff was deeply involved in the business. (Otero Aff., Ex. G, Jantorno Dep. at 27:15-29:4.) Jantorno said that "we can't have that \[hate material\] associated with either our brand, Texaco or Shell" and instructed Sanders to "relieve Steve of duty while we do an investigation." (_Id._ at 29:8-25.) Sanders then told plaintiff that he would be "relieved of duty with pay pending an investigation." (_Id._ at 30:1-16; Otero Aff., Ex. H, Sanders Dep. at 18:1-8.)

## C. The Investigation

Sanders and Jantorno then called Rick Riggs, in the security group associated with Motiva, and told him to "get to the bottom of this problem one way or the other." (Otero Aff., Ex. G, Jantorno Dep. at 33:18-25.) Riggs interviewed plaintiff and Sanders and accessed and viewed what plaintiff acknowledged was his website. (_Id.,_ Ex. J, Riggs Cert. ¶ 6; _id.,_ Ex. G, Jantorno Dep. at 35:6-20.) On December 4, 2001, Riggs submitted a confidential investigative report to defendants, in which he reported that plaintiff "was in fact selling white supremacist materials" including "some pretty offensive stuff." (_Id.,_ Ex. J, Riggs Cert. ¶ 6; _id.,_ Ex. G, Jantorno Dep. at 35:6-20.)<sup><a href="https://scholar.google.com/scholar_case?case=3111564132816580498&amp;q=wiegand+v+motiva+enterprises+llc&amp;hl=en&amp;as_sdt=6,34#[7]" name="r[7]">[7]</a></sup>

Plaintiff's website is called "Micetrap Distribution" and is touted as the place to get "quality Pro-White products with the best service available and at the lowest prices." (Otero Aff., Ex. K.)<sup><a href="https://scholar.google.com/scholar_case?case=3111564132816580498&amp;q=wiegand+v+motiva+enterprises+llc&amp;hl=en&amp;as_sdt=6,34#[8]" name="r[8]">[8]</a></sup> The site promises satisfaction that is "188% guaranteed,"<sup><a href="https://scholar.google.com/scholar_case?case=3111564132816580498&amp;q=wiegand+v+motiva+enterprises+llc&amp;hl=en&amp;as_sdt=6,34#[9]" name="r[9]">[9]</a></sup> [471](https://scholar.google.com/scholar_case?case=3111564132816580498&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34#p471)[\*471](https://scholar.google.com/scholar_case?case=3111564132816580498&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34#p471) (_id._ at 9), sells swastika flags, Nazi paraphernalia, t-shirts with sayings like "Blue Eyed Devil," "Aggravated Assault," and "Mice Trap Records," and music albums, including "The White Race Will Prevail," "Keep the Hate Alive," and others that are "blatantly hate-filled and nasty as humanly possible," (Otero Aff., Exs. K-Q.) Lyrics are included for certain songs, including "Nigger Hatin' Me" and "The New Racism," which lambaste African Americans and refer to Adolf Hitler as "the closest we ever got to a fucking god." (_Id.,_ Exs. O, P.)

Plaintiff is pictured on the website modeling a "Mice Trap Records" t-shirt. (_Id.,_ Ex. Q at 5.) The photo was taken in front of a holocaust memorial in Cherry Hill, New Jersey, but plaintiff testified that he chose the background for "no real reason." (Otero Aff., Ex. B, Wiegand Vol. II Dep. at 82:3-83:14.) Plaintiff is also referred to in the site's web forum; one comment congratulates "Steve" on his acquisition of 14 Word Press, stating that "the fact that Katja chose you speaks volumes about your character and commitment." (Otero Aff., Ex. K at 1.)

The Micetrap Distribution site includes the following disclaimer:

> Micetrap Distribution has quickly established itself as one of the most reliable, fastest and lowest priced sources for underground music, videos, books and flags in the world. Although some of the items available on this site contain violent or "racist" themes, Micetrap Distribution is merely supplying a service and in no way condones illegal activities or the "acting out" of the lyrics contained on these compact discs. The album and song titles, artwork, pictures and lyrics are the intellectual properties of the various bands and do not necessarily represent the personal views of Micetrap Distribution.

> All materials are completely legal in the United States and it is entirely your choice as to whether or not you want to purchase them. If you are offended or opposed to anything contained on my website, close your browser immediately. Simply put, these items are made available for those who seek them. Rather than attacking ideologies and legal merchandise, I suggest that my opponents refocus their attention onto real issues that plague our society; rape and sexual abuse, murder, drugs, thefts, assault and other illegal activities.

(Otero Aff., Ex. K at 10.)

## D. Plaintiff's termination

Upon learning the details of the website, Jantorno called Shawn Cotton in Human Resources, who talked to his supervisor and to the chief of diversity for the company. (Otero Aff., Ex. G, Jantorno Dep. at 35:6-25.) All agreed that plaintiff's employment should be terminated. (_Id._ at 36:21-37:2.) Jantorno called Sanders on December 11, 2001 and told him that "\[w\]e are going to have to let him go." (Otero Aff., Ex. H, Sanders Dep. at 21:21-22.) That day, Jantorno and Sanders met with plaintiff and told him that "his performance over the years ... was satisfactory" but that his employment was being terminated because an investigation of his webbased [472](https://scholar.google.com/scholar_case?case=3111564132816580498&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34#p472)[\*472](https://scholar.google.com/scholar_case?case=3111564132816580498&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34#p472) company revealed that he was distributing material that was a "direct contradiction of our core values \[of\] value and respect for all people." (Otero Aff., Ex. B, Wiegand Vol. I Dep. at 84:11-15; _id.,_ Ex. G, Jantorno Dep. at 37:18-28:7; _id.,_ Ex. H, Sanders Dep. at 22:2-13.)

Plaintiff then filed the present lawsuit in New Jersey Superior Court, Camden County on May 28, 2002, asserting claims of wrongful termination, breach of contract, and promissory estoppel, asserting that defendants could not terminate his employment because of his exercise of speech. (Otero Aff., Ex. R.) Defendants removed the action on August 16, 2002, asserting diversity jurisdiction, and on July 21, 2003, the parties filed the present motions for summary judgment. The Court heard oral argument on the motions on October 14, 2003, and is now prepared to issue its ruling.

## II. DISCUSSION

## A. Standard of Review

Summary judgment is appropriate when the materials of record "show that there is no genuine issue as to any material fact and that the moving party is entitled to judgment as a matter of law." Fed. R.Civ.P. 56(c). A dispute is "genuine" if "the evidence is such that a reasonable jury could return a verdict for the non-moving party." _See_ [_Anderson v. Liberty Lobby, Inc.,_ 477 U.S. 242, 248, 106 S.Ct. 2505, 91 L.Ed.2d 202 (1986)](https://scholar.google.com/scholar_case?case=9272001251064530131&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34). A fact is "material" only if it might affect the outcome of the suit under the applicable rule of law. _Id._ Disputes over irrelevant or unnecessary facts will not preclude a grant of summary judgment. _Id._

In deciding whether there is a disputed issue of material fact, the court must view the evidence in favor of the non-moving party by extending any reasonable favorable inference to that party; in other words, "\[T\]he nonmoving party's evidence \`is to be believed, and all justifiable inferences are to be drawn in \[that party's\] favor.'" [_Hunt v. Cromartie,_ 526 U.S. 541, 552, 119 S.Ct. 1545, 143 L.Ed.2d 731 (1999)](https://scholar.google.com/scholar_case?case=2682540302240026651&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34) (quoting [_Liberty Lobby,_ 477 U.S. at 255, 106 S.Ct. 2505](https://scholar.google.com/scholar_case?case=9272001251064530131&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34)). The threshold inquiry is whether there are "any genuine factual issues that properly can be resolved only by a finder of fact because they may reasonably be resolved in favor of either party." [_Liberty Lobby,_ 477 U.S. at 250, 106 S.Ct. 2505](https://scholar.google.com/scholar_case?case=9272001251064530131&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34); [_Brewer v. Quaker State Oil Refining Corp.,_ 72 F.3d 326, 329-30 (3d Cir.1995)](https://scholar.google.com/scholar_case?case=5338761931634249233&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34) (citation omitted).<sup><a href="https://scholar.google.com/scholar_case?case=3111564132816580498&amp;q=wiegand+v+motiva+enterprises+llc&amp;hl=en&amp;as_sdt=6,34#[10]" name="r[10]">[10]</a></sup>

The standard by which the court decides a summary judgment motion does not change when the parties file cross-motions, as in the present case. [_Weissman v. United States Postal Serv.,_ 19 F.Supp.2d 254 (D.N.J.1998)](https://scholar.google.com/scholar_case?case=5648566754959709052&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34). When ruling on cross-motions [473](https://scholar.google.com/scholar_case?case=3111564132816580498&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34#p473)[\*473](https://scholar.google.com/scholar_case?case=3111564132816580498&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34#p473) for summary judgment, the court must consider the motions independently, [_Williams v. Philadelphia Hous. Auth.,_ 834 F.Supp. 794, 797 (E.D.Pa.1993),](https://scholar.google.com/scholar_case?case=17153239089126084635&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34) _aff'd,_ [27 F.3d 560 (3d Cir.1994),](https://scholar.google.com/scholar_case?about=8790134656152508474&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34) and view the evidence on each motion in the light most favorable to the party opposing the motion. _See_ [_Matsushita Elec. Indus. Co., Ltd. v. Zenith Radio Corp.,_ 475 U.S. 574, 587, 106 S.Ct. 1348, 89 L.Ed.2d 538 (1986)](https://scholar.google.com/scholar_case?case=3152975315662722042&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34).

## B. Analysis

The parties presently seek summary judgment as to the three counts of plaintiff's complaint, namely (1) wrongful termination, (2) breach of contract, and (3) promissory estoppel. Defendants argue that there is no question that plaintiff's termination was not in violation of a clear mandate of public policy, that plaintiff was an at-will employee who did not have a contractual relationship with defendants, and that plaintiff had no reasonable expectation of continued employment. Plaintiff, on the other hand, argues that there is no question that his termination was in violation of the clear mandate of the First Amendment, that he was assured continued employment pursuant to the terms of the Employment Manual, and that he reasonably relied upon an alleged promise by a supervisor that his employment would continue provided he made sure that his web business was not connected to defendants in any way. The Court finds, for the following reasons, that summary judgment must be granted in favor of defendants as to Counts I and II of the Complaint and that summary judgment must be denied as to Count III.

## 1\. Wrongful termination

The New Jersey Supreme Court, in _Pierce v. Ortho Pharmaceutical Corp.,_ held that an at-will employee may sustain a claim for wrongful termination if he shows that his discharge was "contrary to a clear mandate of public policy." 84 N.J. 58, 72, 417 A.2d 505 (1980). "Sources of public policy include the United States and New Jersey Constitutions; federal and state laws and administrative rules, regulations and decisions; the common law and specific judicial decisions; and in certain cases, professional codes of ethics." [_MacDougall v. Weichert,_ 144 N.J. 380, 391, 677 A.2d 162 (1996)](https://scholar.google.com/scholar_case?case=8738269820013647624&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34) (citing [_Hennessey v. Coastal Eagle Point Oil Co.,_ 129 N.J. 81, 92-93, 609 A.2d 11 (1992)](https://scholar.google.com/scholar_case?case=9886162622953187601&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34)).

Here, plaintiff asserts that there is no question that defendants violated a "clear mandate of public policy" because they terminated him because of his exercise of his First Amendment right to free speech. Defendants do not dispute that plaintiff was terminated because of his exercise of speech, but assert that they did not violate a "clear mandate of public policy" in doing so because plaintiff cannot assert a First Amendment claim against them (1) because they are private actors and (2) because they did not violate the First Amendment by terminating plaintiff because of his commercial hate speech.

The issue regarding whether a wrongful termination claim against a private actor can be based on a First Amendment constitutional claim, when First Amendment claims must themselves be based on state action, is one that New Jersey courts have not addressed. The New Jersey Supreme Court has held that the "mandate of public policy" that is necessary to support a wrongful termination claim must be "clearly identified and firmly grounded," and not "vague, controversial, unsettled, \[or\] otherwise problematic," [_MacDougall,_ 144 N.J. at 391-92, 677 A.2d 162,](https://scholar.google.com/scholar_case?case=8738269820013647624&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34) and defendants argue that a wrongful termination claim against a private actor based on the First Amendment is not "clear" because private actors are not directly liable for First Amendment violations. Plaintiff, though, argues that the Court should "find as a [474](https://scholar.google.com/scholar_case?case=3111564132816580498&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34#p474)[\*474](https://scholar.google.com/scholar_case?case=3111564132816580498&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34#p474) matter of law, that the First Amendment may form the basis for a clear mandate of public policy to support the wrongful termination claim of a private employee, regardless of the fact that said employee could not bring an independent claim under the first amendment" because the same speech concerns are implicated.<sup><a href="https://scholar.google.com/scholar_case?case=3111564132816580498&amp;q=wiegand+v+motiva+enterprises+llc&amp;hl=en&amp;as_sdt=6,34#[11]" name="r[11]">[11]</a></sup> (Pl.'s Opp. Br. at 3.) According to plaintiff, an employee, whether public or private, "should not have to be fearful about expressing his personal views in his own home, on his own time. He should not have to worry about losing his job because of his exercise of his first amendment rights in such a private manner that does not affect his employer." (Pl.'s Br. at 10-11.) Here, it is undisputed that the views expressed on plaintiff's website did not infect the workplace in any way. (Pl.'s Ex. H, Wiegand Cert. ¶¶ 19-23; _id.,_ Ex. B, Jantorno Dep. at 48:16-49:3.)

The Court does not need to determine whether New Jersey law confers constitutional protections upon at-will employees in the absence of state action because, even if plaintiff could assert a First Amendment wrongful termination claim against these private defendants, plaintiff cannot here establish that defendants' termination decision was contrary to a clear mandate of public policy.<sup><a href="https://scholar.google.com/scholar_case?case=3111564132816580498&amp;q=wiegand+v+motiva+enterprises+llc&amp;hl=en&amp;as_sdt=6,34#[12]" name="r[12]">[12]</a></sup> There is no question that defendants did not violate a "clear mandate of public policy" when they determined that plaintiff's continued employment as supervisor of their convenience store, a job that required constant interaction with the consuming public, could not continue based on his dissemination of racist music and hate paraphernalia for commercial profit.

The First Amendment does not provide absolute protection for all speech, [_Cantwell_](https://scholar.google.com/scholar_case?case=10099999677896592458&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34) [475](https://scholar.google.com/scholar_case?case=3111564132816580498&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34#p475)[\*475](https://scholar.google.com/scholar_case?case=3111564132816580498&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34#p475) [_v. Connecticut,_ 310 U.S. 296, 304, 60 S.Ct. 900, 84 L.Ed. 1213 (1940),](https://scholar.google.com/scholar_case?case=10099999677896592458&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34) and three of its limitations are relevant in this case, namely the limitations based on commercial speech, on fighting words, and on speech in the employment context. The issue here is not whether plaintiff's speech could form the basis of a First Amendment claim, but is instead whether defendants' restrictions on plaintiff's speech violated a "clear mandate of public policy." This Court finds that it did not because the speech was not "clearly protected" by the First Amendment due to its nature as commercial hate speech regulated by an employer.

First, the Supreme Court has long recognized that commercial speech, which is "expression related solely to the economic interests of the speaker and its audience," is "accorded a lesser degree of First Amendment protection than other kinds of speech." [_Central Hudson Gas & Elec. Corp. v. Public Service Comm'n of New York,_ 447 U.S. 557, 561-63, 100 S.Ct. 2343, 65 L.Ed.2d 341 (1980)](https://scholar.google.com/scholar_case?case=1962482840967580827&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34). The protection available for commercial expression depends on the "nature both of the expression and of the governmental interests served by its regulation." [_Central Hudson,_ 447 U.S. at 563, 100 S.Ct. 2343](https://scholar.google.com/scholar_case?case=1962482840967580827&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34). The government may restrict false or misleading commercial messages that are "more likely to deceive the public than to inform it," and commercial speech about unlawful activities. _Id._ at 562-64, 100 S.Ct. 2343. Commercial speech that is "neither misleading nor related to unlawful activity," may also been restricted if the restriction directly advances a state interest and is "narrowly drawn" to regulate only the speech that poses a danger to the asserted state interest. _Id._ at 564-65, 100 S.Ct. 2343. To determine whether speech is commercial, the Third Circuit requires consideration of three factors, namely (1) whether the speech is an advertisement, (2) whether the speech refers to a specific product or service, and (3) whether the speaker has an economic motivation for the speech. [_In re Orthopedic Bone Screw Products Liability Litigation,_ 193 F.3d 781, 793 (3d Cir.1999)](https://scholar.google.com/scholar_case?case=10965317235191849620&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34).

Here, it is clear that plaintiff's speech was commercial. Plaintiff's website advertises specific products for sale as "quality Pro-White products with the best service available and at the lowest prices," such as "The Complete Johnny Rebel Collection CD" advertised as "the absolute BEST sing-a-long collection of ALL TIME," the "Paul Burnley Is the Real Public Enemy CD" advertized as a "must have" CD with "some of the best Pro-White National Socialist songs ever recorded," the "We Don't Care CD" advertised as "one of the best skinhead rock albums to have ever been recorded in North America." (Otero Aff., Ex. K.) Plaintiff testified that he maintains the website to provide "a place for people to buy music that they normally couldn't find in an average store," and that he retains "100 percent of the profits from micetrap.net." (Otero Aff., Ex. B, Wiegand Vol. I Dep. at 118:23-119:13, 148:10-12.) Commercial speech, even if neither misleading nor related to unlawful activity, still may be regulated to advance a state interest.

Second, the Supreme Court has recognized that "fighting words" can be completely proscribed because they are "of such slight social value ... that any benefit that may be derived from them is clearly outweighed by the social interest in order and morality." [_R.A.V. v. City of St. Paul,_ 505 U.S. 377, 382-83, 112 S.Ct. 2538, 120 L.Ed.2d 305 (1992)](https://scholar.google.com/scholar_case?case=14621372290934958371&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34). The "unprotected category of speech called \`fighting words' is an extremely narrow one" because the First Amendment "on the whole offers broad protection for speech, be it unpleasant, disputatious, or downright offensive" because the right to "free speech under [476](https://scholar.google.com/scholar_case?case=3111564132816580498&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34#p476)[\*476](https://scholar.google.com/scholar_case?case=3111564132816580498&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34#p476) our system of government" is intended to "invite dispute" and thus must be permitted to "induce\[\] a condition of unrest, create\[\] dissatisfaction with conditions as they are, or even stir\[\] people to anger." [_Johnson v. Campbell,_ 332 F.3d 199, 212 (3d Cir.2003)](https://scholar.google.com/scholar_case?case=2219668728892189742&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34) (quoting [_Texas v. Johnson,_ 491 U.S. 397, 408, 109 S.Ct. 2533, 105 L.Ed.2d 342 (1989)](https://scholar.google.com/scholar_case?case=2084618710761560217&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34)). Fighting words, which are unprotected speech, are those which "likely to produce a clear and present danger of a serious substantive evil that rises far above public inconvenience, annoyance, or unrest." _Id._ (quoting [_Terminiello v. City of Chicago,_ 337 U.S. 1, 4, 69 S.Ct. 894, 93 L.Ed. 1131 (1949)](https://scholar.google.com/scholar_case?case=2189837708321658845&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34)). They "do more than bother the listener; they must be nothing less than \`an invitation to exchange fisticuffs.'" _Id._ (quoting [_Johnson,_ 491 U.S. at 409, 109 S.Ct. 2533](https://scholar.google.com/scholar_case?case=2084618710761560217&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34)). Profane words alone are not "fighting words" as "one man's vulgarity is another's lyric," and "so long as one does not incite violence, one should not be forced to express one's anger or disapproval in measured terms." _Id._ at 212-13 (quoting [_Cohen v. California,_ 403 U.S. 15, 20, 25, 91 S.Ct. 1780, 29 L.Ed.2d 284 (1971)](https://scholar.google.com/scholar_case?case=7398433541275578772&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34)). "Majority preferences must be expressed in some fashion other than silencing speech on the basis of content." [_R.A.V.,_ 505 U.S. at 392, 112 S.Ct. 2538](https://scholar.google.com/scholar_case?case=14621372290934958371&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34).

Here, the speech on plaintiff's website is hate speech. The site's disclaimer provision admits that "some of the items available on this site contain violent or \`racist' themes," such as those for the song "Nigger Hatin' Me" by Johnny Rebel which twice state "Stick your black head out and I'll blow it!" (Otero Aff., Ex. K at 10, Ex. O.) Other songs on the "FEATURED COMPACT DISC" by Johnny Rebel include "Who Likes A Nigger," "Move them Niggers North," "Ship them Niggers Back," and "We Don't Want Niggers in Our Schools." (_Id.,_ Ex. K.) Free Mp3 downloads are also available on the site of many albums, including songs like "The White Race Will Prevail," "I Don't Like You," "Time for Payback," "Blood and Honour," "Ethnic Cleansing," "Fuck America!" "Livin' Like a Nigger," and "Fight Till We Win." (_Id.,_ Ex. N.) The disclaimer provision, though, indicates that plaintiff "in no way condones illegal activities or the \`acting out' of the lyrics contained on these compact discs." (_Id.,_ Ex. K at 10.)

The Court need not here determine whether the speech on the site qualifies as "fighting words" which are not provided First Amendment protection. Indeed, for purposes of this motion, it can be assumed that plaintiff's speech does not constitute "fighting words," since the Supreme Court has made clear that "messages of bias-motivated hatred ... based on virulent notions of racial supremacy" are protected by the First Amendment. [_R.A.V.,_ 505 U.S. at 392, 112 S.Ct. 2538](https://scholar.google.com/scholar_case?case=14621372290934958371&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34). Still, the Supreme Court has noted that "diverse communities" have "the responsibility, even the obligation ... to confront such notions in whatever form they appear;" it just cannot do so by placing "selective limitations upon speech." _Id._ Here, even if the speech was protected by the First Amendment, it was sufficiently virulent and odious that "clear public policy" did not require an employer to ignore its effect on the community.

Third, the Supreme Court has held that, in the employment context, the state cannot "condition employment on a basis that infringes the employee's constitutionally protected interest in freedom of expression," [_Connick v. Myers,_ 461 U.S. 138, 142, 103 S.Ct. 1684, 75 L.Ed.2d 708 (1983),](https://scholar.google.com/scholar_case?case=12292534138488546769&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34) but can, in certain situations, "regulat\[e\] the speech of its employees," [_Pickering v. Board of Ed. of Twp. High School Dist. 205,_ 391 U.S. 563, 568, 88 S.Ct. 1731, 20 L.Ed.2d 811 (1968)](https://scholar.google.com/scholar_case?case=16997195768089298466&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34). The "judicial task" in considering speech in the employment context [477](https://scholar.google.com/scholar_case?case=3111564132816580498&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34#p477)[\*477](https://scholar.google.com/scholar_case?case=3111564132816580498&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34#p477) is "to strike a balance between the interests of the employee, as a citizen, in commenting upon matters of public concern and the interest of the State, as an employer, in promoting the efficiency of the public services it performs through its employees." [_Zamboni v. Stamler,_ 847 F.2d 73, 77 (3d Cir.1988)](https://scholar.google.com/scholar_case?case=15611963109473379525&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34) (quoting [_Pickering,_ 391 U.S. at 568, 88 S.Ct. 1731](https://scholar.google.com/scholar_case?case=16997195768089298466&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34)). If the "employee expression cannot be fairly considered as relating to any matter of political, social, or other concern to the community" it is "unnecessary for \[the court\] to scrutinize the reasons for discharge" because "government officials should enjoy wide latitude in managing their offices, without intrusive oversight by the judiciary in the name of the First Amendment." [_Connick,_ 461 U.S. at 146, 103 S.Ct. 1684](https://scholar.google.com/scholar_case?case=12292534138488546769&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34). The speech is still protected by the First Amendment, but the employee is generally not guaranteed continued employment when he speaks upon matters only of personal interest. _Id._ Whether the speech addresses a matter of public concern, or a matter of public interest, "must be determined by the content, form, and context of a given statement, as revealed by the whole record." _Id._ at 148, 103 S.Ct. 1684.

Here, it is undisputed that the problem with plaintiff's speech occurred in the employment context. An employee does have the right to speak on matters of public concern, but here, plaintiff admits that he published this speech for personal financial gain. He asserts that he has simply "operated an online business" that "carr\[ies\] what people ask for," including music that "is racist and/or offensive to some people." (Pl. Facts ¶¶ 6, 7; Otero Aff., Ex. B, Wiegand Vol. II Dep. at 140:13-151:16.) He testified that he finds the music "funny," but that he personally is not prejudiced against African Americans, Jews, or homosexuals, and is not using his website to promote the White Supremacist Movement or the Aryan Nation. (Otero Aff., Ex. B, Wiegand Vol. I Dep. at 148:13-151:17, 176:1-8, 189:6-15.) On the other hand, defendants have a strong interest in ensuring that their employees are not associated with such speech or ideals. As Jantorno testified, "we can't have that \[hate material\] associated with our brand." (Otero Aff., Ex. G, Jantorno Dep. at 29:8-25.) Plaintiff was a supervisor of the convenience store and was in constant contact with the consuming public. Defendants justifiably were concerned that if they allowed his employment to continue, the public could learn of the views expressed on his website and believe that defendants condoned such ideas. While the hate material was not associated with defendants' brand at the time of plaintiff's termination, defendants, as private employers, still had a very strong interest in regulating the speech of their convenience store supervisor to ensure that it personified their values of respect for all.

The Court does not here find that plaintiff's speech would not be protected against governmental restriction under the First Amendment. Instead, the Court finds that no "clear mandate of public policy" was "clearly identified and firmly grounded," [_MacDougall,_ 144 N.J. at 391-92, 677 A.2d 162,](https://scholar.google.com/scholar_case?case=8738269820013647624&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34) when plaintiff's speech was commercial hate speech in the employment context. The Court has considered plaintiff's argument that allowing his termination based on his speech would mean that the Court would have to allow termination of any "employee who actively speaks out on any social issue (i.e. abortion, politics, etc.) in his own home and never at work," (Pl. Br. at 11), but finds that this situation is distinguishable. Here, plaintiff did not simply speak on a social issue; instead, he disseminated hate speech for commercial profit in circumstances where his employer had a strong interest in regulating any appearance of discrimination or racial bias toward fellow employees whom plaintiff supervised and [478](https://scholar.google.com/scholar_case?case=3111564132816580498&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34#p478)[\*478](https://scholar.google.com/scholar_case?case=3111564132816580498&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34#p478) toward customers whom he served. It is the combination of three elements of lesser-protected speech which establishes that there was no "clear mandate of public policy" here. New Jersey has not extended protection to an at-will managerial employee in the private sector who sells racist hate music and items for commercial gain. Plaintiff simply had no "firmly grounded" right under New Jersey's _Pierce v. Ortho_ doctrine to retain employment in the customer service industry while dispersing hate speech for commercial gain.

Thus, this Court will grant defendants' motion for summary judgment, and deny plaintiff's motion, regarding the wrongful termination claim.

## 2\. Breach of contract

The parties also seek summary judgment regarding the breach of contract claim in Count Two of plaintiff's Complaint. Plaintiff bases his claim on the Employee Handbook that he received when he accepted employment with Motiva, asserting that defendants breached it when they terminated him. He argues that the 2001 version of the handbook, and the separate "Code of Conduct" that included the "core values" provision, do not apply to him because there is no evidence that he ever received the 2001 version of the handbook or the Code of Conduct.

Plaintiffs' claim fails because it is undisputed that plaintiff received an employee handbook in August 1994 which stated that he agreed that "THIS HANDBOOK ... DOES NOT CONSTITUTE AN EMPLOYMENT CONTRACT" and that "THE COMPANY IS ... FREE TO TERMINATE THE EMPLOYEE AT ANY TIME FOR ANY REASON." (Otero Aff., Ex. U.)<sup><a href="https://scholar.google.com/scholar_case?case=3111564132816580498&amp;q=wiegand+v+motiva+enterprises+llc&amp;hl=en&amp;as_sdt=6,34#[13]" name="r[13]">[13]</a></sup> It is "well established under New Jersey law that an employment contract is not created by an employee handbook which contains a clear and prominent disclaimer stating that the document does not give rise to a contractual relationship." (Defs.' Opp. Br. at 10 (citing [_Warner v. Federal Express Corp.,_ 174 F.Supp.2d 215, 226 (D.N.J.2001)](https://scholar.google.com/scholar_case?case=5959720381725569412&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34); [_Nicosia v. Wakefern Food Corp.,_ 136 N.J. 401, 413, 643 A.2d 554 (1994)](https://scholar.google.com/scholar_case?case=4405623241045014765&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34))).

Here, there is no question that the disclaimer in plaintiff's handbook was clear and prominent. Plaintiff also has shown that he understood the disclaimer which was written in all capital letters directly above the signature line on the "Employee Handbook Receipt" form that he signed. At his deposition, he indeed admitted that he signed the handbook receipt and he "believe\[d\] that \[he\] could be fired at any time." (Otero Aff., Ex. B, Wiegand Dep. at 51:9-18, 53:10-18.) His first reaction to the newspaper articles, thus, was to ask his supervisor, "Am I going to get fired or is there anything I can do?" (Otero Aff., Ex. H, Sanders Dep. at 15:24-16:2.)

There is thus no question that the handbook at issue here contained a prominent disclaimer, that plaintiff was aware of its terms, and that it did not transform his at-will employment relationship into a contractual relationship. Therefore, this Court will grant defendants' motion for summary judgment, and deny plaintiff's motion, as to the breach of contract claim because there was no contract for defendants to breach.

## 3\. Promissory estoppel

The parties also seek summary judgment as to the promissory estoppel claim [479](https://scholar.google.com/scholar_case?case=3111564132816580498&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34#p479)[\*479](https://scholar.google.com/scholar_case?case=3111564132816580498&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34#p479) in Count Three of plaintiff's Complaint. Plaintiff bases his claim on a promise that he alleges his supervisor Charles Sanders made "that I would not be fired if I(1) prevented any other articles from printing, (2) took the 14 Word Press business out of \[my\] name, and (3) complied with the company's internal investigation." (Pl.'s Ex. H, Wiegand Cert. ¶ 12.) Defendants argue that summary judgment should instead be granted in their favor because there is no evidence that a "clear and definite" promise was made on which plaintiff could reasonably rely.

Under New Jersey law, to establish a claim for promissory estoppel, a plaintiff must show:

> (1) a "clear and definite" promise,

> (2) made with the expectation that the plaintiff would rely on it,

> (3) reasonable reliance on the promise by the plaintiff, and

> (4) definite and substantial detriment to the plaintiff because of his reliance.

_See_ [_Aircraft Inventory Corp. v. Falcon Jet Corp.,_ 18 F.Supp.2d 409, 416 (D.N.J.1998)](https://scholar.google.com/scholar_case?case=18088170152544405188&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34); [_Lobiondo v. O'Callaghan,_ 357 N.J.Super. 488, 815 A.2d 1013 (App.Div.2003)](https://scholar.google.com/scholar_case?case=14251054396153677818&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34).

Here, there is a dispute of fact as to whether plaintiff can establish a claim of promissory estoppel. First, plaintiff has certified that his supervisor, Charles Sanders, promised him continued employment if he prevented further newspaper articles about 14 Word Press, ensured that 14 Word Press would not be registered under his name, and complied with the company's internal investigation.<sup><a href="https://scholar.google.com/scholar_case?case=3111564132816580498&amp;q=wiegand+v+motiva+enterprises+llc&amp;hl=en&amp;as_sdt=6,34#[14]" name="r[14]">[14]</a></sup> (Pl.'s Ex. H, Wiegand Cert. ¶ 12.) He asserts that the statement was made after Sanders had talked to sales manager, Joseph Jantorno, about the problem, (Otero Aff., Ex. B, Wiegand Vol I Dep. at 84:20-85:11), and was made in direct response to his question, "Am I going to get fired or is there anything I can do?" (_id.,_ Ex. H, Sanders Dep. at 15:24-16:2). Because Sanders and Jantorno both had the authority to fire plaintiff, he asserts that his reliance was reasonable. (_See Id.,_ Ex. G, Jantorno Dep. at 6:23-7:4; 37:6-8.) Plaintiff, in fact, cancelled his purchase of 14 Word Press, sold his remaining 14 Word Press inventory, hired an attorney who wrote to the Philadelphia Inquirer to prevent a similar article from being published, and complied with defendants' investigation. (Pl. Ex. G; Pl.Ex. H, Wiegand Cert. ¶¶ 13-15.) Based on these facts, a reasonable factfinder could conclude that plaintiff reasonably believed that his employment would continue if he took certain steps to ensure that his web-based business was not further connected to defendants.

On the other hand, defendants assert that plaintiff was never promised future employment, but that instead, Sanders simply said that it "might help if he got \[14 Word Press\] out of his name." (Otero Aff., Ex. H, Sanders Dep. at 16:3-5.) Sanders testified that he does not remember ever promising plaintiff that his employment would continue or asking plaintiff to prevent further articles from being printed, (_id._ at 20:2-18), and that his comment was made in the same conversation in which he told plaintiff that he would be relieved of duty pending an investigation, (_id._ at 18:1-8, 20:2-7). Based on these facts, a reasonable factfinder could determine that plaintiff was never clearly promised continued employment and that he did not reasonably rely on any promise because [480](https://scholar.google.com/scholar_case?case=3111564132816580498&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34#p480)[\*480](https://scholar.google.com/scholar_case?case=3111564132816580498&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34#p480) Sanders could not have promised continued employment when, in the same conversation, he told plaintiff that there would be an investigation to determine whether plaintiff would retain his employment. There also remains the substantial issue of whether any breach of promissory estoppel was a proximate cause of plaintiff's loss of a job; if defendants terminated plaintiff based on his conduct occurring before plaintiff took the curative steps that Sanders allegedly suggested, then his post-promise reliance did not matter. This question remains to be determined at trial.

Therefore, because questions of fact remain as to plaintiff's promissory estoppel claim, this Court will deny both plaintiff's and defendants' motions for summary judgment as to the promissory estoppel claim in Count III.

## III. CONCLUSION

For the reasons explained herein, this Court will grant defendants' cross-motion for summary judgment, and deny plaintiff's motion for summary judgment, as to the wrongful termination claim of Count I and the breach of contract claim of Count II, and will deny both parties' cross-motions for summary judgment as to the promissory estoppel claim of Count III.

The accompanying Order is entered.

## _ORDER_

THIS MATTER having come before the Court on the motion for summary judgment of plaintiff Steven Wiegand, \[Docket Item 19-1\], and the cross-motion for summary judgment of defendants Motiva Enterprises, LLC and Starstaff, Inc., \[Docket Item 21-1\]; and the Court having considered the parties' written submissions as well as oral arguments made on October 14, 2003; for good cause and the reasons expressed in Opinion of today's date;

IT IS on this day of December, 2003, hereby

ORDERED that plaintiff Steven Wiegand's motion for summary judgment, \[Docket Item 19-1\] be, and hereby is, _DENIED;_ and

IT IS FURTHER ORDERED that defendants Motiva Enterprises, LLC and Starstaff, Inc.'s motion for summary judgment, \[Docket Item 21-1\], be, and hereby is, _GRANTED IN PART_ as to the claims in Counts I and II of plaintiff's Complaint, as to which Counts _JUDGMENT_ is to be entered for defendants, and _DENIED IN PART_ as to the claims in Count III of plaintiff's Complaint.

[\[1\]](https://scholar.google.com/scholar_case?case=3111564132816580498&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34#r[1]) Plaintiff signed under the following provision:

I have received the employee handbook and will read it until I become familiar with its contents.

I UNDERSTAND THAT THIS HANDBOOK IS A GENERAL SUMMARY OF COMPANY RULES AND PROCEDURES, AND DOES NOT CONSTITUTE AN EMPLOYMENT CONTRACT. JUST AS THE EMPLOYEE IS FREE TO LEAVE THE EMPLOY OF THE COMPANY AT ANY TIME FOR ANY REASON, THE COMPANY IS LIKEWISE FREE TO TERMINATE THE EMPLOYEE AT ANY TIME FOR ANY REASON.

I ALSO UNDERSTAND THAT NO REPRESENTATIVE OF THE COMPANY HAS ANY AUTHORITY TO ENTER INTO ANY AGREEMENT FOR EMPLOYMENT FOR ANY SPECIFIED PERIOD OF TIME, OR ASSURE ANY BENEFITS OR TERMS OF EMPLOYMENT.

(Otero Aff., Ex. U.)

[\[2\]](https://scholar.google.com/scholar_case?case=3111564132816580498&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34#r[2]) "SORO" is an abbreviation for "Salary Operated Retail Outlets" which include the convenience stores at Texaco stations. (Otero Aff., Ex. G, Jantorno Dep. at 4:23-5:2.)

[\[3\]](https://scholar.google.com/scholar_case?case=3111564132816580498&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34#r[3]) The July 2001 SORO Employee Resource Guide remained in effect until plaintiff's termination. It stated, in part that:

I UNDERSTAND THAT THIS RESOURCE GUIDE IS A GENERAL SUMMARY OF COMPANY RULES AND PROCEDURES AND DOES NOT CONSTITUTE AN EMPLOYMENT CONTRACT. JUST AS THE EMPLOYEE IS FREE TO QUIT HIS/HER EMPLOYMENT WITH THE COMPANY AT ANY TIME FOR ANY REASON, THE COMPANY IS LIKEWISE FREE TO TERMINATE THE EMPLOYEE AT ANY TIME FOR ANY REASON.

I ALSO UNDERSTAND THAT NO REPRESENTATIVE OF THE COMPANY HAS THE AUTHORITY TO ENTER INTO ANY AGREEMENT THAT THE COMPANY WILL PROVIDE EMPLOYMENT FOR A SPECIFIC PERIOD OF TIME OR PROVIDE ANY BENEFITS OR SPECIFIC TERMS OF EMPLOYMENT. THE COMPANY MAY MODIFY OR TERMINATE THE BENEFITS, POLICIES, PROCEDURES AND GUIDELINES IN THIS RESOURCE GUIDE AT ANY TIME, WITH OR WITHOUT NOTICE, SUBJECT TO ANY APPLICABLE LEGAL REQUIREMENTS FOR MODIFICATION OR TERMINATION.

(Otero Aff., Ex. C.) Plaintiff has certified that he never received this later edition of the handbook. (Wiegand Cert. ¶ 3.)

[\[4\]](https://scholar.google.com/scholar_case?case=3111564132816580498&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34#r[4]) To this end, the Code provided that:

All employees are expected to comply with all applicable laws, foster an affirmative attitude concerning compliance with the law and exhibit conduct consistent with fair, honest and ethical behavior. Any suspected violations of this Code of Conduct, related policy statement or threat to human health, safety, security, the environment or Company assets should be reported to your immediate supervisor ...

(Otero Aff., Ex. C at 2.)

[\[5\]](https://scholar.google.com/scholar_case?case=3111564132816580498&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34#r[5]) Plaintiff testified that he talked to Sanders about his site and says that he told him "exactly what it was ... I carry underground music, non-mainstream." (Otero Aff., Ex. B, Wiegand Vol. I Dep. at 117:21-118:4.) He testified that "everybody has their own perceptions of what is offensive" so that while "some people could call it offensive," it is "not to me, personally." (_Id._ at 118:10-22.) He does not consider his website "racist" because he "consider\[s\] it to be a place for people to buy music that they normally couldn't find in an average store. Underground music is what I classify it as." (_Id._ at 118:23-119:13.)

Plaintiff also says that he does "not cater to the views of a white supremacist or the Aryan Nation" on his website, but instead "gear\[s the site\] towards anybody that wants to buy my products" because "I carry what people ask for." (_Id._ at 140:13-17, 143:4-6, 151:15-16.)

[\[6\]](https://scholar.google.com/scholar_case?case=3111564132816580498&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34#r[6]) Plaintiff disputes several characterizations contained in the article. First, he asserts that "14 Word Press" never actually moved to Maple Shade, but that instead he simply purchased "a thousand or two thousand dollars worth" of its inventory, including "books and Viking jewelry, like rune stones." (_Id._ at 100:9-22, 104:21-24.) He admits, though, that he registered the trade name with the State of New Jersey on October 9, 2001, indicating that he was the "sole proprietor," and that he sold some "14 Word Press" inventory under the "14 Word Press" name. (_Id._ at 107:1-108:12, 111:7-112:7, 115:18-20.)

Second, plaintiff disputes the characterization that he is a "personal friend" of Katja Lane. He says that he always communicated with her as "Katja Maddox," that all his dealings with her were through e-mail, and that he never e-mailed her about her relationship with David Lane or about the White Supremacist Movement. (Otero Aff., Ex. B, Wiegand Vol. I Dep. at 88:25-95:23.) Plaintiff admits that he helped Katja design her original "14 Word Press" website about four years prior, but feels that he "wouldn't call that a personal friend, for somebody I've never met." (_Id._ at 93:1-25; Otero Aff., Ex. B, Wiegand Vol. II Dep. at 11:5-9.)

Third, plaintiff disputes the characterization of his company as a "neo-nazi, skinhead music company" because, while he sells skinhead music and Confederate and swastika flags, he has "all kinds of merchandise" and prefers not to classify his company. (_Id._ at 11:12-24.)

[\[7\]](https://scholar.google.com/scholar_case?case=3111564132816580498&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34#r[7]) The report is not part of the record because Judge Joel B. Rosen, United States Magistrate Judge, after reviewing the report, concluded that it is a confidential document that falls within the purview of the attorney-client privilege. (Otero Aff., Ex. I.)

[\[8\]](https://scholar.google.com/scholar_case?case=3111564132816580498&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34#r[8]) Plaintiff testified that he updates his site every day, (Otero Aff., Ex. B, Wiegand Vol. I Dep. at 185:8-9), and he admits that his site includes numerous references to Adolf Hitler as a "god," and to "nigger" hating, (_id._ at 185:18-189:11). Plaintiff testified, though, that he did not write everything that appears on his site, because others have access to his site for design and layout purposes, (_id._ at 159:15-10), asserts that he does not "refer to myself as a pro-white label, so that \[must have been\] edited," (_id._ at 161:9-10), and testified that he is not prejudiced against African Americans, Jews, or homosexuals, (_id._ at 176:1-8), but finds that his material is "funny," (_id._ at 189:6-15). While his site also continually refers to "our movement," plaintiff testified that he does not know what movement is being referred to. (_See, e.g. id._ at 191:23-192:24.)

[\[9\]](https://scholar.google.com/scholar_case?case=3111564132816580498&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34#r[9]) The number "88" is used throughout the site, as in "188% guaranteed" products, links to the "top 88 sites," and a message to "14/88 Steve." (_See_ Otero Aff., Ex. K at 1, 10; _id.,_ Ex. L at 1; _id.,_ Ex. N at 1; _id.,_ Ex. Q at 1.) The use of "88" is commonly used as an acronym for "Hail Hitler," based on the letter "H's" position as the eighth letter of the alphabet. _See, e.g._ www.acronymfinder.com. Plaintiff admits that the number 88 "can be used for Hail Hitler," but asserts that "I think the number 88 is a number, and that's it" because "I mean, people can use it for whatever purpose they want." (Otero Aff., Ex. B, Wiegand Vol. I Dep. at 169:5-173:21.)

[\[10\]](https://scholar.google.com/scholar_case?case=3111564132816580498&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34#r[10]) The moving party always bears the initial burden of showing that no genuine issue of material fact exists, regardless of which party ultimately would have the burden of persuasion at trial. _See_ [_Celotex Corp. v. Catrett,_ 477 U.S. 317, 323, 106 S.Ct. 2548, 91 L.Ed.2d 265 (1986)](https://scholar.google.com/scholar_case?case=774572446857633137&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34). However, where the nonmoving party bears the burden of persuasion at trial, "the burden on the moving party may be discharged by \`showing' — that is, pointing out to the district court — that there is an absence of evidence to support the nonmoving party's case." [_Celotex Corp.,_ 477 U.S. at 325, 106 S.Ct. 2548](https://scholar.google.com/scholar_case?case=774572446857633137&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34).

The non-moving party "may not rest upon the mere allegations or denials of" its pleading in order to show the existence of a genuine issue. Fed.R.Civ.P. 56(e). Plaintiff must do more than rely only "upon bare assertions, conclusory allegations or suspicions." [_Gans v. Mundy,_ 762 F.2d 338, 341 (3d Cir.1985),](https://scholar.google.com/scholar_case?case=11944887856998194370&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34) _cert. denied,_ [474 U.S. 1010, 106 S.Ct. 537, 88 L.Ed.2d 467 (1985)](https://scholar.google.com/scholar_case?about=7421616905690900327&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34) (citation omitted); _see_ [_Liberty Lobby,_ 477 U.S. at 249-50, 106 S.Ct. 2505](https://scholar.google.com/scholar_case?case=9272001251064530131&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34). Thus, if the plaintiff's evidence is a mere scintilla or is "not significantly probative," the court may grant summary judgment. [_Liberty Lobby,_ 477 U.S. at 249-50, 106 S.Ct. 2505](https://scholar.google.com/scholar_case?case=9272001251064530131&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34).

[\[11\]](https://scholar.google.com/scholar_case?case=3111564132816580498&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34#r[11]) Plaintiff argues that the Third Circuit's decision in [_Novosel v. Nationwide Insurance Co.,_ 721 F.2d 894, 900 (3d Cir.1983),](https://scholar.google.com/scholar_case?case=13017248077146087442&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34) should be followed. There, the Third Circuit, predicting Pennsylvania law, stated that:

The inquiry before us is whether the concern for the rights of political expression and association which animated the public employee cases is sufficient to state a public policy under \[state\] law. While there are no Pennsylvania cases squarely on this point, we believe that the clear direction of the opinions promulgated by the state's courts suggests that this question be answered in the affirmative.

Since _Novosel,_ though, Pennsylvania courts have not followed _Novosel_ and have not permitted a wrongful discharge cause of action under a constitutional provision absent a showing of state action. _See, e.g._ [_Veno v. Meredith,_ 357 Pa.Super. 85, 515 A.2d 571 (1986)](https://scholar.google.com/scholar_case?case=10731451989609279248&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34); [_Martin v. Capital Cities Media, Inc.,_ 354 Pa.Super. 199, 511 A.2d 830, 843-44 (1986)](https://scholar.google.com/scholar_case?case=11688656924355850505&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34). In 1992, therefore, the Third Circuit found:

In light of the narrowness of the public policy exception and of the Pennsylvania courts' continuing insistence upon the state action requirement, we predict that if faced with the issue, the Pennsylvania Supreme Court would not look to the First and Fourth Amendments as sources of public policy when there is no state action.

[_Borse v. Piece Goods Shop, Inc.,_ 963 F.2d 611, 620 (3d Cir.1992)](https://scholar.google.com/scholar_case?case=16360817838662612560&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34). Thus, the _Novosel_ decision does not control here, and, if anything, the later decision in _Borse_ supports defendants' reading of the public policy exception.

[\[12\]](https://scholar.google.com/scholar_case?case=3111564132816580498&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34#r[12]) A federal court exercising diversity jurisdiction must apply state law as declared by the highest state court and, when the state's highest court has not addressed an issue, the federal court must predict what its holding would be. [_Borman v. Raymark Indus., Inc.,_ 960 F.2d 327, 331 (3d Cir.1992)](https://scholar.google.com/scholar_case?case=1518480648502710305&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34) (citing [_Commissioner of Internal Revenue v. Estate of Bosch,_ 387 U.S. 456, 465, 87 S.Ct. 1776, 18 L.Ed.2d 886 (1967)](https://scholar.google.com/scholar_case?case=7945528639113457101&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34); [_Erie R.R. v. Tompkins,_ 304 U.S. 64, 71-80, 58 S.Ct. 817, 82 L.Ed. 1188 (1938)](https://scholar.google.com/scholar_case?case=4671607337309792720&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34)). Though both parties ask this Court to "predict" the law of New Jersey regarding the viability of a First Amendment wrongful termination claim in the private employment context, the Court finds that it is more appropriate in this case to abstain from determining the issue because even if a plaintiff could assert a First Amendment wrongful termination claim against a private actor, plaintiff could not sustain his claim here.

[\[13\]](https://scholar.google.com/scholar_case?case=3111564132816580498&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34#r[13]) The parties dispute which Employee Handbook governs, the 1994 version or the 2001 version, both which contain almost identically worded disclaimers. Which version controls is not material to this dispute because it is clear that plaintiff received the 1994 handbook, signed to indicate his agreement to its prominent disclaimer, and understood that he was an at-will employee.

[\[14\]](https://scholar.google.com/scholar_case?case=3111564132816580498&q=wiegand+v+motiva+enterprises+llc&hl=en&as_sdt=6,34#r[14]) Plaintiff asserts, and defendants did not contest, that plaintiff's version of Sanders' statement is not hearsay pursuant to Fed. R.Evid. 801(d)(1)(C) because it is being offered against a party (defendants Motiva and Starstaff) and was made by a person authorized to make the statement (Charles Sanders who had authority to make hiring and firing decisions for defendants). (Pl. 10/17/03 Ltr.)

Save trees - read court opinions online on Google Scholar.