---
title: Farwell v. Boston & W.R. Corp.
cite: 45 Mass. 49 (1842)
professor: "Eric M. Fink"
revised: 2025-08-24T18:30:43-04:00

subject: Employment Law
repo-url: 'emfink.net/EmploymentLaw'

author: Eric M. Fink
phone: 336-279-9334
appointments-url: 'calendly.com/emfink/'

institution: Elon University School of Law
address: 201 North Greene Street
city-state: Greensboro, North Carolina

term: 'Winter 2026'
room: 'Room 107'
meets: 'Mondays & Wednesdays, 10:30 am–12:15 pm'

format:
  pdf:
    template: case.tex
    keep-tex: true
    output-file: Farwell
---

This is an action of new impression in our courts, and involves a principle of great importance. It presents a case, where two persons are in the service and employment of one company, whose business it is to construct and maintain a rail road, and to employ their trains of cars to carry persons and merchandize for hire. They are appointed and employed by the same company to perform separate duties and services, all tending to the accomplishment of one and the same purpose--that of the safe and rapid transmission of the trains; and they are paid for their respective services according to the nature of their respective duties, and the labor and skill required for their proper performance. The question is, whether, for damages sustained by one of the persons so employed, by means of the carelessness and negligence of another, the party injured has a remedy against the common employer. It is an argument against such an action, though certainly not a decisive one, that no such action has before been maintained.

It is laid down by Blackstone, that if a servant, by his negligence, does any damage to a stranger, the master shall be answerable for his neglect. But the damage must be done while he is actually employed in the master’s service; otherwise, the servant shall answer for his own misbehavior. This rule is obviously founded on the great principle of social duty, that every man, in the management of his own affairs, whether by himself or by   his agents or servants, shall so conduct them as not to injure another; and if he does not, and another thereby sustains damage, he shall answer for it. If done by a servant, in the course of his employment, and acting within the scope of his authority, it is considered, in contemplation of law, so far the act of the master, that the latter shall be answerable civiliter.["answerable civiliter": subject to civil liability.]{.aside} But this presupposes that the parties stand to each other in the relation of strangers, between whom there is no privity; and the action, in such case, is an action sounding in tort. The form is trespass on the case, for the consequential damage. The maxim respondeat superior is adopted in that case, from general considerations of policy and security.

But this does not apply to the case of a servant bringing his action against his own employer to recover damages for an injury arising in the course of that employment, where all such risks and perils as the employer and the servant respectively intend to assume and bear may be regulated by the express or implied contract between them, and which, in contemplation of law, must be presumed to be thus regulated.

The same view seems to have been taken by the learned counsel for the plaintiff in the argument; and it was conceded, that the claim could not be placed on the principle indicated by the maxim respondeat superior, which binds the master to indemnify a stranger for the damage caused by the careless, negligent or unskilful act of his servant in the conduct of his affairs. The claim, therefore, is placed, and must be maintained, if maintained at all, on the ground of contract. As there is no express contract between the parties, applicable to this point, it is placed on the footing of an implied contract of indemnity, arising out of the relation of master and servant. It would be an implied promise, arising from the duty of the master to be responsible to each person employed by him, in the conduct of every branch of business, where two or more persons are employed, to pay for all damage occasioned by the negligence of every other person employed in the same service. If such a duty were established by law--like that of a common carrier, to stand to all losses of goods not caused by the act of God or  of a public enemy--or that of an innkeeper, to be responsible, in like manner, for the baggage of his guests; it would be a rule of frequent and familiar occurrence, and its existence and application, with all its qualifications and restrictions, would be settled by judicial precedents. But we are of opinion that no such rule has been established, and the authorities, as far as they go, are opposed to the principle.

The general rule, resulting from considerations as well of justice as of policy, is, that he who engages in the employment of another for the performance of specified duties and services, for compensation, takes upon himself the natural and ordinary risks and perils incident to the performance of such services, and in legal presumption, the compensation is adjusted accordingly. And we are not aware of any principle which should except the perils arising from the carelessness and negligence of those who are in the same employment. These are perils which the servant is as likely to know, and against which he can as effectually guard, as the master. They are perils incident to the service, and which can be as distinctly foreseen and provided for in the rate of compensation as any others. To say that the master shall be responsible because the damage is caused by his agents, is assuming the very point which remains to be proved. They are his agents to some extent, and for some purposes; but whether he is responsible, in a particular case, for their negligence, is not decided by the single fact that they are, for some purposes, his agents. It seems to be now well settled, what ever might have been thought formerly, that underwriters cannot excuse themselves from payment of a loss by one of the perils insured against, on the ground that the loss was caused by the negligence or unskilfulness of the officers or crew of the vessel, in the performance of their various duties as navigators, although employed and paid by the owners, and, in the navigation of the vessel, their agents. I am aware that the maritime law has its own rules and analogies,  and that we cannot always safely rely upon them in applying them to other branches of law. But the rule in question seems to be a good authority for the point, that persons are not to be responsible, in all cases, for the negligence of those employed by them.

If we look from considerations of justice to those of policy, they will strongly lead to the same conclusion. In considering the rights and obligations arising out of particular relations, it is competent for courts of justice to regard considerations of policy and general convenience, and to draw from them such rules as will, in their practical application, best promote the safety and security of all parties concerned. This is, in truth, the basis on which implied promises are raised, being duties legally inferred from a consideration of what is best adapted to promote the benefit of all persons concerned, under given circumstances. To take the well known and familiar cases already cited; a common carrier, without regard to actual fault or neglect in himself or his servants, is made liable for all losses of goods confided to him for carriage, except those caused by the act of God or of a public enemy, because he can best guard them against all minor dangers, and because, in case of actual loss, it would be extremely difficult for the owner to adduce proof of embezzlement, or other actual fault or neglect on the part of the carrier, although it may have been the real cause of the loss. The risk is therefore thrown upon the carrier, and he receives, in the form of payment for the carriage, a premium for the risk which he thus assumes. So of an innkeeper; he can best secure the attendance of honest and faithful servants, and guard his house against thieves. Whereas, if he were responsible only upon proof of actual negligence, he might connive at the presence of dishonest inmates and retainers, and even participate in the embezzlement of the property of the guests, during the hours of their necessary sleep, and yet it would be difficult, and often impossible, to prove these facts.

The liability of passenger carriers is founded on similar considerations. They are held to the strictest responsibility for care, vigilance and skill, on the part of themselves and all persons  employed by them, and they are paid accordingly. The rule is founded on the expediency of throwing the risk upon those who can best guard against it. 

We are of opinion that these considerations apply strongly to the case in question. Where several persons are employed in the conduct of one common enterprise or undertaking, and the safety of each depends much on the care and skill with which each other shall perform his appropriate duty, each is an observer of the conduct of the others, can give notice of any misconduct, incapacity or neglect of duty, and leave the service, if the common employer will not take such precautions, and employ such agents as the safety of the whole party may require. By these means, the safety of each will be much more effectually secured, than could be done by a resort to the common employer for indemnity in case of loss by the negligence of each other. Regarding it in this light, it is the ordinary case of one sustaining an injury in the course of his own employment, in which he must bear the loss himself, or seek his remedy, if he have any, against the actual wrong-doer.

In applying these principles to the present case, it appears that the plaintiff was employed by the defendants as an engineer, at the rate of wages usually paid in that employment, being a higher rate than the plaintiff had before received as a machinist. It was a voluntary undertaking on his part, with a full knowledge of the risks incident to the employment; and the loss was sustained by means of an ordinary casualty, caused by the negligence of another servant of the company. Under these circumstances, the loss must be deemed to be the result of a pure accident, like those to which all men, in all employments, and at all times, are more or less exposed; and like similar losses from accidental causes, it must rest where it first fell, unless the plaintiff has a remedy against the person actually in default; of which we give no opinion.

It was strongly pressed in the argument, that although this might be so, where two or more servants are employed in the same department of duty, where each can exert some influence over the conduct of the other, and thus to some extent provide for his own security; yet that it could not apply where two or more are employed in different departments of duty, at a distance from each other, and where one can in no degree control or influence the conduct of another. But we think this is founded upon a supposed distinction, on which it would be extremely difficult to establish a practical rule. When the object to be accomplished is one and the same, when the employers are the same, and the several persons employed derive their authority and their compensation from the same source, it would be extremely difficult to distinguish, what constitutes one department and what a distinct department of duty. It would vary with the circumstances of every case. If it were made to depend upon the nearness or distance of the persons from each other, the question would immediately arise, how near or how distant must they be, to be in the same or different departments. In a blacksmith’s shop, persons working in the same building, at different fires, may be quite independent of each other, though only a few feet distant. In a ropewalk, several may be at work on the same piece of cordage, at the same time, at many hundred feet distant from each other, and beyond the reach of sight and voice, and yet acting together.

Besides, it appears to us, that the argument rests upon an assumed principle of responsibility which does not exist. The master, in the case supposed, is not exempt from liability, because the servant has better means of providing for his safety, when he is employed in immediate connexion with those from whose negligence he might suffer; but because the implied contract of the master does not extend to indemnify the servant against the negligence of any one but himself; and he is not liable in tort, as for the negligence of his servant, because the person suffering does not stand towards him in the relation of a stranger, but is one whose rights are regulated by contract express or implied. The exemption of the master, therefore, from   liability for the negligence of a fellow servant, does not depend exclusively upon the consideration, that the servant has better means to provide for his own safety, but upon other grounds. Hence the separation of the employment into different departments cannot create that liability, when it does not arise from express or implied contract, or from a responsibility created by law to third persons, and strangers, for the negligence of a servant.

A case may be put for the purpose of illustrating this distinction. Suppose the road had been owned by one set of proprietors whose duty it was to keep it in repair and have it at all times ready and in fit condition for the running of engines and cars, taking a toll, and that the engines and cars were owned by another set of proprietors, paying toll to the proprietors of the road, and receiving compensation from passengers for their carriage; and suppose the engineer to suffer a loss from the negligence of the switch-tender. We are inclined to the opinion that the engineer might have a remedy against the rail road corporation; and if so, it must be on the ground, that as between the engineer employed by the proprietors of the engines and cars, and the switch-tender employed by the corporation, the engineer would be a stranger, between whom and the corporation there could be no privity of contract; and not because the engineer would have no means of controlling the conduct of the switchtender.["switchtender": A railroad employee responsible for operating track switches.] The responsibility which one is under for the negligence of his servant, in the conduct of his business, towards third persons, is founded on another and distinct principle from that of implied contract, and stands on its own reasons of policy. The same reasons of policy, we think, limit this responsibility to the case of strangers, for whose security alone it is established. Like considerations of policy and general expediency forbid the extension of the principle, so far as to warrant a servant in maintaining an action against his employer for an indemnity which we think was not contemplated in the nature and terms of the employment, and which, if established, would not conduce to the general good.

In coming to the conclusion that the plaintiff, in the present case, is not entitled to recover, considering it as in some measure  a nice question, we would add a caution against any hasty conclusion as to the application of this rule to a case not fully within the same principle. It may be varied and modified by circumstances not appearing in the present case, in which it appears, that no wilful wrong or actual negligence was imputed to the corporation, and where suitable means were furnished and suitable persons employed to accomplish the object in view. We are far from intending to say that there are no implied warranties and undertakings arising out of the relation of master and servant. Whether, for instance, the employer would be responsible to an engineer for a loss arising from a defective or ill-constructed steam engine: Whether this would depend upon an implied warranty of its goodness and sufficiency, or upon the fact of wilful misconduct, or gross negligence on the part of the employer, if a natural person, or of the superintendent or immediate representative and managing agent, in case of an incorporated company--are questions on which we give no opinion. In the present case, the claim of the plaintiff is not put on the ground that the defendants did not furnish a sufficient engine, a proper rail road track, a well constructed switch, and a person of suitable skill and experience to attend it; the gravamen of the complaint is, that that person was chargeable with negligence in not changing the switch, in the particular instance, by means of which the accident occurred, by which the plaintiff sustained a severe loss. It ought, perhaps, to be stated, in justice to the person to whom this negligence is imputed, that the fact is strenuously denied by the defendants, and has not been tried by the jury. By consent of the parties, this fact was assumed without trial, in order to take the opinion of the whole court upon the question of law, whether, if such was the fact, the defendants, under the circumstances, were liable. Upon this question, supposing the accident to have occurred, and the loss to have been caused, by the negligence of the person employed to attend to and change the switch, in his not doing so in the particular case, the court are of opinion that it is a loss for which the defendants are not liable, and that the action cannot be maintained.