---
title: Syllabus
professor: "Eric M. Fink"
revised: 2025-08-24T18:30:43-04:00

subject: Employment Law
repo-url: 'emfink.net/EmploymentLaw'

author: Eric M. Fink
phone: 336-279-9334
appointments-url: 'calendly.com/emfink/'

institution: Elon University School of Law
address: 201 North Greene Street
city-state: Greensboro, North Carolina

term: 'Winter 2025'
room: 'Room 105'
meets: 'Mondays & Wednesdays, 10:30 am–12:15 pm'

format:
  pdf:
    template: syllabus_template.tex
    keep-tex: true
    output-file: EmploymentLawSyllabus

---

## Description {.unnumbered}

This course surveys federal and state laws governing employment, in both the individual and organized labor settings. Topics to be covered include establishing an employment relationship; recruitment & hiring; the scope and limits of supervisory control; confidentiality & competition; wages & hours; employee health & safety; and termination of employment. 

After completing the course, you should be able to recognize and diagnose legal issues arising in the employment context, analyze those issues under the applicable law, and help clients avoid legal problems or pursue remedies when they arise. Simulation problems, including in-class discussion and take-home assignments, provide an opportunity to develop practical skills for representing clients in employment matters.

## Course Materials {.unnumbered}

### Required

Employment Law: An Open-Source Casebook. Available on the course website: [emfink.net/EmploymentLaw](http://www.emfink.net/EmploymentLaw).  

Rachel Arnow-Richman & Nantiya Ruan, Developing Professional Skills: Workplace Law (West Academic 2017) ("Workbook"). 

### Suggested

Ann Hodges & Rafael Gely, Principles of Employment Law (West Academic 2016). Digital version available at no cost through the [West Academic Online Study Aids Collection](https://subscription.westacademic.com/).

## Policies {.unnumbered}

### Grading

Your final grade for the term will be based on three problem assignments (25% each; 75% total) and your contributions to in-class discussion (25%). There will be no final exam or paper for this course.

The graded problem assignments (from the _Developing Professional Skills_ workbook) and due dates are indicated in the "Schedule & Assignments" section of the syllabus. I will provide further information about each assignment in class before it is due. 

### Attendance

Elon Law School has adopted the following attendance policy for all courses:

> The Law School administers a policy that a student maintain regular and punctual class attendance in all courses in which the student is registered, including externships, clinical courses, or simulation courses. Faculty members will give students written notice of their attendance policies before or during the first week of class. These policies may include, but are not limited to: treating late arrivals, early departures, and/or lack of preparation as absences  imposing grade or point reductions for absences, including assigning a failing grade or involuntarily withdrawing a student from the class  and any other policies that a professor deems appropriate to create a rigorous and professional classroom environment.
>  
> In case of illness or emergency, students may contact the Office of Student and Professional Life, which will then notify the student’s instructors. A student may notify the faculty member directly of a planned absence and should refer to individual faculty members regarding any policy that may apply. In the case of prolonged illness or incapacity, the student should contact the [Office of Student Life](https://www.elon.edu/u/law/students/).

You should let me know (in advance if feasible) if you are unable to attend class, will arrive late, or must leave early. I do not require an explanation of the reason, nor do I require a doctor's note or other documentation.

### Disability Accommodations

For disability accommodation requests, contact the [Elon Disability Services Office](https://www.elon.edu/u/academics/koenigsberger-learning-center/disabilities-resources/homepage/graduate-student-resources/).

### Honor Code

The Law School [honor code](https://www.elon.edu/u/law/students/honor-code/) applies to all activities related to your law school study, including conduct during class and examinations.

## Schedule & Assignments {.unnumbered}

 **Date** | **Topic**  | **Assignment**
--|---|--
 &nbsp; | &nbsp; | &nbsp;
 &nbsp; | **Foundations of Employment Law** | &nbsp;
 January 6 | Employment as a Socio-Legal Relationship | Casebook, Chap. 1
 January 8 | Labor Organizing & Collective Bargaining | Casebook, Chap. 2
 &nbsp; |  &nbsp; |  &nbsp;
 &nbsp; | **Establishing an Employment Relationship** | &nbsp;
 January 13 | Identifying Employees | Casebook, Chap. 3, § 1 
 January 15 | Identifying Employers | Casebook, Chap. 3, § 2 
 January 22  | Recruitment & Hiring |  Casebook, Chap. 3, § 3
 January 27 | **Assignment 1 due** | The Canine Trainer (Workbook, Chap. 1)
 &nbsp; |  &nbsp; |  &nbsp;
 &nbsp; | **Scope & Limits of Employer Control** | &nbsp;
 January 27 | Privacy, Autonomy, & Dignity  | Casebook, Chap. 4, § 1.1
 January 29 | Workplace Rules & Protected Concerted Activity | Casebook, Chap. 4, § 1.2
 February 3 | Control Outside Work | Casebook, Chap. 4, § 2
 &nbsp; |  &nbsp; |  &nbsp;
 &nbsp; | **Employee Duties to Employers** | &nbsp;
 February 5 | Confidentiality | Casebook, Chap. 5, § 1
 February 10 | Loyalty | Casebook, Chap. 5, § 2
 February 17 | **Assignment 2 due** | The Doctor Is In (Workbook, Chap. 5)
 &nbsp; |  &nbsp; |  &nbsp;
 &nbsp; | **Wages & Hours** | &nbsp;
 February 12 & 17 | Minimum Wage, Overtime, & Wage Payments | Casebook, Chap. 6
 &nbsp; |  &nbsp; |  &nbsp;
 &nbsp; | **Employee Health & Safety** | &nbsp;
 February 19 | Medical Leave & Disability Discrimination | Casebook, Chap. 7, §§ 1 & 2
 February 24 | OSHA & Workers' Compensation | Casebook, Chap. 7, §§ 3 & 4
 &nbsp; |  &nbsp; |  &nbsp;
 &nbsp; | **Terminating Employment** | &nbsp;
 February 26 | Employment-at-Will | Casebook, Chap. 8, § 1.1
 March 3 | Contractual Claims | Casebook, Chap. 8, § 1.2
 March 5 | Tort Claims | Casebook, Chap. 8, § 1.3
 March 10 | Statutory Claims | Casebook, Chap. 8, § 1.4
 March 12  | Unemployment Compensation | Casebook, Chap. 8, § 2
 March 17 | Make-Up Class (if needed) | &nbsp;
 March 17 | **Assignment 3 due** | The Smart-Tek IPO (Workbook, Chap. 4)

 N.B. This class will not meet on Monday, January 20th (Martin Luther King, Jr. Day)