# Discussion Problem: Confidentiality {.unnumbered}

MegaMedia, Inc. is a major producer and distributor of movies and television programs. The CEO of MegaMedia, Harry Whitestone, has a reputation for egregious treatment of female employees. Several woman have threatened to sue over sexual harassment and abuse by Whitestone while they worked at MegaMedia. To avoid the inevitable negative publicity, the company has settled those claims before any suits were filed. Despite this, the company has allowed Whitestone to remain as CEO, because he is such a successful producer and powerful figure within the industry. Instead, in an effort to avoid further legal claims and settlement payments, the company requires all new hires and current employees to sign the following non-disclosure agreement: 

1. I understand that MegaMedia, Inc. ("Company") is involved in the entertainment industry. I further understand that because Company's business requires a creative working environment, including exposure to offensive speech, I may be exposed to conduct and speech that openly and explicitly relates to sex as well as race, sexual orientation, gender, national origin, religion, disability and age. 
2. I acknowledge that I may be privy to conversations where offensive speech (e.g. their work, scripts or roles that involve nudity, sexual scenarios, racial epithets, suggestive gestures, profanity and references to stereotypes) is utilized. 
3. I understand and acknowledge that as part of my job I may be exposed to speech and conduct that explicitly relates to sex, sexual orientation, gender, national origin, religion, disability and age. 
4. I expressly agree and represent that I do not object to being exposed to such speech and conduct and do not find it otherwise offensive or objectionable, and that I am willing to work in such an environment. 
5. I expressly agree not to disclose information about the working environment and creative process at the Company, including conduct or speech as described above, except as expressly authorized by the Company. This agreement includes, but is not limited to, communications with other Company employees, news or entertainment media, or other persons or entities outside the Company. 

Faye Greener is an actress who has been cast in several MegaMedia productions. Whitestone repeatedly subjected Greener to sexually suggestive remarks and unwanted physical contact. Fed up with Whitestone's behavior, she decides to speak out. She meets with other women who she worked with on MegaMedia productions and they share their experiences of harassment and abuse by Whitestone. Greener then contacts a reporter who covers the movie industry, revealing details about Whitestone's conduct and the company's complicity. Finally, she files an employment discrimination complaint with the EEOC and provides information about her experiences to EEOC officials as part of the agency's investigation into the complaint. 

- Would the non-disclosure agreement be legally enforceable against Greener for any of her actions? 
- If Greener proceeds with a lawsuit against MegaMedia and Whitestone, can the defendants rely on the non-disclosure agreement to establish that Greener did not find Whitestone's conduct to be offensive or objectionable? 
