# Discussion Problem: Employee Loyalty & Concerted Activity {.unnumbered}

Norma Rae Wilson [^NormaRae1] works at the O.P. Henry textile plant in Henleyville, North Carolina. She is an active supporter of a labor organizing campaign by the Textile Workers Union of America (TWUA). She tells union organizer Reuben Warshowsky that the company posted a letter on a bulletin board in the plant, saying "Black employees are being told that by going into the union in mass they can dominate it and control it and this plant as they may see fit." Warshowsky instructs Wilson to go back and "copy it down, line by line, word for word". 
 
Wilson returns to the plant and begins transcribing the letter. A plant manager approaches and tells her "You can't take down that letter." "It's up here on the bulletin board, and I'm gonna copy it," she replies. Ignoring a further warning from the manager, Wilson finishes copying the letter. The manager then tells her, "I don't want you on the premises. You make a phone call to your husband and tell him to come fetch you. I want you out of here quick," warning that the police have been called. Instead, Wilson climbs onto a table, in full view of the other employees, holding a piece of cardboard on which she has written the word "UNION". In response, the other employees shut down their machines. When the police arrive, Wilson climbs down from the table and is escorted out of the plant into a police car. 
 
Lucius White, another textile plant employee and union supporter, gives Wilson and Warshowsky copies of a [video recording of the incident](../video/NormaRae.mp4), which he made on his mobile phone. Wilson, White, and Warshowsky post the video on YouTube and Instagram, writing "This is why workers at O.P. Henry need a union, to end the company's racist, sexist, and abusive practices!" The Union also distributes copies of the video and the letter to local and national media outlets, in support of the Union's call for a consumer boycott of the company's products. 
 
A few days later, the company fires Wilson and White for violating the company's confidentiality policy and rules against using cameras and recording devices in the plant. The Union then files an [Unfair Labor Practice charge](../exhibits/ULPChargeForm.pdf) with the National Labor Relations Board. 

The company also files a lawsuit against Wilson and White under N.C.G.S. ยง99-A-2(b)(1) & (2) and against the union and Warshowsky under ยง99-A-2(c). 

1. Assume you are an attorney for the company. How would you advise your client regarding the ULP charge and its possible defenses? 

2. Assume you are an attorney for the union and the individual defendants in the company's ยง99-A suit. How would you advise your clients regarding their potential liability under that statute and their options in response to the suit? 

[^NormaRae1]: The movie [_Norma Rae_](https://catalog.afi.com/Catalog/moviedetails/56122) is [based on the experience of Crystal Lee Sutton](https://apwu.org/news/real-norma-rae), a textile mill worker and union supporter, in an [organizing campaign at the J.P. Stevens plant](https://southernspaces.org/2014/good-faith-working-class-women-feminism-and-religious-support-struggle-organize-j-p-stevens-textile-workers-southern-piedmont-1974-1980/) in Roanoke Rapids, North Carolina. During the J.P. Stevens campaign, the union filed, and the NLRB sustained, numerous [unfair labor practice charges](../exhibits/NLRB_Notice_JPStevens.pdf) against the company. The union also promoted a consumer boycott to protest the company's labor practices. _See_ [@Minchin2005]. Employees at the Roanoke Rapids plant eventually voted in favor of representation by the Amalgamated Clothing & Textile Workers Union. However, a few years later, J.P. Stevens closed the plant, moving the work to facilities outside the U.S. 
