# Recruitment & Hiring

## Employment References 

### Desai v. Charter Communications, LLC, 381 F.Supp.3d 774 (W.D. Ky. 2019)

Plaintiffs alleged that their former employer, Charter Communications, LLC, falsely accused them of theft after their employment was terminated. Following a weeklong trial, a jury agreed, finding Charter liable for defamation per se. Charter has moved for judgment as a matter of law or a new trial. In the alternative, it seeks reduction of the damage award. For the reasons explained below, the Court will reduce the punitive damages and deny Charter's motion in all other respects.

#### Background

The Court previously summarized the facts of this case as follows:

> Plaintiffs worked at Charter's call center in Louisville, Kentucky, in various capacities. Each was given a Hewlett-Packard (HP) computer printer by Linda Showalter, an administrative assistant at Charter. Plaintiffs maintain that they believed Showalter's distribution of printers was authorized by management. Charter, however, considered Plaintiffs' acceptance of the printers to be a violation of its policy against removing company property without authorization, and it terminated most of the employees involved.
> 
> Approximately one month after Plaintiffs were fired, Charter Human Resources Manager Rodger Simms gave a PowerPoint presentation during a Charter leadership conference. On a slide with the heading "Leadership and Judgment," Simms referred to "'Operation' Green-light, Buzz-kill, Printer-gate." He encouraged employees to "act with Integrity and Character." The notes for Simms's oral presentation accompanying the slide state: "Let's get the elephant in the room out in the open, how many of you have heard of Operation codes for things that weren't right! All examples of poor judgment. Not bad people, people we know and love but they made the wrong choices." Simms emphasized the importance of "integrity," "character," and having "the courage to do the right thing." He also warned that "knowing something isn't right and allowing it to continue is the same as you doing it!" "Green-light" referred to an incident in which a Charter employee used a company credit card for personal benefit and was terminated as a result. "Buzz-kill" involved the sale of illegal drugs on Charter property by Charter employees; those employees were also terminated.
> 
> Plaintiffs sued Charter for defamation on the ground that "Charter made false statements alleging misconduct on the part of the Plaintiffs relating to the distribution of Hewlett-Packard ink jet printers, including but not limited to the PowerPoint presentation." They contend that the use of the term "Printer-gate," particularly in conjunction with references to employee theft and drug-dealing, implied that their actions were criminal.

The case was tried solely on a theory of defamation per se. At the close of Plaintiffs' case, Charter moved for judgment as a matter of law, arguing that "Printer-gate" could not constitute defamation per se because it had no "objectively understood definition" and was not defamatory on its face; that Plaintiffs had no proof of damages to support a claim of defamation per quod; and that any inference arising from "Printer-gate" was true because the term referred to "an incident involving the unauthorized removal of company printers from Charter's premises." The Court denied that motion and later granted Plaintiffs' motion for judgment as a matter of law on Charter's truth defense, concluding that there was insufficient evidence from which a reasonable jury could find that Plaintiffs' actions constituted criminal theft. The jury ultimately found Charter liable, awarding each plaintiff $350,000 in compensatory damages and $1 million in punitive damages. The Court entered judgment for Plaintiffs in accordance with the jury's verdict, and Charter timely sought relief under Rules 50 and 59 of the Federal Rules of Civil Procedure.

#### Analysis

Charter renews its motion for judgment as a matter of law on the issue of whether the term "Printer-gate" can constitute defamation per se. It further argues that it is entitled to a new trial on the grounds that it should have been allowed to present the defenses of truth and qualified privilege; that James Eversole's testimony was admitted in error; and that the jury was required to find malice by clear and convincing evidence in order to award punitive damages. 

##### Defamation Per Se

As it has on numerous prior occasions, Charter argues that the term "Printer-gate" cannot constitute defamation per se. Charter first asserts that there was no evidence to support a finding that Simms's presentation imputed criminal conduct to Plaintiffs. It further contends that the Court, not the jury, should have determined whether defamation per se occurred. Neither argument is persuasive.

**1. Sufficiency of the Evidence**

According to Charter, "on the evidence presented at trial, no reasonable jury could have concluded that the use of the term 'Printer-gate' suggested that the Plaintiffs had engaged in theft." But that was not the issue before the jury; the Court had already found, as a matter of law, that the term was "capable of bearing a defamatory meaning." The jury was tasked with deciding whether the "Printer-gate" reference "was reasonably understood by persons who heard it as accusing the plaintiffs of criminal theft."

Charter observes that "multiple witnesses who attended the presentation testified that they did not understand the term to suggest anything criminal at all." It cites the testimony of current Charter employees Mike Barnard, Sandi Streicher, and Theo Carney defining "Printer-gate" as they understood it. Charter acknowledges, however, that two witnesses who attended the meeting—Samantha Little and James Eversole—testified that they understood the term to imply that Plaintiffs had stolen from the company. Contrary to Charter's representation, Little did not merely "testify vaguely that the term 'insinuates that some type of illegal activity had been performed'"; she also testified that she interpreted it as referring to theft. And Eversole, in addition to his statement that the presentation "kind of compared Plaintiffs to gambling and murder", stated that

> the message that was given during the summit didn't really filter into the conversations that were afterward. Those particular conversations were like, oh, well, _that was the time that we fired a bunch of people because they stole equipment._ Like don't do it, like don't take anything from the company.

Thus, both Little and Eversole provided testimony supporting the jury's verdict.

Charter next asserts that Little's testimony cannot support the verdict because "the vague inference of illegal activity that Little drew from the presentation depended entirely on coupling "Printer-gate" with the two other incidents mentioned in the same presentation (Green-light and Buzz-kill) _and_ upon knowledge of what those incidents involved." According to Charter, "Kentucky courts long ago decided that merely mentioning an incident involving the plaintiff in the same context as incidents involving illegal conduct cannot be treated as implying that the plaintiff engaged in some illegality." The single case it cites in support of this contention, _Boyd v. Hutton,_ 196 Ky. 512 (1922), made no such proclamation and involved starkly different facts.

In _Boyd,_ the plaintiff alleged that he was defamed by a 1920 newspaper report, clearly offensive by today's standards, that read: "Last Thursday night there were lots of fireworks in Harrodsburg. Jim Boyd, colored, claimed that someone shot him through an open window while he was reading, or lacing his shoes. The shots covered nearly all of his entire body." The report appeared under the same headline—"Shootings in Town"—as reports that another person had "shot at a chicken thief the same night" and a third person "shot at a prowler on his premises." Boyd argued that "the reporting of the three news items in one article was intended to connect him with one of the other two shootings, and did in fact impute to him conduct of a disgraceful or degrading nature." In a four-paragraph opinion affirming the directed verdict in favor of the defendant, the court found Boyd's "construction of the article to be wholly fanciful, for it certainly is not warranted by any fair interpretation of the publication itself." 

The Court finds Charter's reliance on _Boyd_ curious in light of the case's historical context; given this context, and the opinion's limited analysis, it has little precedential value. In any event, the facts are clearly distinguishable from those at issue here. Simms's presentation explicitly linked "Printer-gate" to the drug and embezzlement incidents, describing them as "all examples of poor judgment" in which the individuals involved "made the wrong choices." Moreover, as discussed above, there was testimony that some Charter employees who attended the presentation construed the "Printer-gate" reference as imputing criminal conduct to Plaintiffs; in _Boyd,_ there was apparently no testimony beyond the plaintiff's own. In short, _Boyd_ does not preclude consideration of the context in which the "Printergate" reference was made—indeed, even Charter has acknowledged that allegedly defamatory words "_must_ be evaluated in context." 

Viewing the evidence in the light most favorable to Plaintiffs and drawing all reasonable inferences in their favor, the Court concludes that there was sufficient evidence to support the jury's verdict.

**2. Definition of Defamation Per Se**

Charter's overarching argument is that the "Printer-gate" reference in Simms's presentation cannot constitute defamation per se because it requires consideration of extrinsic circumstances. The definition of defamation per se has been a point of contention throughout this case, despite the Kentucky Supreme Court and Court of Appeals' numerous declarations that a statement falsely imputing crime—particularly theft—constitutes defamation per se. 

Notwithstanding this extensive precedent, Charter insists that "Printer-gate" cannot be defamation per se because it is not defamatory on its face. Quoting _Stringer v. Wal-Mart Stores, Inc_., 151 S.W.3d 781 (Ky. 2004), Charter repeatedly asserts that "'if a comprehension of the defamatory nature of the written or spoken words requires extrinsic evidence of context or circumstances,' then the statement can solely be 'libelous or slanderous per quod' and 'special damages, _i.e.,_ actual injury to reputation, must be affirmatively proved.'" By taking this passage out of context, however, Charter misses its point:

> In comparison to slanderous per se oral statements, which must contain defamatory language of a specific nature, the common law treats a broader class of written defamatory statements as actionable per se: "while spoken words are slanderous per se only if they impute crime, infectious disease, or unfitness to perform duties of office, or tend to disinherit him, written or printed publications, which are false and tend to injure one in his reputation or to expose him to public hatred, contempt, scorn, obloquy, or shame, are libelous per se." All other defamatory statements are merely libelous or slanderous per quod, and special damages, i.e., actual injury to reputation, must be affirmatively proved if a comprehension of the defamatory nature of the written or spoken words requires extrinsic evidence of context or circumstances. We need not belabor this discussion further, however, because a "false accusation of theft is actionable per se—that is, libelous or slanderous per se." Accordingly, Appellants were not required to provide affirmative proof of injury to their reputations in order to recover for the defamatory statements at issue in this case.

In other words, certain types of statements—including false accusations of theft—are presumed to have damaged the plaintiffs' reputations, and thus no proof of injury resulting from such statements is required: they are "actionable per se." "All _other_ defamatory statements are merely libelous or slanderous per quod"; these require "affirmative proof of injury to the plaintiffs' reputations." Charter's contention that the per se/per quod determination turns on whether extrinsic proof is needed to interpret the statement as defamatory is thus misguided; it is instead "the proof necessary to demonstrate an injury to reputation" that "varies depending upon the characterization of the defamatory language" as defamation per se or per quod.

Like the instant case, _Stringer_ involved terminated employees who alleged that they were later falsely painted as thieves by their former employer. One of the statements at issue was that "there was more to the plaintiffs' firing than" eating candy from open bags (known as "claims candy"). The _Stringer_ court concluded that this statement alone was enough to support the jury's finding of defamation per se.

Clearly, the words "there was more to it than that" are not, on their face, defamatory. Nor was the statement an obvious reference to theft even if placed in context: an assistant manager, "when asked whether the plaintiffs had been terminated for eating candy from the claims area, responded that "'there was more to it than that" and that he couldn't talk about it.'" Indeed, as in this case, the context (with its reference to "claims candy" or "candy from the claims area") likely would not have been understood by a non-employee. Yet because another employee testified that she interpreted the statement "as an assertion that the plaintiffs had stolen items in addition to claims candy," it was sufficient to support a verdict in favor of the plaintiffs. Charter's contention that the jury could not properly consider the context in which "Printer-gate" was discussed is therefore unavailing.

At bottom, the dispute over the characterization of "Printer-gate" is whether it is _actionable_ per se or per quod—i.e., whether Plaintiffs should have been required to prove damages. As explained in _Stringer,_ no proof of damages is required where the statement amounts to an accusation of theft, whether direct or indirect. Charter is thus not entitled to judgment as a matter of law on this ground.

##### Truth Defense

Charter seeks a new trial on the ground that the Court "erred by granting judgment foreclosing the defense of truth." It contends that this "defense should have gone to the jury as long as there was evidence in the record—from any source—sufficient to permit a reasonable jury to conclude that Plaintiffs' actions met the definition of theft." The two cases it cites in support of this contention state no such rule. Charter next cites the Kentucky model jury instruction for theft by unlawful taking, asserting that "proving the defense of truth simply required evidence from which a jury could conclude" that the three statutory elements of theft were met. Those elements, as set out in the criminal pattern instruction, are (1) that Plaintiffs took property that belonged to Charter; (2) that in so doing, they knew the property was not their own and were not acting under a claim of right to it; and (3) that in taking the property, Plaintiffs intended to deprive Charter of it.

The Court notes that Charter objected at trial to application of the statutory definition of theft (which formed part of the model instruction on defamation per se), and its counsel admitted that no witness had referred to Plaintiffs' conduct as criminal. In fact, Charter's company representative, Mike Barnard, testified unequivocally that Plaintiffs "did not have the intent to steal" and did not steal from Charter. Each of the plaintiffs testified that there was nothing surreptitious about their taking of the printers; some testified that they didn't even need or want the printers but accepted them at Showalter's repeated urging. All testified that they believed Showalter's distribution of the printers was authorized by management. 

Charter nevertheless argues that "there was ample evidence from which the jury could have concluded that the Plaintiffs knew that they did not have legitimate permission to take company property, and that they did so anyway." In support, it first points to various Charter policies and Plaintiffs' acknowledgment that they failed to independently seek authorization from a manager before accepting the printers. According to Charter, "Plaintiffs' decisions _not_ to follow known procedures provides evidence that Plaintiffs knew they did not have authorization to take company property and it could give rise to a reasonable inference that Plaintiffs did not ask for authorization because they knew they would not like the answer they would get." Such an inference is not reasonable, however, in light of the overwhelming evidence—including from Charter's own representative—that Plaintiffs lacked criminal intent.

Charter next asserts that Showalter lacked either actual or apparent authority to distribute the printers because "none of the Plaintiffs testified that a manager at Charter suggested to them that Ms. Showalter had authority to give away the printers." Whether the evidence establishes apparent authority as a matter of Kentucky agency law is of little relevance, however. It is now undisputed that Showalter was not authorized to distribute the printers. The fact that she may have lacked legal authority says nothing about Plaintiffs' state of mind, i.e., whether Plaintiffs "knew the printers were not their own" and thus intended to steal them. Meanwhile, Plaintiffs' testimony that they believed Showalter was authorized to give them the printers fits neatly into Kentucky's "claim of right" defense to theft, which applies if the defendant "had the permission, or believed he had the permission, of the victim or some other person authorized to give permission to take the property.

Charter's final assertion, that "there was evidence that Plaintiffs knew their conduct was improper, because they _lied_ about how they got the printers to make their actions appear legitimate," likewise barely warrants discussion. As evidence of Plaintiffs' purported dishonesty, Charter cites an exhibit attached to each plaintiff's interrogatory answers that characterized the printers as having been "apparently passed out as part of an incentive program with the knowledge of management." Plaintiffs did not, as Charter implies, admit to "fabricating" that statement; rather, they merely acknowledged that they did not receive the printers through an incentive program. A generic exhibit attached to discovery responses, drafted by counsel as part of litigation and with the qualifier "apparently," hardly constitutes the sort of "evidence that one has attempted to cover up a crime" that would serve as "circumstantial proof of one's consciousness of guilt." Charter further misrepresents the record when it claims, citing the testimony of Kruti Desai and Gale Parkerson, that "Plaintiffs admitted that management had not actually been informed of the printer-distribution scheme": Desai acknowledged that she _now_ knows that managers were not aware that she had taken printers, while Gale Parkerson agreed that Charter ultimately determined that Showalter lacked authority to distribute the printers.

In sum, there was insufficient evidence for the jury to reasonably find that Plaintiffs intended to steal the printers, and the Court thus did not err in granting judgment as a matter of law on the issue of truth. Charter is not entitled to a new trial on this ground.

##### Qualified Privilege

Charter next argues that it should have been permitted to assert the defense of qualified privilege. Charter sought leave to amend its answer to assert qualified privilege after the deadline for amendment of pleadings had passed. Magistrate Judge Dave Whalin denied the motion, and the Court overruled Charter's objection to that ruling. In its post-trial motion, Charter argues for the first time that amendment was not required, and it again challenges the denial of its request to amend. 

The court held that "Charter waived the defense of qualified privilege by failing to assert it in a responsive pleading" and that the magistrate judge properly denied Charter's motion for leave to amend its answer to assert that defense. 

The Court recognizes that availability of the qualified-privilege defense could have drastically altered the outcome of this case. An inexplicable oversight or strategic error on Charter's part, however, does not justify altering the litigation schedule or depriving Plaintiffs of necessary discovery in disregard of Sixth Circuit law and the Federal Rules of Civil Procedure. Given Charter's failure to assert qualified privilege in its answer, a timely amended answer, or a motion to dismiss, it is reasonable to conclude that omission of the defense earlier in the case was intentional. Yet Charter now essentially asks the Court to allow it the benefit of hindsight—to benefit both from asserting the defense, and from not asserting it. Charter is not entitled to a new trial on this ground.

### Arku v. Wells Fargo Bank, 621 F.Supp.3d 602 (W.D.N.C. 2022)

#### Factual Background

Plaintiff Josephine Arku filed this action against Defendant Wells Fargo Bank, National Association (“Wells Fargo”) seeking compensatory damages for allegedly informing Plaintiff’s prospective employers that she owed Wells Fargo an overpayment which caused her to lose several job opportunities. 

Accepting the well-pleaded factual allegations of the Complaint as true, Plaintiff worked for Wells Fargo for more than twenty years when she needed to take paid leave from work. Thereafter, in February 2016, she was subject to a corporate layoff and received a severance package which included continuation of her salary for eleven months. Wells Fargo calculated the number of benefits that Plaintiff received. In August 2016, Plaintiff accepted short-term employment for five months through Wells Fargo and then started to apply for other job opportunities. Potential employers notified Plaintiff that Wells Fargo reported her as owing an overpayment to Wells Fargo. Once Plaintiff became aware of the overpayment, she contacted Wells Fargo and paid back the overpayment with the understanding that Wells Fargo would remove the overpayment information from her record. After receiving payment, Wells Fargo failed to remove the overpayment information from Plaintiff’s record, despite numerous requests to do so. Between 2018 and 2020, Plaintiff applied to employers and believes, due to the overpayment listing on her record, that she lost various job opportunities. Plaintiff alleges that Wells Fargo’s failure to correct the adverse employment information caused her to lose $135,000 in income and resulted in a $100,000 increase in interest payments regarding her home and vehicle loans. 

#### Discussion

In the Motion to Dismiss, Wells Fargo argues (1) it is immune from civil liability; and (4) Plaintiff did not meet the heightened pleading standard for a negligent misrepresentation claim.

##### Civil Immunity

Under [N.C. Gen. Stat. § 1-539.12](#ncgs-1-539-12), Wells Fargo asserts that it is immune from liability for both the breach of contract and negligent misrepresentation claims. Wells Fargo cites to subsection (a) of the statute, which states:

> An employer who discloses information about a current or former employee’s job history or job performance to a prospective employer of the current or former employee upon request of the prospective employer or upon request of the current or former employee is immune from civil liability and is not liable in civil damages for the disclosure or any consequences of the disclosure.

The statute further defines “job performance” as “(1) the suitability of the employee for re-employment; (2) the employee’s skills, abilities, and traits as they may relate to suitability for future employment; and (3) in the case of a former employee, the reason for the employee’s separation.” 

Relying on this statute, Wells Fargo argues that it has civil immunity because reporting the overpayment information is akin to disclosing Plaintiff’s job history and performance to a prospective employer. In particular, Wells Fargo argues that the information relates to Plaintiff’s suitability for re-hire. Plaintiff disagrees, arguing that overpayment information is not correlated to an employee’s job performance.

The statute appears incongruent with the facts of this case. The statute only provides immunity when a former employer provides information to a prospective employer regarding an employee’s job performance or job history. Here, the information that Wells Fargo disclosed about Plaintiff was her failure to pay an overpayment that she received from Wells Fargo. It is unclear how this information pertains to her job performance or job history. For example, the best and worst employee could receive an overpayment from the same employer and disclosing this information would provide no insight into the abilities or job performance of either employee.

Moreover, the facts do not show that Wells Fargo disclosed the overpayment information “upon request of the prospective employer.” It appears that Wells Fargo reported this information to a Credit Bureau. There are no facts that Wells Fargo provided any information about Plaintiff directly to a prospective employer upon that prospective employer’s request as required under the statute.

Regardless, even if the statute does apply to information about an employee’s failure to pay back an overpayment, it does not provide immunity when the information is false. Here, Plaintiff alleges that Wells Fargo failed to remove the overpayment information even after she repaid it, and that she lost potential employment because of this. Plaintiff thus alleges that she lost employment opportunities because of false information that Wells Fargo provided. This precludes civil immunity.

##### Negligent Misrepresentation

Wells Fargo asserts that Plaintiff failed to meet the heightened pleading standard for a negligent misrepresentation claim. North Carolina has adopted the definition of negligent misrepresentation set forth in the Restatement (Second) of Torts under which:

> one who, in the course of his business, profession or employment, or in any other transaction in which he has a pecuniary interest, supplies false information for the guidance of others in their business transactions, is subject to liability for pecuniary loss caused to them by their justifiable reliance upon the information, if he fails to exercise reasonable care or competence in obtaining or communicating the information.

Thus, the tort of negligent misrepresentation occurs when (1) a party justifiably relies, (2) to his detriment, (3) on information prepared without reasonable care, (4) by one who owed the relying party a duty of care. “Such a duty commonly arises within professional relationships.” Moreover, Federal Rule of Civil Procedure 9(b) mandates a heightened standard for pleading a claim for fraud or mistake. Rule 9(b) requires, “in alleging fraud or mistake, a party must state with particularity the circumstances constituting fraud or mistake.” To meet this standard, the plaintiff must, at a minimum, describe “the time, place, and contents of the false representations, as well as the identity of the person making the misrepresentation and what he obtained thereby,” otherwise known as the “who, what, when, where, and how” of the alleged fraud. This Court has previously held the heightened pleading standard applies to negligent misrepresentation claims.

Accepting all the well-pleaded facts as true, the Complaint states facts sufficient to meet all the elements of a negligent misrepresentation claim. First, it is plausible that Plaintiff’s former employer, Wells Fargo, owed her a reasonable duty of care when reporting information relating to her credit. Second, the Complaint states that Wells Fargo continued to report false information after Plaintiff repaid the overpayment. This shows that Wells Fargo may have breached its duty to Plaintiff by reporting the information without reasonable care. Third, Plaintiff relied on Wells Fargo’s assertion that it would remove the overpayment notice. And fourth, her reliance on Wells Fargo’s reporting led to her detriment as she lost multiple job opportunities when Wells Fargo failed to remove the notice.

Moreover, the Complaint meets the heightened pleading standard under Rule 9(b) because it states the “who, what, when, where, and how” of the alleged mistake. For example, in the Complaint, the “who” is identified as Wells Fargo, who allegedly committed negligent misrepresentation; the “what” is identified as Wells Fargo’s failure to remove the overpayment notice; the “when” is 2018 to 2020, the time period when the alleged breach occurred; the “where” is on Plaintiff’s credit report; and the “how” is that Wells Fargo failed to remove the notice after Plaintiff repaid the overpayment, in contravention of the agreement between the parties. Plaintiff’s failure to specifically identify the employee(s) she communicated with at Wells Fargo is not fatal to her claim at this time as the Complaint meets the heightened pleading standard.

Moreover, “there is no requirement that any precise formula be followed or that any certain language be used,” and “it is sufficient if, upon a liberal construction of the whole pleading, the charge of fraud might be supported by proof of the alleged constitutive facts.” “Significantly, a court should not dismiss a complaint pursuant to Rule 9(b) if the court is satisfied that the defendant has been made aware of the particular circumstances for which he will have to prepare a defense at trial.” In this respect, Wells Fargo has been made aware of the negligent misrepresentation claim against it that stems from its failure to remove the notice after Plaintiff repaid the overpayment, resulting in lost employment opportunities for Plaintiff. Accordingly, Defendant’s motion to dismiss the negligent misrepresentation claim is denied.

### NCGS § 1-539.12

::: {.legalcode}

#### Immunity from civil liability for employers disclosing information.

(a\) An employer who discloses information about a current or former employee's job history or job performance to a prospective employer of the current or former employee upon request of the prospective employer or upon request of the current or former employee is immune from civil liability and is not liable in civil damages for the disclosure or any consequences of the disclosure. This immunity shall not apply when a claimant shows by a preponderance of the evidence both of the following:

- (1\) The information disclosed by the current or former employer was false.
- (2\) The employer providing the information knew or reasonably should have known that the information was false.

(b\) For purposes of this section, "job performance" includes:

- (1\) The suitability of the employee for re-employment;
- (2\) The employee's skills, abilities, and traits as they may relate to suitability for future employment; and
- (3\) In the case of a former employee, the reason for the employee's separation.

(c\) The provisions of this section apply to any employee, agent, or other representative of the current or former employer who is authorized to provide and who provides information in accordance with the provisions of this section. For the purposes of this section, "employer" also includes a job placement service but does not include a private personnel service as defined in G.S. 95-47.1 except as provided hereinafter. The provisions of this section apply to a private personnel service as defined in G.S. 95-47.1 only to the extent that the service conveys information derived from credit reports, court records, educational records, and information furnished to it by the employee or prior employers and the service identifies the source of the information.

(d\) This section does not affect any privileges or immunities from civil liability established by another section of the General Statutes or available at common law. 

:::

### Friel v. Angell Care, Inc., 440 S.E.2d 111 (N.C. Ct. App. 1994)

Plaintiff Patricia W. Friel was employed as a secretary by defendant company Angell Care Incorporated ("Angell Care") from July 1982 until 17 April 1987. She held several positions within the company before being assigned to be the personal secretary to Bruce Smith, a new vice-president of the company. On or about 18 March 1987, plaintiff alleged that Smith had sexually harassed her. On 17 April 1987, plaintiff entered into a settlement agreement signed by Angell Care's president, Dennis Young, on behalf of Angell Care. Under the terms of the agreement, plaintiff would leave the company and would not discuss the terms and contents of the agreement. Angell Care would pay plaintiff $9566.63; would not discuss the terms or contents of the agreement with plaintiff's prospective employers; and would provide her prospective employers with neutral employment references.

After leaving Angell Care, plaintiff stayed home with her children, intermittently caring for other children in her home.

During the week of 23 May 1988, plaintiff testified against Angell Group Inc., a company related to Angell Care, pursuant to a subpoena in the case of _Angell Group, Inc., et al. v. Bowling Green Health Care Center, Inc., et al.,_ in Forsyth County Superior Court.

In approximately June or July 1990, plaintiff applied for several secretarial positions. She contacted a local attorney, Meyressa Schoonmaker, for employment, either with Schoonmaker's law practice or with the North Carolina Center for Laws Affecting Women ("NCLAW"), an organization of which Schoonmaker was the president and legal director. Plaintiff submitted an application to Schoonmaker, listing her last employer as Angell Care and giving the names of Don Angell and Stewart Swain. Schoonmaker asked a NCLAW employee, Linda Parker, to contact Angell and Swain. Parker contacted Angell. She asked him if he would rehire plaintiff. When he said he would not, Parker asked why. Parker's and Angell's accounts of his response differ. Angell testified that he said, "there was an unproven sexual harassment charge when she left," and that he "was not aware of the details." Parker's written notes of the conversation state, "Angell said that plaintiff left under adverse (?) circumstances, and he really could not discuss the circumstances." Plaintiff was not offered either position with Schoonmaker.

In August 1990, plaintiff asked Sherrill Horton, a friend who worked for a law firm, if she knew anyone who needed a secretary. Horton said that she did not know if the firm had any openings, but one of the attorneys was unhappy with his current secretary. Plaintiff asked Horton to call Don Angell for a reference, because she wanted to know why Angell Care would not rehire her. Horton called Don Angell, indicating that she was calling him on behalf of her firm because plaintiff had listed him as a reference in applying for a job there, even though plaintiff had not actually submitted an application. Horton testified, and Angell confirmed, that she asked if the company would rehire plaintiff; he said it would not; and he said plaintiff had accused a male employee of sexual harassment, but the charge was never proven. Horton further testified that Angell said that plaintiff left the company under adverse circumstances and that she was difficult to work with.

On 19 October 1990, plaintiff sued Angell Care and Don Angell for compensatory and punitive damages. Plaintiff alleged that Angell and Angell Care had breached the settlement contract; committed slander _per se;_ maliciously interfered with her contractual rights; and blacklisted her in violation of N.C.Gen.Stat. § 14-355.

Defendants moved for summary judgment on all the claims. The motion was heard on 16 July 1992. By written order and judgment entered 23 July 1992, the court granted summary judgment for defendants on the slander, malicious interference with contractual rights, and blacklisting claims. On 21 July 1992, plaintiff filed a voluntary dismissal without prejudice of her breach of contract claim.

Plaintiff appealed the claims of slander _per se,_ malicious interference with contractual rights, and blacklisting, as to both defendants.

#### I.

Plaintiff contends that Angell's statements to Parker and Horton were slander _per se_ because they impeached her in her profession.

Initially, we uphold summary judgment on the portion of the slander action that is based on Angell's statements to Horton. All the evidence indicates that the conversation between Angell and Horton took place at the request and direction of the plaintiff. A communication to the plaintiff, or to a person acting at the plaintiff's request, cannot form the basis for a libel or slander claim. In this case, Horton contacted Angell because plaintiff had asked her to "check out (her) references," not because Horton's employer had independently wished to contact Angell. Under these circumstances, plaintiff has no claim for defamation based on any statement made to Horton.

This leaves us with the statements made to Linda Parker. A claim of slander _per se_ has three essential elements:

> To establish a claim for slander _per se,_ a plaintiff must prove: (1) defendant spoke base or defamatory words which tended to prejudice him in his reputation, office, trade, business or means of livelihood or hold him up to disgrace, ridicule or contempt; (2) the statement was false; and (3) the statement was published or communicated to and understood by a third person.

We find that plaintiff has not met the second element of this cause of action. Plaintiff never established that Angell's statements to Parker were false. Angell said that he would not rehire plaintiff; there was an unproven sexual harassment charge when she left the company; and, viewing the evidence in the best light for plaintiff, that plaintiff left the company under adverse circumstances. All the evidence suggests that the statements were in fact true. Plaintiff left the employment of defendant pursuant to a negotiated settlement after making a claim of sexual harassment which was not proven. A description of this situation as "adverse circumstances" does not seem inaccurate.

We note that defendant's statements to Parker and Horton may well have been in breach of the settlement agreement between plaintiff and defendant Angell Care, Inc. However, because plaintiff voluntarily dismissed her claim for breach of contract, issues relating to performance of that contract are not before us today.

#### II.

Plaintiff next contends that defendant maliciously interfered with her right to enter into an employment contract with Meyressa Schoonmaker and the North Carolina Center for Laws Affecting Women. In order to state a claim for malicious interference with contract, plaintiff must establish that the defendant's actions were malicious in the legal sense. To establish legal malice, a plaintiff must show that defendant interfered "with design of injury to plaintiff or gaining some advantage at his expense." Plaintiff never established that defendant intended to injure her or gain some advantage at her expense. The only evidence of malice plaintiff put forth is her belief that Angell felt ill will toward her because after she testified adversely to defendants in the _Bowling Green Health Care_ case, Angell raised his voice and exhibited anger toward the other party (not toward her). Plaintiff's speculation, without any facts to support it, is clearly insufficient to meet her burden of proof. A party cannot prevail against a motion for summary judgment by relying on "conclusory allegations, unsupported by facts." We affirm summary judgment for defendant on the malicious interference with contract claim.

#### III.

Plaintiff's third claim is that defendant Angell's conversations with Parker and Horton violated [N.C.Gen.Stat. § 14-355](https://www.ncleg.gov/EnactedLegislation/Statutes/PDF/BySection/Chapter_14/GS_14-355.pdf), which prohibits blacklisting employees. Under this statute, an employer may be liable if, after discharging someone from employment, it prevents or attempts to prevent that person from obtaining employment:

> If any person, agent, company or corporation, after having discharged any employee from his or its service, shall prevent or attempt to prevent, by word or writing of any kind, such discharged employee from obtaining employment with any other person, company or corporation, such person, agent or corporation shall be guilty of a misdemeanor and shall be liable in penal damages to such discharged person, to be recovered by civil action. This section shall not be construed as prohibiting any person from furnishing in writing, upon request, any other person, company or corporation to whom such discharged person has applied for employment, a truthful statement of the reason for such discharge.

However, statements made about a former employee in response to a request from a prospective employer are privileged under § 14-355. For the statute to be violated, the statements to the prospective employer would have had to have been unsolicited. Plaintiff admits here that Don Angell's statements came only upon inquiry from people he believed to be prospective employers of his former employee. We therefore hold that N.C.Gen.Stat. § 14-355 does not apply as a matter of law and uphold summary judgment for defendants.

### Kadlec Medical Center v. Lakeview Anesthesia Assocs., 527 F.3d 412 (5th Cir. 2008)

Kadlec Medical Center and its insurer, Western Professional Insurance Company, filed this diversity action in Louisiana district court against Louisiana Anesthesia Associates (LAA), its shareholders, and Lakeview Regional Medical Center (Lakeview Medical). The LAA shareholders worked with Dr. Robert Berry—an anesthesiologist and former LAA shareholder—at Lakeview Medical, where the defendants discovered his on-duty use of narcotics. In referral letters written by the defendants and relied on by Kadlec, his future employer, the defendants did not disclose Dr. Berry's drug use.

While under the influence of Demerol at Kadlec, Dr. Berry's negligent performance led to the near-death of a patient, resulting in a lawsuit against Kadlec. Plaintiffs claim here that the defendants' misleading referral letters were a legal cause of plaintiffs' financial injury, i.e., having to pay over $8 million to defend and settle the lawsuit. The jury found in favor of the plaintiffs and judgment followed. We reverse the judgment against Lakeview Medical, vacate the remainder of the judgment, and remand.

#### Factual Background

Dr. Berry was a licensed anesthesiologist in Louisiana and practiced with Drs. William Preau, Mark Dennis, David Baldone, and Allan Parr at LAA. From November 2000 until his termination on March 13, 2001, Dr. Berry was a shareholder of LAA, the exclusive provider of anesthesia services to Lakeview Medical (a Louisiana hospital).

In November 2000, a small management team at Lakeview Medical investigated Dr. Berry after nurses expressed concern about his undocumented and suspicious withdrawals of Demerol. The investigative team found excessive Demerol withdrawals by Dr. Berry and a lack of documentation for the withdrawals.

Lakeview Medical CEO Max Lauderdale discussed the team's findings with Dr. Berry and Dr. Dennis. Dr. Dennis then discussed Dr. Berry's situation with his partners. They all agreed that Dr. Berry's use of Demerol had to be controlled and monitored. But Dr. Berry did not follow the agreement or account for his continued Demerol withdrawals. Three months later, Dr. Berry failed to answer a page while on-duty at Lakeview Medical. He was discovered in the call-room, asleep, groggy, and unfit to work. Personnel immediately called Dr. Dennis, who found Dr. Berry not communicating well and unable to work. Dr. Dennis had Dr. Berry taken away after Dr. Berry said that he had taken prescription medications.

Lauderdale, Lakeview Medical's CEO, decided that it was in the best interest of patient safety that Dr. Berry not practice at the hospital. Dr. Dennis and his three partners at LAA fired Dr. Berry and signed his termination letter on March 27, 2001, which explained that he was fired "for cause":

> You have been fired for cause because you have reported to work in an impaired physical, mental, and emotional state. Your impaired condition has prevented you from properly performing your duties and puts our patients at significant risk. Please consider your termination effective March 13, 2001.

At Lakeview Medical, Lauderdale ordered the Chief Nursing Officer to notify the administration if Dr. Berry returned.

Despite recognizing Dr. Berry's drug problem and the danger he posed to patients, neither Dr. Dennis nor Lauderdale reported Dr. Berry's impairment to the hospital's Medical Executive Committee, eventually noting only that Dr. Berry was "no longer employed by LAA." Neither one reported Dr. Berry's impairment to Lakeview Medical's Board of Trustees, and no one on behalf of Lakeview Medical reported Dr. Berry's impairment or discipline to the Louisiana Board of Medical Examiners or to the National Practitioner's Data Bank. In fact, at some point Lauderdale took the unusual step of locking away in his office all files, audits, plans, and notes concerning Dr. Berry and the investigation.

After leaving LAA and Lakeview Medical, Dr. Berry briefly obtained work as a _locum tenens_ (traveling physician) at a hospital in Shreveport, Louisiana. In October 2001, he applied through Staff Care, a leading _locum tenens_ staffing firm, for _locum tenens_ privileges at Kadlec Medical Center in Washington State. After receiving his application, Kadlec began its credentialing process. Kadlec examined a variety of materials, including referral letters from LAA and Lakeview Medical.

LAA's Dr. Preau and Dr. Dennis, two months after firing Dr. Berry for his on-the-job drug use, submitted referral letters for Dr. Berry to Staff Care, with the intention that they be provided to future employers. The letter from Dr. Dennis stated that he had worked with Dr. Berry for four years, that he was an excellent clinician, and that he would be an asset to any anesthesia service. Dr. Preau's letter said that he worked with Berry at Lakeview Medical and that he recommended him highly as an anesthesiologist. Dr. Preau's and Dr. Dennis's letters were submitted on June 3, 2001, only sixty-eight days after they fired him for using narcotics while on-duty and stating in his termination letter that Dr. Berry's behavior put "patients at significant risk."

On October 17, 2001, Kadlec sent Lakeview Medical a request for credentialing information about Berry. The request included a detailed confidential questionnaire, a delineation of privileges, and a signed consent for release of information. The interrogatories on the questionnaire asked whether "Dr. Berry has been subject to any disciplinary action," if "Dr. Berry has the ability (health status) to perform the privileges requested," whether "Dr. Berry has shown any signs of behavior/personality problems or impairments," and whether Dr. Berry has satisfactory "judgement."

Nine days later, Lakeview Medical responded to the requests for credentialing information about fourteen different physicians. In thirteen cases, it responded fully and completely to the request, filling out forms with all the information asked for by the requesting health care provider. The fourteenth request, from Kadlec concerning Berry, was handled differently. Instead of completing the multi-part forms, Lakeview Medical staff drafted a short letter. In its entirety, it read:

> This letter is written in response to your inquiry regarding Dr. Berry. Due to the large volume of inquiries received in this office, the following information is provided.
> 
> Our records indicate that Dr. Robert L. Berry was on the Active Medical Staff of Lakeview Regional Medical Center in the field of Anesthesiology from March 04, 1997 through September 04, 2001.
> 
> If I can be of further assistance, you may contact me at (504) 867-4076.

The letter did not disclose LAA's termination of Dr. Berry; his on-duty drug use; the investigation into Dr. Berry's undocumented and suspicious withdrawals of Demerol that "violated the standard of care"; or any other negative information. The employee who drafted the letter said at trial that she just followed a form letter, which is one of many that Lakeview Medical used.

Kadlec then credentialed Dr. Berry, and he began working there. After working at Kadlec without incident for a number of months, he moved temporarily to Montana where he worked at Benefis Hospital. During his stay in Montana, he was in a car accident and suffered a back injury. Kadlec's head of anesthesiology and the credentialing department all knew of Dr. Berry's accident and back injury, but they did not investigate whether it would impair his work.

After Dr. Berry returned to Kadlec, some nurses thought that he appeared sick and exhibited mood swings. One nurse thought that Dr. Berry's entire demeanor had changed and that he should be watched closely. In mid-September 2002, Dr. Berry gave a patient too much morphine during surgery, and she had to be revived using Narcan. The neurosurgeon was irate about the incident.

On November 12, 2002, Dr. Berry was assigned to the operating room beginning at 6:30 a.m. He worked with three different surgeons and multiple nurses well into the afternoon. According to one nurse, Dr. Berry was "screwing up all day" and several of his patients suffered adverse affects from not being properly anesthetized. He had a hacking cough and multiple nurses thought he looked sick. During one procedure, he apparently almost passed out.

Kimberley Jones was Dr. Berry's fifth patient that morning. She was in for what should have been a routine, fifteen minute tubal ligation. When they moved her into the recovery room, one nurse noticed that her fingernails were blue, and she was not breathing. Dr. Berry failed to resuscitate her, and she is now in a permanent vegetative state.

Dr. Berry's nurse went directly to her supervisor the next morning and expressed concern that Dr. Berry had a narcotics problem. Dr. Berry later admitted to Kadlec staff that he had been diverting and using Demerol since his June car accident in Montana and that he had become addicted to Demerol. Dr. Berry wrote a confession, and he immediately admitted himself into a drug rehabilitation program.

Jones's family sued Dr. Berry and Kadlec in Washington. Dr. Berry's insurer settled the claim against him. After the Washington court ruled that Kadlec would be responsible for Dr. Berry's conduct under _respondeat superior,_ Western, Kadlec's insurer, settled the claim against Kadlec.

#### Procedural History

Kadlec and Western filed this suit in Louisiana district court against LAA, Dr. Dennis, Dr. Preau, Dr. Baldone, Dr. Parr, and Lakeview Medical, asserting Louisiana state law claims for intentional misrepresentation, negligent misrepresentation, strict responsibility misrepresentation, and general negligence. Plaintiffs alleged that defendants' tortious activity led to Kadlec's hiring of Dr. Berry and the resulting millions of dollars it had to expend settling the Jones lawsuit. Plaintiffs' claim against LAA for negligence, based on a negligent monitoring and investigation theory, was dismissed before trial.

Plaintiffs' surviving claims for intentional and negligent misrepresentation arise out of the alleged misrepresentations in, and omissions from, the defendants' referral letters for Dr. Berry. These claims were tried to a jury, which returned a verdict in favor of the plaintiffs on both claims. The jury awarded plaintiffs $8.24 million, which is approximately equivalent to the amount Western spent settling the Jones lawsuit ($7.5 million) plus the amount it spent on attorneys fees, costs, and expenses (approximately $744,000) associated with the Jones lawsuit. The jury also found Kadlec and Dr. Berry negligent. The jury apportioned fault as follows: Dr. Dennis 20%; Dr. Preau 5%; Lakeview Medical 25%; Kadlec 17%; and Dr. Berry 33%. The judgments against Dr. Dennis and Dr. Preau were _in solido_ with LAA. Because defendants were found liable for intentional misrepresentation, plaintiffs' recovery was not reduced by the percentage of fault ascribed to Kadlec. But the amount was reduced to $5.52 million to account for Dr. Berry's 33% of the fault. The district court entered judgment against Lakeview Medical and LAA.

#### Discussion

##### The Intentional and Negligent Misrepresentation Claims

The plaintiffs allege that the defendants committed two torts: intentional misrepresentation and negligent misrepresentation. The elements of a claim for _intentional_ misrepresentation in Louisiana are: (1) a misrepresentation of a material fact; (2) made with intent to deceive; and (3) causing justifiable reliance with resultant injury. To establish a claim for intentional misrepresentation when it is by silence or inaction, plaintiffs also must show that the defendant owed a duty to the plaintiff to disclose the information. To make out a _negligent_ misrepresentation claim in Louisiana: (1) there must be a legal duty on the part of the defendant to supply correct information; (2) there must be a breach of that duty, which can occur by omission as well as by affirmative misrepresentation; and (3) the breach must have caused damages to the plaintiff based on the plaintiff's reasonable reliance on the misrepresentation.

The defendants argue that any representations in, or omissions from, the referral letters cannot establish liability. We begin our analysis below by holding that after choosing to write referral letters, the defendants assumed a duty not to make affirmative misrepresentations in the letters. We next analyze whether the letters were misleading, and we conclude that the LAA defendants' letters were misleading, but the letter from Lakeview Medical was not. We also examine whether the defendants had an affirmative duty to disclose negative information about Dr. Berry in their referral letters, and we conclude that there was not an affirmative duty to disclose. Based on these holdings, Lakeview Medical did not breach any duty owed to Kadlec, and therefore the judgment against it is reversed. Finally, we examine other challenges to the LAA defendants' liability, and we conclude that they are without merit.

**1. The Affirmative Misrepresentations**

The defendants owed a duty to Kadlec to avoid affirmative misrepresentations in the referral letters. In Louisiana, "although a party may keep absolute silence and violate no rule of law or equity, if he volunteers to speak and to convey information which may influence the conduct of the other party, he is bound to disclose the whole truth." In negligent misrepresentation cases, Louisiana courts have held that even when there is no initial duty to disclose information, "once a party volunteers information, it assumes a duty to insure that the information volunteered is correct."

Consistent with these cases, the defendants had a legal duty not to make affirmative misrepresentations in their referral letters. A party does not incur liability every time it casually makes an incorrect statement. But if an employer makes a misleading statement in a referral letter about the performance of its former employee, the former employer may be liable for its statements if the facts and circumstances warrant. Here, defendants were recommending an anesthesiologist, who held the lives of patients in his hands every day. Policy considerations dictate that the defendants had a duty to avoid misrepresentations in their referral letters if they misled plaintiffs into thinking that Dr. Berry was an "excellent" anesthesiologist, when they had information that he was a drug addict. Indeed, if defendants' statements created a misapprehension about Dr. Berry's suitability to work as an anesthesiologist, then by "volunteering to speak and to convey information which influenced the conduct of Kadlec, they were bound to disclose the whole truth." In other words, if they created a misapprehension about Dr. Berry due to their own statements, they incurred a duty to disclose information about his drug use and for-cause firing to complete the whole picture.

We now review whether there is evidence that the defendants' letters were misleading. We start with the LAA defendants. The letter from Dr. Preau stated that Dr. Berry was an "excellent anesthesiologist" and that he "recommended him highly." Dr. Dennis's letter said that Dr. Berry was "an excellent physician" who "he is sure will be an asset to his future employer's anesthesia service." These letters are false on their face and materially misleading. Notably, these letters came only sixty-eight days after Drs. Dennis and Preau, on behalf of LAA, signed a letter terminating Dr. Berry for using narcotics while on-duty and stating that Dr. Berry's behavior put "patients at significant risk." Furthermore, because of the misleading statements in the letters, Dr. Dennis and Dr. Preau incurred a duty to cure these misleading statements by disclosing to Kadlec that Dr. Berry had been fired for on-the-job drug use.

The question as to whether Lakeview Medical's letter was misleading is more difficult. The letter does not comment on Dr. Berry's proficiency as an anesthesiologist, and it does not recommend him to Kadlec. Kadlec says that the letter is misleading because Lakeview Medical stated that it could not reply to Kadlec's detailed inquiry in full "due to the large volume of inquiries received." But whatever the real reason that Lakeview Medical did not respond in full to Kadlec's inquiry, Kadlec did not present evidence that this could have affirmatively misled it into thinking that Dr. Berry had an uncheckered history at Lakeview Medical.

Kadlec also says that the letter was misleading because it erroneously reported that Dr. Berry was on Lakeview Medical's active medical staff until September 4, 2001. Kadlec presented testimony that had it known that Dr. Berry never returned to Lakeview Medical after March 13, 2001, it would have been suspicious about the apparently large gap in his employment. While it is true that Dr. Berry did not return to Lakeview Medical after March 13, this did not terminate his privileges at the hospital, or mean that he was not on "active medical staff." In fact, it appears that Dr. Berry submitted a formal resignation letter on October 1, 2001, weeks _after_ September 4. Therefore, while the September 4 date does not accurately reflect when Dr. Berry was no longer on Lakeview Medical's active medical staff, it did not mislead Kadlec into thinking that he had less of a gap in employment than he actually had.

In sum, we hold that the letters from the LAA defendants were affirmatively misleading, but the letter from Lakeview Medical was not. Therefore, Lakeview Medical cannot be held liable based on its alleged affirmative misrepresentations. It can only be liable if it had an affirmative duty to disclose information about Dr. Berry. We now examine the theory that, even assuming that there were no misleading statements in the referral letters, the defendants had an affirmative duty to disclose. We discuss this theory with regard to both defendants for reasons that will be clear by the end of the opinion.

**2. The Duty to Disclose**

In Louisiana, a duty to disclose does not exist absent special circumstances, such as a fiduciary or confidential relationship between the parties, which, under the circumstances, justifies the imposition of the duty. Louisiana cases suggest that before a duty to disclose is imposed the defendant must have had a pecuniary interest in the transaction. In Louisiana, the existence of a duty is a question of law, and we review the duty issue here _de novo._

Plaintiffs assert that Lakeview Medical and the LAA doctors had a pecuniary interest in the referral letters supplied to Kadlec. The plaintiffs rely on the pecuniary interest definition in the Second Restatement of Torts. Section 552, comment d of the Restatement, provides (with emphasis added):

> The defendant's pecuniary interest in supplying the information will normally lie in a consideration paid to him for it or paid in a transaction in the course of and as a part of which it is supplied. It may, however, be of a more indirect character.
> 
> The fact that the information is given in the course of the defendant's business, profession or employment is a sufficient indication that he has a pecuniary interest in it, even though he receives no consideration for it at the time. It is not, however, conclusive.

The "course of business" definition of pecuniary interest has been endorsed by Louisiana appellate courts. In _Anderson v. Heck,_ the court defined the "pecuniary interest" of the defendant by directly quoting and applying the portion of the Restatement comment highlighted above. The court in _Dousson v. South Central Bell_ held that the fact that information is given in the course of a party's business or profession is a sufficient indication of pecuniary interest even though the party receives no consideration for it at the time.

The defendants argue that, even assuming the Restatement governs, they did not have a pecuniary interest in providing reference information. They contend that any information provided to future employers about Dr. Berry was gratuitous, and they point out that the Restatement's comments say that a party will not be considered to have a pecuniary interest in a transaction where the information is given "purely gratuitously."

The defendants have the better argument on the lack of pecuniary interest and, in addition, the requisite "special relationship" between the defendants and Kadlec, necessary to impose a duty to disclose, is lacking.

Plaintiffs argue that policy considerations weigh in favor of recognizing a duty to disclose. They contend that imposing a duty on health care employers to disclose that a physician's drug dependence could pose a serious threat to patient safety promotes important policy goals recognized by Louisiana courts. Plaintiffs point to the decision in _Dornak v. Lafayette General Hospital,_ where the Louisiana Supreme Court imposed on a hospital the duty to disclose to its employee the results of a pre-employment physical which showed tuberculosis, "especially considering the fact that her duties placed her in contact with co-employees and hospital patients." The Louisiana legislature recently adopted legislation that requires health care entities to "report to the appropriate professional licensing board each instance in which the health care entity takes an adverse action against a health care professional due to impairment or possible impairment." This shows that the legislature has recognized the importance of reporting possible impairments that could affect patient safety.

Despite these compelling policy arguments, we do not predict that courts in Louisiana—absent misleading statements such as those made by the LAA defendants—would impose an affirmative duty to disclose. The defendants did not have a fiduciary or contractual duty to disclose what it knew to Kadlec. And although the defendants might have had an ethical obligation to disclose their knowledge of Dr. Berry's drug problems, they were also rightly concerned about a possible defamation claim if they communicated negative information about Dr. Berry. As a general policy matter, even if an employer believes that its disclosure is protected because of the truth of the matter communicated, it would be burdensome to impose a duty on employers, upon receipt of a employment referral request, to investigate whether the negative information it has about an employee fits within the courts' description of _which_ negative information must be disclosed to the future employer. Finally, concerns about protecting employee privacy weigh in favor of not mandating a potentially broad duty to disclose.

The Louisiana court in _Louviere_ recognized that no court in Louisiana has imposed on an employer a duty to disclose information about a former employee to a future employer. Furthermore, we have not found a single case outside of Louisiana where a court imposed an affirmative duty on an employer to disclose negative information about a former employee. Some courts have held that employers have a legal duty to disclose negative information about former employees who later cause foreseeable physical harm in their new jobs, at least when there are misleading statements made by the former employer. But each of these cases based its conclusion on the fact that the former employer had made affirmative misrepresentations in its referral, and none imposed a duty based on the employer's mere nondisclosure. These cases reinforce our conclusion that the defendants had a duty to avoid misleading statements in their referral letters, but they do not support plaintiffs' duty to disclose theory. In fact, one court explicitly held that a hospital did not have an affirmative duty to disclose a nurse's past sexual misconduct toward patients when asked for an evaluation by a prospective employer, but that "the defendant did not challenge the proposition that, in undertaking to provide a reference, and in volunteering information about the employee's qualities as a nurse, it incurred a duty to use reasonable care to avoid disclosing factually misleading information."

**3. Legal Cause**

LAA contends that even if it breached a legal duty to Kadlec, the plaintiffs' claims fail for lack of legal causation. LAA argues that legal cause is not met here because Kadlec's and Dr. Berry's intervening negligence precludes concluding that it is a legal cause of plaintiffs' injuries. Because legal cause is a legal question under Louisiana law, we review the district court's conclusion as to legal cause _de novo._

The leading case on legal cause in Louisiana is _Roberts v. Benoit._ There, the Louisiana Supreme Court held that "the critical test in Louisiana is phrased in terms of 'the ease of association' which melds policy and foreseeability into one inquiry: Is the harm which befell the plaintiff easily associated with the type of conduct engaged in by the defendant?" Under Louisiana law, and with the jury's factual findings in mind, the LAA defendants' actions and omissions were a legal cause of Kadlec's liability. Following the Louisiana Supreme Court, we ask ourselves whether the harm to plaintiffs is easily associated with the type of conduct engaged in by the defendant. Here, Dr. Dennis and Dr. Preau gave Dr. Berry favorable recommendations, when they knew that Dr. Berry had used narcotic drugs while on duty at a hospital. LAA even fired Dr. Berry for cause for "reporting to work in an impaired physical, mental, and emotional state, which prevented him from properly performing his duties and put his patients at significant risk." The harm to Jones and the harm to plaintiffs that resulted from the LAA defendants' breaches are "easily associated" with Kadlec's liability. In fact, harm stemming from Dr. Berry's use of narcotic drugs while on-duty is the type of harm we would expect.

The LAA defendants' argument that the intervening negligence of Dr. Berry and Kadlec absolves them of liability is not accepted. _Roberts_ held that "it is well settled in Louisiana law that an intervening act does not automatically absolve a prior negligent party from liability." Whether an intervening act absolves a prior negligent actor from liability depends on the foreseeability of the act from the perspective of the original tortfeasor and whether the intervening act is "easily associated" with the risk of harm brought about by the breach of the original duty. Dr. Berry's hiring and his subsequent negligent use of narcotics while on-duty was foreseeable and "easily associated" with the LAA defendants' actions. He had used narcotics while on-duty in the past, and the LAA defendants could foresee that he would do so again if they misled a future employer about his drug problem.

The LAA defendants focus on Kadlec's negligence and claim that it was a superseding cause of plaintiffs' injuries. They argue that Kadlec had multiple warning signs that Dr. Berry was using drugs, and had it responded with an investigation, plaintiffs' injuries would have been avoided. The LAA defendants focus on Dr. Berry's erratic behavior after his return from Montana, his over-anesthetization of a patient in September 2002, and the signs that he was ill on the day of Jones's surgery. The jury found that Kadlec's own negligence was a cause of plaintiffs' financial injury. But this does not relieve the defendants of liability. The jury also reasonably concluded that the LAA defendants negligently _and intentionally_ misled Kadlec about Dr. Berry's drug addiction. By intentionally covering up Dr. Berry's drug addiction in communications with a future employer, they should have foreseen that the future employer might miss the warning signs of Dr. Berry's addiction. This was within the scope of the risk they took.

Indeed, both plaintiffs' and defendants' witnesses agreed at trial that narcotics addiction is a disease, that addicts try to hide their disease from their co-workers, and that particularly in the case of narcotics-addicted anesthesiologists, for whom livelihood and drug supply are in the same place, colleagues may be the last to know about their addiction and impairment. This is not a case where a future tortious act is so unforeseeable that it should relieve the earlier tortfeasor of liability. In fact, this case illustrates why the comparative fault system was developed—so, as here, multiple actors can share fault for an injury based on their respective degrees of responsibility.

## Background Checks & Testing

### Pham v. Aeva Specialty Pharmacy, No. 21-cv-00703-NYW-STV (D. Colo. Dec. 8, 2022)

Plaintiff Khanh Pham ("Plaintiff" or "Mr. Pham") alleges that in 2020, he applied for an open pharmacist employment position at Aeva Specialty Pharmacy ("Defendant" or "Aeva"), and received a conditional offer of employment. According to Plaintiff, Aeva submitted Plaintiff's information to Clear Screening Technologies LLC ("Clear Screening"), a former defendant in this case, for a routine background check. Mr. Pham asserts that the background screening report erroneously reported that he had been charged with a federal crime in 2018, though he had never been charged with a federal crime. He also alleges that as a result of the incorrect Clear Screening report, Aeva revoked its conditional offer of employment. 

Mr. Pham initiated this civil action on March 9, 2021, raising three claims under the Fair Credit Reporting Act ("FCRA"): two claims against Clear Screening for negligent and willful violations, respectively, of the FCRA, and one claim against Aeva for willful violations of the FCRA. Mr. Pham voluntarily dismissed his claims against Clear Screening with prejudice on August 5, 2021. 

Aeva filed the instant Motion for Summary Judgment on February 10, 2022, seeking judgment in its favor on Plaintiff's FCRA claim. 

#### Undisputed Material Facts

The below material facts are drawn from the Parties' briefing and are undisputed unless otherwise noted.

1\. Mr. Pham is a licensed pharmacist.

2\. In 2020, Mr. Pham applied for employment as a pharmacist with Aeva. 

3\. Prior to interviewing with Aeva, Mr. Pham worked for CVS Pharmacy. Mr. Pham's employment with CVS ended in September 2019.

4\. Mr. Pham "interacted with" Brooke Pendergrass, Aeva's Manager of Human Resources, during the process of interviewing with Aeva.

5\. After Mr. Pham's interview with Aeva, Ms. Pendergrass presented Mr. Pham with a verbal conditional offer of employment.

6\. Mr. Pham did not receive a written offer of employment from Aeva.

7\. At some point after Mr. Pham submitted to a background check, Aeva decided not to hire Mr. Pham.

#### Analysis

The Fair Credit Reporting Act was enacted "to require that consumer reporting agencies adopt reasonable procedures for meeting the needs of commerce for consumer credit in a manner which is fair and equitable to the consumer, with regard to the confidentiality, accuracy, relevancy, and proper utilization of such information." 15 U.S.C. § 1681(b). The FCRA "enables consumers to protect their reputations, and to protect themselves against the dissemination of false or misleading credit information." "The FCRA places distinct obligations on three types of entities: (1) consumer reporting agencies; (2) users of consumer reports; and (3) furnishers of information." 

Under the FCRA, users of consumer reports—like Aeva—must, "in using a consumer report for employment purposes," and "before taking any adverse action based in whole or in part on the report, provide to the consumer to whom the report relates (i) a copy of the report; and (ii) a description in writing of the rights of the consumer under this subchapter." "Congress intended applicants to have a real opportunity to contest an adverse employment decision based on a consumer report," and an applicant "must have enough time between the notice and the final decision to meaningfully contest or explain the contents of the report." 

##### The Applicability of the FCRA

In its Motion for Summary Judgment, Aeva first argues that the FCRA is not applicable to this case because its decision to not hire Plaintiff was unrelated to and did not rely upon Plaintiff's background check. Aeva states that it is undisputed that "at no time was Mr. Pham told he was not hired based on the background report's improper red flag regarding a felony criminal case on an interim background check." Instead, Aeva asserts, Mr. Pham testified that he has "no evidence" that Aeva made its hiring decision based on the background report. Aeva supports its position by citing evidence to Ms. Deinet's deposition testimony, wherein Ms. Deinet testified that the decision to not hire Plaintiff was unrelated to the background report and that Ms. Deinet, "who made the hiring decision," never saw the background report until this lawsuit was filed. 

But Mr. Pham _has_ submitted evidence, in the form of his own testimony, that Ms. Pendergrass called him to revoke his conditional offer of employment and informed him at the time that the revocation was based on the background check results. While Defendant implicitly asks the Court to accept its employees' testimony as true and to discredit Plaintiff's testimony as untrue, the Court cannot make credibility determinations in ruling on a motion for summary judgment. 

The fact that Mr. Pham testified that he has "no evidence" that the hiring decision was based on his background check does not change the Court's conclusion. Mr. Pham, a non-lawyer, simply could have meant that he has no tangible evidence of the reasoning for the decision, i.e., a recording of the telephone call with Ms. Pendergrass. But Mr. Pham's testimony is evidence, and the Court must draw all reasonable inferences from that evidence in Mr. Pham's favor. Because a reasonable jury could conclude, based on Mr. Pham's testimony, that Aeva's decision to not hire Mr. Pham was based on the results of the background check, genuine issues of material fact preclude summary judgment on this basis.

##### Actual Damages

In the alternative, Aeva argues that Plaintiff cannot establish that he was actually damaged by Aeva's actions, which necessitates summary judgment in its favor. The FCRA establishes separate categories of damages for willful and negligent violations of the FCRA. A company that willfully fails to comply with FCRA requirements may be held liable for "any actual damages sustained by the consumer as a result of the failure or damages of not less than $100 and not more than $1,000," as well as punitive damages and attorney's fees and costs. Therefore, a "consumer need not prove actual damages if the FCRA violation is willful, but may recover punitive damages and statutory damages ranging from $100 to $1,000." Meanwhile, an employer who negligently fails to comply with the FCRA may be liable for "any actual damages sustained by the consumer as a result of the failure" and fees and costs. Mr. Pham seeks "actual damages, statutory damages, costs, and attorney's fees," as well as punitive damages, pursuant to 15 U.S.C. § 1681n. 

Aeva argues that Mr. Pham has failed to submit any evidence of actual damages suffered by him as a result of Aeva's purported FCRA violations. In addition, it argues that because Mr. Pham "admitted" a lack of actual damages, this "mandatees dismissal of" Plaintiff's claim. In support of its argument, Aeva cites to deposition testimony wherein Mr. Pham was asked to explain "whether or not he had been harmed by Aeva Pharmacy and whether he had lost money." Plaintiff responded, "No, I have not been harmed." On this basis, Aeva asserts that "Plaintiff has failed to demonstrate that the alleged adverse credit action caused any damages." Aeva further asserts that Mr. Pham was hired by a different employer within 20 days of his interview with Aeva and that Plaintiff "received a settlement from the dismissed co-Defendant in this case of around $20,000," which "negates any possible FCRA claim as Mr. Pham made more money through the settlement than he would have if he had been employed by Aeva."

Aeva's arguments are insufficient to warrant summary judgment in its favor. First, Aeva did not mention Mr. Pham's new employment or the settlement in its Statement of Undisputed Facts, and thus, Mr. Pham was not required to rebut these assertions with record evidence. If Defendant intended to rely on these material assertions in arguing that it is entitled to judgment in its favor, it was required to include them in its Statement of Undisputed Facts. The Court thus cannot conclude that these assertions are undisputed for purposes of the pending Motion.

Second, Aeva has not cited any legal authority suggesting that a settlement with a former party to this lawsuit can "negate" any claim for damages asserted by Plaintiff as to Aeva. Through its independent research, the Court could find no support for Defendant's position. The Court declines to hold that Mr. Pham's settlement with Clear Screening "negates" any claim for damages against Aeva, as such a holding would disincentivize settlement of disputes.

Third, while Defendant suggests that Mr. Pham cannot demonstrate actual damages because he obtained alternative employment within 20 days of his interview with Aeva, the Court respectfully disagrees. Mr. Pham argues in his Response that he can establish actual damages because he "was unable to earn wages that he otherwise would have earned had he been permitted to begin working at Aeva." Indeed, Mr. Pham confirmed at his deposition that he "did not receive wages that he otherwise would have earned had he been offered employment with Aeva and begun working for Aeva." Although Plaintiff testified that he "had not been harmed" by Aeva's actions, which may contradict his statement, credibility determinations and resolution of conflicts in the evidence are issues reserved for the jury. Lost income is one type of actual damages available under the FCRA, and because Mr. Pham has produced evidence that of potentially lost income, the jury must assess its strength. But as Mr. Pham has already adduced evidence of actual damages, the Court is unpersuaded by Defendant's argument that Mr. Pham can produce no such evidence.

##### Willful Violation of the FCRA

Finally, Aeva argues that Plaintiff's request for statutory or punitive damages fails as a matter of law because he has presented no evidence that Aeva acted willfully or with reckless disregard in its purported FCRA violations. For this reason, it asserts that it is entitled to judgment in its favor on Plaintiff's FCRA claim. 

"A showing of malice or evil motive is not required to prove willfulness under the FCRA." Instead, a willful violation of the FCRA is "either an intentional violation or a violation committed by an entity in reckless disregard of its duties under the FCRA." "Recklessness is measured by 'an objective standard: action entailing an unjustifiably high risk of harm that is either known or so obvious that it should be known.'" "A company subject to FCRA does not act in reckless disregard of it unless the action is not only a violation under a reasonable reading of the statute's terms, but shows that the company ran a risk of violating the law substantially greater than the risk associated with a reading that was merely careless." "Willfulness under the FCRA is generally a question of fact for the jury." 

Aeva contends that "at most, Plaintiff believes, without the provision of one scintilla of corroborating evidence, that he was not hired because of an alleged felony conviction on an interim background check. However, Plaintiff's belief is simply inaccurate and wholly unsupported by the evidence—most importantly, his own testimony." Aeva defends its conduct related to the background check as "objectively reasonable" and reiterates its position that it declined to hire Mr. Pham for reasons outside of the background check report. 

In his Response, Mr. Pham directs the Court to evidence that Aeva orders a background check for "every person it hires," and has requested "hundreds" of background checks. Aeva was on notice that it must comply with the FCRA when using background check reports for employment purposes. But despite its regular use of background checks, Aeva does not have any internal policies or procedures regarding the use of background reports for employment purposes, and it does not train its employees on FCRA compliance or on how to use background check reports. Mr. Pham argues that "by failing to take any steps to avoid violating the FCRA, Aeva acted with reckless disregard of its statutory duties" under the law.

Insofar as Defendant bases its argument on its position that there is no dispute that Aeva did not rely on the background check report in revoking the conditional offer of employment, the Court has already rejected this argument, having concluded that genuine disputes of fact exist as to Aeva's underlying purpose for revoking the conditional employment offer. In the alternative, Defendant asserts that Mr. Pham has presented "no evidence" that Aeva acted willfully or with reckless disregard in failing to comply with the FCRA. The Court disagrees. Mr. Pham has produced evidence demonstrating that although Aeva was on notice of its obligation to comply with the FCRA it had no policies or procedures governing FCRA compliance and that it did not train its employees on FCRA compliance. This is sufficient to create a genuine dispute of fact as to whether Aeva acted in reckless disregard of its FCRA obligations in its interactions with Plaintiff. 

Aeva asserts in its Reply that Aeva's policies, or lack thereof, "have no relation to this lawsuit" because "Plaintiff failed to establish that the FCRA requirements were even the responsibility of Aeva." It states that "Aeva hired Clear Screening to run the background check," but Plaintiff "never inquired as to which party had the responsibility to send an adverse notice if the report were relied upon." Insofar as Defendant suggests a missing evidentiary link in this case between the FCRA and Aeva's duties thereunder, the Court is unpersuaded. First, Defendant failed to raise any argument in its Motion for Summary Judgment that it was Clear Screening, and not Aeva, that had a duty to disclose the background report results to Plaintiff; this argument was undoubtedly available to Defendant at the time it filed its Motion, and its failure to raise the argument renders it waived. Furthermore, Aeva has cited no legal authority demonstrating that, by hiring a third party to conduct a background check, a user of credit reports transfers its disclosure obligations under the FCRA to that third party. Inadequately supported arguments need not be considered by the Court. And in any event, the Court is unpersuaded by Defendant's argument. The FCRA provides that the duty to furnish a background report on a prospective employee lies with the party using the consumer report for employment purposes and intending to take an adverse action based on that report. By submitting evidence suggesting that Aeva purportedly rescinded Plaintiff's conditional offer based on the background report, Plaintiff has submitted sufficient evidence to establish a disclosure duty on the part of Aeva. For all of these reasons, the willfulness or recklessness of Aeva's actions must be assessed by the jury.

In sum, Mr. Pham has established genuine disputes of material fact concerning (1) whether Aeva rescinded his conditional offer of employment due to the background check results; (2) whether Mr. Pham was actually damaged by Aeva's actions; and (3) whether Aeva acted willfully or recklessly. Summary judgment is thus not appropriate at this juncture, and Defendant's Motion will be denied.

### Franklin v. Vertex Global Solutions, Inc., No. 20 Civ. 10495 (KPF) (S.D.N.Y. Feb. 9, 2022)

Plaintiff Henry Franklin, on behalf of himself and a putative class of similarly situated job applicants, has sued Defendants Vertex Global Solutions, Inc. ("Vertex") and Fresh Direct, LLC ("Fresh Direct," and collectively, "Defendants") for their alleged use of a pre-employment screening policy that discriminates against job applicants with criminal histories in violation of the New York City Human Rights Law (the "NYCHRL"), N.Y.C. Admin. Code §§ 8-101 to 8-131, as amended by the Fair Chance Act (the "FCA"), N.Y.C. Local Law 63 (2015). Vertex and Fresh Direct have each moved to dismiss Plaintiff's claims, contending that their hiring practices comply with New York City law and do not discriminate against individuals with criminal histories. Fresh Direct additionally argues that Plaintiff's claims should fail because he has not alleged Fresh Direct's participation in any facet of Plaintiff's employment application with Vertex. For the reasons outlined in the remainder of this Opinion, the Court denies Defendants' motions in full.

#### Factual Background

Plaintiff Henry Franklin is a citizen of New York and a man with a criminal record. Defendant Vertex Global Solutions is a staffing agency headquartered in New York. Defendant Fresh Direct is a Delaware corporation specializing in direct-to-consumer food delivery, with its principal place of business in New York. 

On December 6, 2018, Plaintiff arrived at a Fresh Direct facility in the Bronx to participate in a job recruiting program with the company. Upon arriving at the facility that morning, Plaintiff received a nametag that contained his first and last name, the date, and the name "Samantha" clustered below the phrase "freshdirect Vertex." Plaintiff was then directed to a waiting area where dozens of other applicants were seated. After sitting in the waiting area for approximately forty-five minutes, the group of applicants was guided to another room, where a speaker gave a presentation about working for Fresh Direct. Following the presentation, and with no questions asked of them, the applicants in the room each received a document purporting to be a conditional offer of employment that they were told to sign. The Offer Form recited that Vertex was "pleased to offer you a conditional offer of employment," and provided that the applicant's hourly salary would be $13.00. (Offer Form). The form further explained that the employment offer was "contingent upon a satisfactory outcome of the pre-employment screening process, which includes but is not necessarily limited to a review of past employment, education records, verification of ability to work in the United States, history background check and in some cases a drug screen." Plaintiff signed and dated the Offer Form and noted that the time was 11:40 a.m. 

Shortly after signing the Offer Form, at 11:46 a.m., Plaintiff received and signed another form, this time a release authorizing a background check. The release included the question "have you ever been convicted of a crime?" to which Plaintiff responded by checking the box that indicated "no." (Background Check Release). A banner at the top of the release read: "New York City, New York Applicants: DO NOT RESPOND TO THE QUESTIONS SEEKING CRIMINAL RECORD INFORMATION AT THIS TIME. You will only have to answer criminal history questions after you receive a conditional offer of employment. At that time, you will not have to identify arrests or criminal accusations that did not result in a conviction (unless the arrest or criminal accusation is pending)." The Background Check Release makes no specific reference to the Offer Form that Plaintiff and the other applicants in the room had signed just moments earlier.

Once Plaintiff signed the Background Check Release, he was told that the recruiting process was complete and that he was free to leave the facility. Within approximately one to two weeks, Plaintiff received a letter from Vertex, notifying him that his background check had disclosed a criminal record. Plaintiff never heard from Defendants again. Following the rejection of his application, Plaintiff claims that the entire hiring process was "a transparent ruse" and that the "sole purpose of gathering at the Fresh Direct facility was to initiate background checks that would weed out applicants with conviction histories."

Plaintiff alleges that his employment application was for a job with both Vertex and Fresh Direct, even though he formally applied for a job only with Vertex. Plaintiff asserts that both Defendants participated in the hiring of Fresh Direct employees, as evidenced by the fact that Vertex held its recruiting event on Fresh Direct's premises. Moreover, applicants who were hired by Vertex to provide services to Fresh Direct would be formally employed by Vertex for the first few months, after which Fresh Direct would have the option to hire them directly. Even during the initial period where an individual was formally employed by Vertex, all workers providing services to Fresh Direct through Vertex were subject to Fresh Direct's control and supervision. In his Amended Complaint, Plaintiff includes several images of anonymous employee reviews of Vertex from the website Indeed.com; one of these reviews characterizes Vertex as a "temp agency that provides Full Time Job Opportunities." Another review describes working for Vertex as actually "a position for freshdirect" and explains that "if you do well you start working for freshdirect." 

As further evidence of the symbiotic relationship between Defendants, Plaintiff contends that Vertex touts that it offers customized services tailored to the specific requirements of individual employers like Fresh Direct. According to its website, Vertex advertises to prospective employer-clients that it "strives to understand your business, culture, and needs, to ensure we deliver candidates that fit your unique requirements." Vertex describes the value it adds to its clients' hiring process by characterizing itself as "a partner and an extension of your Human Resources Department." Notably, Vertex regularly conducted interviews for prospective Fresh Direct employees on-site at a Fresh Direct facility, as evidenced by an online job posting and Plaintiff's personal experience.

#### Discussion

##### New York City's Fair Chance Act [^Franklin5]

The FCA, which went into effect on October 27, 2015, amended the NYCHRL to provide additional protection from employment discrimination to individuals with criminal histories. _See_ N.Y.C. Local Law 63 (2015); _see also_ N.Y.C. Comm'n on Human Rights, [Legal Enforcement Guidance on the Fair Chance Act](https://www.nyc.gov/site/cchr/law/fair-chance-act.page) ("Enforcement Guidance") at 1 (June 24, 2016) ("The FCA is intended to level the playing field so that New Yorkers who are part of the approximately 70 million adults residing in the United States who have been arrested or convicted of a crime are 'not overlooked during the hiring process simply because they have to check a box.'"). With the aim of preventing an applicant's criminal history from tainting initial hiring decisions, the FCA regulates precisely when in the hiring process an employer may seek and use information regarding an applicant's criminal background. To this end, the FCA deems it an "unlawful employment practice" for most employers to "make any inquiry or statement related to the pending arrest or criminal conviction record of any person who is in the process of applying for employment with such employer or agent thereof until after such employer or agent thereof has extended a conditional offer of employment to the applicant." The FCA defines "any inquiry" as "any question communicated to an applicant in writing or otherwise, or any searches of publicly available records or consumer reports that are conducted for the purpose of obtaining an applicant's criminal background information." The law further defines "any statement" as "a statement communicated in writing or otherwise to the applicant for purposes of obtaining an applicant's criminal background information regarding: (i) an arrest record; (ii) a conviction record; or (iii) a criminal background check." The NYCCHR defined "conditional offer of employment" in the Enforcement Guidance as:

> An offer of employment that can only be revoked based on: i The results of a criminal background check; ii The results of a medical exam in situations in which such exams are permitted by the Americans with Disabilities Act; or iii Other information the employer could not have reasonably known before the conditional offer if, based on the information, the employer would not have made the offer and the employer can show the information is material to job performance.

After an employer extends a conditional offer of employment to an applicant, the FCA permits it to make inquiries into an applicant's criminal history, including by running a background check. However, if an employer wishes to rescind a conditional offer of employment following a criminal background check, the FCA outlines a legal process (the "Fair Chance Process"), pursuant to which an employer must first: (i) disclose to the applicant a written copy of any inquiry it conducted into the applicant's criminal history; (ii) perform an analysis of the applicant under Article 23-A and share a written copy of this analysis with the applicant; and (iii) hold the position open for the applicant for at least three business days from the applicant's receipt of the inquiry and analysis to permit the applicant to respond. 

Pursuant to Article 23-A, an employer cannot withdraw a conditional offer because of the applicant's criminal record, unless the employer can: (i) draw a direct relationship between the applicant's criminal record and the prospective job; or (ii) show that employing the applicant "would involve an unreasonable risk to property or to the safety or welfare of specific individuals or the general public." Before concluding that a direct relationship or unreasonable risk exists because of an applicant's criminal history, Article 23-A requires prospective employers to consider eight factors:

> i The public policy of New York to encourage the licensure and employment of persons previously convicted of one or more criminal offenses; ii The specific duties and responsibilities necessarily related to the license or employment sought or held by the person; iii The bearing, if any, the criminal offense or offenses for which the person was previously convicted will have on his fitness or ability to perform one or more such duties or responsibilities; iv The time which has elapsed since the occurrence of the criminal offense or offenses; v The age of the person at the time of occurrence of the criminal offense or offenses; vi The seriousness of the offense or offenses; vii Any information produced by the person, or produced on his behalf, in regard to his rehabilitation and good conduct; and viii The legitimate interest of the public agency or private employer in protecting property, and the safety and welfare of specific individuals or the general public.

NYCCHR regulations interpreting the NYCHRL, as amended by the FCA, outline six hiring practices that constitute _per se_ violations of the FCA. These _per se_ violations are: (i) "declaring, printing, or circulating any solicitation, advertisement, policy or publication that expresses, directly or indirectly, orally or in writing, any limitation or specification in employment regarding criminal history"; (ii) "using applications for employment that require applicants to either grant employers permission to run a background check or provide information regarding criminal history prior to a conditional offer"; (iii) "making any statement or inquiry relating to the applicant's pending arrest or criminal conviction before a conditional offer is extended"; (iv) "using within New York City a standard form, such as a boilerplate job application, intended to be used across multiple jurisdictions, that requests or refers to criminal history"; (v) "failing to engage in any step of the legal process outlined prior to rescinding a conditional offer of employment"; and (vi) "requiring applicants or employees to disclose an arrest that, at the time disclosure is required, has resulted in a non-conviction." 

The NYCHRL affords a private right of action to "any person claiming to be a person aggrieved by an unlawful discriminatory practice as defined by the NYCHRL." The NYCHRL defines a "person aggrieved" to include one whose "only injury is the deprivation of a right granted or protected by this chapter." In light of this statutory directive, courts are to assess NYCHRL claims "broadly in favor of discrimination plaintiffs to the extent that such a construction is reasonably possible." 

##### Plaintiff Has Plausibly Alleged a Violation of the NYCHRL, as Amended by the FCA

Plaintiff asserts that Defendants' hiring practices violated his rights under the NYCHRL, as amended by the FCA, because Defendants (i) conducted a background check prior to extending a conditional offer of employment; (ii) declared that a background check would be conducted without first making a conditional offer of employment; and (iii) denied him employment without adhering to the Fair Chance Process. Plaintiff's central allegation is that the document that Defendants labeled a "conditional offer of employment" was a contrivance designed to circumvent the FCA and permit Defendants to scrutinize applicants' criminal histories prematurely in the hiring process. Defendants maintain the legitimacy of their conditional offer of employment and insist that their hiring practices accorded with the FCA. Defendants further argue that Franklin lost his right to an Article 23-A analysis before they rescinded their conditional offer because Franklin misrepresented his criminal history in executing the Background Check Release. The Court finds that Plaintiff has plausibly alleged that Defendants feigned a conditional offer of employment before inquiring into his criminal background. Accordingly, Plaintiff has stated a claim pursuant to the NYCHRL, as amended by the FCA.

Central to the parties' dispute in these motions is the legal effect of the Offer Form, and, more specifically, whether Defendants extended to Plaintiff a genuine conditional offer of employment prior to inquiring into his criminal history. In Plaintiff's estimation, the spurious nature of Defendants' conditional offer is evinced by (i) the impersonal and cursory nature of the hiring process and (ii) the language of the Offer Form. Plaintiff argues that the superficial application process, combined with the express reservations outlined in the Offer Form, suggest that Defendants' hiring practices were designed to frustrate the FCA's legal framework, which obligates employers to consider job applicants' qualifications and other positive attributes before investigating their criminal history. Defendants counter that their hiring practices abided by the letter of the law, as the FCA speaks only to the sequence of events that must occur before a prospective employer may inquire into an applicant's criminal background, a sequence Defendants followed. In essence, Defendants ask the Court to probe no further than the formal document that, they maintain, memorializes a conditional offer of employment. On their view, because the FCA contains no requirement that a prospective employer individually assess a candidate before extending a conditional offer, Plaintiff's allegations that Defendants' hiring procedures wholly lacked the traditional markers of a considered application process—such as the pre-offer exchange of background information, an interview, or any other meaningful screening measure—are of no moment. The Court rejects Defendants' suggestion that in pleading an NYCHRL claim, the form of the offer controls over its substance and context. Plaintiff's allegations plausibly call into question whether the Offer Form memorialized a bona fide conditional offer of employment or was merely an artifice to allow premature inquiry into applicants' criminal histories. At this stage of the proceedings, this is all Plaintiff must show to state a claim pursuant to the NYCHRL, as amended by the FCA.

The Court credits both of Plaintiff's arguments suggesting the invalidity of Defendants' purported conditional offer of employment. _First,_ Plaintiff alleges that Defendants expended virtually no effort assessing his (or anyone else's) candidacy before extending offers of employment. In Plaintiff's telling, he arrived at the Fresh Direct facility, sat through a presentation alongside numerous other applicants, reflexively signed an Offer Form, and immediately thereafter authorized a background check into his criminal history. Defendants' pre-offer procedures allegedly lacked any individualized questioning or assessment of any applicant. What is more, Plaintiff was told he could leave immediately after signing and returning his Background Check Release. At no point in the hiring process does Plaintiff allege that he faced individualized scrutiny; instead, he alleges an application process whereby Defendants automatically extended job offers to any candidate who remained present at the facility for the prescribed timeframe. 

Furthering his point, Plaintiff notes that there was an approximately six-minute gap between when Plaintiff signed the Offer Form and when he signed the Background Check Release authorizing Defendants to investigate his criminal history. Plaintiff argues that this near-immediate turnaround suggests that the Offer Form functioned as "an unlawful demand that job applicants relinquish their rights under the FCA, because its singular purpose was to allow Defendants to proceed as though the law did not exist." While Defendants are correct to note that the FCA does not set forth the amount of time that must pass between a conditional offer of employment and a permissible inquiry into a person's criminal history, the Court does not understand Plaintiff to advocate for the imposition of any bright-line temporal limitation in the FCA. Rather, the Court credits Plaintiff's argument that the immediacy of Defendants' distribution of Background Check Release forms _en masse_ to a room full of candidates who had, just moments before, been told they had secured conditional offers of employment, may betoken a hiring process specifically geared toward weeding out applicants with criminal backgrounds. This, combined with Plaintiff's other allegations about the nature of the hiring process, call into question whether the Offer Form can fairly be considered a "conditional offer of employment."

Defendants insist that they adhered to the formal sequence of events outlined by the FCA and that, as such, Plaintiff's claims fail as a matter of law. However, drawing this conclusion at the pleading stage in the present circumstances would effectively authorize employers to conduct the most perfunctory of assessments before opening the door to a candidate's criminal history. The Court admits of the possibility that discovery may bear out that the hiring process was more robust than that detailed in the Amended Complaint. But, taking Plaintiff's allegations as true on this motion, Defendants' conditional "offer" of employment appears to operate as a waiver of an applicant's rights under the FCA not to have their criminal history considered at the front end of the hiring process. In furtherance of the statutory directive to construe the NYCHRL "liberally for the accomplishment of its uniquely broad and remedial purposes," the Court will not interpret the FCA to permit employers to adopt hiring practices that undermine the statute's basic objective of limiting the role that an individual's criminal history plays in making hiring decisions.

_Second,_ Plaintiff argues that the language of the Offer Form undercuts its validity because the offer is expressly conditioned "upon a satisfactory outcome of the pre-employment screening process, which includes but is not necessarily limited to a review of past employment, education records, verification of ability to work in the United States, history background check and in some cases a drug screen." In Plaintiff's view, that Defendants reserved the right to rescind the offer based on a review of basic background information that could have been made available earlier in the hiring process lends further support to the illegitimacy of the conditional offer of employment. Defendants dispute that the FCA dictates the permissible content of a conditional offer of employment and argue that the information Defendants considered post-offer were things they could not reasonably have known earlier in the application process. 

In the enforcement guidance that was in effect at the time of Plaintiff's job application to work for Defendants, the NYCCHR defined a "conditional offer of employment" as an offer that can only be revoked based on: (i) the results of a criminal background check; (ii) the results of a medical exam; or (iii) _other information the employer could not have reasonably known before the conditional offer,_ if this information would have caused the employer not to extend the offer in the first place. Matters such as an applicant's employment history, education record, and verification to work in the United States are attributes that an employer can be expected to inquire into at the threshold, prior to making a conditional offer of employment. Therefore, it would arguably violate the NYCHRL for an employer to rescind a conditional offer of employment based on the information outlined in the Offer Form. To be clear, the Court does not read the FCA to prohibit prospective employers from verifying an applicant's credentials and withdrawing an offer if they come to learn that an applicant misrepresented his credentials—indeed, such information is likely not attainable pre-offer. That said, such is not the issue here, and irrespective of Defendants' rationale for denying Plaintiff employment, the language of the Offer Form lends further support to Plaintiff's contention that Defendants' conditional offer of employment was a hollow formality.

Accordingly, the Court concludes that Plaintiff has plausibly alleged that Defendants failed to make him a genuine conditional offer of employment prior to inquiring into his criminal background, which constitutes an actionable violation of the NYCHRL, as amended by the FCA.

##### Plaintiff Has Plausibly Alleged that Fresh Direct Was a Joint Employer

Independent of whether Plaintiff has plausibly alleged a primary violation of the FCA, Fresh Direct asserts that Plaintiff has failed to allege a basis to hold Fresh Direct liable for the hiring practices instituted by Vertex. Fresh Direct argues that Plaintiff's theory of Fresh Direct's liability is premised entirely on speculation and that the Amended Complaint is bereft of factual allegations tying Fresh Direct to Plaintiff's application for employment with Vertex. Plaintiff rejoins that his allegations suggest that Fresh Direct facilitated Vertex's hiring of employees in an illegal manner and that Vertex employees were subject to Fresh Direct's control. Thus, Plaintiff contends, Fresh Direct may be held liable as either a joint employer or as an aider and abettor of Vertex's discriminatory conduct. The Court concludes that, at the pleading stage, Plaintiff has plausibly alleged that Fresh Direct both acted as Plaintiff's prospective joint employer and aided and abetted Vertex's discriminatory conduct.

For a corporate defendant to be liable for alleged discrimination under the NYCHRL, the defendant must qualify as the plaintiff's "employer," as defined by the statute. A corporate defendant need not be a plaintiff's direct employer for liability to flow under the NYCHRL. "Under the joint employer doctrine, 'an employee, formally employed by one entity, who has been assigned to work in circumstances that justify the conclusion that the employee is at the same time constructively employed by another entity, may impose liability for violations of employment law on the constructive employer, on the theory that this other entity is the employee's joint employer.'" In making the essentially factual determination as to whether two entities are joint employers, courts have considered factors such as "commonality of hiring, firing, discipline, pay, insurance, records, and supervision." An "essential element" of such a finding is "sufficient evidence of immediate control over the employees." "The joint employer doctrine has been applied to temporary employment or staffing agencies and their client entities; it has also been applied to contractors and subcontractors and other scenarios where two separate entities have control over an employee's employment." 

Here, Plaintiff has set forth allegations giving rise to the plausible inference that Fresh Direct exercised sufficient control over Vertex employees to make it Plaintiff's prospective joint employer. In particular, Plaintiff has alleged that Vertex partnered with Fresh Direct to provide staffing services tailored to Fresh Direct's specific needs, going so far as to become "a partner and an extension of Fresh Direct's Human Resources Department." Vertex and Fresh Direct cooperated in the recruitment of job applicants, as shown by the fact that Vertex ran its hiring program at a Fresh Direct facility and that applicants were provided a nametag that included the logos of both Vertex and Fresh Direct. Plaintiff further alleges that individuals hired by Vertex worked under the direct supervision and control of Fresh Direct and sought "to carry out work in furtherance of" Fresh Direct's home grocery delivery business. Importantly for the purposes of the joint employer analysis, employment for Vertex functioned as a probationary period, after which employees who performed adequately could receive a full-time employment offer from Fresh Direct. To corroborate the pipeline between Vertex and Fresh Direct, Plaintiff included several anonymous employee reviews attesting to this arrangement.

Fresh Direct correctly notes that "application of the joint employer doctrine in the staffing agency context is plausible when the staffing agency has actually placed its employee with the third party, with whom it shared immediate control over the employee." However, the Court disagrees with Fresh Direct's conclusion that the joint employer doctrine is inappropriate in the present circumstances because Plaintiff was denied the opportunity for placement with Fresh Direct. It is true that Vertex rejected Plaintiff's job application, thus precluding the possibility that Plaintiff be placed with Fresh Direct. However, the fact that Vertex denied him this opportunity—on an ostensibly discriminatory basis—does not alter Plaintiff's allegations that he applied for a job that entailed providing services to Fresh Direct and being subject to Fresh Direct's supervision and control. Plaintiff's allegations detailing the relationship between Fresh Direct and Vertex—namely, the control that Fresh Direct exercised over individuals hired by Vertex and the foreseeability that Vertex employees would receive a formal job offer from Fresh Direct—suggest a sufficient degree of involvement and control by Fresh Direct to render it plausible that Plaintiff applied for a job in which he would have been "assigned to work in circumstances that justify the conclusion that he was at the same time constructively employed by Fresh Direct." 

Fresh Direct also cites several cases for the proposition that "even when a plaintiff establishes an entity's status as part of a joint employer, the plaintiff must still show 'that the joint employer knew or should have known of the discriminatory conduct and failed to take corrective measures within its control.'" Fresh Direct claims that it cannot be deemed a joint employer because all of the paperwork associated with Plaintiff's application referred to Vertex, and Vertex was the entity that provided Plaintiff with an allegedly sham conditional offer, impermissibly sought authorization to check his criminal history, and rescinded his offer without engaging in the Fair Chance Process. Here too, the Court disagrees with Fresh Direct's conclusion, as Plaintiff has clearly and plausibly alleged that Fresh Direct "knew or should have known of the discriminatory conduct," yet "failed to take corrective measures within its control." For instance, Plaintiff alleges that Vertex advertised itself as a staffing agency offering customized services to meet the specific needs of individual employers. Given the individualized nature of the services Vertex provided to Fresh Direct, Plaintiff intuits that Fresh Direct was at least aware of—indeed, may even have approved of—Vertex's impermissible culling of applicants with criminal backgrounds. Underscoring this point, Vertex operated on Fresh Direct's premises, where Fresh Direct could readily observe how Vertex operated in service of Fresh Direct. These allegations give rise to the plausible inference that Fresh Direct had a measure of control over Vertex and was at the very least aware of how Vertex went about hiring employees on its premises.

Fresh Direct additionally cites _Yousef v. Al Jazeera Media Network_ in support of its position that Plaintiff has not sufficiently alleged Fresh Direct's involvement in Vertex's discriminatory hiring practices. In _Yousef,_ a plaintiff alleging claims of gender discrimination, sexual harassment, and retaliation sought to hold a staffing agency that "provided employer of record services to plaintiff's formal employer, including payroll and human resources services," liable as a joint employer. However, this case actually undermines Fresh Direct's position, as the court found the staffing agency to be a joint employer where the facts connecting it to the alleged discriminatory conduct were sparser than those alleged here. Indeed, the court denied the staffing agency's motion to dismiss despite the absence of facts specifically connecting the agency to the plaintiff's claims of gender discrimination, sexual harassment, and retaliation.The court reasoned that "whether the staffing agency is liable under the joint employer doctrine requires a more fact-intensive inquiry," which could not be resolved in a motion to dismiss. So too here.

The other cases cited by Fresh Direct to defeat its liability under the joint employment doctrine are distinguishable. For instance, in _Sosa v. Medstaff, Inc.,_ the court found a staffing agency not to be liable as a joint employer where the plaintiff failed to assert factual allegations that plausibly connected the purported joint employer to the conduct at issue. More specifically, the plaintiff in _Sosa_ was a nurse placed by a staffing agency at a healthcare facility who brought claims of discrimination and hostile work environment related to conduct by plaintiff's supervisor at the medical facility. As the claims centered on the supervisor's conduct, the court determined that the staffing agency could not be held liable for plaintiff's claims because the supervisor, who was employed by the medical facility, was "not alleged to have had contact, much less a relationship" with the staffing agency. Here, however, Plaintiff's claims center on the alleged discrimination that Vertex perpetuated while on Fresh Direct's premises, in the process of hiring employees who were to provide services to Fresh Direct. Fresh Direct engaged Vertex's services for the specific purpose of hiring employees to staff its business operations. In outsourcing this function to Vertex, Fresh Direct plausibly possessed some degree of knowledge and control over what Vertex was doing on its premises for its benefit. Unlike the cases cited by Fresh Direct, Plaintiff's claims of discriminatory hiring go to the crux of the relationship between Fresh Direct and Vertex and necessarily implicate them both.

Fresh Direct also cites two cases in which sister courts in this District denied joint employer status to defendants that exercised only "the minimal level of oversight" that any contractor would naturally exercise over laborers operating on its premises. In _Conde,_ the court determined that a department store was not a plaintiff's joint employer when the plaintiff was formally employed by a company that operated a cosmetics counter within the department store. While the department store subjected the plaintiff to its dress code and workplace rules, the plaintiff's direct supervisor was an employee of the cosmetics company. The plaintiff alleged that her direct supervisor retaliated against her, fabricated allegations of misconduct against her, and compelled the cosmetic company's human resources director to offer her a transfer to a different department store. The court found that the cosmetics company, rather than the department store, was her employer, and the fact that the department store was involved in seeking plaintiff's transfer did not compel a contrary finding, because "an entity that has the power to request that an employee be moved but not to cause her to be terminated is not a joint employer."

In _Duff,_ the court concluded that a subcontracting company was not a plaintiff's joint employer when he was formally employed by a general contractor to work on a construction project. The plaintiff, who brought claims for race discrimination, hostile work environment and retaliation, was supervised at his worksite by an employee of the subcontracting company, and alleged that the subcontractor maintained records of his hours, had the power to discipline him, and provided anti-discrimination training. Citing _Conde,_ the court in _Duff_ reasoned that these allegations constituted only "'the minimal level of oversight that any' contractor would naturally exercise over laborers working on the contractor's worksite." Furthermore, the court reasoned that the subcontractor's anti-discrimination training merely reflected its interest in managing its workplace and that plaintiff remained employed by the general contractor following his removal from the worksite. 

The Court finds there to be a critical distinction between the putative joint employer relationships in _Conde_ and _Duff_ and that between Fresh Direct and Vertex: Individuals hired by Vertex operated with the expectation that satisfactory performance would lead to a full-time offer from Fresh Direct. This puts the employer relationship between Vertex and Fresh Direct on a fundamentally different plane than those in _Conde_ and _Duff_. In _Conde,_ there was no allegation that a protracted period of good work at the cosmetics counter could get someone hired at the department store. Likewise in _Duff,_ good performance for the general contractor would not be expected to lead to a full-time employment opportunity with the subcontractor. Where the plaintiffs in those cases could have been moved to different department stores or worksites and still maintain their jobs with their formal employers, the job to which Plaintiff applied was restricted at all times to providing services to Fresh Direct. Furthermore, the first three months of an individual's employment with Vertex constituted a "probationary period" that could lead to a full-time offer with Fresh Direct. While it is true that Plaintiff would have been aided by additional allegations of precisely how Fresh Direct exercised control over Vertex hires and the extent to which Fresh Direct possessed the power to terminate Vertex employees, these matters are appropriate subjects of inquiry in discovery. Plaintiff has plausibly alleged that Fresh Direct exercised more control over Vertex's employees than that "minimal level of oversight" incident to any individual working on an employer's premises. Accordingly, the Court concludes that Fresh Direct and Vertex were Plaintiff's prospective joint employers and, therefore, that Fresh Direct may be held liable for Vertex's alleged NYCHRL violations.

[^Franklin5]: (n. 5 in opinion) The FCA is one of a spate of so-called "ban the box" laws that have proliferated in jurisdictions across the United States; these laws generally prohibit the inclusion of questions related to conviction and arrest histories on job applications and delay criminal background checks until later in the hiring process. _See_ Beth Avery & Han Lu, [_Ban the Box: U.S. Cities, Counties, and States Adopt Fair Hiring Policies_](https://www.nelp.org/publication/ban-the-box-fair-chance-hiring-state-and-local-guide/), Nat'l Emp. L. Project (Oct. 1, 2021). 

### Karraker v. Rent-A-Center, Inc., 411 F.3d 831 (7th Cir. 2005)

To prove their worth prior to the annual college draft, NFL teams test aspiring professional football players' ability to run, catch, and throw. But that's not all. In addition to the physical tests, a draft prospect also takes up to 15 personality and knowledge tests, answering questions such as:

> Assume the first two statements are true.
> 
> The boy plays football. All football players wear helmets. The boy wears a helmet.
> 
> Is the final statement:
> 
> "True?
> 
> "False?
> 
> "Not certain

They are also asked questions like "What is the ninth month of the year?" _See_ Richard Hoffer, "Get Smart!", _Sports Illustrated_ (Sept. 5, 1994).

This case involves a battery of nonphysical tests similar to some of those given by NFL teams, though the employees here applied for less glamorous, and far less well-paying, positions. Steven, Michael, and Christopher Karraker are brothers who worked for Rent-A-Center (RAC), a chain of stores that offer appliances, furniture, and other household goods on a rent-to-own basis. During the relevant time, each RAC store had a store manager, several middle managers, and entry-level account managers. Most new employees start as account managers and can progress to upper-level positions. In order to secure a promotion, however, an employee was required to take the APT Management Trainee-Executive Profile, which was made up of nine tests designed to measure math and language skills as well as interests and personality traits.

As part of the APT Test, the Karrakers and others were asked 502 questions from the Minnesota Multiphasic Personality Inventory (MMPI), a test RAC said it used to measure personality traits. But the MMPI does not simply measure such potentially relevant traits as whether someone works well in groups or is comfortable in a fast-paced office. Instead, the MMPI considers where an applicant falls on scales measuring traits such as depression, hypochondriasis, hysteria, paranoia, and mania. In fact, elevated scores on certain scales of the MMPI can be used in diagnoses of certain psychiatric disorders.

All parts of the APT Test were scored together, and any applicant who had more than 12 "weighted deviations" was not considered for promotion. Thus, an applicant could be denied any chance for advancement simply because of his or her score on the MMPI. The Karrakers, who all had more than 12 deviations on the APT, sued on behalf of the employees at 106 Illinois RAC stores, claiming RAC's use of the MMPI as part of its testing program violated the Americans With Disabilities Act of 1990 (ADA). They also claimed that RAC failed to protect the confidentiality of the test results in violation of Illinois tort law.

The district court first granted RAC's motion for partial summary judgment on Steven Karraker's failure to promote claim, finding that he did not file his charge of discrimination with the EEOC within 300 days of any alleged discrimination. The court also granted the Karrakers' motion for class certification on the ADA and public disclosure of private facts claims.

The district court later granted RAC's motion for summary judgment and denied the Karrakers' motion for summary judgment on the outstanding claims with the exception of Steven Karraker's wrongful termination claim. The Karrakers stipulated to the dismissal of that claim to allow this appeal to go forward. Here, they challenge the district court's decision that the use of the MMPI did not violate the ADA, the dismissal of Steven Karraker's failure to promote claim, and the dismissal of the Karrakers' claim of public disclosure of private facts. 

Americans with disabilities often faced barriers to joining and succeeding in the workforce. These barriers were not limited to inaccessible physical structures. They also included attitudinal barriers resulting from unfounded stereotypes and prejudice. People with psychiatric disabilities have suffered as a result of such attitudinal barriers, with an employment rate dramatically lower than people without disabilities and far lower than people with other types of disabilities. 

Congress enacted the ADA to "provide a clear and comprehensive national mandate for the elimination of discrimination against individuals with disabilities." Congress recognized that "the Nation's proper goals regarding individuals with disabilities are to assure equality of opportunity, full participation, independent living, and economic self-sufficiency for such individuals." The ADA's definition of disability is not limited to physical impairments, but also includes mental impairments. Title I of the ADA is devoted to eliminating employment discrimination based on actual or perceived disabilities.

Congress enacted three provisions in Title I which explicitly limit the ability of employers to use "medical examinations and inquiries" as a condition of employment: a prohibition against using pre-employment medical tests; a prohibition against the use of medical tests that lack job-relatedness and business necessity; and a prohibition against the use of tests which screen out (or tend to screen out) people with disabilities.

At its heart, the issue in this case is whether the MMPI fits the ADA's definition of a "medical examination." In that regard, we note the parties' agreement that, although the Karrakers were already employed by RAC, the tests here were administered "pre-employment" for ADA purposes because they were required for those seeking new positions within RAC. This agreement means we need not determine whether the Karrakers should be considered to be in the preemployment offer category. Plaintiffs have argued only that the MMPI is a medical examination. RAC could have argued not only that the MMPI is not a medical examination, but also that even if it is, it is "job-related and consistent with business necessity." By prevailing on the latter, defendants could claim that the test is permissible during employment, even if impermissible pre-offer. By not arguing that the test is "job-related and consistent with business necessity," RAC seeks a clear finding that the MMPI is not a medical examination and thus not regulated at all by the ADA.

The EEOC defines "medical examination" as "a procedure or test that seeks information about an individual's physical or mental impairments or health." _See_ "[ADA Enforcement Guidance: Preemployment Disability-Related Questions and Medical Examinations](https://www.eeoc.gov/laws/guidance/enforcement-guidance-preemployment-disability-related-questions-and-medical)" (1995). According to the EEOC, factors to consider in determining whether a particular test is a "medical examination" include:

> (1\) whether the test is administered by a health care professional;
> 
> (2\) whether the test is interpreted by a health care professional;
> 
> (3\) whether the test is designed to reveal an impairment of physical or mental health;
> 
> (4\) whether the test is invasive;
> 
> (5\) whether the test measures an employee's performance of a task or measures his/her physiological responses to performing the task;
> 
> (6\) whether the test normally is given in a medical setting; and
> 
> (7\) whether medical equipment is used.

"One factor may be enough to determine that a procedure or test is medical." Psychological tests that are "designed to identify a mental disorder or impairment" qualify as medical examinations, but psychological tests "that measure personality traits such as honesty, preferences, and habits" do not.

Therefore, this case largely turns on whether the MMPI test is designed to reveal a mental impairment. RAC argues that, as it used the MMPI, the test only measured personality traits. For example, RAC argues in its brief that the MMPI does not test whether an applicant is clinically depressed, only "the extent to which the test subject is experiencing the kinds of feelings of 'depression' that everyone feels from time to time (_e.g.,_ when their favorite team loses the World Series)." Although that particular example seems odd to us (can an Illinois chain really fill its management positions if it won't promote disgruntled Cubs fans?), the logic behind it doesn't seem to add up, either. Repeating the claim at oral argument, RAC argued that the MMPI merely tested a "state of mood" and suggested that an applicant might, for example, score high on the depression scale because he lost his keys that morning. But why would RAC care if an applicant lost his keys the morning of the MMPI or took the test the day after another Cubs loss? Would RAC really want to exclude an employee from consideration for a promotion because he happened to feel sad on the wrong day? We see two possibilities: either the MMPI was a very poor predictor of an applicant's potential as a manager (which might be one reason it is no longer used by RAC), or it actually was designed to measure more than just an applicant's mood on a given day.

To help us sort out which of these possibilities is more likely, the EEOC guidelines offer three examples of tests given pre-employment:

> Example: A psychological test is designed to reveal mental illness, but a particular employer says it does not give the test to disclose mental illness (for example, the employer says it uses the test to disclose just tastes and habits). But, the test also is interpreted by a psychologist, and is routinely used in a clinical setting to provide evidence that would lead to a diagnosis of a mental disorder or impairment (for example, whether an applicant has paranoid tendencies, or is depressed). Under these facts, this test is a medical examination.
> 
> Example: An employer gives applicants the RUOK Test (hypothetical), an examination which reflects whether applicants have characteristics that lead to identifying whether the individual has excessive anxiety, depression, and certain compulsive disorders (DSM-listed conditions). This test is medical.
> 
> Example: An employer gives the IFIB Personality Test (hypothetical), an examination designed and used to reflect only whether an applicant is likely to lie. This test, as used by the employer, is not a medical examination.

RAC's use of the MMPI almost fits the first example in that it is a psychological test that is designed, at least in part, to reveal mental illness. And RAC claims it uses the test only to measure personality traits, not to disclose mental illness. The parallel falls apart, however, because the test was not interpreted by a psychologist, a difference that led the district court to conclude that it is not a medical examination. In doing so, the district court relied on the deposition testimony of Colin Koransky, a clinical psychologist. Koransky described various scoring methods for the MMPI, explaining that a clinical protocol could be used for medical purposes while a vocational scoring protocol would focus more on personality traits of potential employees. The district court found that, because RAC used the vocational protocol to score the test, RAC used the MMPI "solely for the purposes of discerning personality traits."

The mere fact that a psychologist did not interpret the MMPI is not, however, dispositive. The problem with the district court's analysis is that the practical effect of the use of the MMPI is similar no matter how the test is used or scored—that is, whether or not RAC used the test to weed out applicants with certain disorders, its use of the MMPI likely had the effect of excluding employees with disorders from promotions.

Dr. Koransky claims, for example, that the Pa scale "does not diagnose or detect any psychological disorders," but that "an elevated score on the Pa scale is one of several symptoms which may contribute" to a diagnosis of paranoid personality disorder. We accept Dr. Koransky's contention that a high score on the Pa scale does not necessarily mean that the person has paranoid personality disorder. But it also seems likely that a person who does, in fact, have paranoid personality disorder, and is therefore protected under the ADA, would register a high score on the Pa scale. And that high score could end up costing the applicant any chance of a promotion. Because it is designed, at least in part, to reveal mental illness and has the effect of hurting the employment prospects of one with a mental disability, we think the MMPI is best categorized as a medical examination. And even though the MMPI was only a part (albeit a significant part) of a battery of tests administered to employees looking to advance, its use, we conclude, violated the ADA.

## Negligent Hiring 

### Keith v. Health-Pro Home Care Services, Inc., 873 S.E.2d 567 (N.C. 2022)

Employers are in no way general insurers of acts committed by their employees, but as recognized by our precedent, an employer may owe a duty of care to a victim of an employee's intentional tort when there is a nexus between the employment relationship and the injury. Here, when the evidence is viewed in the light most favorable to the plaintiffs, plaintiffs, who are an elderly infirm couple that contracted with a company to provide them a personal care aide in their home, have shown a nexus between their injury and the employment relationship. The employee was inadequately screened and supervised, being placed in a position of opportunity to commit crimes against vulnerable plaintiffs after her employer suspected her of stealing from plaintiffs. Therefore, we conclude that the Court of Appeals erred by reversing the judgment in favor of plaintiffs and by remanding for entry of a judgment notwithstanding the verdict in favor of defendant. Further, the Court of Appeals misinterpreted North Carolina precedent, and thus erred by holding the trial court erred by denying defendant's requested instructions.

#### Background

On 29 September 2016, plaintiffs Thomas and Teresa Keith (Mr. and Mrs. Keith), an elderly married couple with health and mobility issues, were the victims of a home invasion and armed robbery orchestrated by a personal care aide working for defendant Health-Pro Home Care Services, Inc. (Health-Pro). The aide, Deitra Clark, was assigned to assist the Keiths in their home. Clark subsequently pleaded guilty to first-degree burglary and second-degree kidnapping for her conduct.

In December 2016, the Keiths sued Health-Pro for negligence and punitive damages. The Keiths alleged that they hired Health-Pro as their in-home health care provider and "despite Deitra Clark's criminal record, lack of a driver's license, and history of prior incidents of suspected prior thefts from the Keiths' home, Health-Pro negligently allowed Deitra Clark to provide in-home care to the Keiths, and Health-Pro's conduct in assigning Deitra Clark to these responsibilities, as opposed to some other position in the company, was a proximate cause of the robbery of the Keiths and the consequent injuries sustained by them."

The case proceeded to trial and was tried before a jury at the 19 March 2018 session of superior court in Pitt County. At the conclusion of the Keiths' presentation of evidence, Health-Pro moved for directed verdict on the negligence claim pursuant to North Carolina Rule of Civil Procedure 50. Health-Pro argued that:

> As far as negligence, your Honor, we would contend there has been no evidence to meet the Plaintiffs' burden of proof. My understanding from the proposed jury instructions that the Plaintiffs have passed up is they treat this as an ordinary negligence case. The Defense contends this is negligence sic hiring retention and supervision case, which is part of our proposed instructions. That's very similar to what the Plaintiffs have pled. That type of case is what has essentially been argued to this jury and that's what the evidence has revealed. In order to succeed on that case and even in an ordinary negligence case the Plaintiffs have to show that the events of September 29th, 2016, and Deitra Clarks' unfitness and participation in those events were foreseeable to my clients. Those are the events that have caused the Plaintiffs the only injury they complain of. And there is nothing in the record that suggests that it was foreseeable.

The trial court denied the motion for a directed verdict.

The jury returned a verdict in favor of the Keiths. The jury answered in the affirmative that both Mr. and Mrs. Keith were injured by the negligence of Health-Pro. The jury found Mr. Keith entitled to recover $500,000 in damages from Health-Pro for his personal injuries and found Mrs. Keith entitled to recover $250,000 in damages from Health-Pro for her personal injuries. The trial court then entered judgment to this effect on 11 April 2018.

Health-Pro subsequently moved for judgment notwithstanding the verdict and, in the alternative, for a new trial . The trial court denied these post-trial motions . Health-Pro appealed . 

On appeal, a divided panel of the Court of Appeals reversed the judgment and remanded for entry of a judgment notwithstanding the verdict in Health-Pro's favor. 

To address Health-Pro's appeal of the trial court's denial of its motions for directed verdict and motion for judgment notwithstanding the verdict, the Court of Appeals determined that it "must first decide whether the Keiths' case was appropriately presented to the jury as an 'ordinary' negligence claim instead of an action for negligent hiring." The Court of Appeals considered the allegations in the Keiths' complaint and the evidence presented at trial "within the context of precedent governing both ordinary negligence and negligent hiring." The Court of Appeals ultimately indicated that it agreed with Health-Pro that the Keiths' "allegations and the facts of this case constituted a claim for negligent hiring," obligating the Keiths to prosecute their claim as one for negligent hiring. The Court of Appeals explained as follows:

> _All_ of Plaintiffs' relevant allegations and evidence directly challenge whether Defendant should have hired Ms. Clark as an in-home aide; whether Defendant acted appropriately in response to hearing from Plaintiffs that money had been taken from their home on two occasions—which would have involved either greater supervision of—such as moving Ms. Clark to a no-client-contact position, as suggested by Plaintiffs—or a decision regarding whether to retain her in Defendant's employ at all. Plaintiffs have cited no binding authority for the proposition that an action brought on allegations, and tried on facts, that clearly fall within the scope of a negligent hiring claim may avoid the heightened burden of proving all the elements of negligent hiring by simply designating the action as one in ordinary negligence, and we find none.

As such, the Court of Appeals held that the trial court erred by denying Health-Pro's motions for directed verdict and judgment notwithstanding the verdict "with respect to ordinary negligence, as that claim was not properly before the trial court, and no evidence could support it." 

The Court of Appeals then considered whether the Keiths' evidence was sufficient to survive a motion for judgment notwithstanding the verdict "based upon the theory of negligent hiring." It began by discussing the Court of Appeals' case _Little v. Omega Meats I, Inc.,_ 171 N.C. Ct. App. 583 (2005), which this Court affirmed per curiam without written opinion.

The Court of Appeals concluded that according to _Little,_ "three specific elements must be proven by a plaintiff in order to show that an employer had a duty to protect a third party from its employee's negligent or intentional acts committed out-side of the scope of the employment." Specifically,

> (1\) the employee and the plaintiff must have been in places where each had a right to be when the wrongful act occurred; (2) the plaintiff must have met the employee, when the wrongful act occurred, as a direct result of the employment; and (3) the employer must have received some benefit, even if only potential or indirect, from the meeting of the employee and the plaintiff that resulted in the plaintiff's injury.

The Court of Appeals held that there was no evidence to support any of the three elements in this case.

Next, the Court of Appeals concluded that even if the requirements of _Little_ are not applicable to this case, the trial court still erred by denying Health-Pro's motion for judgment notwithstanding the verdict based on a theory of negligent hiring. Specifically, the Court of Appeals held that Health-Pro had no duty to protect the Keiths' from Clark's criminal acts on 29 September 2016, and the Keiths' "evidence was insufficient to demonstrate proximate cause.

The dissent disagreed with the majority's holding that the judgment in favor of the Keiths must be reversed and that Health-Pro was entitled to judgment as a matter of law. The dissent contended that although the Keiths alleged that Health-Pro was negligent in hiring Clark, the evidence of negligent hiring "is merely a means by which a plaintiff proves ordinary negligence." "Negligent hiring (like any other ordinary negligence claim) requires a plaintiff to show that the defendant owed a duty, that the defendant breached that duty, and that the plaintiff suffered an injury proximately caused by the breach." 

Further, the dissent argued that when viewed in the light most favorable to the Keiths, the evidence was sufficient to make out an ordinary negligence claim based on their evidence of Health-Pro's negligent hiring of a dishonest employee. Unlike the majority, the dissent concluded that the Keiths did not have to prove that the robbery occurred while Clark was on duty. The evidence was sufficient for a negligence claim because when viewed in the light most favorable to the Keiths, Health-Pro's "dishonest employee used 'intel' learned while on duty to facilitate a theft." 

The dissent asserted its view that the majority misread _Little_, and analyzed how the evidence when viewed in the light most favorable to the Keiths, as the non-moving party, is sufficient for each element, rendering denial of the motions for directed verdict and judgment notwithstanding the verdict proper.

The dissent acknowledged that reasonable minds may reach different conclusions concerning Health-Pro's liability for the criminal conduct of Clark in this case, but that decision was for the jury, and the jury has spoken in this case in favor of liability.

The Keiths appealed based on the dissent . 

#### Analysis

##### Health-Pro's Rule 50 Motions

To address the issues before us, we must summarize the relevant aspects of the law of this State concerning negligence and negligent hiring. The common law claim of negligence has three elements: (1) a legal duty owed by the defendant to the plaintiff, (2) a breach of that legal duty, and (3) injury proximately caused by the breach. Precedent decided by this Court further defines the contours of these three elements. For instance, this Court has recognized that "no legal duty exists unless the injury to the plaintiff was foreseeable and avoidable through due care." 

Given this limitation, a defendant rarely has a legal duty to prevent the criminal acts of others. However, "a defendant may be liable for the criminal acts of another when the defendant's relationship with the plaintiff or the third person justifies making the defendant answerable civilly for the harm to the plaintiff." For example, this Court has recognized that a common carrier owes to its passengers a duty to provide for their safe conveyance and that, in the performance of its duty, it must protect a passenger from assault by the carrier's employees and intruders when by the exercise of due care, the acts of violence could have been foreseen and avoided. Similarly, a store owner owes to a customer on its premises during business hours for the purpose of transacting business thereon a duty to protect or warn the customer of endangerment from the criminal acts of third persons when reasonably foreseeable by the store owner and when such acts could have been prevented by the exercise of ordinary care by the store owner. 

In the context of employment, this Court held that a defendant employer owes its employees the duty to exercise reasonable care in its employment and retention of employees, and if there be negligence in this respect, which is shown to be proximate cause of the injury to the employee, the defendant employer may be liable for the injury caused by the negligence of the fellow employee, or by the intentional torts of the employer's supervisors. Later precedent recognized that an employer's duty to exercise reasonable care in its employment and retention of employees could extend to third persons. 

In _Braswell_ and _Medlin,_ this Court expressly recognized that North Carolina courts have recognized a cause of action for negligent hiring. In _Medlin,_ this Court delineated what a plaintiff must prove for this claim:

> (1\) the specific negligent act on which the action is founded (2) incompetency, by inherent unfitness or previous specific acts of negligence, from which incompetency may be inferred; and (3) either actual notice to the master of such unfitness or bad habits, or constructive notice, by showing that the master could have known the facts had he used ordinary care in 'oversight and supervision,' and (4) that the injury complained of resulted from the incompetency proved.

In _Little,_ the Court of Appeals addressed whether there was sufficient evidence for a claim by third-person plaintiffs for negligent hiring against a defendant employer when the injury causing acts were intentional torts and criminal. The Court of Appeals held that on the record before it, the defendant employer did not owe plaintiffs a duty of care and affirmed the trial court's granting of directed verdict in the defendant employer's favor. The Court of Appeals explained:

> In the instant case Smith, an independent contractor for defendant employer Omega, was not in a place where he had a legal right to be since he broke in to plaintiffs' home; Smith and plaintiffs did not meet as a direct result of Smiths' relationship with defendants, since he did not enter plaintiffs' home as a salesman; finally, defendants received no benefit, direct, indirect or potential, from the tragic "meeting" between Smith and plaintiffs. We have found no authority in North Carolina suggesting that defendants owed plaintiffs a duty of care on these facts, and we hold that in fact none existed.
> 
> We refuse to make employers insurers to the public at large by imposing a legal duty on employers for victims of their independent contractors' intentional torts that bear no relationship to the employment. We note that because this is a direct action against the employer, for the purposes of this appeal the result would be the same if Smith had been an employee of defendants instead of an independent contractor. Smith could have perpetrated the exact same crimes against these plaintiffs, in the exact same manner, and with identical chances of success, on a day that he was not selling Omega's meats and driving Omega's vehicle.

Prior to this analysis and holding, the Court of Appeals quoted three sentences from an article published in the Minnesota Law Review:

> Most jurisdictions accepting the theory of negligent hiring have stated that an employer's duty to select competent employees extends to any member of the general public who comes into contact with the employment situation. Thus, courts have found liability in cases where employers invite the general public onto the business premises, or require employees to visit residences or employment establishments. One commentator, in analyzing the requisite connection between plaintiffs and employment situations in negligent hiring cases, noted three common factors underlying most case law upholding a duty to third parties: (1) the employee and the plaintiff must have been in places where each had a right to be when the wrongful act occurred; (2) the plaintiff must have met the employee as a direct result of the employment; and (3) the employer must have received some benefit, even if only potential or indirect, from the meeting of the employee and the plaintiff.

Citing this Article, the Court of Appeals in _Little_ further stated, "courts in other jurisdictions have generally, though not exclusively, declined to hold employers liable for the acts of their independent contractors or employees under the doctrine of negligent hiring or retention when _any one_ of these three factors was not proven."

The dissent in _Little_ contended that "our courts have already established a duty on the part of employers of independent contractors and that the majority opinion's conclusion that there is no duty in this case—as a matter of law—cannot be reconciled with this authority." This Court affirmed per curiam the Court of Appeals' decision. 

In the case before us, the Court of Appeals interpreted the aforementioned statements in _Little_ as having "identified three specific elements that must be proven in order to show that an employer had a duty to protect a third party from its employee's negligent or intentional acts committed out-side of the scope of the employment." We hold that the Court of Appeals erred by reading _Little_ as adopting such rigid requirements for reasons similar to those that the Court of Appeals' dissent in this case raised.

In _Little,_ the Court of Appeals quoted a statement from a Minnesota Law Review article that "_one commentator_ noted three common _factors_ underlying _most_ case law upholding a duty to third parties" and cited this article for support that there is a _general,_ but _not exclusive,_ trend in other jurisdictions related to these factors. The Court of Appeals' analysis in _Little_ implicitly reflected consideration of these factors, but the Court of Appeals indicated that its decision turned on the lack of "authority in North Carolina suggesting that defendants owed plaintiffs a duty of care _on these facts._"

The Court of Appeals did not state that it adopted these factors. It further did not even describe other jurisdictions as holding these factors to be elements. Nowhere in the _Little_ decision did it state that these factors must be alleged, proven, or shown in courts of this State to establish an employer's duty to a third-party injured by an employee to exercise reasonable care in its hiring of employees. Nor is it said that these factors are required. Rather, the Court of Appeals "refused to make employers insurers to the public at large by imposing a legal duty on employers for victims of their independent contractors' intentional torts that bear no relationship to the employment," and thus "required for a duty to third parties for negligent hiring a nexus between the employment relationship and the injury." The _Little_ court considered these factors, in the absence of existing North Carolina law, in determining whether there is a sufficient nexus between the employment relationship and the injury, but it did not adopt a requirement that all three factors be proven.

Thus, the Court of Appeals in this case erred by reading _Little_ to have "identified three specific elements that must be proven," and by declining "to hold employers liable for the acts of their employees under the doctrine of negligent hiring or retention when any one of these three factors was not proven." 

The Court of Appeals further erred by holding that the trial court erred by denying Health-Pro's motions for directed verdict and judgment notwithstanding the verdict. The Court of Appeals agreed with defendant that the Keiths' were obligated to prosecute their claim as one for negligent hiring because the Keiths' allegations and facts of this case constituted a claim for negligent hiring. However, this conclusion and the analysis supporting it failed to properly apply the standard of review for Rule 50 motions, the matter before the Court of Appeals.

Even when addressing an argument by Health-Pro that the negligence claim in this case is in fact a negligent hiring claim, a Rule 50 motion turns on the sufficiency of the evidence at the trial. Thus, we analyze the evidence at trial to assess whether there is support for each element of the nonmoving party's cause of action.

The evidence at trial tended to show the following when viewed in the light most favorable to the nonmoving party, the Keiths. The Keiths were an elderly couple with serious health issues and limited mobility. Mr. Keith had just undergone heart surgery when they sought an at-home-care provider. The Keiths and their son, Fred Keith (Fred), met with Health-Pro's sole owner, Chief Executive Officer, and President, Sylvester Bailey III (Mr. Bailey). Health-Pro provided at-home personal and health care. During that meeting, Health-Pro, through Mr. Bailey, informed them that all employees undergo criminal background checks. After the meeting, the Keiths hired Health-Pro for their services in December 2012.

In 2015, Health-Pro received an employment application from Clark and permission to conduct a criminal background check. Pursuant to State law, "an offer of employment by a home care agency licensed under Chapter 131E on Health Care Facilities and Services to an applicant to fill a position that requires entering the patient's home is conditioned on consent to a criminal history record check of the applicant." 

Health-Pro's criminal background investigation policy was that "all employees of Health-Pro must undergo a criminal background check by the State Bureau of Investigation or other approved entity" and "if the criminal history involves a felony not listed above, a misdemeanor, a series of arrests, or a criminal conviction greater than seven years, the agency will review the offense, its relevance to the particular job performance, and to the length of time between conviction and the employment date." Further, "a decision regarding employment will be reached only after the nature, severity and date of the offense have been carefully evaluated."

Similarly, under State law,

> within five business days of making a conditional offer of employment, a home care agency shall submit a request to the Department of Public Safety under § 143B-939 to conduct a State or national criminal history record check required by § 131E-265, or shall submit a request to a private entity to conduct a State criminal history record check required by § 131E-265.

"If an applicant's criminal history record check reveals one or more convictions of a relevant offense, the home care agency shall consider the enumerated factors in this section in determining whether to hire the applicant." Relevant offense is defined as "a county, state, or federal criminal history of conviction or pending indictment of a crime, whether a misdemeanor or felony, that bears upon an individual's fitness to have responsibility for the safety and well-being of aged or disabled persons." "An entity and officers and employees of an entity shall be immune from civil liability for failure to check an employee's history of criminal offenses if the employee's criminal history record check is requested and received in compliance with N.C.G.S. § 131E-266." 

Health-Pro admitted that it did not run a criminal background check with the State Bureau of Investigation or other approved entity and admitted that the review and evaluation required by the policy was not completed. However, Health-Pro contended it ran a criminal background check and was aware of Clark's misdemeanor convictions and other charges. To the contrary, the only document in Health-Pro's employment file relating to a criminal background check was one page and only showed personal information not material to this decision:

Additionally, the company, from which Health-Pro contended it ran a criminal background check, stated on its website that its services cannot be used to conduct background checks for employees or applicants.

Mr. Bailey offered conflicting testimony at trial concerning why Health-Pro's employment file for Clark only contained this one page, first stating that Health-Pro culled down the file every year because some reports were fifteen pages and then later saying Health-Pro just prints one page of a criminal background report for the file. Notably, Mr. Bailey also testified at his deposition that he conducted the criminal background check but did not have a specific memory of running the check or seeing the charges and convictions. Yet, he subsequently changed his testimony when deposed as the representative of Health-Pro and when he testified at trial.

Health-Pro's criminal background investigation policy also dictated that the criminal history record information received from the criminal background check be stored in a separate locked file in the Human Resource Department, but this was not done. Additionally, the Interviewing and Hiring Process form used by Health-Pro for hiring Clark did not have checks next to the boxes for a criminal background check as reflected below:

Thus, viewed in the light most favorable to the Keiths, Health-Pro did not run a criminal background check of Clark upon hiring her as a personal care aide in September 2015. It did not check to confirm that she had a driver's license as indicated on her application. Health-Pro simply interviewed Clark after receiving her application and then hired her. Nevertheless, Health-Pro represented on its website that it carefully screened caregivers by calling previous employers and performing criminal background checks.

As of the date of her hiring, a criminal background check of Clark would have revealed the following: 2007 charge for no operator's license; 2008 found guilty of driving while license revoked; 2009 charge for possession of marijuana; 2009 found guilty of possession of drug paraphernalia; 2010 charge for possession of drug paraphernalia; 2010 charge for communicating threats (dismissed because of noncooperating witness); 2010 found guilty of criminal contempt; and 2011 charge for communicating threats (dismissed because of noncooperating witness). Further, at that time, Clark did not have a valid driver's license.

Clark, however, indicated on her employment application that she had never been convicted of or entered a plea of guilty in a court of law. Thus, as conceded by Health-Pro, Clark lied on her job application about her criminal background. Health-Pro acknowledged that this dishonesty would be concerning to Health-Pro if caught. Clark also identified that she had a driver's license on her application, but she did not have a driver's license at the time of her application, just an identification card.

A few months later in November or December, Health-Pro assigned Clark to work for the Keiths as a personal care aide at their home. The Keiths understood that Health-Pro ran background checks on all their aides, including Clark, and would provide aides that would do a good job and not pose a danger.

Clark was one of the primary aides working for the Keiths. She helped in the home by cleaning the house, doing laundry, and driving Mrs. Keith for errands. Clark had access to the whole house and could move around the house freely. Through her employment, Clark learned about the Keiths, their valuables, their schedules, their collection of rolled coins, and their spare key.

On or about 25 May 2016, Health-Pro received a letter from Pitt County Child Support Enforcement indicating that a claim against Clark for nonpayment of child support was being pursued.

In 2016, after Clark had been assigned to the Keiths' home, the Keiths' granddaughter and daughter discovered that about $900 of rolled coins were missing. Additionally, $1,260 in cash went missing from Mrs. Keith's dresser. Before the cash went missing, an aide had seen Mrs. Keith remove money from her dresser drawer. Mrs. Keith thought the aide was Clark but was not positive, so she did not accuse her when the cash went missing. Cash also went missing from Mr. Keith's wallet on two occasions.

The Keiths informed Health-Pro about the missing money, and Mr. Bailey on behalf of Health-Pro came to the Keiths' home to discuss in July 2016. The missing money was not located at the meeting (nor was it ever found), but Health-Pro said it would investigate everything and removed Clark and the other aide assigned at the time from servicing the Keiths' home. Health-Pro also agreed to pay back the missing money to the Keiths.

Health-Pro determined that Clark and one other aide were the only aides in the home on the days that money went missing and spoke to them. Yet, Health-Pro did nothing further; it did not run a criminal background check or report the incident to the police.

Fred, the Keiths' son, also met with Mr. Bailey after he learned about the missing money. Mr. Bailey informed Fred that it was either Clark or the other aide but that he had a strong belief that Clark was the one involved. Mr. Bailey assured Fred that neither one of them would be back in his parents' home, and Fred made clear that he did not want Clark back in his parents' home.

Nevertheless, a few weeks later, Health-Pro assigned Clark back to the Keiths' home. Although Health-Pro contended that Fred asked for Clark to return to the home because Clark gave Mrs. Keith better baths than other aides, Fred testified that he disputed Health-Pro's contention, and the Keiths testified that they did not ask for Clark to be reassigned to their home. The Keiths assumed that Health-Pro, after completing its investigation, thought Clark did not pose a threat to the Keiths. Health-Pro also admitted that it did not inform Fred that they were sending Clark back to the home. Thus, viewing the evidence in the light most favorable to the Keiths, Health-Pro made the unilateral decision to reassign Clark as a personal care aide to the Keiths' home after the thefts.

On 9 September 2016, Health-Pro received another letter from Pitt County Child Support Enforcement.

A few weeks later on 28 September 2016, Clark used the information that she gleaned about the Keiths' home, the comings and goings of Health-Pro aides and the Keiths' family, and their valuables to accomplish a home invasion and robbery. Clark informed her accomplices about everything, including the location of the spare hidden key. Clark also knew and shared with her accomplices that the Health-Pro aide assigned to work that evening, Erica, would leave when her shift ended at 11:00 p.m. and no other family was visiting and staying with the Keiths that evening.

The assigned aide, Erica, did in fact leave in accordance with her shift schedule at 11:00 p.m. on the evening of 28 September 2016. Shortly thereafter, Clark drove her two accomplices in her car to the Keiths' house and dropped them off to complete the home invasion and robbery. Her accomplices dressed in dark clothing and wore masks. Between 11:30 p.m. and 12:00 a.m., the accomplices used the spare hidden key to enter the house and walked into the den where Mr. Keith was watching a movie. Mrs. Keith was in bed. The accomplices disconnected the telephone.

As testified by Mr. Keith, the accomplices knew exactly where to go in the house; they knew where everything was.

One accomplice had a gun and pointed the gun at Mr. Keith and ordered Mr. Keith to lay on the floor face down. The other accomplice walked into the bedroom where Mrs. Keith was lying in bed and took from the bed stand the .32 caliber Harrison and Richardson pistol belonging to Mr. Keith. The originally armed accomplice found Mr. Keith's ATM card in one of his desk drawers and started waiving it around like it was something for which he was searching. Additionally, while in the home, the other accomplice stole the Keiths' two boxes of rolled coins, totaling $500. The Keiths had stored the boxes in a black bag under Mr. Keith's work desk in the den of their home. One of the accomplices also told Mrs. Keith that she should be sure to mention the name of Erica.

The originally armed accomplice forced Mr. Keith at gunpoint to drive him to an ATM. During the drive to the ATM, the accomplice asked Mr. Keith if he had a worker that comes over to the home named Erica. After Mr. Keith answered affirmatively, the accomplice told Mr. Keith that he needed to fire Erica because she left the door open. Arriving at the ATM around 12:30 a.m., the accomplice forced Mr. Keith to withdraw a thousand dollars. The accomplice then ordered Mr. Keith to drive him to an elementary school, where the accomplice got out of the car and ran away.

Clark picked up both accomplices along with the stolen cash, coins, and gun. Thereafter, she and the accomplices took her car to Walmart to convert the stolen coins into cash by using a Coinstar machine at around 1:00 a.m.

Health-Pro terminated Clark after it identified her in the video footage from the police showing the conversion of the coins to cash at the Coinstar machine.Only after the home invasion and robbery and after firing Clark did Health-Pro run a criminal background check on Clark.

After undertaking an analysis of the evidence and considering it in the light most favorable to the Keiths, we find that there is evidence to support each element of the Keiths' cause of action and that the motion for directed verdict and subsequent motion for judgment notwithstanding the verdict should be denied. 

Here, the Keiths pursued a negligence claim against the employer of the intentional tortfeasor, Health-Pro, premised on Health-Pro's own negligence in hiring, retaining, and/or assigning Clark, the intentional tortfeasor, to work as a personal care aide at their home. Given that the Keiths' claim relied on negligence by the employer in hiring, retaining, and/or assigning an employee, our precedent recognizes this claim under the theory of liability known as negligent hiring, or more commonly framed as a claim for negligent hiring. While the elements of negligence are a legal duty, breach, and injury proximately caused by the breach, appellate precedent further defines the contours of these elements in specific contexts as previously discussed. Thus, when a plaintiff alleges an employer negligently hired, retained, or supervised an employee, and seeks recovery from the employer for injury caused by the employee, the elements for negligent hiring and the nexus requirement for duty must be satisfied to show a negligence claim in this context.

Therefore, to survive a motion for directed verdict or judgment notwithstanding the verdict for their negligence claim, the Keiths had to present evidence to support each element set forth in _Medlin_ and to support a nexus between the employment and the injury as required by _Little._ The evidence when viewed in the light most favorable to the Keiths, as summarized previously, satisfied the elements in _Medlin_ and the nexus requirement in _Little._ In addition to evidence supporting each of the elements, there is enough distinguishing this case from _Little_ and enough similarity with _Lamb_ to preclude our precedent from foreclosing the claim as a matter of law.

Unlike _Little,_ the evidence viewed in the light most favorable to plaintiffs suggests a sufficient nexus between the injurious act and employment relationship to create a duty. The plaintiffs in this case were daily customers of the defendant employer and had been for years. The defendant employer assigned the intentional tortfeasor employee to work for the plaintiffs inside plaintiffs' home. Thus, defendant employer participated in the meeting between the intentional tortfeasor employee and the plaintiffs and gained financially from their continued meeting. When viewed in the light most favorable to the Keiths, the intentional tortfeasor employee also injured the plaintiff customer, the Keiths, by disclosing and using the intel she gained through her employment to orchestrate a robbery at the intentional tortfeasor employee's place of employment, the Keiths' home.

When the evidence is viewed in the light most favorable to the Keiths, the intentional tortfeasor employee was skilled at her work but incompetent to work for vulnerable customers in the customers' home without supervision by another, rendering this case similar to _Lamb_. In _Lamb,_ the defendant's supervisor had command over the department in which plaintiff, a ten-year-old boy, worked as floor sweeper. The supervisor shoved plaintiff causing him injury, and plaintiff sued the supervisor's employer. While there was no evidence of the unskillfulness of the supervisor, he had treated the plaintiff poorly the day before the injury and had a general reputation for his cruelty and temper. This Court concluded that "the evidence shows that he was unfit and incompetent to perform the duties of supervising children and the help under him by reason of his cruel nature and high temper." Given the foregoing, this Court found that the trial court erred by not submitting the case to the jury and reversed the motion dismissing the case for nonsuit.

In this case, evidence concerning the falsities in Clark's employment application, Health-Pro's belief that she committed the prior thefts, and the particulars of her criminal background support the inference that Health-Pro knew or should have known of Clark's incompetence for her assignment to the Keiths' home. Health-Pro's personal care aides served elderly and vulnerable adults and by the nature of their work gained information about their clients' daily routine, personality, finances, and home and were not supervised while in the home. The Keiths, in fact, retained Health-Pro because Mr. Keith needed an at-home-care provider after his heart surgery and throughout their engagement of Health-Pro's services were elderly and with serious health issues and limited mobility.

In addition to the foregoing, evidence also supports the foreseeability of the injury to the Keiths from such incompetence. "Proximate cause is a cause which in natural and continuous sequence produces a plaintiff's injuries and one from which a person of ordinary prudence could have reasonably foreseen that such a result or some similar injurious result was probable." "It is not necessary that a defendant anticipate the particular consequences which ultimately result from his negligence. It is required only that a person of ordinary prudence could have reasonably foreseen that such a result, _or some similar injurious result,_ was probable under the facts as they existed." 

In this matter, Health-Pro acknowledged that it must discipline employees when Health-Pro knows the employee did something out of compliance because absent discipline, there is a risk that the conduct would get worse. Health-Pro also knew or should have known that Clark was under financial strain on account of the child support enforcement letters and that Clark may retaliate against the Keiths for disclosing the prior thefts given particulars in her criminal background, including charges of communicating threats and a conviction for criminal contempt. Health-Pro further knew or should have known that Clark committed prior thefts in the Keiths' home. Additionally, because of their age, medical conditions, and limited mobility, the Keiths were vulnerable to adverse conduct against them in their home by an incompetent Health-Pro employee. Thus, when viewed in the light most favorable to the Keiths, a person of ordinary prudence could have reasonably foreseen that as a result of Health-Pro's negligent hiring, the home invasion and robbery of the Keiths' home or some similar injurious result was probable and that the trauma from such event would injure the Keiths.

Thus, in this case, the jury, not the court, must decide the outcome of the Keiths' claim. The Court of Appeals in this matter erred by not considering the evidence in the light most favorable to the Keiths, just as Health-Pro's arguments urge us to do. Health-Pro contends that Clark's actions bore no relationship to her employment and no action or inaction by Health-Pro proximately caused the Keiths' injuries because "any information Clark learned about the Keiths' home on the job could have been ascertained just as easily by others watching the home from the street." The jury could have agreed with Health-Pro and weighed the evidence in its favor but given the testimony and evidence before the trial court supporting a contrary interpretation of the facts, this argument cannot justify judgment in Health-Pro's favor as a matter of law. We must view all of the evidence which supports the Keith's claim as true and consider the evidence in the light most favorable to the Keiths, giving them the benefit of every reasonable inference that may legitimately be drawn therefrom and resolving contradictions, conflicts, and inconsistencies in their favor. Therefore, we conclude that the Court of Appeals erred by reversing the trial court and remanding for entry of judgment in favor of Health-Pro.

#### Conclusion

We agree with the Court of Appeals that plaintiffs' negligence claim was dependent on a theory of negligent hiring, which is commonly plead as a negligent hiring claim. However, the evidence, taken in the light most favorable to plaintiffs, was sufficient as a matter of law to be presented to the jury. There was evidence to support each element of the claim, the _Medlin_ elements, and the _Little_ nexus requirement. Therefore, the Court of Appeals erred by reversing the judgment in favor of plaintiffs and by remanding to the trial court for entry of an order granting defendant's motion for judgment notwithstanding the verdict. Further, the Court of Appeals misinterpreted precedent from _Little,_ and under a proper reading of that case and other precedent, the jury instruction requested by defendant was not an accurate statement of the law. Therefore, the Court of Appeals also erred by holding that the trial court erred by denying defendant's requested instruction. Accordingly, we reverse the Court of Appeals' decision.