# Accommodating Employee Medical Needs and Conditions

## Family & Medical Leave

### Family and Medical Leave Act, 29 U.S.C. § 2601 et seq.

::: {.aside}
_See also_, Wage & Hour Division, [Family & Medical Leave Act regulations](https://www.law.cornell.edu/cfr/text/29/part-825), 29 CFR Part 825
:::

::: {.legalcode}

#### § 2601--Definitions

**(2\) Eligible employee**

- **(A\) In general**

- The term “eligible employee” means an employee who has been employed—
	- (i\) for at least 12 months by the employer with respect to whom leave is requested under section 2612 of this title; and
	- (ii\) for at least 1,250 hours of service with such employer during the previous 12-month period.
- (B\) Exclusions
- The term “eligible employee” does not include—
	- (i\)  [ ... ]
	- (ii\) any employee of an employer who is employed at a worksite at which such employer employs less than 50 employees if the total number of employees employed by that employer within 75 miles of that worksite is less than 50.

**(4\) Employer**

- (A\) In general
- The term “employer”—
	- (i\) means any person engaged in commerce or in any industry or activity affecting commerce who employs 50 or more employees for each working day during each of 20 or more calendar workweeks in the current or preceding calendar year;
	- (ii\) includes—
	- (I\) any person who acts, directly or indirectly, in the interest of an employer to any of the employees of such employer; and
	- (II\) any successor in interest of an employer;
	- [ ... ] 

**(11\) Serious health condition**

The term “serious health condition” means an illness, injury, impairment, or physical or mental condition that involves—

- (A\) inpatient care in a hospital, hospice, or residential medical care facility; or
- (B\) continuing treatment by a health care provider.

#### § 2602--Leave requirement

**(a\) In general**

- (1\) Entitlement to leave
- Subject to section 2613 of this title and subsection (d)(3), an eligible employee shall be entitled to a total of 12 workweeks of leave during any 12-month period for one or more of the following:
	- (A\) Because of the birth of a son or daughter of the employee and in order to care for such son or daughter.
	- (B\) Because of the placement of a son or daughter with the employee for adoption or foster care.
	- (C\) In order to care for the spouse, or a son, daughter, or parent, of the employee, if such spouse, son, daughter, or parent has a serious health condition.
	- (D\) Because of a serious health condition that makes the employee unable to perform the functions of the position of such employee.
	- (E\) Because of any qualifying exigency [ ... ] arising out of the fact that the spouse, or a son, daughter, or parent of the employee is on covered active duty (or has been notified of an impending call or order to covered active duty) in the Armed Forces.
	- (F\) During the period beginning on the date the Emergency Family and Medical Leave Expansion Act takes effect, and ending on December 31, 2020, because of a qualifying need related to a public health emergency in accordance with section 2620 of this title.

- **(4\) Combined leave total**

- Subject to subsection (d)(3), during the single 12-month period described in paragraph (3), an eligible employee shall be entitled to a combined total of 26 workweeks of leave under paragraphs (1) and (3). Nothing in this paragraph shall be construed to limit the availability of leave under paragraph (1) during any other 12-month period.

#### § 2614--Employment and benefits protection

(a\) Restoration to position

- (1\) In general
- Except as provided in subsection (b), any eligible employee who takes leave under section 2612 of this title for the intended purpose of the leave shall be entitled, on return from such leave—
	- (A\) to be restored by the employer to the position of employment held by the employee when the leave commenced; or
	- (B\) to be restored to an equivalent position with equivalent employment benefits, pay, and other terms and conditions of employment.
- (2\) Loss of benefits
- The taking of leave under section 2612 of this title shall not result in the loss of any employment benefit accrued prior to the date on which the leave commenced.
- (3\) Limitations
- Nothing in this section shall be construed to entitle any restored employee to—
	- (A\) the accrual of any seniority or employment benefits during any period of leave; or
	- (B\) any right, benefit, or position of employment other than any right, benefit, or position to which the employee would have been entitled had the employee not taken the leave.
- (4\) Certification
- As a condition of restoration under paragraph (1) for an employee who has taken leave under section 2612(a)(1)(D) of this title, the employer may have a uniformly applied practice or policy that requires each such employee to receive certification from the health care provider of the employee that the employee is able to resume work, except that nothing in this paragraph shall supersede a valid State or local law or a collective bargaining agreement that governs the return to work of such employees.
- (5\) Construction
- Nothing in this subsection shall be construed to prohibit an employer from requiring an employee on leave under section 2612 of this title to report periodically to the employer on the status and intention of the employee to return to work.

(b\) Exemption concerning certain highly compensated employees

- (1\) Denial of restoration
- An employer may deny restoration under subsection (a) to any eligible employee described in paragraph (2) if—
	- (A\) such denial is necessary to prevent substantial and grievous economic injury to the operations of the employer;
	- (B\) the employer notifies the employee of the intent of the employer to deny restoration on such basis at the time the employer determines that such injury would occur; and
	- (C\) in any case in which the leave has commenced, the employee elects not to return to employment after receiving such notice.
- (2\) Affected employees
- An eligible employee described in paragraph (1) is a salaried eligible employee who is among the highest paid 10 percent of the employees employed by the employer within 75 miles of the facility at which the employee is employed.

(c\) Maintenance of health benefits

- (1\) Coverage
- Except as provided in paragraph (2), during any period that an eligible employee takes leave under section 2612 of this title, the employer shall maintain coverage under any “group health plan” (as defined in section 5000(b)(1) of title 26) for the duration of such leave at the level and under the conditions coverage would have been provided if the employee had continued in employment continuously for the duration of such leave.
- (2\) Failure to return from leave
- The employer may recover the premium that the employer paid for maintaining coverage for the employee under such group health plan during any period of unpaid leave under section 2612 of this title if—
	- (A\) the employee fails to return from leave under section 2612 of this title after the period of leave to which the employee is entitled has expired; and
	- (B\) the employee fails to return to work for a reason other than—
	- (i\) the continuation, recurrence, or onset of a serious health condition that entitles the employee to leave under subparagraph (C) or (D) of section 2612(a)(1) of this title or under section 2612(a)(3) of this title; or
	- (ii\)other circumstances beyond the control of the employee.
- (3\) Certification
	- (A\) Issuance
	- An employer may require that a claim that an employee is unable to return to work because of the continuation, recurrence, or onset of the serious health condition described in paragraph (2)(B)(i) be supported by—
	- (i\) a certification issued by the health care provider of the son, daughter, spouse, or parent of the employee, as appropriate, in the case of an employee unable to return to work because of a condition specified in section 2612(a)(1)(C) of this title;
	- (ii\) a certification issued by the health care provider of the eligible employee, in the case of an employee unable to return to work because of a condition specified in section 2612(a)(1)(D) of this title; or
	- (iii\) a certification issued by the health care provider of the servicemember being cared for by the employee, in the case of an employee unable to return to work because of a condition specified in section 2612(a)(3) of this title.

#### § 2615--Prohibited acts

(a\) Interference with rights

- (1) Exercise of rights
- It shall be unlawful for any employer to interfere with, restrain, or deny the exercise of or the attempt to exercise, any right provided under this subchapter.
- (2\) Discrimination
- It shall be unlawful for any employer to discharge or in any other manner discriminate against any individual for opposing any practice made unlawful by this subchapter.

(b\) Interference with proceedings or inquiries

It shall be unlawful for any person to discharge or in any other manner discriminate against any individual because such individual—

- (1\) has filed any charge, or has instituted or caused to be instituted any proceeding, under or related to this subchapter;
- (2\) has given, or is about to give, any information in connection with any inquiry or proceeding relating to any right provided under this subchapter; or
- (3\) has testified, or is about to testify, in any inquiry or proceeding relating to any right provided under this subchapter.

:::

### Ramji v. Hospital Housekeeping Systems, LLC, 992 F.3d 1233 (11th Cir. 2021)

The Family Medical Leave Act ("FMLA") is a federal statute that entitles eligible workers who need to recover from a serious injury to take up to twelve weeks of unpaid leave during any twelve-month period. Employers are prohibited from interfering with, restraining, or denying an employee's efforts to exercise any FMLA right. Separately, most states require employers to provide their employees with workers' compensation benefits. Workers' compensation allows an employee who is injured in a work-related incident to receive payments for all reasonable medical care and lost wages resulting from that injury.

Sometimes the benefits of these laws can overlap. That's what happened here. Now, Defendant-Appellee Hospital Housekeeping Systems seeks to use one—workers' compensation—as a shield against the other—the FMLA. Hospital Housekeeping's employee Plaintiff-Appellant Noorjahan Ramji seriously injured her knee while at work. Hospital Housekeeping told her nothing about her rights under the FMLA, instead handling the injury solely as a workers' compensation claim.

After a few days off and a temporary light-duty assignment, Ramji received medical clearance to resume her regular-duty position. But before Hospital Housekeeping would allow her to do so, Ramji first had to pass an essential-functions test, which required her to complete certain physical tasks that the doctor who cleared her was not advised of. Among other things, Ramji had to repeatedly engage in deep squats and bend to one knee. Though Ramji was able to perform several of these exercises, she began to experience pain in her injured knee before she finished all of them. As a result, Ramji did not pass the test. So Hospital Housekeeping discharged Ramji. At no point before Hospital Housekeeping fired Ramji did Hospital Housekeeping advise Ramji of her rights under the FMLA or give Ramji an opportunity to take twelve uninterrupted weeks of leave to rehabilitate her knee, even though the FMLA entitled her to that relief.

Ramji filed suit for interference with her FMLA rights. At the district court, the parties filed cross-motions for summary judgment. Hospital Housekeeping sought in part to avoid liability under the FMLA by pointing to its compliance with its workers' compensation responsibilities. The district court granted summary judgment in favor of Hospital Housekeeping.

But the FMLA does not set up a clash of Titans between itself and workers' compensation. So providing workers' compensation benefits cannot absolve an employer of all obligations under the FMLA. For this reason and others, and with the benefit of oral argument, we vacate the entry of summary judgment and remand for further proceedings.

#### I.

For nearly eleven years, Ramji worked as a housekeeper, cleaning patient-examination rooms, hallways, and bathrooms at Eastside Medical Center in Snellville, Georgia. Her daily tasks included mopping, sweeping, dusting, cleaning walls, removing trash, and making beds.

In 2013, Hospital Housekeeping, which provides contracted cleaning and facilities-management services to hospitals, took over maintenance operations at Eastside Medical Center. Ramji's employment fell under Hospital Housekeeping.

On the morning of September 15, 2016, as Ramji was getting ready to clock out from her night shift, she tripped on the leg of a breakroom table, fell face down onto the ground, and injured her right knee. Pamela Merriweather, then the director of Hospital Housekeeping's division at Eastside Medical Center, assisted Ramji into a wheelchair and took her to the emergency room for an X-ray of her swollen knee.

Upon examining Ramji's knee, Physician Assistant Christina Eid issued Ramji a medical work excuse: "Ramji was seen on 9/15/2016 and is excused from work from 9/15/2016 through 9/18/2016."

At the time of her injury, Hospital Housekeeping did not provide Ramji with any information about eligibility for leave and rights under the FMLA. Instead, Hospital Housekeeping immediately handled Ramji's injury as a workers' compensation claim. And when Ramji needed to take eleven days off between the date of her accident and her return to work in a light-duty position, Hospital Housekeeping required Ramji to use sick leave.

During this eleven-day period, on September 23, Ramji had her first follow-up medical appointment with Dr. David Harkins of Athens Orthopedics. In accordance with Hospital Housekeeping's workers' compensation policy, Merriweather accompanied Ramji to all follow-up appointments and treatments. At the September 23 appointment, Dr. Harkins injected a cortisone shot into Ramji's knee and diagnosed her injury as right knee pain and derangement. Dr. Harkins also referred Ramji for physical-therapy sessions to occur two to three times per week for six to eight weeks. The goal of these sessions was to increase the knee's range of movement and strength while decreasing pain. Besides treating Ramji, Dr. Harkins issued a light-duty medical release permitting Ramji's return to work—but with the following restrictions: no squatting, kneeling, or climbing.

Three days after that appointment, Hospital Housekeeping offered Ramji the chance to return to a light-duty position with restrictions on kneeling, squatting, and climbing. That position included tasks like making copies, folding rags and mops, creating washcloth origami, cleaning small items, counting inventory, and rolling silverware. Ramji accepted the offer and returned to work that day.

On October 10, Ramji, once again accompanied by Merriweather, attended her first physical-therapy session. The physical therapist observed signs and symptoms consistent with right knee derangement and recommended that Ramji initially be seen twice a week for four weeks, for a total of eight visits. But, the physical therapist added, therapy might be extended and occur more frequently, depending on Ramji's progression. Ramji found these physical-therapy sessions helpful in reducing her knee pain.

On October 21, before completing the physical therapist's full recommended physical-therapy course, Ramji had a second follow-up appointment with Dr. Harkins. She told Dr. Harkins that the cortisone injection she received during her September 23 appointment "took away all of her pain," that "physical therapy has helped tremendously," and that she was ready to return to work. After observing the knee's full range of motion without pain or instability, Dr. Harkins concluded that Ramji's right knee and ankle pain had been resolved and that she had reached maximum medical improvement with a zero-percent disability rating. As a result, Dr. Harkins reasoned, Ramji could return to regular-duty work that day.

Significantly, though, Merriweather, who once again accompanied Ramji to her appointment with Dr. Harkins, never advised Dr. Harkins about Ramji's regular duties at Eastside Medical Center. Nor did Merriweather explain that company policy required Ramji to complete an essential-functions test upon her return to work from her injury or what tasks the essential-functions test demanded. Dr. Harkins also did not address the need for Ramji's remaining physical-therapy sessions, and he did not opine on Ramji's ability to complete specific tasks required in her regular-duty position.

With her medical release in hand, Ramji returned to work that same day. Marcia Gordon, then the Assistant Director of Hospital Housekeeping's second and third shifts at Eastside Medical Center, explained that the company's workers' compensation policy required that "all injured employees returning to regular duty complete an Essential Functions Test." Ramji, who was unaware of this requirement, the content of the test, or consequences of failing it, took the test.

The essential-functions test required Ramji to successfully complete twenty tasks assessing her ability to grip, bend, lift, twist, climb, and push. An employee unable to complete every task listed on the test is subject to termination of her employment.

Five of the twenty tasks gave Ramji particular difficulty. Ramji had to complete ten deep-knee bends or squats. Deep-knee squats require the employee to squat down until her calves touch the backs of her thighs. After Ramji completed five deep-knee squats, her right knee began to hurt. Ramji informed Gordon of her knee pain and her inability to perform any more squats. Gordon then brought in Merriweather to help finish administering the essential-functions test. Despite Ramji's recent injury and her complaints of knee pain, Merriweather insisted that Ramji complete the remaining deep-knee squats.

But Ramji's knee pain persisted, and she was concerned about exacerbating her injury. So Ramji asked Merriweather whether she could use accrued sick and vacation leave to give herself additional recovery time to allow her to be able to finish the essential-functions test upon her return from leave. Merriweather refused, stating that Ramji could not use her sick or vacation leave and insisting that Ramji finish the essential-functions test that day.

With no other choice, Ramji continued plugging along with the test. As the test progressed, Ramji had trouble when Merriweather instructed Ramji to kneel on one knee until it touched the floor and then to stand up and kneel on the other knee until it touched the floor. Ramji's knee pain prevented her from being able to complete this task.

Next, Merriweather directed Ramji to use one hand to lift a twenty-pound bag out of a hamper and place into a soiled-linen cart. Ramji struggled to lift a ten-pound bag with one hand.

Merriweather also told Ramji to walk up and down a flight of stairs without using a handrail. Although Ramji walked up and down the stairs, she had to use the guardrail for support. Merriweather also noted that Ramji was "very wobbly coming down" and lost balance on the steps.

The last task that caused difficulty required Ramji to stand on her toes and hold for 30 seconds. Ramji claimed that she was able to hold the pose for more than 30 seconds, but the essential-functions test notes indicated that she did not successfully complete the task. After failing the essential-functions test, Ramji went home for the weekend.

When Ramji returned the following Monday, October 24, Merriweather issued written warnings to Ramji for past incidents, including the September 2016 accident that led to her knee injury, a December 2015 accident in which Ramji tripped on a phone cord and injured her forehead, and an August 2014 insubordination matter where Ramji failed to attend a mandatory staff meeting. Merriweather also notified Ramji that Hospital Housekeeping was terminating her employment for failing to complete five tasks on the essential-functions test. Ramji responded by again asking to use unused sick and vacation leave, but Merriweather denied the request, noting that she was firing Ramji.

Ramji could not pay out of her own pocket for medical appointments and physical-therapy treatments even though the treatments offered promising benefits. So she hired a workers' compensation lawyer, who helped her successfully reinstate medical care and ultimately obtain a financial settlement. But the process of restoring benefits and approving medical providers resulted in somewhat delayed and interrupted follow-up medical and physical-therapy treatments, as we summarize below.

Four months after her termination, Ramji resumed medical appointments when she had her first appointment with Dr. Maurice Jove, who tried a variety of methods to reduce Ramji's knee pain, including a cortisone shot, unloader knee brace, six weeks of physical therapy, and an eight-week supply of an anti-inflammatory medication. After returning to physical-therapy sessions, Ramji felt improvements but wanted to continue physical therapy to ensure her knee completely healed.

Dr. Jove subsequently released Ramji to work "immediately with no restrictions," but he prescribed an additional three physical-therapy sessions per week for six weeks. Despite Dr. Jove's recommendation, Hospital Housekeeping never approved the additional physical-therapy sessions under workers' compensation, so Ramji stopped attending physical therapy. After a review of Ramji's MRI results, Dr. Jove observed that Ramji had osteoarthritis in her knee and recommended a knee replacement, since arthroscopic treatment would be ineffective.

Ramji obtained a second opinion from Dr. Scott Barbour, who also ultimately recommended a knee replacement. But Dr. Barbour concluded that Ramji's condition requiring treatment, including surgery, resulted primarily from the September 16 workplace accident.

Ramji and Hospital Housekeeping ultimately agreed to a settlement of her workers' compensation claim. Because of the costs, at no point until this time was Ramji able to receive an uninterrupted twelve-week period of treatment, including physical-therapy sessions.

After the settlement, Ramji began working with a physical therapist again. She fully recovered when she was finally able to take twelve continuous weeks of physical-therapy sessions and appropriate treatment. Ramji now maintains that she can perform all duties and functions required of her regular-duty position at Hospital Housekeeping.

#### III.

The FMLA entitles employees to take leave for certain family and medical reasons. 29 U.S.C. §§ 2601 and 2612. Among these, an eligible employee may take up to twelve weeks of leave because of a serious health condition that renders the employee unable to perform the functions of her position. § 2612(a)(1)(D). The FMLA also guarantees an eligible employee the right to be restored to her former position, or an equivalent position, at the end of her leave, provided she can execute the essential functions of her job. § 2614(a)(1). But if, after twelve weeks, the employee cannot perform an essential function of her job, her employer may choose to end her employment. 29 C.F.R. § 825.216(c).

Under the FMLA, a covered employer may not interfere with, restrain, or deny the employee's exercise or attempted exercise of her FMLA rights to coverage, leave entitlement, notice, benefits continuation, and job restoration. 29 U.S.C. § 2615(a)(1); 29 U.S.C. §§ 2601-2654; 29 C.F.R. §§ 825.100-825.803.

To establish an FMLA interference claim, an employee must show she was entitled to a benefit under the FMLA and her employer denied her that benefit. But a technical FMLA violation alone is not enough. Rather, the employee must also "demonstrate some harm" from the alleged interference, and that harm must be "remediable by either "damages' or 'equitable relief.'" Below, we address each of these requirements as they relate to Ramji's claim.

##### A.

We begin by considering whether Ramji showed she was entitled to an FMLA benefit. To satisfy this requirement, an eligible employee must demonstrate that she sought leave for a qualifying reason and that she provided notice meeting certain criteria. 

The record contains ample evidence that Ramji's knee injury served as a qualifying reason to take FMLA leave. An employee is entitled to FMLA leave if she has "a serious health condition that makes her unable to perform the functions of her position." 29 U.S.C. § 2612(a)(1)(D). A "serious health condition" means "an illness, injury, impairment, or physical or mental condition that involves continuing treatment by a health care provider." § 2611(11)(B). To qualify as "continuing treatment" under FMLA regulations, treatment (1) must involve a period of incapacity of more than three consecutive, full calendar days, and (2) must require either (a) treatment by a healthcare provider at least twice within 30 days of the first day of incapacity or (b) treatment by a healthcare provider at least once that results in a regimen of continuing treatment under the supervision of the healthcare provider. 29 C.F.R. § 825.115(a)(1)-(a)(2).

Ramji's knee injury satisfies all these definitions.

First, Ramji injured her knee on the morning of September 15, and, after an emergency-room visit, she was excused from work from September 15 through September 18. That's more than three consecutive, full days, so it meets the first half of the "continuing treatment" standard 29 C.F.R. § 825.115(a)(1) articulates.

Second, Ramji attended a follow-up appointment with Dr. Harkins on September 23. At that appointment, he gave her a cortisone injection in her knee, restricted her to light duty, and referred her to physical-therapy sessions occurring two to three times each week for six to eight weeks. That satisfies the second qualifying condition for "continuing treatment," since Dr. Harkins prescribed a continuing regimen of physical therapy for Ramji. 29 C.F.R. § 825.115(a)(2).

Ramji therefore had a qualifying "serious health condition." 29 U.S.C. § 2611(11)(B). And that condition caused her to be unable to perform the essential functions of her job. § 2612(a)(1)(D).

As for whether Ramji placed Hospital Housekeeping on sufficient notice for its duty to inform her of her right to FMLA leave, Ramji provided enough evidence there as well to allow a reasonable jury to conclude she met this requirement. This inquiry presents a mixed question of fact and law: the factfinder identifies the notice given, and the court assesses whether that notice was legally sufficient to cause the employer's obligations to be triggered.

The critical question we must consider asks whether the "employee adequately conveyed to the employer sufficient information to put the employer on notice that her absence was potentially FMLA-qualifying." An employee must provide proper notice to make out an FMLA interference claim. To fulfill this requirement, an employee's notice must be timely and contain sufficient information—requirements that differ, depending on whether the employee's need for leave is foreseeable or unforeseeable. 

When, as here, the employee's need for leave is unforeseeable, she must give notice "as soon as practicable under the facts and circumstances of the particular case." 29 C.F.R § 825.303(a). As for the content of the notice, an employee seeking FMLA leave for the first time need not "expressly assert rights under the FMLA or even mention the FMLA to meet her obligation to provide notice." §§ 825.301(b) and 825.303(b). Rather, notice must simply allow the employer to understand that the employee potentially qualifies for FMLA rights. FMLA regulations offer examples of sufficient notice, such as providing information about the "condition that renders the employee unable to perform the functions of the job" or "the anticipated duration of the absence, if known." § 825.303(b).

Ramji contends that Hospital Housekeeping had real-time, sufficient notice of both her need for leave and the nature of her health condition. She points to the fact that Merriweather, who was Hospital Housekeeping's FMLA administrator for Eastside Medical Center, was there when Ramji injured herself. Not only that, but Merriweather handled Ramji's workers' compensation and workplace-injury forms. Hospital Housekeeping also knew that Ramji was excused from work from September 15 through September 18. Plus, Merriweather personally accompanied Ramji to follow-up medical appointments and the doctor-prescribed physical-therapy sessions. We agree that these facts demonstrate that Hospital Housekeeping knew of the nature of Ramji's injury and her potential qualification for FMLA leave.

So taking the evidence in the light most favorable to Ramji, Ramji has established that she was entitled to an FMLA benefit. For that reason, Ramji meets the first element of an FMLA-interference claim.

##### B.

That brings us to the second element of an FMLA interference claim—whether Ramji demonstrated that Hospital Housekeeping denied her a leave benefit under the FMLA. 

When an employer acquires knowledge that an employee's leave may be for an FMLA-qualifying reason, that triggers the employer's obligation to evaluate whether the employee's requested absence in fact qualifies for FMLA protection. The employer must also provide notice to the employee of her eligibility for and rights under the FMLA within a certain timeframe. 29 C.F.R. § 825.300. A "failure to follow the notice requirements may constitute an interference with, restraint, or denial of the exercise of an employee's FMLA rights." § 825.300(e).

Ramji argues that Hospital Housekeeping denied her two types of FMLA notice: "eligibility notice" and "rights and responsibilities notice." To satisfy its eligibility-notice requirement, an employer must advise its employee of her "eligibility to take FMLA leave within five business days, absent extenuating circumstances." § 825.300(b)(1). Rights-and-responsibilities notice must "detail the specific expectations and obligations of the employee and explain any consequences of a failure to meet these obligations." § 825.300(c)(1). As relevant here, rights-and-responsibilities notice must advise the employee of (1) the fact that "the leave may be designated and counted against the employee's annual FMLA leave entitlement and the applicable 12-month period for FMLA entitlement," (2) "the employee's right to substitute paid leave ," as applicable, and (3) "the employee's rights to maintenance of benefits during the FMLA leave and restoration to the same or an equivalent job upon return from FMLA leave." § 825.300(c)(1)(i), (iii), and (vi). The employer must give the employee the rights-and-responsibilities notice at the same time it provides eligibility notice. § 825.300(c)(1).

Here, on September 16, a formal workers' compensation claim for Ramji was filed with Hospital Housekeeping. That claim included information about the nature of Ramji's knee injury, the need for emergency medical and follow-up treatment, and a release excusing Ramji from three days of work. And this information, in turn, activated Hospital Housekeeping's duty to provide Ramji with FMLA notice within five business days, or in this case, by September 23. § 825.300(b)(1). But Hospital Housekeeping never offered Ramji FMLA eligibility and rights-and-responsibilities notice at any point during Ramji's knee-injury recovery. So a reasonable jury could conclude that Hospital Housekeeping interfered with Ramji's FMLA rights.

Hospital Housekeeping offers two excuses for why Ramji was not entitled to notice of her FMLA rights. First, it notes that it handled Ramji's on-the-job injury through workers' compensation. And Hospital Housekeeping asserts that, as Ramji was compensated for the excused days of work between September 15 and September 18 and was expected to return to work on September 19, it had no reason to believe Ramji needed FMLA leave for that period, and Ramji did not request FMLA leave. Second, Hospital Housekeeping observes that Ramji's September 23 follow-up appointment fell on the same day as the purported deadline for the employer's FMLA notice requirement. Based on this circumstance, Hospital Housekeeping contends that extenuating circumstances prevented it from offering Ramji FMLA leave before her appointment. And because Hospital Housekeeping waited until after the appointment before making an FMLA determination, it reasons, offering Ramji FMLA leave at that time would have contradicted Dr. Harkin's medical assessment that Ramji could return to light-duty work on September 23.

Hospital Housekeeping's first argument fails as a matter of law. Hospital Housekeeping cannot exempt itself from its FMLA notice obligations by offering Ramji paid workers' compensation from the date of her injury on September 15 through her return to light-duty work on September 26. In fact, the FMLA regulations contemplate this scenario and specify that "the workers' compensation absence and FMLA leave may run concurrently." 29 C.F.R. § 825.702(d)(2) ("An employee may be on a workers' compensation absence due to an on-the-job injury or illness which also qualifies as a serious health condition under FMLA. The workers' compensation absence and FMLA leave may run concurrently (subject to proper notice and designation by the employer).").

Hospital Housekeeping's second argument similarly lacks merit. Ramji's acceptance of a light-duty position did not relieve Hospital Housekeeping of its FMLA obligations. The FMLA regulations unambiguously prohibit precisely this employer conduct: "if FMLA entitles an employee to leave, _an employer may not, in lieu of FMLA leave entitlement,_ require an employee to take a job with a reasonable accommodation." 29 C.F.R. § 825.702(d)(1) (emphasis added); § 852.702(d)(2) ("If the employer offers a light-duty position, the employee is permitted but not required to accept the position. As a result, the employee may no longer qualify for payments from the workers' compensation benefit plan, but the employee is entitled to continue on unpaid FMLA leave until either the employee is able to return to the same or equivalent job the employee left or until the 12-week FMLA leave entitlement is exhausted.") (citation omitted).

So once Dr. Harkins cleared Ramji for a light-duty position instead of the same or equivalent position she had, Ramji was entitled to decline Hospital Housekeeping's light-duty job offer. 29 C.F.R. § 825.207(e). But Ramji never had the opportunity to decide between taking a light-duty position or taking unpaid FMLA leave. Hospital Housekeeping made that choice for her by offering only a light-duty assignment. § 825.220(d) (specifying that an "employee's acceptance of such light duty assignment does not constitute a waiver of the employee's prospective rights, including the right to be restored to the same position the employee held at the time the employee's FMLA leave commenced or to an equivalent position").

And even assuming Hospital Housekeeping had the best of intentions in adopting a wait-and-see approach after Ramji's September 23 follow-up appointment, an "employer's motives are irrelevant" under the FMLA. We also find no basis to conclude that this reason for Hospital Housekeeping's delay qualifies as an extenuating circumstance justifying its failure to provide Ramji with notice within the five-day period. 29 C.F.R. § 825.300(b)(1). Because Hospital Housekeeping did not give Ramji any FMLA notice whatsoever, it did not satisfy its FMLA notice obligations under 29 C.F.R. § 825.300(b)(1) and (c)(1). It therefore denied her a leave benefit under the FMLA, so Ramji established the second element of the FMLA interference claim.

##### C.

Finally, we must determine whether Ramji can demonstrate harm, or prejudice, resulting from the employer's interference with her exercise (or attempted exercise) of an FMLA benefit to which she is entitled. An employee may obtain relief for interference with an FMLA right only if she "has been prejudiced by the violation." So an employee must show that the FMLA violation caused her to suffer injury that could be remedied in a way that the FMLA allows: damages or equitable relief.

First, as relevant here, when an employee has been denied or lost wages, the employer can be liable for "damages," including "any wages, salary, employment benefits, or other compensation" that the employee has not received "by reason of" the FMLA violation. 29 U.S.C. § 2617(a)(1)(A)(i)(I). Second, employers are liable for "such equitable relief as may be appropriate, including employment, reinstatement, and promotion." § 2617(a)(1)(B). Ramji contends that she can demonstrate two forms of prejudice resulting from Hospital Housekeeping's violations: Hospital Housekeeping's refusal to reinstate her and its denial to her of a lump-sum payment.

Beginning with reinstatement, Ramji observes that the FMLA notice provisions exist to ensure that employees "make informed decisions about leave." She asserts that, consistent with its notice duties, Hospital Housekeeping should have advised Ramji of her right to take FMLA leave. Had Hospital Housekeeping done so, Ramji asserts, she would have used that knowledge to (1) make informed decisions about her healthcare with the knowledge that her job would be protected, (2) receive additional physical therapy and medical treatment for her knee, and (3) return to work after further treatment.

More specifically, when faced with the essential-functions test (or at the first sign of pain from the essential-functions test) that would end her employment if she did not pass it, she would have made the informed decision to first take the full twelve weeks of FMLA leave. Then she could have used that time to undergo a complete course of continuous physical therapy and to have longer to heal and regain her strength before attempting to take the essential-functions test. As Ramji explained,

> If Ms. Merriweather let me take FMLA leave, I would have gotten physical therapy during my leave knowing that my job would be held for me while I was on leave. I did not know that they had to keep my job open. I would have found a way to pay for the treatment to keep my job. I could have borrowed money from my sister or other family members. I would have gotten the therapy because I really wanted my job back.

Hospital Housekeeping retorts that providing Ramji with the required notice would have made no difference. In its view, even if Ramji received notice of her right to FMLA leave and benefits (whether on September 15, the date of her injury, or October 21, the date she failed the essential-functions test), Ramji would not have been able to completely recover before the twelve weeks of FMLA leave expired. So, Hospital Housekeeping reasons, she would not have been reinstated because she still would have failed the essential-functions test. In support of this argument, Hospital Housekeeping relies on the statements of Dr. Jove, who testified in the resolution of Ramji's state workers' compensation claim. Dr. Jove opined that Ramji could have returned to complete knee function after only a total knee replacement, for which Ramji would have required more than twelve weeks to fully recover.

On this record, we conclude that a material issue of fact exists over whether an uninterrupted twelve-week FMLA leave period would have made a difference to whether Ramji could have passed her essential-functions test and returned to work. True, a reasonable jury might accept Dr. Jove's medical opinion that Ramji would not have successfully recovered during twelve weeks of FMLA leave. But a reasonable jury would not be required to agree with Dr. Jove, in view of the other evidence in the record. This record also supports the conclusion that Ramji aggravated her condition during the essential-functions test administered so soon after her injury. And that, along with the delay in uninterrupted physical therapy, contributed to the injury and impaired her chances for a faster recovery by the time Dr. Jove met with Ramji.

In particular, Dr. Jove did not meet with Ramji until five months after her workplace injury. And even at that time, because Ramji no longer received medical benefits from Hospital Housekeeping following her termination, Ramji had been able to complete only four of the approved 24 physical therapy sessions.

A reasonable jury could draw the inference that when Ramji presented her knee to Dr. Jove five months after her injury, the injured knee Dr. Jove saw was not in the condition it would have been had Ramji taken twelve weeks of FMLA leave after the accident and received the entirety of her necessary treatment, instead of aggravating the injury by trying to complete the essential-functions test too early in her recovery period and having her necessary physical therapy delayed. Indeed, Ramji attested that once she eventually did receive a full twelve weeks of physical therapy, her knee regained its original ability, and she can now perform all tasks from the essential-functions test. A jury might find this evidence particularly compelling in light of Dr. Barbour's conclusion that Ramji's condition requiring treatment resulted primarily from the September 16 accident, not arthritis. In other words, unlike Dr. Jove, Dr. Barbour did not think that Ramji had a preexisting condition that would have substantially hindered her recovery.

That is enough to create a material issue of fact concerning whether Hospital Housekeeping's failure to give Ramji the required FMLA notice prejudiced Ramji's ability to obtain reinstatement to her job. To the extent that Hospital Housekeeping suggests that Ramji must definitively prove she would have been able to recover within twelve weeks, it is mistaken. The evidence Ramji has produced is enough to allow a reasonable jury to find in her favor. Requiring ironclad proof is more than summary judgment requires, and in a situation like this one, it would allow an employer to benefit from its failure to comply with the FMLA and provide the required notice.

This alone is sufficient for Ramji to have demonstrated prejudice.[^Ramji7]

But Ramji has also presented enough evidence to demonstrate a material issue of fact over whether Hospital Housekeeping's failure to provide FMLA notice prejudiced her by inflicting damages. As Ramji points out, Hospital Housekeeping's FMLA policy requires that employees "must use earned, but unused, paid time off, such as vacation and sick pay during the absence." Significantly, it further explains that "all unused vacation and sick time runs concurrently with FMLA leave and will be paid out in one lump sum at the time of the FMLA start date" (emphasis omitted). So had Hospital Housekeeping given the proper FMLA notice, Ramji asserts, she would have taken her leave as FMLA leave and received a lump-sum payout of her accrued paid sick and vacation leave. But because Hospital Housekeeping failed to provide the required notice, Ramji continues, she lost out on that lump-sum payment.

Hospital Housekeeping disagrees that Ramji can show prejudice this way. It notes that it initially handled Ramji's claim as a workers' compensation claim. So, it reasons, if Ramji later tried to designate her leave, she would be unable to do so, since, in Hospital Housekeeping's view, the regulations render "substitution of the employee's accrued paid leave inapplicable." 29 C.F.R. § 825.207(e).

The problem with Hospital Housekeeping's position is that it accounts for only the leave Ramji took that was covered by workers' compensation. But that leave amounted to just a small portion of the total twelve-week period of leave that Ramji could have taken under the FMLA. And as soon as the FMLA leave kicked in exclusively, the regulations again would have permitted substitution of accrued paid leave. So Ramji could have chosen or Hospital Housekeeping could have required Ramji to use her accrued paid leave. In fact, under Hospital Housekeeping's own policy, Ramji would have been entitled to her accrued-leave payout. So Ramji has additionally and alternatively pointed to evidence in the record that establishes a material issue of fact concerning prejudice in the form of damages. Whether by damages or equitable relief (or both), Ramji satisfies the final requirement for a successful FMLA-interference claim—harm—so her claim survives summary judgment.

[^Ramji7]: (n. 7 in opinion) Similarly unavailing is Hospital Housekeeping's argument that an ADA reasonable-accommodation claim offered Ramji her sole option for relief. Hospital Housekeeping cannot shirk its FMLA obligations and force Ramji into an ADA claim by depriving her of a chance to take FMLA leave to which she is entitled.

## Disability Discrimination

### Americans with Disabilities Act, 42 U.S.C. § 12101 et seq.

::: {.aside}
_See also_, EEOC, [Regulations to Implement the Equal Employment Provisions of the Americans with Disabilities Act](https://www.law.cornell.edu/cfr/text/29/part-1630), 29 CFR Part 1630.
:::

::: {.legalcode}

#### § 12102--Definition of disability

As used in this chapter-number:

(1\) Disability

The term “disability” means, with respect to an individual—

- (A\) a physical or mental impairment that substantially limits one or more major life activities of such individual;
- (B\) a record of such an impairment; or
- (C\) being regarded as having such an impairment (as described in paragraph (3)) .

(2\) Major life activities

- (A\) In general
- For purposes of paragraph (1), major life activities include, but are not limited to, caring for oneself, performing manual tasks, seeing, hearing, eating, sleeping, walking, standing, lifting, bending, speaking, breathing, learning, reading, concentrating, thinking, communicating, and working.
- (B\) Major bodily functions
- For purposes of paragraph (1), a major life activity also includes the operation of a major bodily function, including but not limited to, functions of the immune system, normal cell growth, digestive, bowel, bladder, neurological, brain, respiratory, circulatory, endocrine, and reproductive functions.

(3\) Regarded as having such an impairment

For purposes of paragraph (1)(C):

- (A\) An individual meets the requirement of “being regarded as having such an impairment” if the individual establishes that he or she has been subjected to an action prohibited under this chapter because of an actual or perceived physical or mental impairment whether or not the impairment limits or is perceived to limit a major life activity.
- (B\) Paragraph (1)(C) shall not apply to impairments that are transitory and minor. A transitory impairment is an impairment with an actual or expected duration of 6 months or less.

(4\) Rules of construction regarding the definition of disability

The definition of “disability” in paragraph (1) shall be construed in accordance with the following:

- (A\) The definition of disability in this chapter shall be construed in favor of broad coverage of individuals under this chapter, to the maximum extent permitted by the terms of this chapter.
- (B\) The term “substantially limits” shall be interpreted consistently with the findings and purposes of the ADA Amendments Act of 2008.
- (C\) An impairment that substantially limits one major life activity need not limit other major life activities in order to be considered a disability.
- (D\) An impairment that is episodic or in remission is a disability if it would substantially limit a major life activity when active.
- (E\) 
	- (i\) The determination of whether an impairment substantially limits a major life activity shall be made without regard to the ameliorative effects of mitigating measures such as—
		- (I\) medication, medical supplies, equipment, or appliances, low-vision devices (which do not include ordinary eyeglasses or contact lenses\) , prosthetics including limbs and devices, hearing aids and cochlear implants or other implantable hearing devices, mobility devices, or oxygen therapy equipment and supplies;
		- (II\) use of assistive technology;
		- (III\) reasonable accommodations or auxiliary aids or services; or
		- (IV\) learned behavioral or adaptive neurological modifications.
	- (ii\) The ameliorative effects of the mitigating measures of ordinary eyeglasses or contact lenses shall be considered in determining whether an impairment substantially limits a major life activity.

[ ... ] 

#### § 12111--Definitions

As used in this subchapter-number:

**(1\) Commission**

The term “Commission” means the Equal Employment Opportunity Commission [ ... ].

**(2\) Covered entity**

The term “covered entity” means an employer, employment agency, labor organization, or joint labor-management committee.

**(3\) Direct threat**

The term “direct threat” means a significant risk to the health or safety of others that cannot be eliminated by reasonable accommodation.

**(8\) Qualified individual**

The term “qualified individual” means an individual who, with or without reasonable accommodation, can perform the essential functions of the employment position that such individual holds or desires. For the purposes of this subchapter, consideration shall be given to the employer’s judgment as to what functions of a job are essential, and if an employer has prepared a written description before advertising or interviewing applicants for the job, this description shall be considered evidence of the essential functions of the job.

**(9\) Reasonable accommodation**

The term “reasonable accommodation” may include—

- (A\) making existing facilities used by employees readily accessible to and usable by individuals with disabilities; and

- (B\) job restructuring, part-time or modified work schedules, reassignment to a vacant position, acquisition or modification of equipment or devices, appropriate adjustment or modifications of examinations, training materials or policies, the provision of qualified readers or interpreters, and other similar accommodations for individuals with disabilities.

**(10\) Undue hardship**

- (A\) In general
- The term “undue hardship” means an action requiring significant difficulty or expense, when considered in light of the factors set forth in subparagraph (B).
- (B\) Factors to be considered
- In determining whether an accommodation would impose an undue hardship on a covered entity, factors to be considered include—
	- (i\) the nature and cost of the accommodation needed under this chapter;
	- (ii\) the overall financial resources of the facility or facilities involved in the provision of the reasonable accommodation; the number of persons employed at such facility; the effect on expenses and resources, or the impact otherwise of such accommodation upon the operation of the facility;
	- (iii\) the overall financial resources of the covered entity; the overall size of the business of a covered entity with respect to the number of its employees; the number, type, and location of its facilities; and
	- (iv\) the type of operation or operations of the covered entity, including the composition, structure, and functions of the workforce of such entity; the geographic separateness, administrative, or fiscal relationship of the facility or facilities in question to the covered entity.

#### § 12112--Discrimination

**(a\) General rule**

No covered entity shall discriminate against a qualified individual on the basis of disability in regard to job application procedures, the hiring, advancement, or discharge of employees, employee compensation, job training, and other terms, conditions, and privileges of employment.

:::

### Frilando v. New York City Transit Authority, 513 F.Supp.3d 356 (S.D.N.Y. 2021)

Kenneth Frilando is a profoundly deaf man whose primary language is American Sign Language ("ASL"). Between 2016 and 2018, Mr. Frilando applied for three civil service positions: bus operator with the Manhattan and Bronx Surface Transit Operating Authority ("MaBSTOA"), train operator with the New York City Transit Authority (the "NYCTA"), and track worker with the NYCTA. Each position required applicants to pass a multiple-choice exam and "to understand and be understood in English." The Department of Citywide Administrative Services ("DCAS") regulates the examination procedures for the train operator, bus operator, and track worker exams and—as a matter of DCAS policy—the exams are not offered in languages other than English. For each exam, Mr. Frilando sought additional time and ASL interpretation of the oral instructions, exam questions, and exam answer choices. The NYCTA and MaBSTOA offered Mr. Frilando extra time and ASL interpretation of oral exam instructions, but denied Mr. Frilando's request for ASL interpretation of exam questions and answers. Mr. Frilando did not ultimately take the exams for any of the three positions.

Kenneth Frilando then sued the NYCTA and MaBSTOA (collectively, "Defendants"), alleging violations of the Americans with Disabilities Act (the "ADA") and NY state and city law. 

The Court has carefully reviewed the parties' pretrial submissions, the transcript of the trial, the trial exhibits, and the parties' post-trial submissions. In addition, the Court has made credibility determinations based, among other things, on its observation of each witness's demeanor and the consistency and logic of the witness's accounts. Based on all this, the Court now issues its findings of fact and conclusions of law and, for the reasons that follow, grants judgment in favor of Defendants.

#### Findings of Fact

Kenneth Frilando is profoundly deaf. With hearing aids, Mr. Frilando can detect environmental noises like car horns, but he cannot understand spoken English and "has extremely poor speech and lip reading skills." Specifically, Mr. Frilando reads English at only a third-grade reading level. Even with the aid of a dictionary or computerized "auto-correct," he can write only hesitantly in English. In contrast, "he is completely fluent in American Sign Language."

To his credit, Mr. Frilando has periodically sought employment, but has had difficulty achieving that goal. Around 2017, Mr. Frilando found the track worker, train operator, and bus operator positions on the career section of the MTA website and reviewed the job description and requirements for each position. 

Track workers maintain, install, inspect, and repair subway and elevated train tracks, a job that requires lifting heavy equipment and working in the path of oncoming trains. Because they work under hazardous conditions, track workers work in "gangs" that verbally communicate with one another about the safety aspects of the work being performed. One core function of a track worker is "flagging," in which track workers verbally communicate with train operators about when it is safe to proceed. 

Train operator responsibilities include operating subway cars and trains, preparing trains for road service, making announcements, and "responding to audible signals such as alarm bells, train whistles, horns and radio conversation."

Bus operators drive passenger buses in compliance with state law and local traffic regulations, collect fares, write reports on "revenues, accidents, faulty equipment and unusual occurrences," and must be able to "hear horns, buzzers and verbal warnings."

After reading the requirements for each application, Mr. Frilando applied for each position. He believed he was suited for the MaBSTOA bus operator position and NYCTA track worker position because these positions did not require formal education. However, the train operator position at the NYCTA required a year of "work experience continuous with one employer," which Mr. Frilando did not have. Although not referenced in the Notices of Examination, the track worker and train operator positions with the NYCTA and the bus operator position with MaBSTOA also require candidates to meet a minimum hearing standard, which Mr. Frilando did and does not meet. Each position also required applicants "to understand and be understood in English,"As noted, Mr. Frilando does not speak English clearly or fluently. Finally, each position requires applicants to take and pass a multiple-choice exam. 

Pursuant to Memoranda of Understanding between the NYCTA and DCAS entered into in 2011 and 2018, the NYCTA must adhere to DCAS protocols in the administration and development of civil service exams. Although MaBSTOA is a separate legal entity from the NYCTA, nevertheless, pursuant to a 2006 Memorandum of Understanding, the NYCTA also develops and administers examinations for MaBSTOA positions, adhering to the aforementioned DCAS regulations. Among other things, DCAS regulations specify that all "candidates must be able to understand and be understood in English." Per DCAS policy, examinations must be administered in English and the questions may not be translated into any other language.

An examination development group (the "Exams Unit") develops qualifying exams for both NYCTA and MaBSTOA positions after producing a detailed "job analysis," which must be updated at least every five years. Through field interviews, surveys, and on-the-job observation of employees and their supervisors, the job analysis identifies the "knowledge, skills, and abilities required to perform essential tasks on the job." The Exams Unit also asks "incumbents in the position to give importance and frequency ratings" to these core tasks. Based on incumbents' ratings, the Exams Unit determines what knowledge, skill, or abilities the qualifying exams should test. 

For the train operator position, the Exams Unit determined based on the job analysis that "written comprehension" and "written expression" were sufficiently important and frequently used skills to "be included in the competitive multiple-choice test plan." Accordingly, 10 of the 60 questions on the train operator exam test "written comprehension" and 9 test "written expression." Similarly, the job analysis for the track worker exam indicates that "written comprehension" and "written expression" abilities should be tested on the qualifying exam. 

The bus operator exam was primarily developed for MaBSTOA by an outside company. However, the bus operator exam was also developed using a job analysis report. The job analysis for the bus operator exam indicates that it is "important" for a bus operator to be able to "read and interpret bulletins and directives," "report unusual circumstances," and "report delays, mechanical problems and emergencies to the Dispatcher via two-way radio." Accordingly, the multiple-choice bus operator exam includes questions testing "written comprehension" and "written expression."

On April 20, 2017, Mr. Frilando emailed the Exams Unit to request an ASL interpreter for the instructions and test questions on the train operator exam. Mr. Frilando submitted an audiological report and a doctor's note with his accommodation request. Although Mr. Frilando did not initially request additional time in taking the exam, the doctor's note stated that "as the result of his disability, Mr. Frilando will need some additional time to complete his DCAS testing." 

A month later, Jennifer Garcia, an associate analyst at the NYCTA, informed Mr. Frilando that the NYCTA would provide extra time for taking the exam and an ASL interpreter to interpret the test instructions in ASL but not to interpret the exam questions themselves, adding that "you need to be able to read in English if you want to take the exam."

While waiting for Mr. Frilando to confirm whether he wanted to take the train operator exam, Ms. Garcia sent the accommodation request and supporting documentation to her manager, Michael Quiery. Mr. Quiery believed that more documentation was needed to support Mr. Frilando's request for an interpreter. Accordingly, on June 2, 2017, the Exams Unit informed Mr. Frilando that "upon further review of the document submitted to support your request, we can only grant your request for additional time" and sought additional documentation from a licensed medical professional specifically supporting Mr. Frilando's request for an ASL interpreter. 

On November 21, 2017, Mr. Frilando requested ASL interpretation of the instructions and questions on the bus operator exam. On March 1, 2018, Mr. Frilando requested ASL interpretation of the instructions and questions on the track worker exam. A week later, Michael Nigro confirmed that the NYCTA was "in the process of planning your accommodation(s)" for the track worker, train operator, and bus operator exams and inquired whether Mr. Frilando sought additional time as well as ASL interpretation. In response, Mr. Frilando confirmed that he was requesting additional time. Michael Nigro inquired about Mr. Frilando's calendar availability to take the exams, but Mr. Frilando did not respond until several weeks later. On April 2, 2018, Mr. Frilando confirmed his availability and asked for 100% extra time. 

In late August 2018, the Exams Unit ultimately offered Mr. Frilando 200% of the time otherwise prescribed for taking each exam, as well as ASL interpretation of the spoken and printed exam instructions. However, the Exams Unit maintained that it would "not provide translation or interpretation services of test examination questions for any candidate whose primary language is not English," because "the positions require that the candidate understand and be understood in English." The NYCTA offered Mr. Frilando several late August and early September 2018 test dates for the track worker, train operator, and bus operator exams, but Mr. Frilando did not take any of the three exams.

#### Conclusions of Law

Against this factual background, Mr. Frilando argues that Defendants discriminated against him on the basis of disability in violation of the ADA, the NYSHRL, the NYCHRL, and the Rehabilitation Act by failing to accommodate his request for ASL interpretation of the questions and answers on the track worker, train operator, and bus operator exams. For the reasons that follow, the Court concludes that Defendants are not liable for disability discrimination under any of these laws.

To succeed on a reasonable accommodation claim under the ADA, a plaintiff must be "otherwise qualified" for the position, meaning that he "can perform the essential functions of the employment position" at issue "with or without reasonable accommodation." 42 U.S.C. §§ 12111(8), 12112(a). 

When a job applicant claims he or she was denied a reasonable accommodation to take a preemployment exam, courts ask (1) whether the applicant is qualified to perform the essential functions of job with (or without) an accommodation and (2) whether the preemployment exam measures the skills it intends to measure. 

This two-step inquiry follows from the text and structure of the ADA. Title I of the ADA prohibits employers from denying a reasonable accommodation to "an otherwise qualified individual with a disability who is an applicant," unless "the accommodation would impose an undue hardship." 42 U.S.C. § 12112(b)(5)(A). Separately, the ADA specifically addresses the use of preemployment tests in the application process by defining "discrimination against a qualified individual" to include "failing to select and administer tests concerning employment to ensure that, when such test is administered to a job applicant or employee who has an impairment, such test results accurately reflect the skills, aptitude, or whatever other factor of such applicant or employee that such test purports to measure, rather than reflecting the impaired skills (except where such skills are the factors that the test purports to measure)." 42 U.S.C. § 12112(b)(7). However, unlike the general reasonable accommodation provision, the preemployment test provision does not repeat the term "qualified individual," and thus does not expressly incorporate the requirement that a candidate be able to perform the essential functions of the job.

As a result, Mr. Frilando can succeed on his disability discrimination claim if he can prove either of two things: either that he can perform the essential functions of the track worker, train operator, or bus operator jobs with (or without) an accommodation; or, alternatively, that Defendants' preemployment exams do not purport to measure English comprehension and expression. The Court considers each in turn.

#### I. The Essential Functions of the Positions

Mr. Frilando has not proven that he could perform the essential functions of the track worker, train operator, or bus operator jobs. When determining the "essential functions" of a position, courts look to (1) "the employer's judgment as to which functions are essential," (2) "written job descriptions prepared before advertising or interviewing applicants for the job," (3) "the amount of time spent on the job performing the function," and (4) "the work experience of past incumbents in the job." 29 C.F.R. § 1630.2(n)(3). The essential functions of a position "are a matter of judgment and opinion," and "the NYCTA has a statutory responsibility to operate the transit system 'for the safety of the public.'" The NYCTA "may properly deem" a function essential for operating public transport because the function "conduces to the safety of passengers and because it serves to limit NYCTA's tort liability in situations where an impairment might cause an accident as well as where it may be alleged to have done so." 

The NYCTA and MaBSTOA consider both the ability to engage in oral and written communication in English and sufficient hearing ability to meet the minimum hearing standard to be essential to the jobs here in issue. Because the job analyses are based on interviews with incumbents and survey data on the importance and frequency of certain tasks in each position, the job analyses are also instructive on the "essential functions" of each position. In addition, the Notices of Examination are "written job descriptions prepared before advertising or interviewing applicants for the job," and should also be given significant weight when analyzing the essential functions of the track worker, train operator, and bus operator jobs. [29 C.F.R. § 1630.2(n)](https://www.law.cornell.edu/cfr/text/29/1630.2).

The job analyses and Notices of Examination indicate that the essential functions of the track worker position include spoken communication with train operators and track workers about track hazards. The essential functions of the train operator position include making announcements in English and responding to bells, whistles, horns, and radio conversation. The essential functions of the bus operator position include writing reports on accidents and defective equipment, hearing horns and buzzers, and understanding verbal warnings in English. These functions are conducive to the safety of passengers, and thus the NYCTA and MaBSTOA have reasonably deemed them essential. Mr. Frilando is not qualified for any of the positions for which he applied, both because, as he concedes, he cannot understand or be understood in spoken English, and because trial testimony shows that Mr. Frilando cannot satisfy the minimum hearing standard for any position. 

#### II. Defendants' Use of Preemployment Exams

Mr. Frilando also has not proven that Defendants' preemployment exams do not intend to measure English comprehension. While the civil service exams may not have been designed to identify a particular grade level of reading proficiency, the exams are designed to test the written comprehension and expression necessary to perform transit job functions. The Exams Unit determined that the track worker, train operator, and bus operator exams should test "written comprehension" and "written expression." The Notices of Examination for the train operator and track worker exams confirm that the multiple-choice exams may test "the ability to understand written sentences or paragraphs" or "to use English for words or sentences in writing so others will understand." 

The Court's review of the evidence related to the exams—including a review of one of the current examinations—convinces the Court that the tests not only purport to measure English comprehension and expression, but also do in fact function as English comprehension and expression tests. For instance, certain exam questions test only whether applicants can read signs to write accurate reports. Because the exams plainly purport to and do measure comprehension of written English and Mr. Frilando's proposed accommodation would eliminate that very skill, Mr. Frilando cannot prove that Defendants discriminated against him in test selection or administration within the meaning of 42 U.S.C. § 12112(a).

##### Good-Faith Interactive Process

Separate from the above, Mr. Frilando claims that Defendants can be held independently liable for failure to engage in an interactive process to assess his needs. Although federal, city, and state laws envision that employers will "engage in a good faith interactive process that assesses the needs of the disabled individual and the reasonableness of the accommodation requested," the precedents are clear that failure to engage in a good-faith interactive process is evidence tending to show disability discrimination, not an independent cause of action. 

Separately, the Court also finds that Defendants did in fact engage in a good faith interactive process with Mr. Frilando, at least to the extent reasonably required at the early stage before Mr. Frilando chose not to take the exams. An adequate interactive process can involve "meeting with the employee who requests an accommodation, requesting information about the condition and what limitations the employee has, asking the employee what he or she specifically wants, showing some sign of having considered the employee's request, and offering and discussing available alternatives when the request is too burdensome." Defendants corresponded with Mr. Frilando over sixteen months, sought details and documentation about Mr. Frilando's disability and resulting limitations, repeatedly attempted to clarify Mr. Frilando's requests, considered the requests, and discussed alternative accommodations. This lengthy exchange satisfies the interactive process requirement.

### Searls v. Johns Hopkins Hospital, 158 F.Supp.3d 427 (D. Md. 2016)

Lauren Searls brings this action against Johns Hopkins Hospital ("JHH"), claiming that the defendant discriminated against her on the basis of disability in violation of Title I of the Americans with Disabilities Act, 42 U.S.C. §§ 12112(a) (the "ADA" or "Title I") and Section 504 of the Rehabilitation Act of 1973, 29 U.S.C. § 794 ("Section 504"). She seeks declaratory and injunctive relief, compensatory damages, attorneys' fees and costs, and other appropriate equitable and legal relief. The plaintiff has filed a motion for partial summary judgment on the issue of liability under the ADA and Section 504, leaving the issue of damages to be resolved at trial. The defendant has filed a cross-motion for summary judgment on all of the plaintiff's claims. For the reasons stated below, the court will grant the plaintiff's motion for partial summary judgment, and deny the defendant's cross-motion for summary judgment.

::: {.aside}
The Rehabilitation Act (1973), 29 U.S.C. § 701 et seq., prohibits disability discrimination by federal government agencies, federally-funded programs, and federal contractors. The employment discrimination standards under the Rehabilitation Act are the same as under the ADA. 29 U.S.C. §§ 791(f) and 794(d).
:::

#### Background

Searls is a deaf 2012 graduate of the Johns Hopkins School of Nursing. She can read lips but understands better through American Sign Language ("ASL"). When communicating with hearing individuals, she voices for herself. As a nursing student, Searls completed two clinical rotations in the Halsted 8 unit at JHH. During her clinical placements at JHH, the School of Nursing provided a full-time ASL interpreter. At the end of her final rotation, she received a faculty summary of her clinical performance. In the summary, the faculty member wrote that Searls "worked well with others on the team and communicated appropriately and with empathy with the patients and their families." Under "overall performance," the faculty member wrote:

> Lauren provided quality nursing care in a very professional, caring and skilled manner. She has shown a strong work ethic and very positive attitude that helped to create a very positive work environment. She has performed as an entry-level graduate nurse on Johns Hopkins Hospital Halstead sic 8 unit. Lauren Searls has met all of the course objectives at the expected and frequently at a higher level.

On July 13, 2012, a few days before Searls' graduation from the School of Nursing, Nurse Manager Stacey Rotman sent Searls an email giving her advance notice that she would be posting two openings for Nurse Clinician I positions in Halsted 8 and encouraging Searls to apply. Rotman later sent her an e-mail with the two job postings. 

JHH's job description of the Nurse Clinician I position states that a nurse is responsible for coordinating care, providing evidence-based patient care, working collaboratively, supporting safety standards, and using resources in a cost-effective manner. A requisite skill is "highly effective verbal communication and interpersonal skills to establish working relationships." Communication is listed as an "essential job function," and a nurse is required to "listen actively to opinions, ideas and feelings expressed by others and respond in a courteous and tactful manner." Another essential job function is "communcating unresolved issues to appropriate personnel." Nurses must also be competent in "general physiologic monitoring and patient care equipment such as defibrillator and glucometer monitor."

Searls applied for the Nurse Clinician I position, and JHH offered her an interview. She interviewed with Rotman on August 15 and was offered the Nurse Clinician I position on Halsted 8 the next day. Searls accepted the offer that same day. Her offer letter included the provision that "the offer of employment and start date are contingent upon successful completion of a health screening and clearance by the Office of Occupational Health Services." The annual salary for the position was $59,508.80. 

After Searls received the offer, she asked Rotman whom to contact to request an ASL interpreter. Rotman told her to notify the Department of Occupational Health during her pre-employment screening. Searls told a staff member from the Department of Occupational Health that she would require full-time ASL interpretation as an accommodation. The staff member told Searls that Rhodora Osborn, JHH's ADA Compliance Specialist, would be in touch with her to discuss the request.  Mary Henderson from the Department of Occupational Health sent Osborn an email informing her that Searls "has a hearing deficit since age 2 and has bilateral hearing aids" and that she was "requesting a sign language interpreter." Osborn then notified Kate Demers, the ADA/Accessibility Consultant at JHH at the time, and spoke with Henderson about Searls' request for an interpreter. 

Demers investigated the cost of providing one or two interpreters and determined that the average annual salary of an ASL interpreter proficient in medical terminology would be between $40,000 and $60,000 and concluded that Searls would require a team of two interpreters with her at all times at an annual cost of $240,000. In 2012, Halsted 8 had an operational budget of $3.4 million. Halsted 8 was a part of JHH's Department of Medicine, which had an operational budget of $88 million in 2012. JHH had an overall operational budget of $1.7 billion in 2012. 

On September 12, Demers sent Rotman an email with the estimate of the cost of an interpreter. Rotman forwarded this email to Karen Davis, the director of Medical and Radiology Nursing, commenting, "I know that we can't afford this." She also wrote, "They are expecting the department to pay for this. Why isn't the hospital responsible?" Davis forwarded the emails to her supervisor, Vice President of Nursing Karen Haller, to ask for her thoughts. Davis wrote that Searls "is qualified," but because of the cost of an interpreter, her "first response to this, given our financial issues, is to respond that I cannot accommodate this." Davis also speculated that having an interpreter could create scheduling issues and that the interpreter might tell Searls the wrong medicine to use during an emergency situation. Davis concluded her email by writing that "Stacey Rotman tells me the nurse is bright and would be a good hire other than this hearing issue." In response, Haller wrote, "I do not think we can accommodate this." Following this exchange, Rotman responded to Demers' email stating that she had talked to her director "and the department cannot accept the restrictions." Demers then asked for Rotman's reasoning, although she noted, "I assume it is cost." She also wrote, "I want to be sure we have thoroughly investigated all avenues as Searls is a qualified applicant, and we are part of the larger JHH." Rotman responded, "Yes, the reason is cost." 

On September 17, Demers asked Rotman for a "further breakdown" on the reason for rejecting the accommodation request, explaining her desire to "demonstrate we have shown good effort." She asked Rotman to "try to include as much information as possible to illustrate hardship on the organization." The next day, Demers asked Rotman to "determine what your department's threshold would be for interpreting costs," explaining that "it would be helpful to know what your department would be able to spend so we can see if a compromise would be a solution." 

Davis, who was also on the email chain, responded to Demers that while she would like to accommodate Searls, "this will not be possible." She wrote, "There are no other funds to pull from within our department. The interpreters would be an ongoing operating expense that is not budgeted or funded. Thus, our threshold is zero for interpreter costs." Davis further explained that because the overall budget of the unit was $3.4 million and the overall budget of the department was $88 million, "we would have to lay off 4 nurses to fund this as we cannot incur any new expenses." She cautioned that laying off nurses "would cause inappropriate nurse patient ratios on this unit and an enormous safety risk." Davis did not express any of the concerns she had raised in her email to Haller about scheduling and emergency situations, and only raised cost as the reason for not hiring Searls. During the time Searls' accommodation request was evaluated, no one asked Searls how she would work with an interpreter, including during an emergency situation or when an alarm sounded, or proposed any alternative accommodation. 

On September 20, Searls explained to Osborn that she was only seeking one full-time ASL interpreter. A few days later, Demers sent Rotman an email explaining that with one interpreter, instead of two, the cost of providing the accommodation would decrease to $120,000 per year, but "the undue hardship based on cost would still apply from my understanding." Demers wrote that "a letter is being drafted for Lauren explaining the undue hardship based on cost," but asked Rotman to let her know "if there are other reasons we should add." Rotman never provided Demers with any reason other than cost for not hiring Searls. 

Osborn and Rotman rescinded Searls' job offer in a letter dated September 28. They explained:

> After several interactive consultations with you and other resources as appropriate, we regret to inform you that we are unable to provide the interpreter services. We are unable to provide the accommodation because of its effect on the resources and operation of the department. As a result of the decision, we must rescind the offer of employment.

In January 2013, after several months of searching for a new job, Searls began working as a nurse at the University of Rochester Medical Center's Strong Memorial Hospital ("Strong"), where she continues to work today. After Strong offered her the job, Searls requested a full-time ASL interpreter. Strong agreed, and since January 2013, Searls has worked with an ASL interpreter. Searls' supervisor at Strong testified that Searls' deafness and use of an interpreter have never negatively affected patient care, her response to alarms, or her participation in codes. At Strong, Searls has exceeded standards on her performance reviews and has received promotions.

#### Analysis

Searls claims that JHH violated the ADA and Section 504 of the Rehabilitation Act by rescinding her job offer even though she was a qualified individual who, with the accommodation of an ASL interpreter, was fully able to perform the essential job functions of a nurse. The ADA makes it illegal for an employer to "discriminate against a qualified individual on the basis of disability." 42 U.S.C. § 12112(a). To establish a prima facie case on her failure-to-accommodate claim, Searls must show that (1) she is an individual with a disability within the meaning of the ADA; (2) JHH had notice of her disability; (3) she could perform the essential functions of her job with a reasonable accommodation; and (4) JHH refused to make such reasonable accommodation. Section 504 of the Rehabilitation Act mandates that "no otherwise qualified individual with a disability shall, solely by reason of her or his disability, be excluded from the participation in, be denied the benefits of, or be subjected to discrimination under any program or activity receiving Federal financial assistance." 29 U.S.C. § 794(a). Employment discrimination claims brought under Section 504 are evaluated using the same standards as those "applied under Title I of the Americans with Disabilities Act of 1990."

Even if Searls establishes her prima facie failure-to-accommodate case, JHH may avoid liability "if it can show as a matter of law that the proposed accommodation will cause undue hardship in the particular circumstances," or that Searls constituted a "direct threat," meaning that she posed a significant risk to the health or safety of others that could not be eliminated or reduced to an acceptable level by a reasonable accommodation.

The parties do not dispute that Searls is deaf and therefore has a disability within the meaning of the ADA and Section 504. JHH had notice of Searls' disability because she had previously worked at the hospital with ASL interpreters during her clinical rotations, and she formally requested an ASL interpreter during her employee health screening. Furthermore, it is undisputed that JHH declined to provide Searls with her requested accommodation of a full-time ASL interpreter and rescinded her job offer as a result. Thus, whether Searls can make out a prima facie case of disability discrimination depends on whether an ASL interpreter was a reasonable accommodation, which in turn depends on whether hiring an ASL interpreter to work with Searls would have reallocated essential job functions.

#### I. Reasonable Accommodation

The parties dispute whether Searls' request for a full-time accommodation was reasonable. To defeat an employer's motion for summary judgment, a plaintiff must "present evidence from which a jury may infer that the proposed accommodation is reasonable on its face, i.e., ordinarily or in the run of cases. A reasonable accommodation is one that is feasible or plausible." The reasonableness of an accommodation depends on whether it "enables the employee to perform the essential functions of the job in question." Essential job functions are "functions that bear more than a marginal relationship to the job at issue."

In defining "reasonable accommodation," Congress expressly included "the provision of qualified readers or interpreters" as an illustration. 42 U.S.C. § 12111(9)(B). The Second Circuit recently explained that although an ASL interpreter may not always be a reasonable accommodation, interpreters are a well-recognized accommodation:

> First, the term "reasonable accommodation" is defined by regulation to include "the provision of qualified readers or interpreters." 29 C.F.R. § 1630.2(o)(2)(ii). Per se rules are unreliable in the disability context, so ASL interpretive services may not _always_ constitute a reasonable accommodation. But according to the regulations, interpreters are a common form of reasonable accommodation. _See_ 29 C.F.R. § 1630 app. ("Part 1630 lists the examples, specified in title I of the ADA, of the most common types of accommodation that an employer or other covered entity may be required to provide.").

Searls further supports the reasonableness of her accommodation request through evidence from her experts, her current experience as a nurse at Strong where she works with an ASL interpreter and has received positive performance reviews, and her clinical rotation at Halsted 8 during which she was provided an ASL interpreter and received a positive review. Notably, Rotman offered Searls the nursing position at Halsted 8 because she thought she would be a strong addition to the unit, based in part on her colleagues' opinion that Searls was able to perform her nursing duties during her Halsted 8 clinical rotation in which she worked with an ASL interpreter. Given that Congress included an "interpreter" as an illustrative example of a "reasonable accommodation," employers commonly provide interpreters as a reasonable accommodation, and Searls has worked effectively with interpreters at Halsted 8 and in her current nursing job, Searls' proposed accommodation was reasonable unless, as JHH argues, hiring a full-time ASL interpreter would have reallocated essential job functions.

"A reasonable accommodation 'does not require an employer to reallocate essential job functions or assign an employee 'permanent light duty.'" "The ADA simply does not require an employer to hire an additional person to perform an essential function of a disabled employee's position." The Equal Employment Opportunity Commission's regulations explain that:

> An employer or other covered entity is not required to reallocate essential functions. The essential functions are by definition those that the individual who holds the job would have to perform, with or without reasonable accommodation, in order to be considered qualified for the position. For example, suppose a security guard position requires the individual who holds the job to inspect identification cards. An employer would not have to provide an individual who is legally blind with an assistant to look at the identification cards for the legally blind employee. In this situation the assistant would be performing the job for the individual with a disability rather than assisting the individual to perform the job. 

29 C.F.R. § 1630 app.

In determining which job functions are essential, "consideration shall be given to the employer's judgment as to what functions of a job are essential, and if an employer has prepared a written description for the job, this description shall be considered evidence of the essential functions of the job." 42 U.S.C. § 12111(8). The two essential job functions included in the JHH Nurse Clinician I job description that are relevant to this case are (1) communicating with patients, family members, and other hospital personnel, and (2) monitoring and responding to alarms. The parties agree that Searls could not have performed these essential functions without an accommodation, but they disagree whether providing an ASL interpreter would have reallocated these duties.

Searls' case is distinguishable from other cases where providing the requested accommodation amounted to reallocating essential job functions. In those cases, the accommodation request was found unreasonable because the employee requested that another employee perform the entirety of an essential job function, leaving the employee with no portion of the essential job function to perform. In contrast, even with the assistance of an ASL interpreter, Searls would perform a significant portion of the essential job functions of communicating and responding to alarms herself: Searls would decide which questions to ask, she would voice for herself in speaking to patients and other professionals, and she would act in response to alarms. An interpreter, lacking the requisite medical training, could not act independently of Searls to communicate about patient care and respond to alarms.

Therefore, because it is clear that Searls would retain responsibility for a substantial portion of the duties of communicating and responding to alarms if she were provided an ASL interpreter, the question becomes whether her inability to hear affected her ability to communicate and respond to alarms such that she would be "unable to 'perform' these essential functions within the meaning of the ADA. When the question is thus a matter of degree a plaintiff fails to perform the essential function only if her failure detrimentally affects the purpose of the employment." As noted, with the aid of an interpreter, Searls could perform a substantial portion of the essential job functions of communicating and responding to alarms—most importantly, those portions requiring nursing judgment—so that her inability to hear did not detrimentally affect the purpose of employing her as a nurse. A nurse's duties with respect to communicating and responding to alarms go beyond hearing what patients are saying and hearing an alarm ringing. Searls would have used her own medical expertise and training when speaking to patients, families, and other hospital personnel; providing care based on her exchanges with patients; and taking the appropriate action in response to an alarm after an interpreter communicated the sound of an alarm visually. Therefore, Searls' accommodation request would not have reallocated the essential job functions of communicating with others and responding to alarms. Searls' request for a full-time ASL interpreter was reasonable, and Searls has established a prima facie case of disability discrimination.

#### II. Undue Hardship Defense

JHH argues that providing Searls with an interpreter would have caused an undue hardship on the hospital's operations. An employer is not liable if it "can demonstrate that the accommodation would impose an undue hardship on the operation of its business." 42 U.S.C. § 12112(b)(5)(A). Title I of the ADA defines "undue hardship" as "an action requiring significant difficulty or expense, when considered in light of the factors set forth in subparagraph (B)." § 12111(10)(A). Subparagraph (B), in turn, provides a non-exhaustive list of relevant factors to be considered:

> (i) the nature and cost of the accommodation needed under this chapter; (ii) the overall financial resources of the facility or facilities involved in the provision of the reasonable accommodation; the number of persons employed at such facility; the effect on expenses and resources, or the impact otherwise of such accommodation upon the operation of the facility; (iii) the overall financial resources of the covered entity; the overall size of the business of a covered entity with respect to the number of its employees; the number, type, and location of its facilities; and (iv) the type of operation or operations of the covered entity, including the composition, structure, and functions of the workforce of such entity; the geographic separateness, administrative, or fiscal relationship of the facility or facilities in question to the covered entity.

§ 12111(10)(B). To demonstrate undue hardship, the employer "must show special (typically case-specific) circumstances." 

JHH's overall budget, the Department of Medicine's operational budget, and Halsted 8's operational budget are all relevant factors. 42 U.S.C. § 12111(10)(B)(ii)-(iii). Despite the relevance of JHH's overall budget, JHH's motion for summary judgment focuses exclusively on the resources and operations of Halsted 8 and the Department of Medicine and ignores the question of how providing an interpreter costing at most $120,000, or 0.007% of JHH's 2012 operational budget of $1.7 billion, could impose an undue hardship on the hospital.

JHH essentially argues that it had no money in its budget for reasonable accommodations. The employer's budget for reasonable accommodations is "an irrelevant factor in assessing undue hardship" because "allowing an employer to prevail on its undue hardship defense based on its own budgeting decisions would effectively cede the legal determination on this issue to the employer that allegedly failed to accommodate an employee with a disability. Taken to its logical extreme, the employer could budget $0 for reasonable accommodations and thereby always avoid liability." In its motion for summary judgment, JHH maintains that "neither of the operating budgets of the Halsted 8 unit nor the Department of Medicine, in which Halsted 8 was then located, had the budgeted resources to absorb the additional $120,000 cost." JHH then claims that because a nurse's starting salary is about $60,000, and a full-time ASL interpreter would cost $120,000, "in order to fund the $120,000 annual cost, the nursing unit would have needed to lay-off at least two full-time Registered Nurses." The nursing unit would only have to discharge two nurses, however, and thereby reallocate the nurses' combined salaries totaling $120,000, if it had budgeted $0 for reasonable accommodations. JHH's position in its motion for summary judgment is consistent with the statement from Davis, the director of Medical and Radiology Nursing, that the department's "threshold is zero for interpreter costs."

Additionally, even if it is correct that the salary of a full-time ASL interpreter would be twice the salary of a nurse, that in itself does not establish that an ASL interpreter would be an undue hardship. The EEOC's interpretive guidance on its Title I ADA regulations explains that "simply comparing the cost of the accommodation to the salary of the individual with a disability in need of the accommodation will not suffice." 29 C.F.R. § 1630 app. Furthermore, it is "particularly relevant" that Strong has been able to accommodate deaf nurses. Because Strong has been able to provide Searls with an ASL interpreter, and because JHH seeks to prevail on its undue hardship defense based on its decision to budget $0 for reasonable accommodations, while failing to account for its $1.7 billion budget, JHH has not met its burden of establishing undue hardship. The plaintiff's motion for summary judgment on this defense will be granted.

#### III. Direct Threat Defense

JHH also argues that employing Searls as a nurse would have imposed a direct threat. The ADA defines a "direct threat" as "a significant risk to the health or safety of others that cannot be eliminated by reasonable accommodation." 42 U.S.C. § 12111(3). An "employer must determine whether a reasonable accommodation would either eliminate the risk or reduce it to an acceptable level." In its motion for summary judgment, JHH notes that some alarms were only auditory and argues that "it would have been a significant patient safety risk to rely on an interpreter, without any nursing training, to engage in nursing judgment by determining which alarm was sounding and to rely on the interpreter's judgment to determine when a patient emergency was occurring, requiring nursing assistance." 

JHH's direct threat defense is based on post-hoc rationalizations and is therefore suggestive of pretext. The only statement JHH uses to support its direct threat defense that was made contemporaneously with its decision to rescind Searls' offer of employment was Rotman's September 23 email that noted Searls would need an interpreter during all work hours because "she will have unexpected phone calls, call bells ringing, critical patient situations, etc." Nowhere in the email did Rotman state that Searls could not manage unexpected phone calls, call bells, or critical patient situations with the aid of an interpreter. All other contemporaneous evidence indicates that JHH rescinded the job offer because of the cost of providing a full-time ASL interpreter. Notably, Rotman explained that "the reason is cost" for not providing the accommodation. Additionally, when Demers wrote to Rotman to inform her that she was drafting a letter to Searls explaining "the undue hardship based on cost," she asked "if there are other reasons we should add please let us know," but Rotman never provided Demers any other reasons for denying the accommodation. Because JHH did not raise patient safety concerns until after Searls brought the lawsuit, because the issue of patient safety is absent from contemporaneous communications concerning the reason for denying Searls an ASL interpreter, and because the only explanation JHH gave to Searls for revoking her job offer was the cost of providing a full-time interpreter, JHH has not met its burden on its direct threat defense. 

JHH's direct threat defense also fails because the record shows that JHH failed to base its determination "on an individualized assessment of Searls' present ability to safely perform the essential functions of her job." Such an assessment must "be based on a reasonable medical judgment that relies on the most current medical knowledge and/or on the best available objective evidence" and must consider factors such as: "(1) The duration of the risk; (2) The nature and severity of the potential harm; (3) The likelihood that the potential harm will occur; and (4) The imminence of the potential harm." 29 C.F.R. § 1630.2(r). No such individualized assessment occurred here. Instead, JHH relied on stereotypes or generalizations about deafness. Aside from Rotman's September 23 email previously discussed, the only other evidence JHH presents to support its direct threat defense is Rotman's deposition where she testified that she was concerned about Searls' "ability to function safely as a nurse on Halsted 8" based on whether "she would be able to hear the alarms." Rotman admitted that she had never observed Searls fail to respond to an alarm. She also said that it "wouldn't be a safe situation" for a non-nurse to be trained to differentiate between the alarms. Rotman never expressed this concern to Searls. In fact, the defendant does not dispute that no JHH employee ever raised patient safety concerns with Searls or asked how she planned to work with an interpreter to respond to alarms. Rotman speculated that because Searls is deaf and cannot hear alarms she would endanger patient health, but she "failed to provide any medical basis for her conclusion, and she does not discuss whether the safety concerns could be alleviated by reasonable accommodation." Therefore, JHH has not met its burden of establishing that Searls constituted a "direct threat" to the safety of others at Halsted 8. The court will grant the plaintiff's motion for partial summary judgment on the issue of direct threat.