# Labor Organizing & Concerted Activity

## Organized Labor as Unlawful Combination

#### @CommonwealthPullis_Phila1806

Indictment for common law conspiracy, tried before a jury consisting of two inn-keepers, a tavern-keeper, three grocers, a merchant, a hatter, a tobacconist, a watchmaker, a tailor, a bottler.

The indictment charged in substance:

(1\) That defendants conspired and agreed that none of them would work at the shoemaking craft except at certain specified prices higher than prices which had theretofore customarily been paid;

(2\) that defendants conspired and agreed that they would endeavor to prevent "by threats, menaces, and other unlawful means" other craftsmen from working except at said specified rates; and 

(3\) that defendants, having formed themselves into an association, conspired and agreed that none of them would work for any master who should employ a cordwainer[Cordwainer is an archaic term for a shoemaker.]{.aside} who had broken any rule or bylaw of the association, and that defendants, in accordance with such agreement refused to work at the usual rates and prices.

It is proper to consider, is such a combination consistent with the principles of our law, and injurious to the public welfare? The usual means by which the prices of work are regulated, are the demand for the article and the excellence of its fabric. Where the work is well done, and the demand is considerable, the prices will necessarily be high. Where the work is ill done, and the demand is inconsiderable, they will unquestionably be low. If there are many to consume, and few to work, the price of the article will be high; but if there are few to consume, and many to work, the article must be low.

Much will depend, too, upon these circumstances, whether the materials are plenty or scarce; the price of the commodity, will in consequence be higher or lower. These are the means by which prices are regulated in the natural course of things. To make an artificial regulation, is not to regard the excellence of the work or quality of the material, but to fix a positive and arbitrary price, governed by no standard, controlled by no impartial person, but dependent on the will of the few who are interested; this is the unnatural way of raising the price of goods or work. This is independent of the number who are to do the work. It is an unnatural, artificial means of raising the price of work beyond its standard, and taking an undue advantage of the public. Is the rule of law bottomed upon such principles, as to permit or protect such conduct?

Consider it on the footing of the general commerce of the city. Is there any man who can calculate (if this is tolerated) at what price he may safely contract to deliver articles, for which he may receive orders, if he is to be regulated by the journeymen in an arbitrary jump from one price to another? It renders it impossible for a man, making a contract for a large quantity of such goods, to know whether he shall lose or gain by it. If he makes a large contract for goods today, for delivery at three, six or nine months hence, can he calculate what the prices will be then, if the journeymen in the intermediate time, are permitted to meet and raise their prices, according to their caprice or pleasure? Can he fix the price of his commodity for a future day? It is impossible that any man can carry on commerce in this way. There cannot be a large contract entered into, but what the contractor will make at his peril. He may be ruined by the difference of prices made by the journeymen in the intermediate time. What then is the operation of this kind of conduct upon the commerce of the city? It exposes it to inconveniences, if not to ruin; therefore, it is against the public welfare.

What is the case now before us? A combination of workmen to raise their wages may be considered in a two fold point of view; one is to benefit themselves the other is to injure those who do not join their society. The rule of law condemns both. If the rule be clear, we are bound to conform to it even though we do not comprehend the principle upon which it is founded. We are not to reject it because we do not see the reason of it. It is enough, that is the will of the majority. It is law because it is their will—if it is law, there may be good reasons for it though we cannot find them out. But the rule in this case is pregnant with sound sense and all the authorities are clear upon the subject. 

It is adopted by Blackstone,[William Blackstone (1723-1780) & William Murray, 1st Earl of Mansfield (1705-1793) were prominent British jurists.]{.aside} and laid down as the law by Lord Mansfield, that an act innocent in an individual, is rendered criminal by a confederacy to effect it. One man determines not to work under a certain price and it may be individually the opinion of all; in such a case it would be lawful in each to refuse to do so, for if each stands, alone, either may extract from his determination when he pleases. In the turn-out["turn-out": an archaic word for a labor strike.]{.aside} of last fall, if each member of the body had stood alone, fettered by no promises to the rest, many of them might have changed their opinion as to the price of wages and gone to work; but it has been given to you in evidence, that they were bound down by their agreement, and pledged by mutual engagements, to persist in it, however contrary to their own judgment. The continuance in improper conduct may therefore well be attributed to the combination. The good sense of those individuals was prevented by this agreement, from having its free exercise.

The defendants were found guilty and were fined eight dollars each plus costs. 

#### @CommonwealthHunt_Mass1842

The general rule of the common law is, that it is a criminal and indictable offence, for two or more to confederate and combine together, by concerted means, to do that which is unlawful or criminal, to the injury of the public, or portions or classes of the community, or even to the rights of an individual. This rule of law may be equally in force as a rule of the common law, in England and in this Commonwealth; and yet it must depend upon the local laws of each country to determine, whether the purpose to be accomplished by the combination, or the concerted means of accomplishing it, be unlawful or criminal in the respective countries. 

But the great difficulty is, in framing any definition or description, to be drawn from the decided cases, which shall specifically identify this offence—a description broad enough to include all cases punishable under this description, without including acts which are not punishable. Without attempting to review and reconcile all the cases, we are of opinion, that as a general description, though perhaps not a precise and accurate definition, a conspiracy must be a combination of two or more persons, by some concerted action, to accomplish some criminal or unlawful purpose, or to accomplish some purpose, not in itself criminal or unlawful, by criminal or unlawful means. We use the terms criminal or unlawful, because it is manifest that many acts are unlawful, which are not punishable by indictment or other public prosecution; and yet there is no doubt, we think, that a combination by numbers to do them would be an unlawful conspiracy, and punishable by indictment.

But yet it is clear, that it is not every combination to do unlawful acts, to the prejudice of another by a concerted action, which is punishable as conspiracy. 

Several rules upon the subject seem to be well established, to wit, that the unlawful agreement constitutes the gist of the offence, and therefore that it is not necessary to charge the execution of the unlawful agreement. And when such execution is charged, it is to be regarded as proof of the intent, or as an aggravation of the criminality of the unlawful combination.

Another rule is a necessary consequence of the former, which is, that the crime is consummate and complete by the fact of unlawful combination, and, therefore, that if the execution of the unlawful purpose is averred, it is by way of aggravation, and proof of it is not necessary to conviction.

And it follows, as another necessary legal consequence, from the same principle, that the indictment must—by averring the unlawful purpose of the conspiracy, or the unlawful means by which it is contemplated and agreed to accomplish a lawful purpose, or a purpose not of itself criminally punishable—set out an offence complete in itself, without the aid of any averment of illegal acts done in pursuance of such an agreement; and that an illegal combination, imperfectly and insufficiently set out in the indictment, will not be aided by averments of acts done in pursuance of it.

From these views of the rules of criminal pleading, it appears to us to follow, as a necessary legal conclusion, that when the criminality of a conspiracy consists in an unlawful agreement of two or more persons to compass or promote some criminal or illegal purpose, that purpose must be fully and clearly stated in the indictment; and if the criminality of the offence, which is intended to be charged, consists in the agreement to compass or promote some purpose, not of itself criminal or unlawful, by the use of fraud, force, falsehood, or other criminal or unlawful means, such intended use of fraud, force, falsehood, or other criminal or unlawful means, must be set out in the indictment.

The first count set forth, that the defendants, with divers others unknown, on the day and at the place named, being workmen, and journeymen, in the art and occupation of bootmakers, unlawfully, perniciously and deceitfully designing and intending to continue, keep up, form, and unite themselves, into an unlawful club, society and combination, and make unlawful by-laws, rules and orders among themselves, and thereby govern themselves and other workmen, in the said art, and unlawfully and unjustly to extort great sums of money by means thereof, did unlawfully assemble and meet together, and being so assembled, did unjustly and corruptly conspire, combine, confederate and agree together, that none of them should thereafter, and that none of them would, work for any master or person whatsoever, in the said art, mystery and occupation, who should employ any workman or journeyman, or other person, in the said art, who was not a member of said club, society or combination, after notice given him to discharge such workman, from the employ of such master; to the great damage and oppression, etc.

Now it is to be considered, that the preamble and introductory matter in the indictment—such as unlawfully and deceitfully designing and intending unjustly to extort great sums, etc.—is mere recital and therefore cannot aid an imperfect averment of the facts constituting the description of the offence. The same may be said of the concluding matter, which follows the averment, as to the great damage and oppression not only of their said masters, employing them in said art and occupation, but also of divers other workmen in the same art, mystery and occupation, to the evil example, etc. If the facts averred constitute the crime, these are properly stated as the legal inferences to be drawn from them. If they do not constitute the charge of such an offence, they cannot be aided by these alleged consequences.

Stripped then of these introductory recitals and alleged injurious consequences, and of the qualifying epithets attached to the facts, the averment is this; that the defendants and others formed themselves into a society, and agreed not to work for any person, who should employ any journeyman or other person, not a member of such society, after notice given him to discharge such workman.

The manifest intent of the association is, to induce all those engaged in the same occupation to become members of it. Such a purpose is not unlawful. It would give them a power which might be exerted for useful and honorable purposes, or for dangerous and pernicious ones. If the latter were the real and actual object, and susceptible of proof, it should have been specially charged. Such an association might be used to afford each other assistance in times of poverty, sickness and distress; or to raise their intellectual, moral and social condition; or to make improvement in their art; or for other proper purposes. Or the association might be designed for purposes of oppression and injustice. But in order to charge all those, who become members of an association, with the guilt of a criminal conspiracy, it must be averred and proved that the actual, if not the avowed object of the association, was criminal. An association may be formed, the declared objects of which are innocent and laudable, and yet they may have secret articles, or an agreement communicated only to the members, by which they are banded together for purposes injurious to the peace of society or the rights of its members. Such would undoubtedly be a criminal conspiracy, on proof of the fact, however meritorious and praiseworthy the declared objects might be. The law is not to be hoodwinked by colorable pretences. It looks at truth and reality, through whatever disguise it may assume. But to make such an association, ostensibly innocent, the subject of prosecution as a criminal conspiracy, the secret agreement, which makes it so, is to be averred and proved as the gist of the offence. But when an association is formed for purposes actually innocent, and afterwards its powers are abused, by those who have the control and management of it, to purposes of oppression and injustice, it will be criminal in those who thus misuse it, or give consent thereto, but not in the other members of the association. In this case, no such secret agreement, varying the objects of the association from those avowed, is set forth in this count of the indictment.

Nor can we perceive that the objects of this association, whatever they may have been, were to be attained by criminal means. The means which they proposed to employ, as averred in this count, and which, as we are now to presume, were established by the proof, were, that they would not work for a person, who, after due notice, should employ a journeyman not a member of their society. Supposing the object of the association to be laudable and lawful, or at least not unlawful, are these means criminal? The case supposes that these persons are not bound by contract, but free to work for whom they please, or not to work, if they so prefer. In this state of things, we cannot perceive, that it is criminal for men to agree together to exercise their own acknowledged rights, in such a manner as best to subserve their own interests. One way to test this is, to consider the effect of such an agreement, where the object of the association is acknowledged on all hands to be a laudable one. Suppose a class of workmen, impressed with the manifold evils of intemperance, should agree with each other not to work in a shop in which ardent spirit was furnished, or not to work in a shop with any one who used it, or not to work for an employer, who should, after notice, employ a journeyman who habitually used it. The consequences might be the same. A workman, who should still persist in the use of ardent spirit, would find it more difficult to get employment; a master employing such an one might, at times, experience inconvenience in his work, in losing the services of a skilful but intemperate workman. Still it seems to us, that as the object would be lawful, and the means not unlawful, such an agreement could not be pronounced a criminal conspiracy.

From this count in the indictment, we do not understand that the agreement was, that the defendants would refuse to work for an employer, to whom they were bound by contract for a certain time, in violation of that contract; nor that they would insist that an employer should discharge a workman engaged by contract for a certain time, in violation of such contract. It is perfectly consistent with every thing stated in this count, that the effect of the agreement was, that when they were free to act, they would not engage with an employer, or continue in his employment, if such employer, when free to act, should engage with a workman, or continue a workman in his employment, not a member of the association. If a large number of men, engaged for a certain time, should combine together to violate their contract, and quit their employment together, it would present a very different question. Suppose a farmer, employing a large number of men, engaged for the year, at fair monthly wages, and suppose that just at the moment that his crops were ready to harvest, they should all combine to quit his service, unless he would advance their wages, at a time when other laborers could not be obtained. It would surely be a conspiracy to do an unlawful act, though of such a character, that if done by an individual, it would lay the foundation of a civil action only, and not of a criminal prosecution. It would be a case very different from that stated in this count.

The second count, omitting the recital of unlawful intent and evil disposition, and omitting the direct averment of an unlawful club or society, alleges that the defendants, with others unknown, did assemble, conspire, confederate and agree together, not to work for any master or person who should employ any workman not being a member of a certain club, society or combination, called the Boston Journeymen Bootmaker's Society, or who should break any of their by-laws, unless such workmen should pay to said club, such sum as should be agreed upon as a penalty for the breach of such unlawful rules, etc; and that by means of said conspiracy they did compel one Isaac B. Wait, a master cordwainer, to turn out of his employ one Jeremiah Horne, a journeyman boot-maker, etc. in evil example, etc. So far as the averment of a conspiracy is concerned, all the remarks made in reference to the first count are equally applicable to this. It is simply an averment of an agreement amongst themselves not to work for a person, who should employ any person not a member of a certain association. It sets forth no illegal or criminal purpose to be accomplished, nor any illegal or criminal means to be adopted for the accomplishment of any purpose. It was an agreement, as to the manner in which they would exercise an acknowledged right to contract with others for their labor. It does not aver a conspiracy or even an intention to raise their wages; and it appears by the bill of exceptions, that the case was not put upon the footing of a conspiracy to raise their wages.

As to the latter part of this count, which avers that by means of said conspiracy, the defendants did compel one Wait to turn out of his employ one Jeremiah Horne, we remark, in the first place, that as the acts done in pursuance of a conspiracy, as we have before seen, are stated by way of aggravation, and not as a substantive charge; if no criminal or unlawful conspiracy is stated, it cannot be aided and made good by mere matter of aggravation. If the principal charge falls, the aggravation falls with it. 

But further; if this is to be considered as a substantive charge, it would depend altogether upon the force of the word "compel," which may be used in the sense of coercion, or duress, by force or fraud. It would therefore depend upon the context and the connexion with other words, to determine the sense in which it was used in the indictment. If, for instance, the indictment had averred a conspiracy, by the defendants, to compel Wait to turn Horne out of his employment, and to accomplish that object by the use of force or fraud, it would have been a very different case; especially if it might be fairly construed, as perhaps in that case it might have been, that Wait was under obligation, by contract, for an unexpired term of time, to employ and pay Horne. As before remarked, it would have been a conspiracy to do an unlawful, though not a criminal act, to induce Wait to violate his engagement, to the actual injury of Horne. To mark the difference between the case of a journeyman or a servant and master, mutually bound by contract, and the same parties when free to engage anew, I should have before cited the case of the _Boston Glass Co. v. Binney_. In that case, it was held actionable to entice another person's hired servant to quit his employment, during the time for which he was engaged; but not actionable to treat with such hired servant, whilst actually hired and employed by another, to leave his service, and engage in the employment of the person making the proposal, when the term for which he is engaged shall expire. It acknowledges the established principle, that every free man, whether skilled laborer, mechanic, farmer or domestic servant, may work or not work, or work or refuse to work with any company or individual, at his own option, except so far as he is bound by contract. But whatever might be the force of the word "compel," unexplained by its connexion, it is disarmed and rendered harmless by the precise statement of the means, by which such compulsion was to be effected. It was the agreement not to work for him, by which they compelled Wait to decline employing Horne longer. On both of these grounds, we are of opinion that the statement made in this second count, that the unlawful agreement was carried into execution, makes no essential difference between this and the first count.

The third count, reciting a wicked and unlawful intent to impoverish one Jeremiah Horne, and hinder him from following his trade as a boot-maker, charges the defendants, with others unknown, with an unlawful conspiracy, by wrongful and indirect means, to impoverish said Horne and to deprive and hinder him, from his said art and trade and getting his support thereby, and that, in pursuance of said unlawful combination, they did unlawfully and indirectly hinder and prevent, etc. and greatly impoverish him.

If the fact of depriving Jeremiah Horne of the profits of his business, by whatever means it might be done, would be unlawful and criminal, a combination to compass that object would be an unlawful conspiracy, and it would be unnecessary to state the means. 

Suppose a baker in a small village had the exclusive custom of his neighborhood, and was making large profits by the sale of his bread. Supposing a number of those neighbors, believing the price of his bread too high, should propose to him to reduce his prices, or if he did not, that they would introduce another baker; and on his refusal, such other baker should, under their encouragement, set up a rival establishment, and sell his bread at lower prices; the effect would be to diminish the profit of the former baker, and to the same extent to impoverish him. And it might be said and proved, that the purpose of the associates was to diminish his profits, and thus impoverish him, though the ultimate and laudable object of the combination was to reduce the cost of bread to themselves and their neighbors. The same thing may be said of all competition in every branch of trade and industry; and yet it is through that competition, that the best interests of trade and industry are promoted. It is scarcely necessary to allude to the familiar instances of opposition lines of conveyance, rival hotels, and the thousand other instances, where each strives to gain custom to himself, by ingenious improvements, by increased industry, and by all the means by which he may lessen the price of commodities, and thereby diminish the profits of others.

We think, therefore, that associations may be entered into, the object of which is to adopt measures that may have a tendency to impoverish another, that is, to diminish his gains and profits, and yet so far from being criminal or unlawful, the object may be highly meritorious and public spirited. The legality of such an association will therefore depend upon the means to be used for its accomplishment. If it is to be carried into effect by fair or honorable and lawful means, it is, to say the least, innocent; if by falsehood or force, it may be stamped with the character of conspiracy. It follows as a necessary consequence, that if criminal and indictable, it is so by reason of the criminal means intended to be employed for its accomplishment; and as a further legal consequence, that as the criminality will depend on the means, those means must be stated in the indictment. If the same rule were to prevail in criminal, which holds in civil proceedings--that a case defectively stated may be aided by a verdict--then a court might presume, after verdict, that the indictment was supported by proof of criminal or unlawful means to effect the object. But it is an established rule in criminal cases, that the indictment must state a complete indictable offence, and cannot be aided by the proof offered at the trial.

The fourth count avers a conspiracy to impoverish Jeremiah Horne, without stating any means; and the fifth alleges a conspiracy to impoverish employers, by preventing and hindering them from employing persons, not members of the Bootmakers' Society; and these require no remarks, which have not been already made in reference to the other counts.

Whatever illegal purpose can be found in the constitution of the Bootmakers' Society, it not being clearly set forth in the indictment, cannot be relied upon to support this conviction. So if any facts were disclosed at the trial, which, if properly averred, would have given a different character to the indictment, they do not appear in the bill of exceptions, nor could they, after verdict, aid the indictment. But looking solely at the indictment, disregarding the qualifying epithets, recitals and immaterial allegations, and confining ourselves to facts so averred as to be capable of being traversed and put in issue, we cannot perceive that it charges a criminal conspiracy punishable by law. The exceptions must, therefore, be sustained, and the judgment arrested.

## Antitrust, Labor Injunctions, and Yellow Dog Contracts 

In the early 20th century, employers turned to a new weapon against organized labor: the @ShermanAntitrustAct1890, which outlaws "conspiracies in restraint of trade or commerce among the several States". The Supreme Court endorsed the application of the Sherman Act against labor union activity in the Danbury Hatters' case, @LoeweLawlor_US1908. The case arose out of organizing efforts by the United Hatters of North America. The union called for a boycott of manufacturers who refused to recognize and bargain with the union. D. E. Loewe & Company, a manufacturer that resisted the union's demand, sued more than 200 union members, alleging that the boycott interfered with the company's sale of hats. The trial court dismissed the suit, concluding that the Sherman Act did not apply to the union's conduct. But the Supreme Court reversed, holding that the boycott fell within the prohibition against conspiracies in restraint of interstate commerce. On remand, the trial judge directed a verdict in favor of the company. After another appeal and retrial, which the union again lost, the case finally returned to the Supreme Court, which affirmed the judgment against the union. @LawlorLoewe_US1915.

> _The impact of Danbury Hatters was devastating for organized labor. The unions, and many others, felt that the statute had been interpreted improperly, inasmuch as organized labor was not the focal point of congressional debate that took place prior to the enactment of antitrust legislation. Moreover, because the Sherman Antitrust Act provides for treble damages rather than the actual amount of the losses incurred (as well as criminal sanctions), the final judgment after fourteen years of litigation in Danbury Hatters awarded a substantial amount of money ($250,000). What was particularly troublesome about the judgment was that the members of the union were individually and personally liable. Though the case was settled in 1917 for slightly over $234,000_^[Equivalent to about $6.5 million in 2023.] _and the AFL was able to obtain $216,000 in voluntary contributions from union members, the fact that labor had to "pass the hat" to avoid the foreclosure of members’ homes made the case unforgettable._[^gould1]
 
[^gould1]: [@Gould2004, 14-15].

In 1914, Congress amended federal antitrust law with the @ClaytonAntitrustAct1914, which included provisions that union leader Samuel Gompers hailed as "labor's Magna Carta and Bill of Rights and the most important legislation since the abolition of slavery."[^gould2]

[^gould2]: [@Gould2004, 15-16].

Section 6 of the Clayton Act sought to exempt labor activity from antitrust liability: 

> The labor of a human being is not a commodity or article of commerce. Nothing contained in the antitrust laws shall be construed to forbid the existence and operation of labor, agricultural, or horticultural organizations, instituted for the purposes of mutual help, and not having capital stock or conducted for profit, or to forbid or restrain individual members of such organizations from lawfully carrying out the legitimate objects thereof; nor shall such organizations, or the members thereof, be held or construed to be illegal combinations or conspiracies in restraint of trade, under the antitrust laws.

Section 20 of the Clayton Act sought to restrict the use of injunctions in labor disputes:

> No restraining order or injunction shall be granted by any court of the United States, or a judge or the judges thereof, in any case between an employer and employees, or between employers and employees, or between employees, or between persons employed and persons seeking employment, involving, or growing out of, a dispute concerning terms or conditions of employment, unless necessary to prevent irreparable injury to property, or to a property right, of the party making the application, for which injury there is no adequate remedy at law, and such property or property right must be described with particularity in the application, which must be in writing and sworn to by the applicant or by his agent or attorney.
> 
> And no such restraining order or injunction shall prohibit any person or persons, whether singly or in concert, from terminating any relation of employment, or from ceasing to perform any work or labor, or from recommending, advising, or persuading others by peaceful means so to do; or from attending at any place where any such person or persons may lawfully be, for the purpose of peacefully obtaining or communicating information, or from peacefully persuading any person to work or to abstain from working; or from ceasing to patronize or to employ any party to such dispute, or from recommending, advising, or persuading others by peaceful and lawful means so to do; or from paying or giving to, or withholding from, any person engaged in such dispute, any strike benefits or other moneys or things of value; or from peaceably assembling in a lawful manner, and for lawful purposes; or from doing any act or thing which might lawfully be done in the absence of such dispute by any party thereto; nor shall any of the acts specified in this paragraph be considered or held to be violations of any law of the United States.

But in @DuplexPrintingPressCo_US1921, the Supreme Court, interpreting these provisions narrowly, held that they did not prohibit the issuance of injunctions against secondary boycotts (i.e. where a union has a dispute with an employer, the "primary" target, and calls for strikes or boycotts of the employer's customers, the "secondary" targets, so that they will cease doing business with the primary target). Like the Danbury Hatters' case, _Duplex Printing_ involved an organizing campaign in which the company resisted the union's demand for a closed shop. 

> _When only a few of the workers joined in the union’s efforts, the union attempted to boycott the company’s products by warning customers that it would be better for them not to purchase from the company, threatening customers with sympathetic strikes, and inciting the employees of customers to strike against their employers. It also notified repair shops not to do repair work on Duplex presses and threatened union men with the loss of their union cards if they assisted in the installation of Duplex presses. The Duplex company brought an antitrust action against the union for unlawful restraint of trade._
>
> _The Court stated that a distinction between a primary and a secondary boycott was material to the question of whether union conduct was immunized by virtue of the Clayton Act. The Court first examined section 6 and stated the following:_
> 
> > The section assumes the normal objects of a labor organization to be legitimate, and declares that nothing in the antitrust laws shall be construed to forbid the existence and operation of such organizations, or to forbid their members from lawfully carrying out their legitimate objects; and that such an organization shall not be held in itself—merely because of its existence and operation—to be an illegal combination or conspiracy in restraint of trade. But there is nothing in the section to exempt such an organization or its members from accountability where it or they depart from its normal and legitimate objects and engage in an actual combination of conspiracy in restraint of trade.
>
> _The Court then focused on section 20 of the Clayton Act, noting that the provision specifically forbade the issuance of restraining orders or injunctions in U.S. courts where there was a labor dispute between an "employer and employees" and that the first paragraph’s prohibition of orders in such circumstances "unless necessary to prevent irreparable injury to property, or to a property right" where there was no adequate remedy of law (that is to say, where the wronged party could not be adequately compensated through damages) was merely "declaratory of the law as it stood before." ... The Court noted that the second paragraph referred to cases where the parties were "standing in proximate relation to a controversy" of the kind designated in the first paragraph. Noting that the majority of the circuit courts of appeals had previously concluded that the words "employers and employees" should be treated as referring to "the business class or clan to which the parties litigant respectively belong," the Court nevertheless concluded that any construction of the statute that would preclude employer relief where union secondary activity was involved against employers "wholly unconnected" with the Battle Creek factory was a statutory construction "altogether inadmissible." ... Significantly, the Court made clear its condemnation of the damage done to "many innocent people"—secondary employees and employees who were "far remote" from the "original" dispute._[^gould3]
 
[^gould3]: [@Gould2004, 16-18].

Another legal strategy employers used against labor organizing was the "yellow dog" contract, in which employees promised not to join or remain a member of a union. Labor opposition led to the adoption of statutes outlawing yellow dog contracts. But, following @LochnerNewYork_US1905, the Supreme Court struck down those statutes as unconstitutional infringements on liberty of contract. @AdairUnitedStates_US1908 (striking down federal statute making it a criminal offense for a railroad to fire an employee because of union membership); @CoppageKansas_US1915 (striking down state statute making it a crime for employers to require yellow dog contracts as a condition of employment). 

## The NLRA and Protected Concerted Activity

In the 1930s, the landscape of U.S. labor law changed dramatically with the passage of two federal statutes. 

First, the @NorrisLaGuardiaAct1932, declared "yellow dog" contracts unenforceable and significantly limited the ability of federal courts to issue injunctions in cases involving labor disputes. Many states followed suit by adopting "Little Norris-LaGuardia Acts" restricting labor injunctions in state court. 

Second, the @NationalLaborRelations1935 enshrined the right of employees to organize and engage in collective bargaining and other concerted activity (§ 7), prohibited unfair labor practices by employers (§ 8), established a framework for union representation based on majority support of employees (§ 9), and created the National Labor Relations Board to administer and enforce the Act (§§ 3-6, 10-11). The Labor-Management Relations Act (1947) amended the NLRA, including the addition of § 8(b) prohibiting unfair labor practices by unions. 

Under the NLRA, once a majority of employees within a designated bargaining unit have opted for union representation, the union becomes the exclusive bargaining agent for all employees within the unit. The union owes a duty of fair representation to all bargaining unit employees, regardless of whether or not they are union members. 

Even where employees are not represented by a union, NLRA § 7 protects their right to engage in "concerted activities for the purpose of collective bargaining or other mutual aid or protection". 

#### @NationalLaborRelations1935

::: {.legalcode}

##### Section 1—Declaration of Policy

- The denial by some employers of the right of employees to organize and the refusal by some employers to accept the procedure of collective bargaining lead to strikes and other forms of industrial strife or unrest, which have the intent or the necessary effect of burdening or obstructing commerce by (a) impairing the efficiency, safety, or operation of the instrumentalities of commerce; (b) occurring in the current of commerce; (c) materially affecting, restraining, or controlling the flow of raw materials or manufactured or processed goods from or into the channels of commerce, or the prices of such materials or goods in commerce; or (d) causing diminution of employment and wages in such volume as substantially to impair or disrupt the market for goods flowing from or into the channels of commerce.
- The inequality of bargaining power between employees who do not possess full freedom of association or actual liberty of contract, and employers who are organized in the corporate or other forms of ownership association substantially burdens and affects the flow of commerce, and tends to aggravate recurrent business depressions, by depressing wage rates and the purchasing power of wage earners in industry and by preventing the stabilization of competitive wage rates and working conditions within and between industries.
- Experience has proved that protection by law of the right of employees to organize and bargain collectively safeguards commerce from injury, impairment, or interruption, and promotes the flow of commerce by removing certain recognized sources of industrial strife and unrest, by encouraging practices fundamental to the friendly adjustment of industrial disputes arising out of differences as to wages, hours, or other working conditions, and by restoring equality of bargaining power between employers and employees.
- Experience has further demonstrated that certain practices by some labor organizations, their officers, and members have the intent or the necessary effect of burdening or obstructing commerce by preventing the free flow of goods in such commerce through strikes and other forms of industrial unrest or through concerted activities which impair the interest of the public in the free flow of such commerce. The elimination of such practices is a necessary condition to the assurance of the rights herein guaranteed.
- It is hereby declared to be the policy of the United States to eliminate the causes of certain substantial obstructions to the free flow of commerce and to mitigate and eliminate these obstructions when they have occurred by encouraging the practice and procedure of collective bargaining and by protecting the exercise by workers of full freedom of association, self-organization, and designation of representatives of their own choosing, for the purpose of negotiating the terms and conditions of their employment or other mutual aid or protection.

##### Section 2—Definitions

- (2) The term “employer” includes any person acting as an agent of an employer, directly or indirectly, but shall not include the United States or any wholly owned Government corporation, or any Federal Reserve Bank, or any State or political subdivision thereof, or any person subject to the Railway Labor Act, as amended from time to time, or any labor organization (other than when acting as an employer), or anyone acting in the capacity of officer or agent of such labor organization.
- (3) The term “employee” shall include any employee, and shall not be limited to the employees of a particular employer, unless this subchapter explicitly states otherwise, and shall include any individual whose work has ceased as a consequence of, or in connection with, any current labor dispute or because of any unfair labor practice, and who has not obtained any other regular and substantially equivalent employment, but shall not include any individual employed as an agricultural laborer, or in the domestic service of any family or person at his home, or any individual employed by his parent or spouse, or any individual having the status of an independent contractor, or any individual employed as a supervisor, or any individual employed by an employer subject to the Railway Labor Act, as amended from time to time, or by any other person who is not an employer as herein defined.
- (5) The term “labor organization” means any organization of any kind, or any agency or employee representation committee or plan, in which employees participate and which exists for the purpose, in whole or in part, of dealing with employers concerning grievances, labor disputes, wages, rates of pay, hours of employment, or conditions of work.
- (9) The term “labor dispute” includes any controversy concerning terms, tenure or conditions of employment, or concerning the association or representation of persons in negotiating, fixing, maintaining, changing, or seeking to arrange terms or conditions of employment, regardless of whether the disputants stand in the proximate relation of employer and employee.

##### Section 7—Right of employees as to organization, collective bargaining, etc.

- Employees shall have the right to self-organization, to form, join, or assist labor organizations, to bargain collectively through representatives of their own choosing, and to engage in other concerted activities for the purpose of collective bargaining or other mutual aid or protection, and shall also have the right to refrain from any or all of such activities except to the extent that such right may be affected by an agreement requiring membership in a labor organization as a condition of employment as authorized in section 158(a)(3) of this title.

##### Section 8—Unfair labor practices

- (a) Unfair labor practices by employer
- It shall be an unfair labor practice for an employer—
	- (1) to interfere with, restrain, or coerce employees in the exercise of the rights guaranteed in section 157 of this title;
	- (2) to dominate or interfere with the formation or administration of any labor organization or contribute financial or other support to it: Provided, That subject to rules and regulations made and published by the Board pursuant to section 156 of this title, an employer shall not be prohibited from permitting employees to confer with him during working hours without loss of time or pay;
	- (3) by discrimination in regard to hire or tenure of employment or any term or condition of employment to encourage or discourage membership in any labor organization;
	- (4) to discharge or otherwise discriminate against an employee because he has filed charges or given testimony under this subchapter;
	- (5) to refuse to bargain collectively with the representatives of his employees, subject to the provisions of section 159(a) of this title.
- (b) Unfair labor practices by labor organization
- It shall be an unfair labor practice for a labor organization or its agents—
	- (1) to restrain or coerce (A) employees in the exercise of the rights guaranteed in section 157 of this title: Provided, That this paragraph shall not impair the right of a labor organization to prescribe its own rules with respect to the acquisition or retention of membership therein; or (B) an employer in the selection of his representatives for the purposes of collective bargaining or the adjustment of grievances;
	- (2) to cause or attempt to cause an employer to discriminate against an employee in violation of subsection (a)(3) or to discriminate against an employee with respect to whom membership in such organization has been denied or terminated on some ground other than his failure to tender the periodic dues and the initiation fees uniformly required as a condition of acquiring or retaining membership [ ... ];
	- (3) to refuse to bargain collectively with an employer, provided it is the representative of his employees subject to the provisions of section 159(a) of this title;
	- [ ... ]
- (d) Obligation to bargain collectively. 
- For the purposes of this section, to bargain collectively is the performance of the mutual obligation of the employer and the representative of the employees to meet at reasonable times and confer in good faith with respect to wages, hours, and other terms and conditions of employment, or the negotiation of an agreement, or any question arising thereunder, and the execution of a written contract incorporating any agreement reached if requested by either party, but such obligation does not compel either party to agree to a proposal or require the making of a concession 

##### Section 9—Representatives and elections

- (a) Exclusive representatives; employees’ adjustment of grievances directly with employer
- Representatives designated or selected for the purposes of collective bargaining by the majority of the employees in a unit appropriate for such purposes, shall be the exclusive representatives of all the employees in such unit for the purposes of collective bargaining in respect to rates of pay, wages, hours of employment, or other conditions of employment: Provided, That any individual employee or a group of employees shall have the right at any time to present grievances to their employer and to have such grievances adjusted, without the intervention of the bargaining representative, as long as the adjustment is not inconsistent with the terms of a collective-bargaining contract or agreement then in effect: Provided further, That the bargaining representative has been given opportunity to be present at such adjustment.
- (b) Determination of bargaining unit by Board
- The Board shall decide in each case whether, in order to assure to employees the fullest freedom in exercising the rights guaranteed by this subchapter, the unit appropriate for the purposes of collective bargaining shall be the employer unit, craft unit, plant unit, or subdivision thereof.

##### Section 13—Right to strike preserved

- Nothing in this subchapter, except as specifically provided for herein, shall be construed so as either to interfere with or impede or diminish in any way the right to strike, or to affect the limitations or qualifications on that right.

:::

#### @NLRBWashingtonAluminumCo_US1962

The Court of Appeals for the Fourth Circuit, with Chief Judge Sobeloff dissenting, refused to enforce an order of the National Labor Relations Board directing the respondent Washington Aluminum Company to reinstate and make whole seven employees whom the company had discharged for leaving their work in the machine shop without permission on claims that the shop was too cold to work in. Because that decision raises important questions affecting the proper administration of the National Labor Relations Act, we granted certiorari. 

The Board's order, as shown by the record and its findings, rested upon these facts and circumstances. The respondent company is engaged in the fabrication of aluminum products in Baltimore, Maryland, a business having interstate aspects that subject it to regulation under the National Labor Relations Act. The machine shop in which the seven discharged employees worked was not insulated and had a number of doors to the outside that had to be opened frequently. An oil furnace located in an adjoining building was the chief source of heat for the shop, although there were two gas-fired space heaters that contributed heat to a lesser extent. The heat produced by these units was not always satisfactory and, even prior to the day of the walkout involved here, several of the eight machinists who made up the day shift at the shop had complained from time to time to the company's foreman "over the cold working conditions."

January 5, 1959, was an extraordinarily cold day for Baltimore, with unusually high winds and a low temperature of 11 degrees followed by a high of 22. When the employees on the day shift came to work that morning, they found the shop bitterly cold, due not only to the unusually harsh weather, but also to the fact that the large oil furnace had broken down the night before and had not as yet been put back into operation. As the workers gathered in the shop just before the starting hour of 7:30, one of them, a Mr. Caron, went into the office of Mr. Jarvis, the foreman, hoping to warm himself but, instead, found the foreman's quarters as uncomfortable as the rest of the shop. As Caron and Jarvis sat in Jarvis' office discussing how bitingly cold the building was, some of the other machinists walked by the office window "huddled" together in a fashion that caused Jarvis to exclaim that "if those fellows had any guts at all, they would go home." When the starting buzzer sounded a few moments later, Caron walked back to his working place in the shop and found all the other machinists "huddled there, shaking a little, cold." Caron then said to these workers, "Dave Jarvis told me if we had any guts, we would go home. I am going home, it is too damned cold to work." Caron asked the other workers what they were going to do and, after some discussion among themselves, they decided to leave with him. One of these workers, testifying before the Board, summarized their entire discussion this way: "And we had all got together and thought it would be a good idea to go home; maybe we could get some heat brought into the plant that way." As they started to leave, Jarvis approached and persuaded one of the workers to remain at the job. But Caron and the other six workers on the day shift left practically in a body in a matter of minutes after the 7:30 buzzer.

When the company's general foreman arrived between 7:45 and 8 that morning, Jarvis promptly informed him that all but one of the employees had left because the shop was too cold. The company's president came in at approximately 8:20 a.m. and, upon learning of the walkout, immediately said to the foreman, "if they have all gone, we are going to terminate them." After discussion "at great length" between the general foreman and the company president as to what might be the effect of the walkout on employee discipline and plant production, the president formalized his discharge of the workers who had walked out by giving orders at 9 a.m. that the affected workers should be notified about their discharge immediately, either by telephone, telegram or personally. This was done.

On these facts the Board found that the conduct of the workers was a concerted activity to protest the company's failure to supply adequate heat in its machine shop, that such conduct is protected under the provision of § 7 of the National Labor Relations Act which guarantees that "Employees shall have the right to engage in concerted activities for the purpose of collective bargaining or other mutual aid or protection," and that the discharge of these workers by the company amounted to an unfair labor practice under § 8 (a) (1) of the Act, which forbids employers "to interfere with, restrain, or coerce employees in the exercise of the rights guaranteed in section 7." The Board then ordered the company to reinstate the discharged workers to their previous positions and to make them whole for losses resulting from what the Board found to have been the unlawful termination of their employment.

In denying enforcement of this order, the majority of the Court of Appeals took the position that because the workers simply "summarily left their place of employment" without affording the company an "opportunity to avoid the work stoppage by granting a concession to a demand," their walkout did not amount to a concerted activity protected by § 7 of the Act On this basis, they held that there was no justification for the conduct of the workers in violating the established rules of the plant by leaving their jobs without permission and that the Board had therefore exceeded its power in issuing the order involved here because § 10 (c) declares that the Board shall not require reinstatement or back pay for an employee whom an employer has suspended or discharged "for cause."

We cannot agree that employees necessarily lose their right to engage in concerted activities under § 7 merely because they do not present a specific demand upon their employer to remedy a condition they find objectionable. The language of § 7 is broad enough to protect concerted activities whether they take place before, after, or at the same time such a demand is made. To compel the Board to interpret and apply that language in the restricted fashion suggested by the respondent here would only tend to frustrate the policy of the Act to protect the right of workers to act together to better their working conditions. Indeed, as indicated by this very case, such an interpretation of § 7 might place burdens upon employees so great that it would effectively nullify the right to engage in concerted activities which that section protects. The seven employees here were part of a small group of employees who were wholly unorganized. They had no bargaining representative and, in fact, no representative of any kind to present their grievances to their employer. Under these circumstances, they had to speak for themselves as best they could. As pointed out above, prior to the day they left the shop, several of them had repeatedly complained to company officials about the cold working conditions in the shop. These had been more or less spontaneous individual pleas, unsupported by any threat of concerted protest, to which the company apparently gave little consideration and which it now says the Board should have treated as nothing more than "the same sort of gripes as the gripes made about the heat in the summertime." The bitter cold of January 5, however, finally brought these workers' individual complaints into concert so that some more effective action could be considered. Having no bargaining representative and no established procedure by which they could take full advantage of their unanimity of opinion in negotiations with the company, the men took the most direct course to let the company know that they wanted a warmer place in which to work. So, after talking among themselves, they walked out together in the hope that this action might spotlight their complaint and bring about some improvement in what they considered to be the "miserable" conditions of their employment. This we think was enough to justify the Board's holding that they were not required to make any more specific demand than they did to be entitled to the protection of § 7.

Although the company contends to the contrary, we think that the walkout involved here did grow out of a "labor dispute" within the plain meaning of the definition of that term in § 2 (9) of the Act, which declares that it includes "any controversy concerning terms, tenure or _conditions of employment_ ." The findings of the Board, which are supported by substantial evidence and which were not disturbed below, show a running dispute between the machine shop employees and the company over the heating of the shop on cold days— a dispute which culminated in the decision of the employees to act concertedly in an effort to force the company to improve that condition of their employment. The fact that the company was already making every effort to repair the furnace and bring heat into the shop that morning does not change the nature of the controversy that caused the walkout. At the very most, that fact might tend to indicate that the conduct of the men in leaving was unnecessary and unwise, and it has long been settled that the reasonableness of workers' decisions to engage in concerted activity is irrelevant to the determination of whether a labor dispute exists or not. Moreover, the evidence here shows that the conduct of these workers was far from unjustified under the circumstances. The company's own foreman expressed the opinion that the shop was so cold that the men should go home. This statement by the foreman but emphasizes the obvious— that is, that the conditions of coldness about which complaint had been made before had been so aggravated on the day of the walkout that the concerted action of the men in leaving their jobs seemed like a perfectly natural and reasonable thing to do.

Nor can we accept the company's contention that because it admittedly had an established plant rule which forbade employees to leave their work without permission of the foreman, there was justifiable "cause" for discharging these employees, wholly separate and apart from any concerted activities in which they engaged in protest against the poorly heated plant. Section 10 (c) of the Act does authorize an employer to discharge employees for "cause" and our cases have long recognized this right on the part of an employer. But this, of course, cannot mean that an employer is at liberty to punish a man by discharging him for engaging in concerted activities which § 7 of the Act protects. And the plant rule in question here purports to permit the company to do just that for it would prohibit even the most plainly protected kinds of concerted work stoppages until and unless the permission of the company's foreman was obtained.

It is of course true that § 7 does not protect all concerted activities, but that aspect of the section is not involved in this case. The activities engaged in here do not fall within the normal categories of unprotected concerted activities such as those that are unlawful, violent, or in breach of contract. Nor can they be brought under this Court's more recent pronouncement which denied the protection of § 7 to activities characterized as "indefensible" because they were there found to show a disloyalty to the workers' employer which this Court deemed unnecessary to carry on the workers' legitimate concerted activities. The activities of these seven employees cannot be classified as "indefensible" by any recognized standard of conduct. Indeed, concerted activities by employees for the purpose of trying to protect themselves from working conditions as uncomfortable as the testimony and Board findings showed them to be in this case are unquestionably activities to correct conditions which modern labor-management legislation treats as too bad to have to be tolerated in a humane and civilized society like ours.

We hold therefore that the Board correctly interpreted and applied the Act to the circumstances of this case and it was error for the Court of Appeals to refuse to enforce its order. The judgment of the Court of Appeals is reversed and the cause is remanded to that court with directions to enforce the order in its entirety.

#### @NLRBCityDisposalSystems_US1984

James Brown, a truck driver employed by respondent, was discharged when he refused to drive a truck that he honestly and reasonably believed to be unsafe because of faulty brakes. Article XXI of the collective-bargaining agreement between respondent and Local 247 of the International Brotherhood of Teamsters, Chauffeurs, Warehousemen and Helpers of America, which covered Brown, provides:

> The Employer shall not require employees to take out on the streets or highways any vehicle that is not in safe operating condition or equipped with the safety appliances prescribed by law. It shall not be a violation of this Agreement where employees refuse to operate such equipment unless such refusal is unjustified.

The question to be decided is whether Brown's honest and reasonable assertion of his right to be free of the obligation to drive unsafe trucks constituted "concerted activity" within the meaning of § 7 of the National Labor Relations Act (NLRA or Act). The National Labor Relations Board (NLRB or Board) held that Brown's refusal was concerted activity within § 7, and that his discharge was, therefore, an unfair labor practice under § 8(a)(1) of the Act. The Court of Appeals disagreed and declined enforcement. At least three other Courts of Appeals, however, have accepted the Board's interpretation of "concerted activities" as including the assertion by an individual employee of a right grounded in a collective-bargaining agreement. We granted certiorari to resolve the conflict, and now reverse.

[I]{.casesection}

The facts are not in dispute in the current posture of this case. Respondent, City Disposal Systems, Inc. (City Disposal), hauls garbage for the city of Detroit. Under the collective-bargaining agreement with Local Union No. 247, respondent's truckdrivers haul garbage from Detroit to a landfill about 37 miles away. Each driver is assigned to operate a particular truck, which he or she operates each day of work, unless that truck is in disrepair.

James Brown was assigned to truck No. 245. On Saturday, May 12, 1979, Brown observed that a fellow driver had difficulty with the brakes of another truck, truck No. 244. As a result of the brake problem, truck No. 244 nearly collided with Brown's truck. After unloading their garbage at the landfill, Brown and the driver of truck No. 244 brought No. 244 to respondent's truck-repair facility, where they were told that the brakes would be repaired either over the weekend or in the morning of Monday, May 14.

Early in the morning of Monday, May 14, while transporting a load of garbage to the landfill, Brown experienced difficulty with one of the wheels of his own truck—No. 245—and brought that truck in for repair. At the repair facility, Brown was told that, because of a backlog at the facility, No. 245 could not be repaired that day. Brown reported the situation to his supervisor, Otto Jasmund, who ordered Brown to punch out and go home. Before Brown could leave, however, Jasmund changed his mind and asked Brown to drive truck No. 244 instead. Brown refused, explaining that "there's something wrong with that truck. Something was wrong with the brakes there was a grease seal or something leaking causing it to be affecting the brakes." Brown did not, however, explicitly refer to Article XXI of the collective-bargaining agreement or to the agreement in general. In response to Brown's refusal to drive truck No. 244, Jasmund angrily told Brown to go home. At that point, an argument ensued and Robert Madary, another supervisor, intervened, repeating Jasmund's request that Brown drive truck No. 244. Again, Brown refused, explaining that No. 244 "has got problems and I don't want to drive it." Madary replied that half the trucks had problems and that if respondent tried to fix all of them it would be unable to do business. He went on to tell Brown that "we've got all this garbage out here to haul and you tell me about you don't want to drive." Brown responded, "Bob, what you going to do, put the garbage ahead of the safety of the men?" Finally, Madary went to his office and Brown went home. Later that day, Brown received word that he had been discharged. He immediately returned to work in an attempt to gain reinstatement but was unsuccessful.

On May 15, the day after the discharge, Brown filed a written grievance, pursuant to the collective-bargaining agreement, asserting that truck No. 244 was defective, that it had been improper for him to have been ordered to drive the truck, and that his discharge was therefore also improper. The union, however, found no objective merit in the grievance and declined to process it.

On September 7, 1979, Brown filed an unfair labor practice charge with the NLRB, challenging his discharge. The Administrative Law Judge (ALJ) found that Brown had been discharged for refusing to operate truck No. 244, that Brown's refusal was covered by § 7 of the NLRA, and that respondent had therefore committed an unfair labor practice under § 8(a)(1) of the Act. The ALJ held that an employee who acts alone in asserting a contractual right can nevertheless be engaged in concerted activity within the meaning of § 7:

> When an employee makes complaints concerning safety matters which are embodied in a contract, he is acting not only in his own interest, but is attempting to enforce such contract provisions in the interest of all the employees covered under that contract. Such activity we have found to be concerted and protected under the Act, and the discharge of an individual for engaging in such activity to be in violation of Section 8(a)(1).

The NLRB adopted the findings and conclusions of the ALJ and ordered that Brown be reinstated with backpay.

On a petition for enforcement of the Board's order, the Court of Appeals disagreed with the ALJ and the Board. Finding that Brown's refusal to drive truck No. 244 was an action taken solely on his own behalf, the Court of Appeals concluded that the refusal was not a concerted activity within the meaning of § 7. 

[II]{.casesection}

Section 7 of the NLRA provides that "employees shall have the right to join or assist labor organizations, to bargain collectively through representatives of their own choosing, and to engage in other concerted activities for the purpose of collective bargaining or other mutual aid or protection." 29 U. S. C. § 157. The NLRB's decision in this case applied the Board's longstanding "_Interboro_ doctrine," under which an individual's assertion of a right grounded in a collective-bargaining agreement is recognized as "concerted activity" and therefore accorded the protection of § 7. The Board has relied on two justifications for the doctrine: First, the assertion of a right contained in a collective-bargaining agreement is an extension of the concerted action that produced the agreement; and second, the assertion of such a right affects the rights of all employees covered by the collective-bargaining agreement.

We have often reaffirmed that the task of defining the scope of § 7 "is for the Board to perform in the first instance as it considers the wide variety of cases that come before it," and, on an issue that implicates its expertise in labor relations, a reasonable construction by the Board is entitled to considerable deference. The question for decision today is thus narrowed to whether the Board's application of § 7 to Brown's refusal to drive truck No. 244 is reasonable. Several reasons persuade us that it is.

[A]{.casesubsection}

Neither the Court of Appeals nor respondent appears to question that an employee's invocation of a right derived from a collective-bargaining agreement meets § 7's requirement that an employee's action be taken "for purposes of collective bargaining or other mutual aid or protection." As the Board first explained in the _Interboro_ case, a single employee's invocation of such rights affects all the employees that are covered by the collective-bargaining agreement. This type of generalized effect, as our cases have demonstrated, is sufficient to bring the actions of an individual employee within the "mutual aid or protection" standard, regardless of whether the employee has his own interests most immediately in mind. 

The term "concerted activity" is not defined in the Act but it clearly enough embraces the activities of employees who have joined together in order to achieve common goals. What is not self-evident from the language of the Act, however, and what we must elucidate, is the precise manner in which particular actions of an individual employee must be linked to the actions of fellow employees in order to permit it to be said that the individual is engaged in concerted activity. We now turn to consider the Board's analysis of that question as expressed in the _Interboro_ doctrine.

Although one could interpret the phrase, "to engage in other concerted activities," to refer to a situation in which two or more employees are working together at the same time and the same place toward a common goal, the language of § 7 does not confine itself to such a narrow meaning. In fact, § 7 itself defines both joining and assisting labor organizations—activities in which a single employee can engage—as concerted activities. Indeed, even the courts that have rejected the _Interboro_ doctrine recognize the possibility that an individual employee may be engaged in concerted activity when he acts alone. They have limited their recognition of this type of concerted activity, however, to two situations: (1) that in which the lone employee intends to induce group activity, and (2) that in which the employee acts as a representative of at least one other employee. The disagreement over the _Interboro_ doctrine, therefore, merely reflects differing views regarding the nature of the relationship that must exist between the action of the individual employee and the actions of the group in order for § 7 to apply. We cannot say that the Board's view of that relationship, as applied in the _Interboro_ doctrine, is unreasonable.

The invocation of a right rooted in a collective-bargaining agreement is unquestionably an integral part of the process that gave rise to the agreement. That process—beginning with the organization of a union, continuing into the negotiation of a collective-bargaining agreement, and extending through the enforcement of the agreement—is a single, collective activity. Obviously, an employee could not invoke a right grounded in a collective-bargaining agreement were it not for the prior negotiating activities of his fellow employees. Nor would it make sense for a union to negotiate a collective-bargaining agreement if individual employees could not invoke the rights thereby created against their employer. Moreover, when an employee invokes a right grounded in the collective-bargaining agreement, he does not stand alone. Instead, he brings to bear on his employer the power and resolve of all his fellow employees. When, for instance, James Brown refused to drive a truck he believed to be unsafe, he was in effect reminding his employer that he and his fellow employees, at the time their collective-bargaining agreement was signed, had extracted a promise from City Disposal that they would not be asked to drive unsafe trucks. He was also reminding his employer that if it persisted in ordering him to drive an unsafe truck, he could reharness the power of that group to ensure the enforcement of that promise. It was just as though James Brown was reassembling his fellow union members to reenact their decision not to drive unsafe trucks. A lone employee's invocation of a right grounded in his collective-bargaining agreement is, therefore, a concerted activity in a very real sense.

Furthermore, the acts of joining and assisting a labor organization, which § 7 explicitly recognizes as concerted, are related to collective action in essentially the same way that the invocation of a collectively bargained right is related to collective action. When an employee joins or assists a labor organization, his actions may be divorced in time, and in location as well, from the actions of fellow employees. Because of the integral relationship among the employees' actions, however, Congress viewed each employee as engaged in concerted activity. The lone employee could not join or assist a labor organization were it not for the related organizing activities of his fellow employees. Conversely, there would be limited utility in forming a labor organization if other employees could not join or assist the organization once it is formed. Thus, the formation of a labor organization is integrally related to the activity of joining or assisting such an organization in the same sense that the negotiation of a collective-bargaining agreement is integrally related to the invocation of a right provided for in the agreement. In each case, neither the individual activity nor the group activity would be complete without the other. 

The _Interboro_ doctrine is also entirely consistent with the purposes of the Act, which explicitly include the encouragement of collective bargaining and other "practices fundamental to the friendly adjustment of industrial disputes arising out of differences as to wages, hours, or other working conditions." 29 U. S. C. § 151. Although, as we have said, there is nothing in the legislative history of § 7 that specifically expresses the understanding of Congress in enacting the "concerted activities" language, the general history of § 7 reveals no inconsistency between the _Interboro_ doctrine and congressional intent. That history begins in the early days of the labor movement, when employers invoked the common-law doctrines of criminal conspiracy and restraint of trade to thwart workers' attempts to unionize. As this Court recognized in _NLRB v. Jones & Laughlin Steel Corp.,_ 301 U. S. 1, 33 (1937), a single employee at that time "was helpless in dealing with an employer; he was dependent ordinarily on his daily wage for the maintenance of himself and family; if the employer refused to pay him the wages that he thought fair, he was nevertheless unable to leave the employ and resist arbitrary and unfair treatment; union was essential to give laborers opportunity to deal on an equality with their employer."

Congress' first attempt to equalize the bargaining power of management and labor, and its first use of the term "concert" in this context, came in 1914 with the enactment of §§ 6 and 20 of the Clayton Act, which exempted from the antitrust laws certain types of peaceful union activities. There followed, in 1932, the Norris-La Guardia Act, which declared that "the individual worker shall be free from the interference, restraint, or coercion, of employers in self-organization or in _other_ _concerted activities for the purpose of collective bargaining or other mutual aid or protection._" 29 U. S. C. § 102 (emphasis added). This was the source of the language enacted in § 7. It was adopted first in § 7(a) of the National Industrial Recovery Act and then, in 1935, in § 7 of the NLRA.

Against this background, it is evident that, in enacting § 7 of the NLRA, Congress sought generally to equalize the bargaining power of the employee with that of his employer by allowing employees to band together in confronting an employer regarding the terms and conditions of their employment. There is no indication that Congress intended to limit this protection to situations in which an employee's activity and that of his fellow employees combine with one another in any particular way. Nor, more specifically, does it appear that Congress intended to have this general protection withdrawn in situations in which a single employee, acting alone, participates in an integral aspect of a collective process. Instead, what emerges from the general background of § 7—and what is consistent with the Act's statement of purpose—is a congressional intent to create an equality in bargaining power between the employee and the employer throughout the entire process of labor organizing, collective bargaining and enforcement of collective-bargaining agreements.

The Board's _Interboro_ doctrine, based on a recognition that the potential inequality in the relationship between the employee and the employer continues beyond the point at which a collective-bargaining agreement is signed, mitigates that inequality throughout the duration of the employment relationship, and is, therefore, fully consistent with congressional intent. Moreover, by applying § 7 to the actions of individual employees invoking their rights under a collective-bargaining agreement, the _Interboro_ doctrine preserves the integrity of the entire collective-bargaining process; for by invoking a right grounded in a collective-bargaining agreement, the employee makes that right a reality, and breathes life, not only into the promises contained in the collective-bargaining agreement, but also into the entire process envisioned by Congress as the means by which to achieve industrial peace.

To be sure, the principal tool by which an employee invokes the rights granted him in a collective-bargaining agreement is the processing of a grievance according to whatever procedures his collective-bargaining agreement establishes. No one doubts that the processing of a grievance in such a manner is concerted activity within the meaning of § 7. Indeed, it would make little sense for § 7 to cover an employee's conduct while negotiating a collective-bargaining agreement, including a grievance mechanism by which to protect the rights created by the agreement, but not to cover an employee's attempt to utilize that mechanism to enforce the agreement.

In practice, however, there is unlikely to be a bright-line distinction between an incipient grievance, a complaint to an employer, and perhaps even an employee's initial refusal to perform a certain job that he believes he has no duty to perform. It is reasonable to expect that an employee's first response to a situation that he believes violates his collective-bargaining agreement will be a protest to his employer. Whether he files a grievance will depend in part on his employer's reaction and in part upon the nature of the right at issue. In addition, certain rights might not be susceptible of enforcement by the filing of a grievance. In such a case, the collective-bargaining agreement might provide for an alternative method of enforcement, as did the agreement involved in this case, or the agreement might be silent on the matter. Thus, for a variety of reasons, an employee's initial statement to an employer to the effect that he believes a collectively bargained right is being violated, or the employee's initial refusal to do that which he believes he is not obligated to do, might serve as both a natural prelude to, and an efficient substitute for, the filing of a formal grievance. As long as the employee's statement or action is based on a reasonable and honest belief that he is being, or has been, asked to perform a task that he is not required to perform under his collective-bargaining agreement, and the statement or action is reasonably directed toward the enforcement of a collectively bargained right, there is no justification for overturning the Board's judgment that the employee is engaged in concerted activity, just as he would have been had he filed a formal grievance.

The fact that an activity is concerted, however, does not necessarily mean that an employee can engage in the activity with impunity. An employee may engage in concerted activity in such an abusive manner that he loses the protection of § 7. Furthermore, if an employer does not wish to tolerate certain methods by which employees invoke their collectively bargained rights, he is free to negotiate a provision in his collective-bargaining agreement that limits the availability of such methods. No-strike provisions, for instance, are a common mechanism by which employers and employees agree that the latter will not invoke their rights by refusing to work. In general, if an employee violates such a provision, his activity is unprotected even though it may be concerted. Whether Brown's action in this case was unprotected, however, is not before us.

[B]{.casesubsection}

Respondent argues that the _Interboro_ doctrine undermines the arbitration process by providing employees with the possibility of provoking a discharge and then filing an unfair labor practice claim. This argument, however, misses the mark for several reasons. First, an employee who purposefully follows this route would run the risk that the Board would find his actions concerted but nonetheless unprotected, as discussed above.

Second, the _Interboro_ doctrine does not shift dispute resolution from the grievance and arbitration process to NLRB adjudication in any way that is different from the alternative position adopted by the Court of Appeals, and pressed upon us by respondent. As stated above, the Court of Appeals would allow a finding of concerted activity if two employees together invoke a collectively bargained right, if a lone employee represents another employee in addition to himself when he invokes the right, or if the lone employee invokes the right in a manner that is intended to induce at least one other employee to join him. In each of these situations, however, the underlying substance of the dispute between the employees and the employer is the same as when a single employee invokes a collectively bargained right by himself. In each case the employees are claiming that their employer violated their collective-bargaining agreement, and if the complaining employee or employees in those situations are discharged, their unfair labor practice action would be identical to an action brought by an employee who has been discharged for invoking a collectively bargained right by himself. Because the employees in each of these situations are equally well positioned to go through the grievance and arbitration process, there is no basis for singling out the _Interboro_ doctrine as undermining that process any more than would the approach of respondent and the Courts of Appeals that have rejected the doctrine.

Finally, and most importantly, to the extent that the factual issues raised in an unfair labor practice action have been, or can be, addressed through the grievance process, the Board may defer to that process. There is no reason, therefore, for the Board's interpretation of "concerted activity" in § 7 to be constrained by a concern for maintaining the integrity of the grievance and arbitration process.

[III]{.casesection}

In this case, the Board found that James Brown's refusal to drive truck No. 244 was based on an honest and reasonable belief that the brakes on the truck were faulty. Brown explained to each of his supervisors his reason for refusing to drive the truck. Although he did not refer to his collective-bargaining agreement in either of these confrontations, the agreement provided not only that "the Employer shall not require employees to take out on the streets or highways any vehicle that is not in safe operating condition," but also that "it shall not be a violation of this Agreement where employees refuse to operate such equipment, unless such refusal is unjustified." There is no doubt, therefore, nor could there have been any doubt during Brown's confrontations with his supervisors, that by refusing to drive truck No. 244, Brown was invoking the right granted him in his collective-bargaining agreement to be free of the obligation to drive unsafe trucks. Moreover, there can be no question but that Brown's refusal to drive the truck was reasonably well directed toward the enforcement of that right. Indeed, it would appear that there were no other means available by which Brown could have enforced the right. If he had gone ahead and driven truck No. 244, the issue may have been moot.

Respondent argues that Brown's action was not concerted because he did not explicitly refer to the collective-bargaining agreement as a basis for his refusal to drive the truck. The Board, however, has never held that an employee must make such an explicit reference for his actions to be covered by the _Interboro_ doctrine, and we find that position reasonable. We have often recognized the importance of "the Board's special function of applying the general provisions of the Act to the complexities of industrial life." As long as the nature of the employee's complaint is reasonably clear to the person to whom it is communicated, and the complaint does, in fact, refer to a reasonably perceived violation of the collective-bargaining agreement, the complaining employee is engaged in the process of enforcing that agreement. In the context of a workplace dispute, where the participants are likely to be unsophisticated in collective-bargaining matters, a requirement that the employee explicitly refer to the collective-bargaining agreement is likely to serve as nothing more than a trap for the unwary.

Respondent further argues that the Board erred in finding Brown's action concerted based only on Brown's reasonable and honest belief that truck No. 244 was unsafe. Respondent bases its argument on the language of the collective-bargaining agreement, which provides that an employee may refuse to drive an unsafe truck "unless such refusal is unjustified." In the view of respondent, this language allows a driver to refuse to drive a truck only if the truck is objectively unsafe. Regardless of whether respondent's interpretation of the agreement is correct, a question as to which we express no view, this argument confuses the threshold question whether Brown's conduct was concerted with the ultimate question whether that conduct was protected. The rationale of the _Interboro_ doctrine compels the conclusion that an honest and reasonable invocation of a collectively bargained right constitutes concerted activity, regardless of whether the employee turns out to have been correct in his belief that his right was violated. No one would suggest, for instance, that the filing of a grievance is concerted only if the grievance turns out to be meritorious. As long as the grievance is based on an honest and reasonable belief that a right had been violated, its filing is a concerted activity because it is an integral part of the process by which the collective-bargaining agreement is enforced. The same is true of other methods by which an employee enforces the agreement. On the other hand, if the collective-bargaining agreement imposes a limitation on the means by which a right may be invoked, the concerted activity would be unprotected if it went beyond that limitation. 

In this case, because Brown reasonably and honestly invoked his right to avoid driving unsafe trucks, his action was concerted. It may be that the collective-bargaining agreement prohibits an employee from refusing to drive a truck that he reasonably believes to be unsafe, but that is, in fact, perfectly safe. If so, Brown's action was concerted but unprotected. As stated above, however, the only issue before this Court and the only issue passed upon by the Board or the Court of Appeals is whether Brown's action was concerted, not whether it was protected.

#### @StericycleInc_NLRB2023

Today, after previously issuing a notice and invitation for briefing, we adopt a new legal standard to decide whether an employer’s work rule that does not expressly restrict employees’ protected concerted activity under Section 7 of the National Labor Relations Act (Act) is facially unlawful under Section 8(a)(1) of the Act. Here, an administrative law judge found that the Respondent violated Section 8(a)(1) by maintaining certain rules for its employees that addressed personal conduct, conflicts of interest, and confidentiality of harassment complaints. In making those findings, the judge applied the standard established by a divided Board in _Boeing Co._, 365 NLRB No. 154 (2017), which sua sponte reversed the standard announced in _Lutheran Heritage Village-Livonia_, 343 NLRB 646 (2004).

Given the ubiquity of work rules and the importance of ensuring that such rules do not operate to undermine employees’ exercise of their rights under the Act, we sought public input on the standard adopted in _Boeing_, then purportedly clarified in _LA Specialty Produce_ Co., 368 NLRB No. 93 (2019), and applied in subsequent cases where the Board found that several types of work rules were categorically lawful for employers to maintain, essentially without regard to how the particular rules were drafted.

Accordingly, we invited the parties and interested amici to address the following questions:

1. Should the Board continue to adhere to the standard adopted in _Boeing Co._ and revised in _LA Specialty Produce Co._?
2. In what respects, if any, should the Board modify existing law addressing the maintenance of employer work rules to better ensure that:
	a. the Board interprets work rules in a way that accounts for the economic dependence of employees on their employers and the related potential for a work rule to chill the exercise of Section 7 rights by employees;
	b. the Board properly allocates the burden of proof in cases challenging an employer’s maintenance of a work rule under Section 8(a)(1); and
	c. the Board appropriately balances employees’ rights under Section 7 and employers’ legitimate business interests?
3. Should the Board continue to hold that certain categories of work rules--such as investigative-confidentiality rules, non-disparagement rules, and rules prohibiting outside employment--are always lawful to maintain?

Having carefully considered the briefs of the parties and amici, as well as the Board’s past experiences regarding these issues and the view of our dissenting colleague, we have decided to adopt an approach to assessing facial challenges to employer work rules under Section 8(a)(1) that builds on and revises the _Lutheran Heritage_ standard. As we will explain, the primary problem with the standard from _Boeing_ and _LA Specialty Produce_ is that it permits employers to adopt overbroad work rules that chill employees’ exercise of their rights under Section 7 of the Act, which include the “right to self-organization, to form, join, or assist labor organizations, to bargain collectively . . ., and to engage in other concerted activities for the purpose of collective bargaining or other mutual aid or protection.” 29 U.S.C. § 157. To begin, the current standard fails to account for the economic dependency of employees on their employers. Because employees are typically (and understandably) anxious to avoid discharge or discipline, they are reasonably inclined both to construe an ambiguous work rule to prohibit statutorily protected activities and to avoid the risk of violating the rule by engaging in such activity. In turn, _Boeing_ gives too little weight to the burden a work rule could impose on employees’ Section 7 rights. At the same time, _Boeing_’s purported balancing test gives too much weight to employer interests. Crucially, _Boeing_ also condones overbroad work rules by not requiring the party drafting the work rules--the employer--to narrowly tailor its rules to only promote its legitimate and substantial business interests while avoiding burdening employee rights.

The standard we adopt today remedies these fundamental defects. We adopt a modified version of the basic framework set forth in _Lutheran Heritage_, which recognized that overbroad workplace rules and polices may chill employees in the exercise of their Section 7 rights and properly focused the Board’s inquiry on NLRA-protected rights. During the 13 years when the _Lutheran Heritage_ standard was in place, reviewing courts repeatedly and uncontroversially applied and upheld the standard. No court rejected the _Lutheran Heritage_ standard or held that the Board was, in fact, applying some standard other than the one it articulated. However, although _Lutheran Heritage_ implicitly allowed the Board to evaluate employer interests when considering whether a particular rule was unlawfully overbroad, the standard itself did not clearly address how employer interests factored into the Board’s analysis. The modified standard we adopt today makes explicit that an employer can rebut the presumption that a rule is unlawful by proving that it advances legitimate and substantial business interests that cannot be achieved by a more narrowly tailored rule. Because we overrule _Boeing_, _LA Specialty Produce_, and the work rules cases relying on them, including those that placed rules into an “always lawful” category based simply on their subject matter, we reject _Boeing_’s categorical approach, instead returning to a particularized analysis of specific rules, their language, and the employer interests actually invoked to justify them.

As under _Lutheran Heritage_, our standard requires the General Counsel to prove that a challenged rule has a reasonable tendency to chill employees from exercising their Section 7 rights. We clarify that the Board will interpret the rule from the perspective of an employee who is subject to the rule and economically dependent on the employer, and who also contemplates engaging in protected concerted activity. Consistent with this perspective, the employer’s intent in maintaining a rule is immaterial. Rather, if an employee could reasonably interpret the rule to have a coercive meaning, the General Counsel will carry her burden, even if a contrary, noncoercive interpretation of the rule is also reasonable. If the General Counsel carries her burden, the rule is presumptively unlawful, but the employer may rebut that presumption by proving that the rule advances a legitimate and substantial business interest and that the employer is unable to advance that interest with a more narrowly tailored rule. If the employer proves its defense, then the work rule will be found lawful to maintain.

[I.]{.casesection}

Applying Section 8(a)(1) of the Act, the Board has long and consistently recognized that an employer’s mere maintenance of a work rule may unlawfully interfere with, restrain, or coerce employees in the exercise of their Section 7 rights. The Supreme Court long ago confirmed the Board’s authority to regulate employer work rules, as part of the flexibility the Board requires “to accomplish the dominant purpose” of the Act: to protect “the right of employees to organize for mutual aid without employer interference.” Because overbroad and ambiguous work rules may have a coercive effect on employees, the Board and courts have long acknowledged that the regulation of work rules “serves an important prophylactic function: it allows the Board to block rules that might chill the exercise of employees’ rights by cowing the employees into inaction, rather than forcing the Board to ‘wait until that chill is manifest,’ and then try to ‘undertake the difficult task of dispelling it.”’

In its decisions carrying out this important function, the Board has grappled with two interrelated issues. The first has been determining the appropriate interpretive principles to apply in evaluating the potentially deleterious impact of a work rule on employees’ exercise of their Section 7 rights. In doing so, the Board regularly has assessed work rules to determine “the reasonably foreseeable effects of the wording of the rule on the conduct of the employees,” observing that “where the language is ambiguous and may be misinterpreted by the employees in such a way as to cause them to refrain from exercising their statutory rights, then the rule is invalid even if interpreted lawfully by the employer in practice.” The second issue for the Board has been determining how to ensure that the rule minimizes any potential impact on employee rights, notwithstanding the legitimate business interests that the employer may be trying to advance by maintaining its rule.

Over the past nearly 25 years, the Board has attempted to articulate and consistently apply a generally applicable test under Section 8(a)(1) for assessing facial challenges to work rules. For almost half that time, the _Lutheran Heritage_ standard provided the interpretive principles relevant to assessing the impact of a given rule on employees’ rights. We detail the Board’s recent history below with an eye toward explaining why a modified version of the _Lutheran Heritage_ standard is the best approach to evaluating facial challenges to work rules in light of the Board’s experience and long-established statutory principles. Our decision today does not disturb the Board’s long-established doctrines covering work rules that address union (or other protected) solicitation, distribution, or insignia. Consistent with the Board’s decisions in both _Lutheran Heritage_ and _Boeing_, we preserve Board precedent in those areas.

[Lafayette Park]{.casesubsection}

The recent history of the Board’s approach to work rules begins with _Lafayette Park Hotel_ (1998). There, a full Board considered facial challenges to rules defining various types of “unacceptable conduct.” The Board identified “the appropriate inquiry” as “whether the rules would reasonably tend to chill employees in the exercise of their Section 7 rights” and that, where there is a likely chilling effect, “the Board may conclude that their maintenance is an unfair labor practice, even absent evidence of enforcement.” For that standard, the Board referred to the Supreme Court’s decision in _Republic Aviation_, quoting its admonition that assessing the challenged rules involves “working out an adjustment between the undisputed right of self-organization assured to employees under the Act and the equally undisputed right of employers to maintain discipline in their establishments.” Member Hurtgen, disagreeing with the majority, expressed his view that “if a rule reasonably chills the exercise of Sec. 7 rights, it can nonetheless be lawful if it is justified by significant employer interests.”

In analyzing the challenged rules’ impact on employees under its announced standard, the _Lafayette Park_ Board did consider the employer’s interests in maintaining its rules, if not in the manner Member Hurtgen sought. l use of certain of the employer’s facilities, the Board noted the “legitimate business reasons for such a rule” and its view that “employees would recognize the rule for its legitimate purpose.” Similarly, when assessing the employer’s rule forbidding fraternization between employees and customers, the Board noted that employees “would recognize the legitimate business reasons for which such a rule was promulgated, and would not reasonably believe that it reaches Section 7 activity.” Although the Board considered the employer’s interests (as effectively communicated to employees), it did so in the course of interpreting a rule and assessing its potential chilling effect on employees.

The _Lafayette Park_ Board was divided, too, in how to correctly apply the announced standard to particular rules. In a partial dissent, Members Fox and Liebman thought the majority merely paid “lip service” to the applicable interpretive principles in upholding rules that, in their view, had “the likely effect of chilling Section 7 activity.” In response, Chairman Gould characterized their dissenting approach as one that improperly “parsed out certain words and createed theoretical definitions” for rules “that differ from the obvious ones.” He asserted that the Board should not “focus on whether any language in the rules could theoretically encompass Section 7 activity” but, instead, should focus on “whether a reasonable employee could believe that the rule prohibits protected activity.” 

[Lutheran Heritage]{.casesubsection}

A few years later, in another full-Board decision, _Lutheran Heritage_ (2004), the majority construed Lafayette Park to mean that the relevant inquiry “begins with the issue of whether the rule explicitly restricts activities protected by Section 7.” If it does not, a violation “is dependent upon a showing of one of the following: (1) employees would reasonably construe the language to prohibit Section 7 activity; (2) the rule was promulgated in response to union activity; or (3) the rule has been applied to restrict the exercise of Section 7 rights.” Under the first of these prongs, the majority instructed that the Board “must refrain from reading particular phrases in isolation,” “must not presume” that a rule will cause “improper interference with employee rights,” and should not conclude “that a reasonable employee would read a rule to apply to Section 7 activity simply because the rule could be interpreted that way.” 

In an effort to refine the standard applied in _Lafayette Park_, the Board in _Lutheran Heritage_ observed that it was not enough to establish a violation of Section 8(a)(1) merely because a rule “could conceivably be read to cover Section 7 activity,” but in referring to how a reasonable employee ““would read” the rule, the majority did not expressly hold that the coercive meaning must be the only reasonable interpretation of the rule or the most reasonable interpretation. The _Lutheran Heritage_ Board acknowledged that the rules it was scrutinizing “serve legitimate business purposes” and that reasonable employees “would realize the lawful purpose of the challenged rules”--thereby suggesting that such considerations had informed its conclusions--but again the _Lutheran Heritage_ majority did not clearly explain how employer interests factored into the analysis. Finally, _Lutheran Heritage_ rejected a categorical approach to work rules. The majority acknowledged the case-by-case nature of the Board’s work rules decisions, noting that it did “not consider it necessary or appropriate to decide in this case what rules in a future hypothetical case would be unlawful.”

In dissent, Members Liebman and Walsh raised the issue of balancing. They argued that in Lafayette Park the Board had recognized that “determining the lawfulness of an employer’s work rules requires balancing competing interests,” and they accused the majority of “ignoring the employees’ side of the balance.” The dissenters agreed that employers have legitimate business interests that warrant protection through the maintenance of work rules but contended that the employer must do so “subject to the requirement that employers articulate those rules with sufficient specificity that they do not impinge on employees’ free exercise of Section 7 rights.”

_Lutheran Heritage_, then, again demonstrated the Board’s ongoing efforts to develop a standard that grappled with the two key questions posed in work rules cases: (1) how to interpret a rule and (2) whether and how employer interests factor into the analysis.

[Aftermath of Lutheran Heritage]{.casesubsection}

Following _Lutheran Heritage_, the Board decided many work rules cases, and reviewing courts consistently applied and upheld the standard.8 However, there was some degree of confusion and disagreement about some aspects of its proper application, in particular whether, and if so, how, to consider an employer’s reasons for maintaining a challenged rule.

For instance, in _Flagstaff Medical Center_ (2011), a panel majority found a hospital employer’s rule restricting employees’ use of cameras lawful, in part because of the employer’s “significant interest” in having the rule to prevent the disclosure of patient health information. The majority there viewed the employer’s interest in maintaining the rule relevant to the analysis insofar as it informed the majority’s assessment that reasonable employees would recognize that employer interest and view the rule “as a legitimate means of protecting the privacy of patients and their hospital surroundings, not as a prohibition of protected activity.” 

But in a separate decision issued on the same day, a different panel majority assessed an employer’s maintenance of certain work rules and made no mention of the employer’s interests. Instead, the majority determined that the “only question” relevant was whether the employees “would reasonably construe the . . . rules to prohibit Section 7 activity” and did not mention the employer’s interests for maintaining the rules as part of its analysis resolving that question. Courts occasionally regarded the Board’s implicit approach to addressing employer interests under _Lutheran Heritage_ as placing a rebuttal burden on the employer, once it was established that a rule had a reasonable tendency to chill employees’ exercise of Section 7 rights.9

[William Beaumont]{.casesubsection}

In _William Beaumont Hospital_ (2016), a majority consisting of then-Member McFerran and Member Hirozawa struck down a hospital employer’s rule prohibiting conduct that “impedes harmonious interactions and relationships” because employees would reasonably understand that it could encompass interactions protected by Section 7. The majority also found a rule prohibiting “negative or disparaging comments” unlawful because it would reasonably be construed to prohibit protected expressions of concern about working conditions. 

In dissent, Member Miscimarra contended that the _Lutheran Heritage_ standard foreclosed consideration of employers’ justifications for their rules. In his view, the “‘reasonably construe’ standard entailed a single-minded consideration of NLRA-protected rights, without taking into account the legitimate justifications of particular policies, rules and handbook provisions.” He advocated a revised approach whereby, in every case challenging an employer’s maintenance of a work rule, the Board would determine “the potential adverse impact of the rule on NLRA-protected activity” and “the legitimate justifications an employer may have for maintaining the rule.” Once the competing interests were identified, the Board should then balance them such that “a facially neutral rule should be declared unlawful only if the justifications are outweighed by the adverse impact on Section 7 activity.” 

In response, the _William Beaumont_ majority acknowledged that assessing work rules was a “difficult area of labor law,” particularly because of “the remarkable number, variety, and detail of employer work rules.” But the majority also noted that, in the years since the Board had decided _Lutheran Heritage_, no court of appeals had rejected the standard that the Board regularly applied in work-rules cases. The majority further explained that the _Lutheran Heritage_ standard did, in fact, “take into account employer interests.” It did so by leaving employers free to protect their legitimate business interests by adopting more narrowly tailored rules while not infringing on Section 7 rights. The majority noted that when the Board found that a rule was not unlawfully overbroad, “it was typically because the rule was tailored such that the employer’s legitimate business interest in maintaining the rule was sufficiently apparent to a reasonable employee.” 

[Boeing and LA Specialty Produce]{.casesubsection}

Less than 2 years later, without being asked and without seeking any public input, a newly constituted Board effectively incorporated the William Beaumont dissent into the majority opinion in _Boeing Co._ (2017). The _Boeing_ majority held that, when deciding the lawfulness of maintaining a ““facially neutral” work rule, the Board “will evaluate two things: (i) the nature and extent of the potential impact on NLRA rights, and (ii) legitimate justifications associated with the rule.” Those two factors would be balanced against each other. According to the majority, the _Lutheran Heritage_ standard did not permit the Board to consider an employer’s legitimate business reasons for maintaining a rule; to distinguish between more and less important Section 7 interests; to differentiate among industries, work settings, or specific circumstances reflected in a given rule; or to produce consistent rulings in work-rules cases. And the majority claimed that past Board decisions specifying criteria for assessing the lawfulness of specific types of rules--like rules concerning workplace solicitation and distribution of literature--comport with its standard, which permitted accommodating employer interests, but not under _Lutheran Heritage_, which it asserted did not.

The majority also created a categorical classification system for evaluating rules under its standard. In “Category 1”--rules that were always lawful to maintain--it would put rules that, as a type, did not interfere with Section 7 rights and rules where the adverse impacts on Section 7 rights were outweighed by justifications associated with such rules. In “Category 2”--rules that were sometimes lawful to maintain--it would put rules that “warrant scrutiny in each case.” And in “Category 3”--rules that were always unlawful to maintain--it would put rules that, given their impact on protected activity, could never be justified by an employer. The purported intent of this categorical approach was to “provide far greater clarity and certainty” for regulated parties. 

Applying its new standard, the _Boeing_ majority upheld a rule maintained by the employer, a manufacturer of military and commercial aircraft, restricting the use of cameras in the workplace because any “adverse impact” on Section 7 rights was “comparatively slight” and was “outweighed by substantial and important justifications associated with _Boeing_’s maintenance of the no-camera rule.” Without further explanation, it deemed all rules of that type always lawful for employers to maintain no matter the circumstances. Remarkably, the _Boeing_ Board also designated all rules “requiring employees to abide by basic standards of civility”--of the sort at issue in _William Beaumont_, but not at issue in _Boeing_--as always lawful. 

Then-Member McFerran and Member Pearce both dissented, expressing similar views. Member McFerran asserted that, as the Board had recently explained in _William Beaumont_, the standard under _Lutheran Heritage_ did allow for consideration of an employer’s legitimate business justifications for its work rules. But Member McFerran contended that the majority’s approach here went too far, privileging an employer’s interests over the rights of employees, who, because of their economic dependence on employers, reasonably take a cautious approach when interpreting work rules for fear of running afoul of a rule whose scope is unclear. Member McFerran also criticized the majority’s assertion that its approach would provide more “certainty and clarity,” as she noted that it failed to identify which Section 7 rights and which employer interests are entitled to more or less weight in its balancing. 

As to the majority’s categorical approach, Member McFerran noted that designating a type of rule as always lawful to maintain improperly forgoes particularized scrutiny of a similar rule in an altogether different workplace by finding it lawful without addressing what particular Section 7 rights are at stake, what justifications an employer might actually offer for its rule, and what industry or work setting is involved. 

Member Pearce expressed similar criticisms. He found “particularly troubling” the majority’s designation of civility rules as always lawful to maintain. He pointed out that no civility rules were at issue in the case and that, in any event, civility rules threatened to chill the sort of heated expression that was not uncommon when employees engage in Section 7 activity. 

Less than 2 years later, in _LA Specialty Produce Co._ (2019), a Board majority observed that _Boeing_ needed to be buttressed with some “points of clarification.” One ostensible clarification addressed how rules should be interpreted. The majority asserted that the reasonable employee does “not view every employer policy through the prism of the NLRA,” such that “a challenged rule may not be found unlawful merely because it could be interpreted, under some hypothetical scenario, as potentially limiting some type of Section 7 activity.” A second ostensible clarification addressed the burden of proof to demonstrate a work rule’s impact on Section 7 rights, holding that “it is the General Counsel’s initial burden in all cases to prove that a facially neutral rule would in context be interpreted by a reasonable employee . . . to potentially interfere with the exercise of Section 7 rights.” The majority also attempted to clarify the categorical approach by explaining that a rule should be placed in Category 1, and thus deemed always lawful to maintain, when the “general” employer interests in maintaining such a rule outweigh the potential impact on the exercise of Section 7 rights. 

Member McFerran dissented. As a threshold matter, she summarized what she deemed to be the primary defects in the reasoning of the _Boeing_ Board. Those included (1) that the Board, in rejecting _Lutheran Heritage_ and announcing a new standard, did so sua sponte and without public input; (2) that the standard under _Lutheran Heritage_ already permitted the Board to consider an employer’s legitimate business justifications for its work rules; (3) that the _Boeing_ standard fails to properly assess rules from the perspective of a reasonable employee because it does not consider the economic dependence of employees on employers, which increases the chilling potential of ambiguous rules; and (4) that _Boeing_’s categorical approach dispenses with individualized scrutiny for rules by ignoring their wording, whether they were narrowly tailored, and their context. 

Member McFerran also disagreed with the clarifications that _LA Specialty Produce_ purported to make to _Boeing_. Specifically, she argued that the majority’s description of a reasonable employee ignored employees’ economic dependence on the employer and the resulting reasonable tendency to interpret work rules as coercive, even where a disinterested person would not. She also faulted the majority’s requirement that the General Counsel must prove that a work rule “would in context be interpreted . . . to potentially interfere with the exercise of Section 7 rights” as effectively (but not explicitly) requiring a showing that the coercive interpretation of a rule is the only reasonable interpretation. As for the balancing test, Member McFerran noted that the majority failed to explain which party has the burden of proof with respect to the balancing, and that its endorsement of a “general” balancing approach eliminated consideration of the language of a particular rule or the requirement of narrow tailoring. 

[Aftermath of Boeing and LA Specialty Produce]{.casesubsection}

Since _Boeing_ was decided, both before and after the Board’s attempted clarification of it in _LA Specialty Produce_, the Board has applied its new standard in a number of cases. The Board has usually found work rules lawful to maintain and, generally, has categorically deemed all similar rules to be lawful to maintain, no matter the specific wording of any particular rule or the specific workplace context in which they are maintained.

[II.]{.casesection}

Having considered the valuable perspectives of the parties and amici, as well as the Board’s past experience and the views of our dissenting colleague, we have decided the better approach is a modified version of the framework set forth in _Lutheran Heritage_ for evaluating facial challenges to employer work rules that do not explicitly restrict Section 7 activity by employees and were not promulgated in response to such activity, as clarified herein. As explained, the key issues presented are: (1) defining the interpretive principles to apply to discern when work rules have a reasonable tendency to chill employees’ exercise of their statutory rights and (2) working out the proper adjustment between protecting employee rights and accommodating employers’ legitimate and substantial business interests in maintaining their rules. Although Lafayette Park and _Lutheran Heritage_ established the Board’s proper interpretive focus--the perspective of a reasonable employee subject to the rule--they did not sufficiently (or clearly) articulate how employers’ interests fit into the analysis. While _Boeing_ and _LA Specialty Produce_, in turn, appropriately recognized that employer interests should factor into the Board’s analysis, they adopted interpretive principles that failed to reflect the true coercive potential of work rules. In addition, those decisions gave too little weight to employees’ Section 7 rights and too much weight to employer interests, in particular by failing to require employers to narrowly tailor their work rules to minimize as much as reasonably possible, if not altogether eliminate, any infringement of employee rights.

The approach we adopt today seeks to preserve the insights of the Board’s prior decisions while addressing their shortcomings. Given the wide range of work rules, the varying language they use, and the many different employment contexts in which they arise, we do not expect our new standard to provide complete certainty and predictability in this area of the law. That abstract goal--as the Board’s experience under _Boeing_ suggests--could be achieved only by arbitrarily expanding the universe of work rules deemed always lawful to maintain, at the obvious expense to employees’ ability to exercise the rights guaranteed to them by the Act.

Our approach is focused on furthering what the Supreme Court many decades ago defined as the “dominant purpose” of the Act: protecting “the right of employees to organize for mutual aid without employer interference.” In the context of this case, achieving the Act’s purpose means ensuring that the Board does not condone employer work rules that chill employees’ exercise of their statutory rights for fear of discipline or discharge if they violate them. The potential for intimidation is great precisely because of what the Supreme Court has described as “the economic dependence of the employees on their employers, and the necessary tendency of the former, because of that relationship, to pick up intended implications of the latter that might be more readily dismissed by a more disinterested ear.” This fact of workplace life should be reflected in the Board’s treatment of work rules under Section 8(a)(1) of the Act, just as the Supreme Court has required with respect to the analysis of employers’ arguably coercive statements to employees.

But “equally undisputed,” as the Supreme Court has also observed, is the “right of employers to maintain discipline in their establishments” and otherwise protect their legitimate and substantial business interests by regulating employees’ workplace conduct. Accordingly, in the work-rules context, as in other situations governed by Section 8(a)(1) of the Act, the Board must fulfill its duty to protect employees’ Section 7 rights while also considering employers’ legitimate and substantial business interests. As we will explain, our new standard gives employers the necessary leeway to maintain rules of their own choosing to advance legitimate and substantial business interests. They simply need to narrowly tailor those rules to significantly minimize, if not altogether eliminate, their coercive potential. If employers do so, their rules will be lawful to maintain.

[A.]{.casesubsection}

It has long been established that the test for evaluating whether an employer’s conduct or statements violate Section 8(a)(1) of the Act is whether they have a reasonable tendency to interfere with, restrain, or coerce employees who may engage in activities protected by Section 7. The General Counsel, of course, has the burden of establishing a violation of the Act. As we now explain, our initial focus in the work-rules context is on whether the General Counsel has proven that a rule has a reasonable tendency to interfere with, restrain, or coerce employees who contemplate engaging in protected activity. To discern that tendency, the Board--as in all other Section 8(a)(1) contexts--appropriately “views employer statements ‘from the standpoint of employees over whom the employer has a measure of economic power.”’ 

Interpreting a work rule from the perspective of the economically dependent employee who contemplates engaging in Section 7 activity is consistent with workplace reality--employees ordinarily do not wish to risk their jobs by violating their employers’ rules--and with the employee-protective purposes of the Act. As suggested, this frame of reference is entirely consistent with, and arguably compelled by, the Supreme Court’s decision in _Gissel_, which considered whether certain statements made by an employer to his employees violated Section 8(a)(1). Addressing the employer’s argument that its statements were protected by Section 8(c) of the Act, the _Gissel_ Court explained that “an employer’s rights cannot outweigh the equal rights of the employees to associate freely, as those rights are embodied in § 7 and protected by § 8(a)(1).” The Court reasoned that “any balancing of those rights must take into account the economic dependence of the employees on their employers, and the necessary tendency of the former, because of that relationship, to pick up intended implications of the latter that might be more readily dismissed by a more disinterested ear.” These “obvious principles,” in the Court’s words, should be central to our analysis when the Board evaluates a work rule. Accordingly, in interpreting a rule, the Board will take the perspective of the “economically dependent employee” who contemplates engaging in Section 7 activity. Such an employee is readily inclined to avoid violating a rule, and so readily inclined to interpret it more broadly to restrict or prohibit Section 7 activity than a disinterested observer might. Being discharged might mean--to take just two very real examples--being unable to pay rent or put food on the table. For purposes of the Act, then, the coercive potential of a work rule is inextricably intertwined with the vulnerable position of employees.

By explicitly incorporating the perspective of the economically dependent employee into our analysis, we adopt an important interpretive principle that sometimes explicitly factored into the Board’s analysis under Lafayette Park and _Lutheran Heritage_. This principle is consistent with the Board’s long-established practice of construing any ambiguity in a work rule against the employer as the drafter of the rule.

Despite stating that work rules should be interpreted from “the employees’ perspective,” the _Boeing_ Board did not base this perspective on employees’ economic dependence. And, in turn, the Board in _LA Specialty Produce_ obfuscated the issue by asserting--in response to the dissent’s view that rules should be assessed from the perspective of an economically dependent employee--that “a reasonable employee does not presume a Section 7 violation lurks around every corner.” Such rhetoric obscures the need to promote the policies of the Act, consistent with the Supreme Court’s insight in Gissel about employees’ economic position. For statutory purposes, the relevant reasonable employee is the employee who contemplates engaging in Section 7 activity, because this is the activity that the Act is explicitly intended to protect from employer interference. Whether some hypothetical employee only sometimes, or even never, contemplates Section 7 activity is immaterial. Indeed, if the likelihood of an employee contemplating Section 7 activity were somehow a relevant consideration, then even a rule explicitly prohibiting such activity could arguably be lawful (as not having a reasonable tendency, in fact, to interfere with the Section 7 activity of an employee who would not contemplate engaging in such activity). It is appropriate, then, for the Board to interpret an ambiguous work rule from the perspective of an employee who contemplates Section 7 activity, but who wishes to avoid the risk of being disciplined or discharged for violating the rule. The Board’s goal, of course, is to ensure that employers do not maintain unlawfully overbroad work rules that have a reasonable tendency to chill employees from exercising their statutory rights.

In interpreting rules from the perspective of a reasonable employee, we believe the Board must also recognize that a typical employee interprets work rules as a layperson rather than as a lawyer. This uncontroversial principle has long been recognized by the Board, which has sensibly observed that “employees do not generally carry lawbooks to work or apply legal analysis to company rules as do lawyers, and cannot be expected to have the expertise to examine company rules from a legal standpoint.” 

In sum, going forward, the Board will begin its analysis by assessing whether the General Counsel has established that a challenged work rule has a reasonable tendency to chill employees from exercising their Section 7 rights. In doing so, the Board will interpret the rule from the perspective of the reasonable employee who is economically dependent on her employer and thus inclined to interpret an ambiguous rule to prohibit protected activity she would otherwise engage in. The reasonable employee interprets rules as a layperson, not as a lawyer. If an employee could reasonably interpret a rule to restrict or prohibit Section 7 activity, the General Counsel has satisfied her burden and demonstrated that the rule is presumptively unlawful. That is so even if the rule could also reasonably be interpreted not to restrict Section 7 rights and even if the employer did not intend for its rule to restrict Section 7 rights.

[B.]{.casesubsection}

For reasons already explained, in some circumstances a violation of Section 8(a)(1) may require more than a showing that an employee could reasonably interpret a work rule to restrict or prohibit Section 7 activity. In such cases, the Board must still evaluate the lawfulness of a work rule in the context of the legitimate and substantial business interests of the employer in maintaining a specific work rule under the particular circumstances. Accordingly, if the General Counsel carries her burden of demonstrating that a rule is presumptively unlawful, an employer may rebut the presumption by proving that the rule advances a legitimate and substantial business interest and that the employer is unable to advance that interest with a more narrowly tailored rule.

As we have explained, prior to _Boeing_, it was unclear precisely how the Board’s work-rules standard incorporated an assessment of employer interests. Our new standard makes explicit that the Board will consider employer interests when evaluating the employer’s rebuttal to the General Counsel’s showing that a rule is presumptively unlawful.

The clarified standard improves on the conspicuous shortcomings of the approach adopted in _Boeing_. Under the _Boeing_ standard, a challenged rule’s “potential impact on NLRA rights” was balanced against “legitimate justifications associated with” the rule. But in practice, the _Boeing_ balancing test was heavily weighted against employees’ Section 7 rights and in favor of employer interests, because--with little if any explanation--the Board proceeded to treat employee rights as “peripheral.” Although the Board under _Boeing_ never explained which employee rights are “peripheral”--and there is no clear support in the Act for making such a determination--the characterization allowed the Board to regularly (and, in our view, arbitrarily) diminish the deleterious impacts of a challenged rule on Section 7 rights.

Crucially, _Boeing_’s balancing approach measured employer interests against employee interests without any requirement that a rule be narrowly tailored to serve the employer’s legitimate interests in having the rule. Under _Boeing_, then, overbroad work rules are perfectly permissible. So long as the employer interests advanced by the rule are found to outweigh the burden on employees’ rights, that rule is lawful to maintain--even if the employer interests could still be advanced by more narrowly crafting the rule such that it lessened or eliminated its burden on employees’ rights. We believe that requiring employers to narrowly tailor their rules is a critical part of working out the proper adjustment between employee rights and employer interests in the work-rules context.

Such a requirement acknowledges employers’ prerogative to craft rules that they need to advance legitimate and substantial business interests while necessarily minimizing or eliminating the burden that such rules can have on employees’ exercise of their statutory rights. We impose no unreasonable burden on employers by expecting them to be aware of their employees’ rights under the National Labor Relations Act, a statute enacted in 1935, more than 85 years ago, and long understood to apply in most workplaces, unionized and nonunionized alike--and to craft rules that minimize interference with their employees’ exercise of these long-established federal rights. Indeed, as we have noted, it has long been uncontroversial that any ambiguity in a work rule must be construed against the employer as the drafter of the rule.

Prior to _Boeing_, the Board often applied a narrow-tailoring requirement. As the Board explained then, many of the Board’s pre-_Boeing_ findings that a given rule was lawful to maintain were “typically because” the rule was narrowly tailored. The courts of appeals approved of the Board’s application of a narrow-tailoring requirement. After all, courts are well familiar with the concepts of facial overbreadth and the importance of narrowly tailoring a rule from the First Amendment context. 

We believe that a narrow-tailoring requirement is exactly the sort of reasonable “adjustment between the undisputed right of self-organization assured to employees under the Act and the equally undisputed right of employers to maintain discipline in their establishments” that the Supreme Court has instructed us to make in comparable situations. 

Under _Boeing_, even after attempting to provide clarifications in _LA Specialty Produce_, the Board never explained which party has the burden of proof with respect to the balancing test. We make clear here that, when a rule is presumptively unlawful, it is the employer’s burden to prove that its legitimate and substantial business interests cannot be accomplished with a more narrowly tailored rule and that, as a result, the rule should be deemed lawful to maintain. Placing the burden on the employer is consistent with the Supreme Court’s decisions in comparable circumstances. This burden allocation is no different than under our more generally applicable Section 8(a)(1) framework. See, e.g., _ANG Newspapers_, 343 NLRB 564, 565 (2004) (“Under the 8(a)(1) standard, the Board first examines whether the employer’s conduct reasonably tended to interfere with Section 7 rights. If so, the burden is on the employer to demonstrate a legitimate and substantial business justification for its conduct.”). This approach also does not change the General Counsel’s burden of proving the unfair labor practice, but rather extends to the employer something akin to an affirmative defense that it has the burden of sustaining to overcome the presumption that a given work rule is unlawful.And allocating this burden to the employer is sensible given that the employer is in the best position to explain its legitimate and substantial business interest, how its rule advances that interest, and why a more narrowly tailored rule would fail to advance that interest.

[C.]{.casesubsection}

Having rescinded the standard adopted in _Boeing_ and revised in _LA Specialty Produce_, we necessarily reject those decisions and their progeny, including the categorical holding that the Board has made to find certain types of work rules always lawful to maintain. Instead of that rigid--indeed, arbitrary--categorical approach, we return to a case-by-case approach, which examines the specific language of particular rules and the employer interests actually invoked to justify them.

The primary problem with _Boeing_’s categorical approach is that it was regularly applied to designate all rules of a generalized type as always lawful to maintain, no matter their specific wording, the specific industry or workplace in which the employer maintained the rule, the specific employer interests that the rule was supposed to advance, or any number of context-specific factors that may have arisen in a particular case. _Boeing_ itself exemplifies the arbitrary nature of this categorical approach.

In _Boeing_, the employer was “one of the country’s most prominent defense contractors.” It maintained a rule that, absent a manager-approved business need and a permit issued by its security department, prohibited employees’ use of the camera features of electronic devices (like smartphones) on all company property. Although the Board in _Boeing_ cursorily labeled the adverse impact of this ““no camera” rule on employees’ exercise of Section 7 rights “comparatively slight” (ignoring the importance of photo or video documentation of unfair labor practices, protected concerted activity, and the like), it at least acknowledged that the rule infringed on employees’ exercise of their rights. Yet in applying its balancing test, the _Boeing_ Board found that the employer’s interests advanced by the rule outweighed the adverse impact on employee rights and so deemed the rule lawful to maintain. 

The employer interests advanced by the rule included: serving as an integral component of _Boeing_’s security protocols, “which were necessary to maintain _Boeing_’s accreditation as a federal contractor to perform classified work for the United States Government”; furnishing “a fail-safe to ensure that classified information will not be released outside of _Boeing_ in the event that such information finds its way into a non-classified area”; playing “a key role in ensuring that _Boeing Co._ complies with its federally mandated duty to prevent the disclosure of export-controlled information,” including “‘sensitive equipment, software and technology,’ the export of which is controlled by the federal government ‘as a means to promote our national security and foreign policy objectives'”; mitigating “documented” instances of “foreign powers” trying to steal _Boeing_’s proprietary technology; and limiting “the risk”--in light of _Boeing_’s “documented evidence” of “surveillance by potentially hostile actors”--“of _Boeing_ becoming a target of terrorist attack.” 

All of these interests that pertained to _Boeing_ are obviously unique to “one of the country’s most prominent defense contractors.” They have no relevance to the overwhelming majority of employers who do not deal in “classified” information, “export-controlled information,” and the like. Despite that fact, and remarkably without any further justification, the _Boeing_ Board put “no camera” and “no recording” rules “into Category 1,” meaning that all rules of that type are always lawful for every employer to maintain. In other words, every employer can lawfully maintain a “no camera” or “no recording” rule that the _Boeing_ Board admitted chills the exercise of Section 7 rights even if--as will be true for the overwhelming majority of them--those employers share none of the interests that justified _Boeing_’s maintenance of its rule. _Boeing_ thus reflects an arbitrary and capricious approach to the analysis of work rules. We reject it.

In _LA Specialty Produce_, in turn, the Board purported to offer “points of clarification” for the categorical approach. The primary point of purported clarification was to state that _Boeing_’s “Category 1” balancing test involves measuring “general” employer interests advanced by a rule against the rule’s interference with employees’ exercise of Section 7 rights. While there may be some legitimate interests common to all employers at all times, and that are always entitled to the same weight in a balancing analysis, it is easy to see how such a broad approach can lead to giving employer interests in a particular case too much weight with too little justification, unnecessarily sacrificing Section 7 rights in the process. In endorsing “general” employer interests, _LA Specialty Produce_ clearly did not effectively limit _Boeing_’s most obvious analytical flaw by leaving undisturbed _Boeing_’s holding that all “no camera” and “no recording” rules are always lawful. Confirmation of that fact is apparent in the Board’s post-_LA Specialty Produce_ decisions. For instance, in _AT&T Mobility, LLC_, the Board found a cellphone retail employer’s rule that prohibited employees from recording conversations lawful to maintain “as a matter of law” simply because it was a “no recording” rule and thus categorically lawful to maintain. It did not matter that a cellphone retailer does not deal with classified information, export controls, documented threats of foreign interference, and the like, despite that those were the very interests that justified the categorical lawfulness of the “no camera” rule in _Boeing_. We believe that a return to “case-specific justification” better serves the purposes of the Act.

_Boeing_’s categorical approach is also hamstrung by its elimination of any consideration of the specific language or context of particular rules. Under _Boeing_, this was done by, in a single case, analyzing whether one particular rule--including its specific wording and context--chills employees’ exercise of Section 7 rights, concluding that it does not, and then broadly declaring lawful all similar rules of that general type, regardless of the specific language or context of any of those purportedly similar rules.

Our return to a case-specific approach is intended to remedy the obvious problems with _Boeing_’s categorical approach. In order to consider all important aspects of the problem posed by potentially overbroad work rules, the Board should examine the specific wording of the rule, the specific industry and workplace context in which it is maintained, the specific employer interests it may advance, and the specific statutory rights it may infringe. The case-by-case approach will not sacrifice clarity and predictability for regulated parties. As is always the norm, the Board will aim to ensure that like cases will be decided alike. The nearer the wording of a specific rule is to a rule assessed in a prior case, or the nearer the workplace context or employer interests are to those factors previously considered, the more likely the Board’s determination of the rule’s legality will be the same. As a consequence, more predictable outcomes will emerge over time. For instance, many of the Board’s core pre-_Lafayette Park_ work-rules holdings--such as those concerning maintenance of a “no solicitation” rule--that _Boeing_ did not overrule and that we maintain, describe generally applicable parameters for assessing certain types of rules. But that process should not be short-circuited, as the Board plainly did in applying _Boeing_. Put somewhat differently, consistent with the Act, predictability and certainty cannot be achieved simply by giving employers broad authority to adopt work rules and by correspondingly shrinking the scope of Section 7.

[III.]{.casesection}

In this case, the General Counsel alleges that the Respondent unlawfully maintained overbroad work rules governing personal conduct, conflicts of interest, and confidentiality of harassment complaints. Applying _Boeing_ and its progeny, the judge determined that maintenance of those rules was unlawful. Having overruled those decisions, we do not review the judge’s application of them. Instead, to allow the parties an opportunity to present arguments and introduce any relevant evidence under the new standard announced today, we remand this case to the judge for further proceedings consistent with this decision.