# Work-Related Injuries and Illness

## Occupational Health & Safety Act

### Occupational Safety & Health Act, 29 U.S.C. § 641 et seq.

::: {.aside}
See Also, [Occupational Safety & Health Administration regulations](https://www.law.cornell.edu/cfr/text/29/chapter-XVII), 29 CFR chap. XVII.
:::

::: {.legalcode}

#### § 651--Congressional statement of findings and declaration of purpose and policy

(a\) The Congress finds that personal injuries and illnesses arising out of work situations impose a substantial burden upon, and are a hindrance to, interstate commerce in terms of lost production, wage loss, medical expenses, and disability compensation payments.

(b\) The Congress declares it to be its purpose and policy, through the exercise of its powers to regulate commerce among the several States and with foreign nations and to provide for the general welfare, to assure so far as possible every working man and woman in the Nation safe and healthful working conditions and to preserve our human resources—

- (1\) by encouraging employers and employees in their efforts to reduce the number of occupational safety and health hazards at their places of employment, and to stimulate employers and employees to institute new and to perfect existing programs for providing safe and healthful working conditions;
- (2\) by providing that employers and employees have separate but dependent responsibilities and rights with respect to achieving safe and healthful working conditions;
- (3\) by authorizing the Secretary of Labor to set mandatory occupational safety and health standards applicable to businesses affecting interstate commerce, and by creating an Occupational Safety and Health Review Commission for carrying out adjudicatory functions under this chapter;

#### § 654--Duties of employers and employees

(a\) Each employer—

- (1\) shall furnish to each of his employees employment and a place of employment which are free from recognized hazards that are causing or are likely to cause death or serious physical harm to his employees;
- (2\) shall comply with occupational safety and health standards promulgated under this chapter.

(b\) Each employee shall comply with occupational safety and health standards and all rules, regulations, and orders issued pursuant to this chapter which are applicable to his own actions and conduct.

#### § 655--Standards

**(a\) Promulgation by Secretary of national consensus standards and established Federal standards;**

[T]he Secretary shall, [ … ], by rule promulgate as an occupational safety or health standard any national consensus standard, and any established Federal standard, unless he determines that the promulgation of such a standard would not result in improved safety or health for specifically designated employees. In the event of conflict among any such standards, the Secretary shall promulgate the standard which assures the greatest protection of the safety or health of the affected employees.

#### § 657--Inspections, investigations, and recordkeeping

**(a\) Authority of Secretary to enter, inspect, and investigate places of employment; time and manner**

In order to carry out the purposes of this chapter, the Secretary, upon presenting appropriate credentials to the owner, operator, or agent in charge, is authorized—

- (1\) to enter without delay and at reasonable times any factory, plant, establishment, construction site, or other area, workplace or environment where work is performed by an employee of an employer; and
- (2\) to inspect and investigate during regular working hours and at other reasonable times, and within reasonable limits and in a reasonable manner, any such place of employment and all pertinent conditions, structures, machines, apparatus, devices, equipment, and materials therein, and to question privately any such employer, owner, operator, agent, or employee.

**(f\) Request for inspection by employees or representative of employees; [ … ]**

- (1\) Any employees or representative of employees who believe that a violation of a safety or health standard exists that threatens physical harm, or that an imminent danger exists, may request an inspection by giving notice to the Secretary or his authorized representative of such violation or danger. [ … ] If upon receipt of such notification the Secretary determines there are reasonable grounds to believe that such violation or danger exists, he shall make a special inspection in accordance with the provisions of this section as soon as practicable, to determine if such violation or danger exists. If the Secretary determines there are no reasonable grounds to believe that a violation or danger exists he shall notify the employees or representative of the employees in writing of such determination.
- (2\) Prior to or during any inspection of a workplace, any employees or representative of employees employed in such workplace may notify the Secretary or any representative of the Secretary responsible for conducting the inspection, in writing, of any violation of this chapter which they have reason to believe exists in such workplace. The Secretary shall, by regulation, establish procedures for informal review of any refusal by a representative of the Secretary to issue a citation with respect to any such alleged violation and shall furnish the employees or representative of employees requesting such review a written statement of the reasons for the Secretary’s final disposition of the case.

#### § 658--Citations

**(a\) Authority to issue; grounds; contents; notice in lieu of citation for de minimis violations**

If, upon inspection or investigation, the Secretary or his authorized representative believes that an employer has violated a requirement of section 654 of this title, of any standard, rule or order promulgated pursuant to section 655 of this title, or of any regulations prescribed pursuant to this chapter, he shall with reasonable promptness issue a citation to the employer. Each citation shall be in writing and shall describe with particularity the nature of the violation, including a reference to the provision of the chapter, standard, rule, regulation, or order alleged to have been violated. In addition, the citation shall fix a reasonable time for the abatement of the violation. The Secretary may prescribe procedures for the issuance of a notice in lieu of a citation with respect to de minimis violations which have no direct or immediate relationship to safety or health.

#### § 659--Enforcement procedures

**(a\) Notification of employer of proposed assessment of penalty subsequent to issuance of citation;**

If, after an inspection or investigation, the Secretary issues a citation under section 658(a) of this title, he shall, within a reasonable time after the termination of such inspection or investigation, notify the employer by certified mail of the penalty, if any, proposed to be assessed under section 666 of this title and that the employer has fifteen working days within which to notify the Secretary that he wishes to contest the citation or proposed assessment of penalty. If, within fifteen working days from the receipt of the notice issued by the Secretary the employer fails to notify the Secretary that he intends to contest the citation or proposed assessment of penalty, and no notice is filed by any employee or representative of employees under subsection (c) within such time, the citation and the assessment, as proposed, shall be deemed a final order of the Commission and not subject to review by any court or agency.

**(b\) Notification of employer of failure to correct in allotted time period violation for which citation was issued and proposed assessment of penalty for failure to correct;**

If the Secretary has reason to believe that an employer has failed to correct a violation for which a citation has been issued within the period permitted for its correction (which period shall not begin to run until the entry of a final order by the Commission in the case of any review proceedings under this section initiated by the employer in good faith and not solely for delay or avoidance of penalties), the Secretary shall notify the employer by certified mail of such failure and of the penalty proposed to be assessed under section 666 of this title by reason of such failure, and that the employer has fifteen working days within which to notify the Secretary that he wishes to contest the Secretary’s notification or the proposed assessment of penalty. If, within fifteen working days from the receipt of notification issued by the Secretary, the employer fails to notify the Secretary that he intends to contest the notification or proposed assessment of penalty, the notification and assessment, as proposed, shall be deemed a final order of the Commission and not subject to review by any court or agency.

**(c\) Advisement of Commission by Secretary of notification of contest by employer of citation or notification or of filing of notice by any employee or representative of employees; hearing by Commission; orders of Commission and Secretary; rules of procedure**

If an employer notifies the Secretary that he intends to contest a citation issued under section 658(a) of this title or notification issued under subsection (a) or (b) of this section, or if, within fifteen working days of the issuance of a citation under section 658(a) of this title, any employee or representative of employees files a notice with the Secretary alleging that the period of time fixed in the citation for the abatement of the violation is unreasonable, the Secretary shall immediately advise the Commission of such notification, and the Commission shall afford an opportunity for a hearing [ … ]. The Commission shall thereafter issue an order, based on findings of fact, affirming, modifying, or vacating the Secretary’s citation or proposed penalty, or directing other appropriate relief, and such order shall become final thirty days after its issuance. Upon a showing by an employer of a good faith effort to comply with the abatement requirements of a citation, and that abatement has not been completed because of factors beyond his reasonable control, the Secretary, after an opportunity for a hearing as provided in this subsection, shall issue an order affirming or modifying the abatement requirements in such citation. The rules of procedure prescribed by the Commission shall provide affected employees or representatives of affected employees an opportunity to participate as parties to hearings under this subsection.

#### § 660--Judicial review

**(c\) Discharge or discrimination against employee for exercise of rights under this chapter; prohibition; procedure for relief**

- (1\) No person shall discharge or in any manner discriminate against any employee because such employee has filed any complaint or instituted or caused to be instituted any proceeding under or related to this chapter or has testified or is about to testify in any such proceeding or because of the exercise by such employee on behalf of himself or others of any right afforded by this chapter.
- (2\) Any employee who believes that he has been discharged or otherwise discriminated against by any person in violation of this subsection may, within thirty days after such violation occurs, file a complaint with the Secretary alleging such discrimination. Upon receipt of such complaint, the Secretary shall cause such investigation to be made as he deems appropriate. If upon such investigation, the Secretary determines that the provisions of this subsection have been violated, he shall bring an action in any appropriate United States district court against such person. In any such action the United States district courts shall have jurisdiction, for cause shown to restrain violations of paragraph (1) of this subsection and order all appropriate relief including rehiring or reinstatement of the employee to his former position with back pay.
- (3\) Within 90 days of the receipt of a complaint filed under this subsection the Secretary shall notify the complainant of his determination under paragraph (2) of this subsection.

####  § 666--Civil and criminal penalties

**(a\) Willful or repeated violation**

Any employer who willfully or repeatedly violates the requirements of section 654 of this title, any standard, rule, or order promulgated pursuant to section 655 of this title, or regulations prescribed pursuant to this chapter may be assessed a civil penalty of not more than $70,000 for each violation, but not less than $5,000 for each willful violation.

**(b\) Citation for serious violation**

Any employer who has received a citation for a serious violation of the requirements of section 654 of this title, of any standard, rule, or order promulgated pursuant to section 655 of this title, or of any regulations prescribed pursuant to this chapter, shall be assessed a civil penalty of up to $7,000 for each such violation.

**(c\) Citation for violation determined not serious**

Any employer who has received a citation for a violation of the requirements of section 654 of this title, of any standard, rule, or order promulgated pursuant to section 655 of this title, or of regulations prescribed pursuant to this chapter, and such violation is specifically determined not to be of a serious nature, may be assessed a civil penalty of up to $7,000 for each such violation.

**(d\) Failure to correct violation**

Any employer who fails to correct a violation for which a citation has been issued under section 658(a) of this title within the period permitted for its correction [ … ], may be assessed a civil penalty of not more than $7,000 for each day during which such failure or violation continues.

**(e\) Willful violation causing death to employee**

Any employer who willfully violates any standard, rule, or order promulgated pursuant to section 655 of this title, or of any regulations prescribed pursuant to this chapter, and that violation caused death to any employee, shall, upon conviction, be punished by a fine of not more than $10,000 or by imprisonment for not more than six months, or by both; except that if the conviction is for a violation committed after a first conviction of such person, punishment shall be by a fine of not more than $20,000 or by imprisonment for not more than one year, or by both.

**(f\) Giving advance notice of inspection**

Any person who gives advance notice of any inspection to be conducted under this chapter, without authority from the Secretary or his designees, shall, upon conviction, be punished by a fine of not more than $1,000 or by imprisonment for not more than six months, or by both.

**(g\) False statements, representations or certification**

Whoever knowingly makes any false statement, representation, or certification in any application, record, report, plan, or other document filed or required to be maintained pursuant to this chapter shall, upon conviction, be punished by a fine of not more than $10,000, or by imprisonment for not more than six months, or by both.

**(i\) Violation of posting requirements**

Any employer who violates any of the posting requirements, as prescribed under the provisions of this chapter, shall be assessed a civil penalty of up to $7,000 for each violation.

**(j\) Authority of Commission to assess civil penalties**

The Commission shall have authority to assess all civil penalties provided in this section, giving due consideration to the appropriateness of the penalty with respect to the size of the business of the employer being charged, the gravity of the violation, the good faith of the employer, and the history of previous violations.

**(k\) Determination of serious violation**

For purposes of this section, a serious violation shall be deemed to exist in a place of employment if there is a substantial probability that death or serious physical harm could result from a condition which exists, or from one or more practices, means, methods, operations, or processes which have been adopted or are in use, in such place of employment unless the employer did not, and could not with the exercise of reasonable diligence, know of the presence of the violation.

:::

### Seaworld of Florida, LLC v. Perez, 748 F.3d 1202 (D.C. Cir. 2014)

SeaWorld of Florida, LLC, operates a theme park in Orlando, Florida, that is designed to entertain and educate paying customers by displaying and studying marine animals. Following the death of one of SeaWorld's trainers while working in close contact with a killer whale during a performance, the Occupational Safety and Health Review Commission found that SeaWorld had violated the general duty clause, § 5(a)(1) of the Occupational Safety and Health Act of 1970, 29 U.S.C. § 654(a)(1), by exposing the trainers to recognized hazards when working in close contact with killer whales during performances, and that the abatement procedures recommended by the Secretary of Labor were feasible. SeaWorld challenges the order with respect to one citation. Concluding its challenges are unpersuasive, we deny the petition for review.

#### I.

On February 24, 2010, SeaWorld trainer Dawn Brancheau was interacting with Tilikum, a killer whale, during a performance before a live audience in a pool at Shamu Stadium in Orlando. Ms. Brancheau was reclined on her back on a platform a few inches below the water surface. Tilikum was supposed to mimic her behavior by rolling over. Instead, the killer whale grabbed her and pulled her off the platform into the pool, refusing to release her. She suffered traumatic injuries and drowned as a result of Tilikum's actions.

The Secretary of Labor issued three citations to SeaWorld after an investigation by an Occupational Safety and Health Administration ("OSHA") compliance officer. Only the second citation is at issue. It alleged two instances of a "willful" violation of the general duty clause for exposing animal trainers to the recognized hazards of drowning or injury when working with killer whales during performances. The first instance related to animal trainers working with Tilikum being exposed to "struck-by and drowning hazards" by being "allowed unprotected contact with Tilikum" while conducting "'drywork' performances on pool ledges, slideouts and platforms." In SeaWorld's terms, when trainers are out of the pool or on submerged ledges called "slideouts" in water no deeper than their knees, their interactions with killer whales are called "drywork." Any interaction in deeper water is "waterwork." According to the Secretary, "among other methods, one feasible and acceptable means of abatement would be to not allow animal trainers to have any contact with Tilikum unless they are protected by a physical barrier." The second instance concerned animal trainers working with killer whales other than Tilikum who were exposed to struck-by and drowning hazards when they were "allowed to engage in 'waterwork' and 'drywork' performances with the killer whales without adequate protection." The Secretary listed as possible abatement methods "prohibiting animal trainers from working with killer whales, including 'waterwork' or 'dry work,' unless the trainers are protected through the use of physical barriers or through the use of decking systems, oxygen supply systems or other engineering or administrative controls that provide the same or greater level of protection for the trainers." The Secretary proposed a penalty of $70,000.

Following an evidentiary hearing, the Administrative Law Judge ("ALJ") found that on February 24, 2010, a "performance" was still in progress when Tilikum seized Ms. Brancheau and pulled her into the pool water. The ALJ found that the first and third elements of a violation of the general duty clause—existence of a workplace condition presenting a hazard that likely caused death or serious physical harm—were established by the events on February 24, 2010: Ms. Brancheau's death demonstrated that close contact with killer whales was a hazard likely to cause death or serious injury. Based on evidence regarding three previous deaths involving killer whales (beginning in 1991 with Tilikum), SeaWorld's written training manuals and safety lectures as implemented specifically to Tilikum, and SeaWorld's incident reports, the ALJ found that the Secretary had established by "abundant" record evidence that "SeaWorld recognized the hazard created when its trainers worked in close contact with Tilikum during drywork performances," satisfying the second element of a violation. Further, the ALJ found that evidence, including SeaWorld's incident reports, established that SeaWorld recognized the hazard when trainers worked in close contact with other killer whales; SeaWorld's statistics regarding the predictability of killer whale behavior, on the other hand, were unpersuasive because not based on rigorous, scientific data. The ALJ concluded that SeaWorld's claim that "it was unaware working with killer whales presents a recognized hazard is difficult to reconcile with numerous comments made over the years by SeaWorld management personnel, including two corporate curators of animal training whose comments were documented and circulated among all of the SeaWorld parks." 

The ALJ also found that the Secretary had established the fourth element of a violation: feasible abatement of the hazard for trainers working with Tilikum and other killer whales. SeaWorld had not argued, the ALJ noted, that it is infeasible to install barriers or implement a minimum distance between trainers and whales, but rather "considers the extensive safety training of its trainers and the operant conditioning of its killer whales to be an adequate means of abatement that materially reduces the hazard the killer whales present to the trainers." The ALJ found the Secretary had met her burden to show SeaWorld's safety program is inadequate. Despite SeaWorld's contention that its operant conditioning "materially reduces the recognized hazard," the ALJ concluded that "SeaWorld's reliance on its trainers to recognize precursors and prevent unpredictable behavior by the killer whales runs counter to the requirements of the Act. 'The duty to comply with section 5(a)(1) rests with the employer.'" The ALJ further concluded that "SeaWorld holds trainers to a near—impossible standard set by upper management, who engage in a form of Monday morning quarterbacking." Additionally, the ALJ noted that SeaWorld had already implemented the means of abatement recommended by the Secretary for trainers working with Tilikum—namely, maintaining a minimum distance from the killer whale, or imposing a physical barrier between the killer whale and trainers—and concluded the same or similar abatement involving other killer whales was no less feasible.

Although crediting the testimony of a SeaWorld curator of animal training regarding the educational and inspirational justification for continuing "waterwork" with killer whales, the ALJ concluded that justification "must be measured against the risk incurred by allowing trainers to interact closely with killer whales." Observing that OSHA has "no specific standard" regulating employees working in close contact with killer whales, and that the Secretary had presented no evidence SeaWorld had a "heightened awareness of the illegality of its conduct" or manifested "plain indifference to employee safety," the ALJ found that violations were "serious," not "willful," and imposed a fine of $7,000 for the general duty clause violation, emphasizing that his order was limited to show performances. SeaWorld unsuccessfully sought discretionary review by the Commission, whereupon the ALJ's decision and order became final.SeaWorld petitions for review of the general duty violation.

#### II.

The general duty clause, § 5(a)(1) of the Occupational Safety and Health Act, provides: "Each employer  shall furnish to each of his employees employment and a place of employment which are free from recognized hazards that are causing or are likely to cause death or serious physical harm to his employees." 29 U.S.C. § 654(a)(1). As explained by the House Committee on Education and Labor, "bearing in mind the fact that there is no automatic penalty for violation of the general duty, this clause enables the Federal Government to provide for the protection of employees who are working under such _unique_ circumstances that no standard has yet been enacted to cover this situation." In a seminal case this court, in turn, observed that "though novel in approach and sweeping in coverage, the legislation is no more drastic than the problem it aims to meet." Notwithstanding the "unqualified and absolute" textual imperative that the workplace be "free" of the recognized hazard, the court further observed that "Congress quite clearly did not intend the general duty clause to impose strict liability: The duty was to be an achievable one". So understood, the court held that "all preventable forms and instances of hazardous conduct must be entirely excluded from the workplace." 

"To establish a violation of the General Duty Clause, the Secretary must establish that: (1) an activity or condition in the employer's workplace presented a hazard to an employee, (2) either the employer or the industry recognized the condition or activity as a hazard, (3) the hazard was likely to or actually caused death or serious physical harm, and (4) a feasible means to eliminate or materially reduce the hazard existed." Tempering the range of potential remedies that might be imposed upon finding a violation of the clause, the court explained: "In other words, 'the _Secretary_ must prove that a reasonably prudent employer familiar with the circumstances of the industry would have protected against the hazard in the manner specified by the Secretary's citation."' 

SeaWorld contests only the second and fourth elements regarding recognized hazard and feasibility. In challenging the general duty citation, SeaWorld does not perforce contend that the Secretary of Labor or the Occupational Safety and Health Review Commission lack legal authority to require employers to provide a reasonably safe working environment for employees. Rather, SeaWorld takes issue with the interpretation by these officials of what constitutes a recognized hazard that would subject an employer to citation under the Occupational Safety and Health Act. First, SeaWorld contends that the finding that it exposed its employees to a "recognized hazard" is unsupported by substantial evidence. Second, it contends that "when some risk is inherent in a business activity, that risk cannot constitute a 'recognized hazard.'" Pet'r Br. at 33. Third, it contends that the ALJ's decision was based on unreliable expert testimony about the extent of killer whale predictability after SeaWorld's training and precautions. As regards the feasibility of physical barriers and minimum distances SeaWorld contends that the Secretary failed to prove feasible abatement methods (or that SeaWorld had already implemented these measures), and that the ALJ failed to consider evidence these abatement measures present additional hazards and erred because eliminating close contact changes the nature of a trainer's job. Finally, SeaWorld contends the general duty clause is unconstitutionally vague as applied because SeaWorld lacked fair notice of the Secretary's abatement measures.

The court must uphold the Commission's decision unless it is "arbitrary, capricious, an abuse of discretion, or otherwise not in accordance with law." The factual findings of the Commission, "if supported by substantial evidence on the record considered as a whole, shall be conclusive." 29 U.S.C. § 660(a). Under this standard, the court must "uphold Commission findings so long as there is 'such relevant evidence as a reasonable mind might accept as adequate to support a conclusion.'" Likewise, the court "must accept the ALJ's credibility determinations unless they are patently unsupportable." The court will "defer to the Secretary's interpretation of the Act and regulations, upholding such interpretations so long as they are consistent with the statutory language and otherwise reasonable." 

##### A.

Whether a work condition poses a recognized hazard is a question of fact. Substantial evidence supports the finding that "drywork" and "waterwork" with killer whales were recognized hazards. Tilikum is a 32-year-old male killer whale with known aggressive tendencies who in 1991 killed a whale trainer at a marine park in Vancouver, British Columbia. SeaWorld had established special protocols for Tilikum, which prohibited "waterwork" and, among other things, required non-killer whale personnel and guests to stay five feet behind pool walls or three feet from Tilikum's head, indicating that SeaWorld recognized the possibility of harm to people standing outside of the pool on land. Although "drywork" with Tilikum continued, SeaWorld limited it to a team of experienced trainers who used extra caution. The caution with which SeaWorld treated Tilikum even when trainers were poolside or on "slideouts" in the pool indicates that it recognized the hazard the killer whale posed, not that it considered its protocols rendered Tilikum safe.

As to other killer whales, SeaWorld suggests that close contact with these whales was not a recognized hazard because all whales behave differently and its incident reports help SeaWorld improve training. But SeaWorld's incident reports demonstrate that it recognized the danger its killer whales posed to trainers notwithstanding its protocols. At the time of Ms. Brancheau's death, seven killer whales were at the Orlando park. Even though SeaWorld had not recorded incident reports on all of its killer whales, a substantial portion of SeaWorld's killer whale population had at least one reported incident. The ALJ also relied on the many comments by SeaWorld management personnel, including corporate curators of animal training, who described the need for caution around killer whales generally, not only around certain killer whales. Killer whales bit trainers' body parts on several occasions (although not generally puncturing skin) and in 2006 a killer whale pulled a trainer underwater by the foot and submerged him repeatedly for approximately 10 minutes. Although this incident occurred during "waterwork," substantial evidence supports the finding with regard to "drywork" as well. On numerous occasions, trainers fell or were pulled into the water, as later happened with Tilikum and Ms. Brancheau, or killer whales lunged out of the water toward trainers. These incidents constitute substantial evidence to support the ALJ's finding that "drywork" was also a recognized hazard.

SeaWorld's position is that working with killer whales was not a recognized hazard because its training and safety program adequately controlled the risk. To train its killer whales, SeaWorld uses "operant conditioning" to reinforce desired behaviors with food or other rewards. It also trains its employees who work with killer whales to recognize particular behaviors that it calls "precursors," which indicate that the killer whales may act aggressively, and keeps detailed incident reports of when its killer whales had behaved aggressively or otherwise undesirably toward trainers, including pulling trainers into the pool. The Secretary presented evidence that the killer whales posed a hazard in spite of SeaWorld's safety measures. On multiple occasions, including the death of Ms. Brancheau, SeaWorld's incident reports indicated that the killer whales showed no immediate precursors of aggressive behavior or ignored SeaWorld's emergency procedures designed to make them cease aggressive behavior. Statements by SeaWorld managers do not indicate that SeaWorld's safety protocols and training made the killer whales safe; rather, they demonstrate SeaWorld's recognition that the killer whales interacting with trainers are dangerous and unpredictable and that even senior trainers can make mistakes during performances, and the managers repeatedly urged caution in working with the killer whales. The evidence thus supports the ALJ's finding that a recognized hazard existed, even beyond the impact of SeaWorld's safety protocols.

In relying on SeaWorld's safety program to establish a recognized hazard, the ALJ did not, as SeaWorld suggests, "invert the requirement of the General Duty Clause that the Secretary, 'as a threshold matter,' 'submit evidence proving that the methods undertaken by the employer to address the alleged hazard were inadequate.'" In the _Postal Service_ case, the Secretary alleged that letter carriers risked being hit by cars in dim or dark conditions and proposed carriers be required to wear reflective garments that complied with industry standards, but failed to show that carriers had been hit because of lack of visibility when wearing the reflective garments provided by their employer, or that the proposed reflective garments would have made a difference. Here, there was substantial record evidence that SeaWorld recognized its precautions were inadequate to prevent serious bodily harm or even death to its trainers and that the residual hazard was preventable.

The remedy imposed for SeaWorld's violations does not change the essential nature of its business. There will still be human interactions and performances with killer whales; the remedy will simply require that they continue with increased safety measures. SeaWorld itself has limited human interactions. After Ms. Brancheau's death in 2010, SeaWorld ceased "waterwork" with all of its killer whales. It also imposed distance between trainers and Tilikum during drywork and, to a lesser degree, between other killer whales and trainers during drywork. These self-imposed limitations are relevant to the assessment of which aspects of SeaWorld's business are essential and indicate that the Secretary's remedy will not eliminate any essential element. SeaWorld does not assert (and at oral argument disavowed) that a public perception of danger to its trainers is essential to its business. Nor has SeaWorld ever argued that limiting interactions in the way that the remedy requires would have a detrimental economic impact on its profits. And SeaWorld is, after all, a for-profit entity owned, at times relevant to the Commission proceedings, by the Blackstone Group, an investment firm.

_Pelron Corp.,_ 12 BNA OSHC 1833 (No. 82-388, 1986), on which SeaWorld relies, is inapposite. That case involved an enforcement action against a company that manufactured products by mixing, _inter alia,_ ethylene oxide. The ALJ had defined the alleged hazard as the "possibility" of accumulations of unreacted ethylene oxide, which the Commission found could never be prevented. Thus, impliedly, the only remedy would have been to close the plant. Here, the Secretary and the Commission could reasonably conclude that the danger to SeaWorld's trainers during performances from killer whales can be prevented by use of physical barriers and distance, and closing SeaWorld is not at issue. The hazard killer whales pose during performances is not "so idiosyncratic and implausible" that it cannot be considered preventable. SeaWorld controls its employees' access to and contact with its killer whales, unlike the employer in _Megawest Financial Inc.,_ 17 BNA OSHC 1337 (No. 93-2879, 1995) (ALJ), who could not prevent the potentially criminal, violent actions of third parties residing in the apartment buildings it managed. SeaWorld's reliance on the Commission's observation in _Pelron_ that "some industrial activities are by their very nature dangerous. To permit the normal activities in such an industry to be defined as a 'recognized hazard' within the meaning of section 5(a)(1) is to eliminate an element of the Secretary's burden of proof," is misplaced; the Commission was addressing the requirement that recognized hazards be "preventable" and "be defined in a way that identifies conditions or practices over which the employer can reasonably be expected to exercise control."

To the extent SeaWorld maintains that close contact is integral to cleaning and caring for their animals (_i.e.,_ "husbandry"), and that it was arbitrary and capricious to find a recognized hazard in the performance context but not in the husbandry context, its position is unfounded. Contact during husbandry was not at issue before the ALJ or the Commission. Regardless, although some aspects of husbandry may require close contact, according to SeaWorld's vice president for veterinary services, many procedures can be conducted in a medical pool with a lifting bottom that restricts the killer whale's mobility, or can be performed from poolside behind a short wall. In his opinion, notwithstanding performance-contact limitations, "SeaWorld is adequately caring for these animals to this day." 

SeaWorld's suggestion that because trainers "formally accepted and controlled their own exposure to risks," the hazard of close contact with killer whales cannot be recognized, contravenes Congress's decision to place the duty to ensure a safe and healthy workplace on the employer, not the employee. This court has long held "this duty is not qualified by such common law doctrines as assumption of risk, contributory negligence, or comparative negligence." SeaWorld's reliance on _Oil, Chemical & Atomic Workers International Union v. American Cyanamid Co.,_ 741 F.2d 444 (D.C.Cir.1984), is misplaced; the alleged hazard in that case was the employer's policy prohibiting women of childbearing age from working in high lead-exposure positions unless they had been surgically sterilized, and the court held that "the general duty clause does not apply to a policy as contrasted with a physical condition of the workplace." The court explained that the optional sterilization policy "does not affect employees while they are engaged in work or work-related activities." The potential harm to SeaWorld's trainers exists in their workplace and involves conditions over which SeaWorld has control.

The Secretary and the Commission could also reasonably determine that the remedy does not go to the essence of SeaWorld's productions. SeaWorld has had no "waterwork" performances since Ms. Brancheau's death in 2010, and it temporarily suspended "waterwork" after other incidents, such as the killing of a trainer by a killer whale in 2009 at a nonSeaWorld park in Spain. With distance and physical barriers between Tilikum and trainers during drywork, Tilikum can still perform almost the same behaviors performed when no barriers were present. The nature of SeaWorld's workplace and the unusual nature of the hazard to its employees performing in close physical contact with killer whales do not remove SeaWorld from its obligation under the General Duty Clause to protect its employees from recognized hazards.

##### C.

Substantial evidence supports the ALJ's findings that it was feasible for SeaWorld to abate the hazard to its employees by using barriers or minimum distance between trainers and killer whales, most notably because SeaWorld has implemented many of these measures on its own. When an employer has existing safety procedures, the burden is on the Secretary to show that those procedures are inadequate. The record evidence showed that SeaWorld's training and protocols did not prevent continued incidents, including the submerging and biting of one trainer in 2006, the killing of a trainer by a SeaWorld-trained and—owned killer whale in 2009 at an amusement park in Spain, and Ms. Brancheau's death in 2010. SeaWorld employees repeatedly acknowledged the unpredictability of its killer whales. This record evidence supports the ALJ's finding that existing protocols were inadequate to eliminate or materially reduce the hazard to SeaWorld's trainer employees performing with killer whales.

Abatement is "feasible" when it is "economically and technologically capable of being done." After Ms. Brancheau's death, SeaWorld required that all trainers work with Tilikum from a minimum distance or behind a barrier, and "waterwork" ceased with all of its killer whales. Implementing the ordered abatement is feasible because it would involve extending these practices to all killer whales and into the future. As the ALJ noted, SeaWorld had not argued the Secretary's proposed abatement was not economically or technologically feasible and had already implemented abatement for at least one of its killer whales and needed only to apply the same or similar protective contact measures it used with Tilikum to other killer whales. Consequently, the Secretary was not required to specify the precise manner in which abatement should be implemented. That the ALJ subsequently granted SeaWorld's request for a six-month extension of the abatement deadline, in view of SeaWorld's difficulty in scheduling two consulting experts, does not undermine the substantial evidence that SeaWorld could feasibly abate the hazard. SeaWorld does not dispute that the Secretary's abatement measures would materially reduce, if not eliminate, the hazard killer whales pose to its employees during performances. SeaWorld's use of protective contact with Tilikum, the three-year moratorium on "waterwork" after Ms. Brancheau's death, and repeated temporary cessation of "waterwork" with all killer whales or particular killer whales after other incidents support the finding that these changes were feasible and would not fundamentally alter the nature of the trainers' employment or SeaWorld's business.

To the extent SeaWorld suggests that veterinary care would be less effective and dangers to trainers from killer whales might increase absent close contact during performances, this issue is not properly before the court. SeaWorld's petition to the Commission for review did not include this issue, and SeaWorld presents no extraordinary circumstances to excuse its failure to do so. The court, therefore, lacks jurisdiction to consider it. 

##### D.

Facial challenges to the general duty clause have been rejected, and although an as-applied challenge would be possible, courts have long accommodated possible constitutional problems with fair notice in this context by interpreting "recognized hazard" only to include preventable hazards, or applying the clause only "when a reasonably prudent employer in the industry would have known that the proposed method of abatement was required," 

SeaWorld contends the general duty clause is unconstitutionally vague as applied because it lacked fair notice that the abatement measures would be required. But the administrative record establishes that SeaWorld did not lack fair notice because the hazard arising from trainers' close contact with killer whales in performance is preventable. Given evidence of continued incidents of aggressive behavior by killer whales toward trainers notwithstanding SeaWorld's training, operant conditioning practices, and emergency measures, SeaWorld could have anticipated that abatement measures it had applied after other incidents would be required. SeaWorld suggests that it was entitled to rely on the fact that the State of California's Division of Occupational Safety and Health ("Cal/OSHA") did not issue a citation for killer whale hazards after a killer whale bit and dragged a trainer underwater during a performance, puncturing the trainer's skin on both feet and breaking the metatarsal in his left foot. Cal/OSHA, however, inspected a different SeaWorld facility (in San Diego) and it, not the federal OSHA, resolved the citation question. In any event, the State inspection report included a warning on point. Although noting that SeaWorld had been following industry standards and was a recognized leader in training killer whales for performance, and that its employees were well-trained and followed emergency procedures, Cal/OSHA concluded that SeaWorld of San Diego's procedures "were not entirely effective at stopping the unwanted behaviors of the killer whale during this attack" and that "short of eliminating all of the water interactions with the killer whales, there is no guarantee that employees can be kept safe from an attack by the killer whale once they get in the water with the animal." 

### Whirlpool Corp. v. Marshall, 445 U.S. 1 (1980)

The Occupational Safety and Health Act of 1970 (Act) prohibits an employer from discharging or discriminating against any employee who exercises "any right afforded by" the Act. The Secretary of Labor (Secretary) has promulgated a regulation providing that, among the rights that the Act so protects, is the right of an employee to choose not to perform his assigned task because of a reasonable apprehension of death or serious injury coupled with a reasonable belief that no less drastic alternative is available. The question presented in the case before us is whether this regulation is consistent with the Act.

#### I

The petitioner company maintains a manufacturing plant in Marion, Ohio, for the production of household appliances. Overhead conveyors transport appliance components throughout the plant. To protect employees from objects that occasionally fall from these conveyors, the petitioner has installed a horizontal wire-mesh guard screen approximately 20 feet above the plant floor. This mesh screen is welded to angleiron frames suspended from the building's structural steel skeleton.

Maintenance employees of the petitioner spend several hours each week removing objects from the screen, replacing paper spread on the screen to catch grease drippings from the material on the conveyors, and performing occasional maintenance work on the conveyors themselves. To perform these duties, maintenance employees usually are able to stand on the iron frames, but sometimes find it necessary to step onto the steel mesh screen itself.

In 1973, the company began to install heavier wire in the screen because its safety had been drawn into question. Several employees had fallen partly through the old screen, and on one occasion an employee had fallen completely through to the plant floor below but had survived. A number of maintenance employees had reacted to these incidents by bringing the unsafe screen conditions to the attention of their foremen. The petitioner company's contemporaneous safety instructions admonished employees to step only on the angle-iron frames.

On June 28, 1974, a maintenance employee fell to his death through the guard screen in an area where the newer, stronger mesh had not yet been installed. Following this incident, the petitioner effectuated some repairs and issued an order strictly forbidding maintenance employees from stepping on either the screens or the angle-iron supporting structure. An alternative but somewhat more cumbersome and less satisfactory method was developed for removing objects from the screen. This procedure required employees to stand on power-raised mobile platforms and use hooks to recover the material.

On July 7, 1974, two of the petitioner's maintenance employees, Virgil Deemer and Thomas Cornwell, met with the plant maintenance superintendent to voice their concern about the safety of the screen. The superintendent disagreed with their view, but permitted the two men to inspect the screen with their foreman and to point out dangerous areas needing repair. Unsatisfied with the petitioner's response to the results of this inspection, Deemer and Cornwell met on July 9 with the plant safety director. At that meeting, they requested the name, address, and telephone number of a representative of the local office of the Occupational Safety and Health Administration (OSHA). Although the safety director told the men that they "had better stop and think about what they were doing," he furnished the men with the information they requested. Later that same day, Deemer contacted an official of the regional OSHA office and discussed the guard screen.

The next day, Deemer and Cornwell reported for the night shift at 10:45 p.m. Their foreman, after himself walking on some of the angle-iron frames, directed the two men to perform their usual maintenance duties on a section of the old screen. Claiming that the screen was unsafe, they refused to carry out this directive. The foreman then sent them to the personnel office, where they were ordered to punch out without working or being paid for the remaining six hours of the shift. The two men subsequently received written reprimands, which were placed in their employment files.

A little over a month later, the Secretary filed suit in the United States District Court for the Northern District of Ohio, alleging that the petitioner's actions against Deemer and Cornwell constituted discrimination in violation of § 11(c)(1) of the Act. As relief, the complaint prayed, _inter alia,_ that the petitioner be ordered to expunge from its personnel files all references to the reprimands issued to the two employees, and for a permanent injunction requiring the petitioner to compensate the two employees for the six hours of pay they had lost by reason of their disciplinary suspensions.

Following a bench trial, the District Court found that the regulation in question justified Deemer's and Cornwell's refusals to obey their foreman's order on July 10, 1974. The court found that the two employees had "refused to perform the cleaning operation because of a genuine fear of death or serious bodily harm," that the danger presented had been "real and not something which had existed only in the minds of the employees," that the employees had acted in good faith, and that no reasonable alternative had realistically been open to them other than to refuse to work. The District Court nevertheless denied relief, holding that the Secretary's regulation was inconsistent with the Act and therefore invalid.

The Court of Appeals for the Sixth Circuit reversed the District Court's judgment. Finding ample support in the record for the District Court's factual determination that the actions of Deemer and Cornwell had been justified under the Secretary's regulation, the appellate court disagreed with the District Court's conclusion that the regulation is invalid. It accordingly remanded the case to the District Court for further proceedings. We granted certiorari, because the decision of the Court of Appeals in this case conflicts with those of two other Courts of Appeals on the important question in issue. That question, as stated at the outset of this opinion, is whether the Secretary's regulation authorizing employee "self-help" in some circumstances, [[29 CFR § 1977.12(b)(2)](https://www.law.cornell.edu/cfr/text/29/1977.12), is permissible under the Act.

#### II

The Act itself creates an express mechanism for protecting workers from employment conditions believed to pose an emergent threat of death or serious injury. Upon receipt of an employee inspection request stating reasonable grounds to believe that an imminent danger is present in a workplace, OSHA must conduct an inspection. 29 U.S.C. § 657(f)(1). In the event this inspection reveals workplace conditions or practices that "could reasonably be expected to cause death or serious physical harm immediately or before the imminence of such danger can be eliminated through the enforcement procedures otherwise provided by" the Act, 29 U.S.C. § 662(a), the OSHA inspector must inform the affected employees and the employer of the danger and notify them that he is recommending to the Secretary that injunctive relief be sought. § 662(c). At this juncture, the Secretary can petition a federal court to restrain the conditions or practices giving rise to the imminent danger. By means of a temporary restraining order or preliminary injunction, the court may then require the employer to avoid, correct, or remove the danger or to prohibit employees from working in the area. § 662(a).

To ensure that this process functions effectively, the Act expressly accords to every employee several rights, the exercise of which may not subject him to discharge or discrimination. An employee is given the right to inform OSHA of an imminently dangerous workplace condition or practice and request that OSHA inspect that condition or practice. 29 U.S.C. § 657(f)(1). He is given a limited right to assist the OSHA inspector in inspecting the workplace, §§ 657(a)(2), (e), and (f)(2), and the right to aid a court in determining whether or not a risk of imminent danger in fact exists. See § 660(c)(1). Finally, an affected employee is given the right to bring an action to compel the Secretary to seek injunctive relief if he believes the Secretary has wrongfully declined to do so. § 662(d).

In the light of this detailed statutory scheme, the Secretary is obviously correct when he acknowledges in his regulation that, "as a general matter, there is no right afforded by the Act which would entitle employees to walk off the job because of potential unsafe conditions at the workplace." By providing for prompt notice to the employer of an inspector's intention to seek an injunction against an imminently dangerous condition, the legislation obviously contemplates that the employer will normally respond by voluntarily and speedily eliminating the danger. And in the few instances where this does not occur, the legislative provisions authorizing prompt judicial action are designed to give employees full protection in most situations from the risk of injury or death resulting from an imminently dangerous condition at the worksite.

As this case illustrates, however, circumstances may sometimes exist in which the employee justifiably believes that the express statutory arrangement does not sufficiently protect him from death or serious injury. Such circumstances will probably not often occur, but such a situation may arise when (1) the employee is ordered by his employer to work under conditions that the employee reasonably believes pose an imminent risk of death or serious bodily injury, and (2) the employee has reason to believe that there is not sufficient time or opportunity either to seek effective redress from his employer or to apprise OSHA of the danger.

Nothing in the Act suggests that those few employees who have to face this dilemma must rely exclusively on the remedies expressly set forth in the Act at the risk of their own safety. But nothing in the Act explicitly provides otherwise. Against this background of legislative silence, the Secretary has exercised his rulemaking power under 29 U.S.C. § 657(g)(2) and has determined that, when an employee in good faith finds himself in such a predicament, he may refuse to expose himself to the dangerous condition, without being subjected to "subsequent discrimination" by the employer.

The question before us is whether this interpretative regulation constitutes a permissible gloss on the Act by the Secretary, in light of the Act's language, structure, and legislative history. Our inquiry is informed by an awareness that the regulation is entitled to deference unless it can be said not to be a reasoned and supportable interpretation of the Act. 

##### A

The regulation clearly conforms to the fundamental objective of the Act—to prevent occupational deaths and serious injuries. The Act, in its preamble, declares that its purpose and policy is "to assure so far as possible every working man and woman in the Nation safe and healthful working conditions and to _preserve_ our human resources.." 29 U.S.C. § 651(b). 

To accomplish this basis purpose, the legislation's remedial orientation is prophylactic in nature. The Act does not wait for an employee to die or become injured. It authorizes the promulgation of health and safety standards and the issuance of citations in the hope that these will act to prevent deaths or injuries from ever occurring. It would seem anomalous to construe an Act so directed and constructed as prohibiting an employee, with no other reasonable alternative, the freedom to withdraw from a workplace environment that he reasonably believes is highly dangerous.

Moreover, the Secretary's regulation can be viewed as an appropriate aid to the full effectuation of the Act's "general duty" clause. That clause provides that "each employer shall furnish to each of his employees employment and a place of employment which are free from recognized hazards that are causing or are likely to cause death or serious physical harm to his employees." 29 U.S.C. § 654(a)(1). As the legislative history of this provision reflects, it was intended itself to deter the occurrence of occupational deaths and serious injuries by placing on employers a mandatory obligation independent of the specific health and safety standards to be promulgated by the Secretary. Since OSHA inspectors cannot be present around the clock in every workplace, the Secretary's regulation ensures that employees will in all circumstances enjoy the rights afforded them by the "general duty" clause.

The regulation thus on its face appears to further the over-riding purpose of the Act, and rationally to complement its remedial scheme. In the absence of some contrary indication in the legislative history, the Secretary's regulation must, therefore, be upheld, particularly when it is remembered that safety legislation is to be liberally construed to effectuate the congressional purpose.

##### B

In urging reversal of the judgment before us, the petitioner relies primarily on two aspects of the Act's legislative history.

Representative Daniels of New Jersey sponsored one of several House bills that led ultimately to the passage of the Act. As reported to the House by the Committee on Education and Labor, the Daniels bill contained a section that was soon dubbed the "strike with pay" provision. This section provided that employees could request an examination by the Department of Health, Education, and Welfare (HEW) of the toxicity of any materials in their workplace. If that examination revealed a workplace substance that had "potentially toxic or harmful effects in such concentration as used or found," the employer was given 60 days to correct the potentially dangerous condition. Following the expiration of that period, the employer could not require that an employee be exposed to toxic concentrations of the substance unless the employee was informed of the hazards and symptoms associated with the substance, the employee was instructed in the proper precautions for dealing with the substance, and the employee was furnished with personal protective equipment. If these conditions were not met, an employee could "absent himself from such risk of harm for the period necessary to avoid such danger without loss of regular compensation for such period."

This provision encountered stiff opposition in the House. Representative Steiger of Wisconsin introduced a substitute bill containing no "strike with pay" provision. In response, Representative Daniels offered a floor amendment that, among other things, deleted his bill's "strike with pay" provision.He suggested that employees instead be afforded the right to request an immediate OSHA inspection of the premises, a right which the Steiger bill did not provide. The House ultimately adopted the Steiger bill.

The bill that was reported to and, with a few amendments, passed by the Senate never contained a "strike with pay" provision. It did, however, give employees the means by which they could request immediate Labor Department inspections. These two characteristics of the bill were underscored on the floor of the Senate by Senator Williams, the bill's sponsor.

After passage of the Williams bill by the Senate, it and the Steiger bill were submitted to a Conference Committee. There, the House acceded to the Senate bill's inspection request provisions.

The petitioner reads into this legislative history a congressional intent incompatible with an administrative interpretation of the Act such as is embodied in the regulation at issue in this case. The petitioner argues that Congress' overriding concern in rejecting the "strike with pay" provision was to avoid giving employees a unilateral authority to walk off the job which they might abuse in order to intimidate or harass their employer. Congress deliberately chose instead, the petitioner maintains, to grant employees the power to request immediate administrative inspections of the workplace which could in appropriate cases lead to coercive judicial remedies. As the petitioner views the regulation, therefore, it gives to workers precisely what Congress determined to withhold from them.

We read the legislative history differently. Congress rejected a provision that did not concern itself at all with conditions posing real and immediate threats of death or severe injury. The remedy which the rejected provision furnished employees could have been invoked only after 60 days had passed following HEW's inspection and notification that improperly high levels of toxic substances were present in the workplace. Had that inspection revealed employment conditions posing a threat of imminent and grave harm, the Secretary of Labor would presumably have requested, long before expiration of the 60-day period, a court injunction pursuant to other provisions of the Daniels bill. Consequently, in rejecting the Daniels bill's "strike with pay" provision, Congress was not rejecting a legislative provision dealing with the highly perilous and fast-moving situations covered by the regulation now before us.

It is also important to emphasize that what primarily troubled Congress about the Daniels bill's "strike with pay" provision was its requirement that employees be paid their regular salary after having properly invoked their right to refuse to work under the section. It is instructive that virtually every time the issue of an employee's right to absent himself from hazardous work was discussed in the legislative debates, it was in the context of the employee's right to continue to receive his usual compensation.

When it rejected the "strike with pay" concept, therefore, Congress very clearly meant to reject a law unconditionally imposing upon employers an obligation to continue to pay their employees their regular paychecks when they absented themselves from work for reasons of safety. But the regulation at issue here does not require employers to pay workers who refuse to perform their assigned tasks in the face of imminent danger. It simply provides that in such cases the employer may not "discriminate" against the employees involved. An employer "discriminates" against the employee only when he treats that employee less favorably than he treats others similarly situated.

The second aspect of the Act's legislative history upon which the petitioner relies is the rejection by Congress of provisions contained in both the Daniels and the Williams bills that would have given Labor Department officials, in imminent-danger situations, the power temporarily to shut down all or part of an employer's plant. These provisions aroused considerable opposition in both Houses of Congress. The hostility engendered in the House of Representatives led Representative Daniels to delete his version of the provision in proposing amendments to his original bill. The Steiger bill that ultimately passed the House gave the Labor Department no such authority. The Williams bill, as approved by the Senate, did contain an administrative shutdown provision, but the Conference Committee rejected this aspect of the Senate bill.

The petitioner infers from these events a congressional will hostile to the regulation in question here. The regulation, the petitioner argues, provides employees with the very authority to shut down an employer's plant that was expressly denied a more expert and objective United States Department of Labor.

As we read the pertinent legislative history, however, the petitioner misconceives the thrust of Congress' concern. Those in Congress who prevented passage of the administrative shutdown provisions in the Daniels and Williams bills were opposed to the unilateral authority those provisions gave to federal officials, without any judicial safeguards, drastically to impair the operation of an employer's business. Congressional opponents also feared that the provisions might jeopardize the Government's otherwise neutral role in labor-management relations.

Neither of these congressional concerns is implicated by the regulation before us. The regulation accords no authority to Government officials. It simply permits private employees of a private employer to avoid workplace conditions that they believe pose grave dangers to their own safety. The employees have no power under the regulation to order their employer to correct the hazardous condition or to clear the dangerous workplace of others. Moreover, any employee who acts in reliance on the regulation runs the risk of discharge or reprimand in the event a court subsequently finds that he acted unreasonably or in bad faith. The regulation, therefore, does not remotely resemble the legislation that Congress rejected.

##### C

For these reasons we conclude that 29 CFR § 1977.12(b)(2) was promulgated by the Secretary in the valid exercise of his authority under the Act. Accordingly, the judgment of the Court of Appeals is affirmed.

## Workers' Compensation 

### North Carolina Workers' Compensation Act, N.C. Gen. Stat. chap. 97, art. 1

::: {.legalcode}

#### § 97-2. Definitions.

When used in this Article, unless the context otherwise requires:

- (6\) Injury.--"Injury and personal injury" shall mean only injury by accident arising out of and in the course of the employment, and shall not include a disease in any form, except where it results naturally and unavoidably from the accident. With respect to back injuries, however, where injury to the back arises out of and in the course of the employment and is the direct result of a specific traumatic incident of the work assigned, "injury by accident" shall be construed to include any disabling physical injury to the back arising out of and causally related to such incident. Injury shall include breakage or damage to eyeglasses, hearing aids, dentures, or other prosthetic devices which function as part of the body; provided, however, that eyeglasses and hearing aids will not be replaced, repaired, or otherwise compensated for unless injury to them is incidental to a compensable injury.

#### § 97-3. Presumption that all employers and employees have come under provisions of Article.

[E]very employer and employee, as hereinbefore defined and except as herein stated, shall be presumed to have accepted the provisions of this Article respectively to pay and accept compensation for personal injury or death by accident arising out of and in the course of his employment and shall be bound thereby.

#### § 97-5. Presumption as to contract of service.

Every contract of service between any employer and employee covered by this Article, written or implied, now in operation or made or implied prior to July 1, 1929, shall, after that date, be presumed to continue, subject to the provisions of this Article; and every such contract made subsequent to that date shall be presumed to have been made subject to the provisions of this Article.

#### § 97-10.1. Other rights and remedies against employer excluded.

If the employee and the employer are subject to and have complied with the provisions of this Article, then the rights and remedies herein granted to the employee, his dependents, next of kin, or personal representative shall exclude all other rights and remedies of the employee, his dependents, next of kin, or representative as against the employer at common law or otherwise on account of such injury or death. 

#### § 97-10.2.  Rights under Article not affected by liability of third party; rights and remedies against third parties.

(a\) The right to compensation and other benefits under this Article for disability, disfigurement, or death shall not be affected by the fact that the injury or death was caused under circumstances creating a liability in some person other than the employer to pay damages therefor, such person hereinafter being referred to as the "third party." The respective rights and interests of the employee-beneficiary under this Article, the employer, and the employer's insurance carrier, if any, in respect of the common-law cause of action against such third party and the damages recovered shall be as set forth in this section.

:::

### McGrady v. Olsten Corp., 583 S.E.2d 371 (N.C. Ct. App. 2003)

Defendants (Olsten Corporation and ITT Specialty Risk Services, Inc.) appeal from a divided opinion of the Industrial Commission, awarding plaintiff (Alice McGrady) medical benefits and temporary total disability. We affirm.

The factual background of this appeal is summarized as follows: Plaintiff was fifty years old at the time of the hearing and had an eighth grade education. In 1994, she completed the course required for certification as a certified nursing assistant (CNA), and was employed by defendant as a CNA. As a CNA, plaintiff provided in-home care for patients requiring assistance with daily living. In July, 1999, plaintiff's only client was Ms. Withers, an elderly woman with limited physical abilities. Plaintiff assisted Ms. Withers with bathing, dressing, personal care, housekeeping, and meal preparation. In addition, plaintiff drove Ms. Withers to various places in the community and did her grocery shopping. Ms. Withers enjoyed fresh fruit, which plaintiff obtained for her from the local farmers market or at a grocery store.

Plaintiff's regular hours were from 6:00 a.m. until 3:30 p.m. On 26 July 1999 plaintiff arrived at her usual time and assisted Ms. Withers with breakfast. During breakfast, Ms. Withers asked plaintiff to take her dog "Footsie" out to the yard. Plaintiff testified she "usually took her out ... sometimes twice a day." While plaintiff was outside with Footsie, she noticed that Ms. Withers' pear tree had borne a pear. She had previously obtained fruit from Ms. Withers' peach tree without incident and decided to retrieve the pear for her and Ms. Withers to share. Plaintiff began to climb the tree; however, she soon realized that the pear was too high up for her to shake it out of the tree, so she started back down. As plaintiff was climbing back to the ground, she fell. Plaintiff was taken by ambulance to a hospital, where physicians determined that she had broken her back, suffering "50 percent compression fracture" of her spine, and resulting in "quite a bit of damage to the vertebral body." She was initially treated with pain medication and bed rest, until further examination revealed that plaintiff had both an "acute compression fracture" and a "burst fracture" of the spine. Accordingly, plaintiff's treating physician performed surgery on her vertebrae and implanted steel rods in her back. Despite the surgery, plaintiff continued to experience pain, and her physician testified at the hearing that it was unlikely that plaintiff could ever return to work, "even light duty." He also testified that plaintiff's injuries were caused by the fall from Ms. Withers' pear tree.

On 9 September 1999, plaintiff filed a claim for workers' compensation, which was denied by defendants on the basis that her injuries were not causally connected to her employment. A hearing was conducted before Deputy Commissioner Wanda Taylor on 17 April 2000, and on 5 October 2000 the deputy commissioner issued an opinion denying plaintiff's claim for workers' compensation. The opinion concluded that, although plaintiff's accident had proximately caused her injuries, the fall itself "was not an activity which a person so employed might reasonably do in employment such as plaintiff's." Plaintiff appealed to the Full Commission, which conducted a review of the record on 7 January 2002. On 18 April 2002, the Industrial Commission issued an opinion reversing the deputy commissioner and awarding plaintiff medical compensation and temporary total disability. The opinion concluded that plaintiff's attempt to get a pear from Ms. Withers' pear tree either was "within plaintiff's work duties" or was not a serious deviation from her job duties, and thus that plaintiff's injuries were compensable. One commissioner dissented on the basis that "climbing a pear tree was not a contemplated action of plaintiff's employment" and thus that there was "no causal relationship between plaintiff's injuries and ... her employment as an in-home caregiver." From this opinion and award, defendants appealed.

"The standard of appellate review of an opinion and award of the Industrial Commission in a workers' compensation case is whether there is any competent evidence in the record to support the Commission's findings of fact and whether these findings support the Commission's conclusions of law." Further, the Industrial Commission's findings of fact "are conclusive on appeal if supported by any competent evidence." "Thus, on appeal, this Court 'does not have the right to weigh the evidence and decide the issue on the basis of its weight. The court's duty goes no further than to determine whether the record contains any evidence tending to support the finding.'" "Even where there is competent evidence to the contrary, we must defer to the findings of the Commission where supported by any competent evidence. The Commission's findings of fact may only be set aside when 'there is a complete lack of competent evidence to support them.'" The Commission's conclusions of law, however, are reviewed _de novo_. 

Defendants argue on appeal that the Industrial Commission erred by finding that plaintiff suffered a compensable injury. Under N.C.G.S. § 97-2(6) (2001) a compensable injury "means only injury by accident arising out of and in the course of the employment." In the present case, there is no dispute that plaintiff's injuries were caused by an accident. However, defendants contend that plaintiff's injury did not arise "out of and in the course of" her employment.

"Whether an injury arises out of and in the course of a claimant's employment is a mixed question of fact and law, and our review is thus limited to whether the findings and conclusions are supported by the evidence." "The phrase 'arising out of' refers to the requirement that there be some causal connection between the injury and claimant's employment. 'In the course of' refers to the time and place constraints on the injury; the injury must occur during the period of employment at a place where an employee's duties are calculated to take him." Thus, "where the evidence shows that the injury occurred during the hours of employment, at the place of employment, and while the claimant was actually in the performance of the duties of the employment, the injury is in the course of the employment." "In other words, to be compensable, the injury must spring from the employment or have its origin therein." The burden of proof is upon the claimant who "must establish both the 'arising out of' and 'in the course of' requirements to be entitled to compensation." Moreover:

> while the 'arising out of' and 'in the course of' elements are distinct tests, they are interrelated and cannot be applied entirely independently. Both are part of a single test of work-connection. Because the terms of the Act should be liberally construed in favor of compensation, deficiencies in one factor are sometimes allowed to be made up by strength in the other.

In the instant case, the Industrial Commission's findings of fact included, in relevant part, the following:

> In August 1994, plaintiff became employed with defendant-employer as an in-home caregiver. As a caregiver, plaintiff had a variety of job duties relating to the care of clients. Plaintiff also was required to make meals for clients for breakfast, lunch and dinner as well as snacks, perform household chores such as cleaning and laundering, as well as transporting the client and grocery shopping if requested.

> While working for defendant-employer plaintiff was assigned as a caregiver in the home of Ms. Nancy Withers.

> On July 26, 1999, after assisting Ms. Withers out of bed and preparing her breakfast, plaintiff took Ms. Withers' dog outside and, while outside in the yard, plaintiff decided to pick a pear from the pear tree for herself and Ms. Withers. Plaintiff climbed into the tree to retrieve a pear and, as she was coming down, she fell from the tree.

> Plaintiff regularly served fruit to Ms. Withers as a part of her job.

> As an employee for defendant-employer, plaintiff was to provide services pursuant to a plan of care which authorized plaintiff to fix meals for Ms. Withers and to go grocery shopping.

> Plaintiff's activities in obtaining and preparing food for Ms. Withers were in the course and scope of her employment with defendant-employer. The taking of the pear was thereby consistent with plaintiff's duties to acquire and prepare food for Ms. Withers.

Because defendants do not assign as error any of the Industrial Commission's findings of fact, they are "conclusively established on appeal." 

We next determine whether the Industrial Commission correctly applied the law to these facts when it reached the following conclusion: "On July 26, 1999, plaintiff sustained a compensable injury by accident arising out of and in the course of her employment with defendant-employer when she fell from a pear tree while picking a pear for the consumption of her employer's patient."

Defendants argue that plaintiff's injury is not compensable. They contend that, because plaintiff was not authorized to climb a tree in order to obtain a pear for Ms. Withers, plaintiff's injury did not result from "a risk which might have been contemplated by a reasonable person familiar with the whole situation as incidental to the service when he entered the employment." _Bartlett v. Duke University,_ 284 N.C. 230 (1973) (denying compensation to claimant who aspirated food while dining out during a business trip). Defendants frame the issue of compensability primarily in terms of whether plaintiff was authorized to obtain a pear by climbing a tree, which defendants term "the critical issue  in this case."

However, a review of relevant appellate law indicates that a plaintiff's entitlement to workers' compensation generally is not defeated by his negligence, or by evidence that at the time of injury the plaintiff was engaged in a foolish, even forbidden, activity:

> The Workers' Compensation Act is a compromise. Nothing in it supports the notion that it was enacted just for the protection of careful, prudent employees, or that employees that do not stick strictly to their business are beyond its protection. It is not required that the employment be the sole proximate cause of the injury, it being enough that 'any reasonable relationship to the employment exists, or employment is a contributory cause.'

_Bare v. Wayne Poultry Co.,_ 70 N.C.App. 88 (1984)(plaintiff suffers compensable injury "participating in horseplay" with deboning knife). _See also, e.g.,_ the following cases allowing compensation: _Hoyle v. Isenhour Brick and Tile Co.,_ 306 N.C. 248 (1982) (compensation not barred by actions that violate employer's rules unless undertaken in "disobedience of a direct and specific order by a then present superior"); _Watkins v. City of Wilmington,_ 290 N.C. 276 (1976) (injury compensable if "competent proof exists that the employee understood, or had reasonable grounds to believe that the act resulting in injury was incidental to his employment") (citation omitted); _Stubblefield v. Construction Co.,_ 277 N.C. 444 (1970) (plaintiff suffered fatal accident while idly knocking dust and debris from conveyor rollers, actions which "had no relation to his duties"); _Choate v. Sara Lee Products,_ 133 N.C.App. 14 (1999) (plaintiff injured in parking lot after she left production line in violation of company rules); _Spratt v. Duke Power Co.,_ 65 N.C.App. 457 (1983) (claimant injured while running to vending machine in violation of company rules); _Patterson v. Gaston Co.,_ 62 N.C.App. 544 (1983) ("negligence does not necessarily bar the award of compensation"). As explained by this Court:

> An appellate court is justified in upholding a compensation award if the accident is 'fairly traceable to the employment as a contributing cause' or if 'any reasonable relationship to employment exists.' Compensability of a claim basically turns upon whether or not the employee was acting for the benefit of his employer 'to any appreciable extent' when the accident occurred. _In close cases, the benefit of the doubt concerning this issue should be given to the employee_ in accordance with the established policy of liberal construction and application of the Workers' Compensation Act.

We conclude that the Industrial Commission's findings of fact easily establish that plaintiff's accident arose "in the course of" her employment. We further conclude that these findings of fact sufficiently support its conclusion that plaintiff's injury arose "out of" her employment. We note that the Commission's findings specifically state that plaintiff (1) "was required to make meals as well as snacks"; (2) "regularly served fruit to Ms. Withers as a part of her job"; (3) "took Ms. Withers' dog outside and decided to pick a pear for herself _and Ms. Withers_ "; and (4) that plaintiff's "activities in obtaining food for Ms. Withers were in the course and scope of her employment with defendant-employer."

Defendants' arguments are not without force. However, bearing in mind that we are bound by the Industrial Commission's findings of fact, we are constrained to conclude that plaintiff suffered a compensable injury.

### Deem v. Treadway & Sons Painting & Wallcovering, Inc., 543 S.E.2d 209 (N.C. Ct. App. 2001)

Robert Deem ("plaintiff") appeals the trial court's grant of defendants' motions to dismiss pursuant to Rules 12(b)(1) and 12(b)(6). We agree with the trial court that the North Carolina Industrial Commission ("Industrial Commission") has exclusive jurisdiction over plaintiff's claims. Thus, we affirm.

The facts pertinent to this case are as follows: On 26 July 1993, plaintiff was an employee of defendant Treadaway & Sons Painting ("Treadaway Painting") when he fell off a ladder and suffered a compensable injury. With the assistance of an attorney, plaintiff filed a workers' compensation claim with the Industrial Commission against his employer, Treadaway Painting and its workers' compensation carrier, defendant Montgomery Mutual Insurance Company ("Montgomery Mutual"). Montgomery Mutual hired an independent adjusting company, defendant R.E. Pratt & Co. ("Pratt"), to handle plaintiff's workers' compensation claim. Defendant Goad was Pratt's adjuster assigned to plaintiff's claim.

Plaintiff returned to work in November 1994 as a paint foreman. Later, his condition worsened and he was taken out of work on 3 January 1996. About the same time, Montgomery Mutual and Pratt hired defendant Concentra Managed Care ("Concentra") "to provide vocational rehabilitation counseling for the Plaintiff." Defendants Smith, Wertz and Seltzer were employees of Concentra. On 20 February 1996, plaintiff was released to work by his attending physician, however the release was based upon a number of restrictions. When Concentra notified Treadaway Painting that plaintiff could return to work with restrictions, Concentra was informed that plaintiff's job was no longer vacant. However, Treadaway Painting offered the job of laborer to plaintiff, which plaintiff accepted.

On 11 July 1997 plaintiff, through counsel, entered into an "Agreement of Final Settlement and Release" with Treadaway Painting, Montgomery Mutual and Pratt.

> Pursuant to this agreement, the plaintiff and his attorney Seth N. Bernanke agreed to release and discharge all claims available under the North Carolina Worker's Compensation Act relating to this injury in exchange for payment of $100,000. On July 23, 1997 the Industrial Commission entered an order approving the compromise settlement agreement reached by the plaintiff and Treadaway, Montgomery Mutual and R.E. Pratt & Co. in the amount of $100,000.

Notwithstanding the former release and settlement agreement, on 31 December 1998, plaintiff filed this suit against Treadaway Painting, Montgomery Mutual, Pratt, Goad, Concentra and Concentra's three employees, alleging that defendants committed fraud, bad faith, unfair and deceptive trade practices, intentional infliction of emotional distress and civil conspiracy _arising out of the handling of his workers' compensation claim._

In response to plaintiff's complaint, each defendant filed a motion to dismiss pursuant to Rule 12(b)(1), specifically stating that North Carolina's general courts of justice are without subject matter jurisdiction due to the Industrial Commission having exclusive jurisdiction, and; pursuant to Rule 12(b)(6), specifically stating that the plaintiff had failed to state a claim for which relief may be granted. The trial court agreed with defendants and granted each of their motions to dismiss based upon both Rules 12(b)(1) and (6). On appeal, plaintiff brings forward three assignments of error, all dealing with the trial court's grant of each defendant's motion to dismiss. Finding the record before us clear and case law plain, we affirm the trial court's rulings.

In _Johnson v. First Union Corp._, plaintiffs Johnson and Smith each "filed claims with the North Carolina Industrial Commission seeking workers' compensation benefits for repetitive motion disorders they allegedly suffered in the course of their employment. However, both subsequently had their claims rejected." Like the plaintiff in this case, plaintiffs Johnson and Smith later filed suit in superior court against their employer, its workers' compensation carrier, the adjusting company and the rehabilitation provider along with one of its employees, alleging: fraud, bad faith, refusal to pay or settle a valid claim, unfair and deceptive trade practices, intentional infliction of emotional distress and civil conspiracy. Although the trial court dismissed plaintiffs' case stating that plaintiffs had failed to state a claim upon which relief may be granted pursuant to Rule 12(b)(6), on appeal defendants argued—and this Court agreed—that the claims should have been dismissed pursuant to Rule 12(b)(1) because the Industrial Commission had exclusive jurisdiction. 

In enacting the North Carolina Workers' Compensation Act ("the Act"), our General Assembly set clear boundaries for how an employee injured on the job must seek remedy. Additionally, although the Legislature has amended parts of the Act over time, the main thrust of the Act and its purpose have remained the same:

> ... to provide compensation for an employee in this State who has suffered an injury by accident which arose out of and in the course of his employment, the compensation to be paid by the employer, in accordance with the provisions of the act, without regard to whether the accident and resulting injury was caused by the negligence of the employer, as theretofore defined by the law of this State.

We note here that, North Carolina is a contributory negligence state. Thus, to gain any remedy before the Act was enacted, an employee injured on the job would be subject to proving not only that the employer was negligent but that she herself was not negligent at all. Instead, under the Act:

> The right of the employee to compensation, and the liability of the employer therefore, are founded upon mutual concessions, as provided in the Act, _by which each surrenders rights and waives remedies which he theretofore had under the law of this State._ 

Thus, although there is a trade-off of rights, our Supreme Court has held that "the act establishes a sound public policy, and is just to both employer and employee." 

Nevertheless, plaintiff at bar argues that it matters not that his claims originally arose out of his compensable injury. Instead, he argues that the "intentional conduct" of defendants fails to come under the exclusivity provisions of the Act because that conduct did not arise out of and in the course of plaintiff's employment relationship. Again, finding _Johnson_ on point, we disagree.

From both his complaint and his brief to this Court, we can clearly glean that _plaintiff's cause of action arises out of_ his belief that "defendants engaged in fraudulent, illegal, and improper conduct designed at forcing plaintiff back into the job market at a made up job so that the defendants could artificially cut off _plaintiff's right to benefits under the Workers' Compensation Act_." (Emphasis added.) Therefore, plaintiff's complaint is nothing more than an allegation that defendants did not appropriately handle his workers' compensation claim, and thus he was injured because he did not receive his entitled benefit. This is the exact argument of the _Johnson_ plaintiffs and, in that case, this Court held that "the North Carolina Workers' Compensation Act gives the North Carolina Industrial Commission exclusive jurisdiction over workers' compensation claims _and all related matters, including issues such as those raised in the case at bar_." Noting that the _Johnson_ plaintiffs also alleged the defendant committed intentional torts against them (including unfair and deceptive trade practices), we hold in the case at bar that plaintiff's claims are ancillary to his original compensable injury and thus, are absolutely covered under the Act and this collateral attack is improper. 

However, plaintiff further argues that his current claims should be allowed in the general court of justice because they are claims of "intentional conduct." Thus, plaintiff contends that as such, the "actions fall within the North Carolina Supreme Court's exception of intentional conduct from the exclusivity rule" as set out in _Woodson v. Rowland_. Again, we disagree.

It is well established that the "substantially certain" standard set out in _Woodson_ creates an exception to the exclusivity provision of the Act. However, it is also well established that the exception is extremely narrow in that plaintiff's "forecast of evidence" must show the "employer intentionally engaged in the misconduct complained of knowing it was substantially certain to cause serious injury or death to the employee  and the employee was injured or killed by that misconduct." Since plaintiff does not contend, neither is there evidence of record to support a finding that defendants' actions were _"substantially certain to cause serious injury or death"_ to plaintiff, plaintiff's claims do not rise to the level of a _Woodson_ claim. Thus, the trial court's dismissal of plaintiff's claims for lack of subject matter jurisdiction is affirmed, as the Industrial Commission has sole jurisdiction over all the issues raised. We specifically note that the Industrial Commission has the exclusive jurisdiction over workers' compensation agreements and employee claims of fraud, misrepresentation, undue influence, mutual mistake, intentional infliction of emotional distress, and unfair and deceptive trade practices with respect to those agreements. Our Supreme Court has long held that:

> "If a plaintiff desires to attack a workers' compensation agreement for fraud, misrepresentation, undue influence, or mutual mistake, and has evidence to support such an attack, he may make application in due time for a further hearing for that purpose. In such event, the Industrial Commission shall hear the evidence offered by the parties, find the facts with respect thereto, and upon such findings determine whether the agreement was erroneously executed due to fraud, misrepresentation, undue influence or mutual mistake. If such error is found, the Commission may set aside the agreement, and determine whether a further award is justified and, if so, the amount thereof."

Thus, plaintiff's sole remedy in this case was to petition the Industrial Commission to set aside his agreement with Treadaway Painting. We recognize plaintiff is contending that this remedy is insufficient. However, we believe our General Assembly is the correct body to consider changes to our current workers' compensation remedies.

Having held that the trial court properly dismissed plaintiff's claims for lack of subject matter jurisdiction, we need not address the issue of whether plaintiff's claims were properly dismissed pursuant to N.C. Gen.Stat. § 1-1A, Rule 12(b)(6).