# Confidentiality and Loyalty

## Confidentiality Policies

### @LowesHomeCentersLLC_NLRB2021

Lowe’s workplace policy prohibits disclosure of confidential information, and an employee challenged the policy under Section 8(a)(1) of the National Labor Relations Act, which prevents employers from limiting employees’ discussions of their wages. The administrative law judge (“ALJ”) concluded that Lowe’s policy violated the Act. Lowe’s appealed to the National Labor Relations Board, and the Board affirmed. We AFFIRM.

[Factual and Procedural History]{.casesection}

Employee Amber Frare filed an unfair labor practice claim against Lowe’s. She alleged that a section of Lowe’s employee code violated 29 U.S.C. § 158(a)(1) by interfering with employees’ right to discuss wages. The relevant part of the Lowe’s policy reads as follows:

> Employees must maintain the confidentiality of information entrusted to them by Lowe’s, its suppliers, its customers, or its competitors, except when disclosure is authorized by the Chief Compliance Officer or required by law. Employees must consult with the Chief Compliance Officer before disclosing any information that could be considered confidential.
> 
> Confidential information includes, but is not limited to:
> 
> - material non-public information; and
> - proprietary information relating to Lowe’s business such as customer, budget, financial, credit, marketing, pricing, supply cost, personnel, medical records or salary information, and future plans and strategy.

[Discussion]{.casesection}

[“Reasonably construe” standard]{.casesubsection}

In _Boeing_, the Board adopted a more flexible standard for assessing whether a facially neutral employment rule violates Secion 8(a)(1).

> When a facially neutral rule, reasonably interpreted, would not prohibit or interfere with the exercise of NLRA rights, maintenance of the rule is lawful without any need to evaluate or balance business justifications, and the Board’s inquiry into maintenance of the rule comes to an end. Even under Lutheran Heritage--in which legality turned solely on a rule’s potential impact on protected rights--a rule could lawfully be maintained whenever it would not ‘reasonably’ be construed to prohibit NLRA-protected activity, even though it ‘could conceivably be read to cover Section 7 activity.’ Conversely, when a rule, reasonably interpreted, would prohibit or interfere with the exercise of NLRA rights, the mere existence of some plausible business justification will not automatically render the rule lawful. Again, the Board must carefully evaluate the nature and extent of a rule’s adverse impact on NLRA rights, in addition to potential justifications, and the rule’s maintenance will violate Section 8(a)(1) if the Board determines that the justifications are outweighed by the adverse impact on rights protected by Section 7.

In other words, when a facially neutral rule cannot reasonably be interpreted to violate the NLRA, the rule is lawful. There is no need to examine the employer’s justifications for the rule. When a facially neutral rule is reasonably interpreted to violate the NLRA, the rule’s lawfulness is uncertain, and further analysis is required. 

Here, the Board concluded that Lowe’s policy was facially neutral and could be reasonably construed to restrict employees’ wage discussions. The policy prohibits employees from discussing confidential information which explicitly includes “salary information.” We thus agree with the Board’s conclusion that the policy can be reasonably construed to limit employees’ rights under the NLRA. We now turn to Lowe’s legitimate justifications for the policy.

[Lowe’s Legitimate Justifications]{.casesubsection}

Under _Boeing_, the Board created three categories of rules. Category 1 rules are per se lawful, either because they cannot be reasonably interpreted to interfere with employees’ rights or because the adverse impacts on rights is outweighed by justifications for the rule. Category 2 rules warrant individualized scrutiny in each case, and the Board must weigh the adverse impacts on NLRA rights with employer’s legitimate justifications. 

Category 3 rules are generally unlawful because they “would prohibit or limit NLRA-protected conduct, and the adverse impact on NLRA rights is not outweighed by justifications associated with the rule. An example of a Category 3 rule would be a rule that prohibits employees from discussing wages or benefits with one another.” 

The Board reasonably construed Lowe’s policy as limiting the exercise of NLRA rights and looked to Lowe’s justifications. Lowe’s argues that its policy was justified by its need to prevent employees from disseminating its confidential information. The Board recognized that employers have legitimate interests in maintaining confidential records but concluded that those “circumstances were not present in this case” because Lowe’s policy was overly broad. The policy was not tailored to address only those employees with special access to confidential information. 

We find no error in the Board’s analysis. Lowe’s policy falls within the Category 3 rules contemplated by _Boeing_ because the policy can be reasonably construed to limit employees’ wages and because Lowe’s justification does not save the policy. The policy is too broad to be justified by Lowe’s interest in preventing employees from sharing confidential information.

### @TeslaInc_NLRB2021

For the reasons discussed below, we find that the Respondent violated Section 8(a)(1) by maintaining a media-contact provision in its Confidentiality Agreement.

[Media-Contact Provision ]{.casesection}

[Relevant Facts]{.casesubsection}

In October and November 2016, the Respondent required its employees to sign the following Confidentiality Agreement:

> In response to recent leaks of confidential Tesla information, we are reminding everyone who works at Tesla, whether full-time, temporary or via contract, of their confidentiality obligations and asking them to reaffirm their commitment to honor them.
> 
> These obligations are straightforward. Provided that it’s not already public information, everything that you work on, learn about or observe in your work about Tesla is confidential information under the agreement that you signed when you first started. This includes information about products and features, pricing, customers, suppliers, employees, financial information, and anything similar. Additionally, regardless of whether information has already been made public, it is never OK to communicate with the media or someone closely related to the media about Tesla, unless you have been specifically authorized in writing to do so.
> 
> Unless otherwise allowed by law or you have received written approval, you must not, for example, discuss confidential information with anyone outside of Tesla, take or post photos or make video or audio recordings inside Tesla facilities, forward work emails outside of Tesla or to a personal email account, or write about your work in any social media, blog, or book. If you are unsure, check with your manager, HR, or Legal. Of course, these obligations are not intended to limit proper communications with government agencies.
> 
> The consequence for careless violation of the confidentiality agreement, could include, depending on severity, loss of employment. Anyone engaging in intentional violation of the confidentiality agreement will be held liable for all the harm and damage that is caused to the company, with possible criminal prosecution. These obligations remain in place even if no longer working at Tesla.
> 
> By acknowledging, I affirm my agreement to comply with my confidentiality obligations to Tesla. I also represent that at no time over the past 12 months have I disclosed any Tesla confidential information outside of Tesla unless properly authorized to do so.

The Respondent created the Confidentiality Agreement in response to leaks of its confidential information, including a leak to the media of an August 29, 2016 email from the Respondent’s CEO, Elon Musk, to all employees, discussing the Respondent’s financial position and future projections. The Respondent requires employees to sign documents that include confidentiality obligations when they are hired and had previously reminded employees by email not to disclose confidential information to anyone outside of the Respondent. However, the Respondent had not previously required employees to reaffirm their confidentiality obligations.

The Respondent initially tried to have every employee physically sign a copy of the Confidentiality Agreement in the presence of a human resources (HR) partner. When that method proved to be logistically difficult, the Respondent, through a November 2, 2016 email sent by Vice President of Human Resources Mark Lipscomb, instructed all employees to electronically sign the Confidentiality Agreement in Workday. Lipscomb’s email stated that “it’s absolutely critical that we maintain strict confidentiality on all internal matters as any leak can have a negative impact on our company,” and that “in order to reinforce the importance of confidentiality, we are asking everyone to sign an updated confidentiality agreement.”

[Legal Standard]{.casesubsection}

In _Boeing Co._, the Board set out a new standard for determining whether a facially neutral work rule or policy, reasonably interpreted, would unlawfully interfere with, restrain, or coerce employees in the exercise of their Section 7 rights. The Board in _Boeing_ held:

> When evaluating a facially neutral policy, rule or handbook provision that, when reasonably interpreted, would potentially interfere with the exercise of NLRA rights, the Board will evaluate two things: (i) the nature and extent of the potential impact on NLRA rights, and (ii) legitimate justifications associated with the rule.

In conducting this evaluation, the Board will strike the proper balance between the employer’s asserted business justifications for the policy against the extent to which the policy interferes with employee rights under the Act, viewing the rule or policy from the employees’ perspective. Ultimately, the Board places work rules into one of three categories:

> Category 1 will include rules that the Board designates as lawful to maintain, either because (a) the rule, when reasonably interpreted, does not prohibit or interfere with the exercise of NLRA rights; or (b) the potential adverse impact on protected rights is outweighed by justifications associated with the rule.
> 
> Category 2 will include rules that warrant individualized scrutiny in each case as to whether the rule would prohibit or interfere with NLRA rights, and if so, whether any adverse impact on NLRA-protected conduct is outweighed by legitimate justifications.
> 
> Category 3 will include rules that the Board will designate as unlawful to maintain because they would prohibit or limit NLRA-protected conduct, and the adverse impact on NLRA rights is not outweighed by justifications associated with the rule.

However, these categories “will represent a classification of results from the Board’s application of the new test” and “are not part of the test itself.” 

The General Counsel has the initial burden to prove that a facially neutral rule or policy would, when read in context, be interpreted by a reasonable employee as potentially interfering with the exercise of Section 7 rights. If the General Counsel fails to meet this initial burden, the Board does not need to address the employer’s legitimate justifications for the rule. Instead, the rule is lawful and fits within _Boeing_ Category 1(a). Conversely, if the General Counsel does meet the initial burden of proving that a reasonable employee would interpret a rule as potentially interfering with the exercise of Section 7 rights, the Board will then balance that potential interference against the employer’s legitimate justifications for the rule. When the balance favors general employer interests, the rule at issue will be lawful and will fit within _Boeing_ Category 1(b). When the potential interference with Section 7 rights generally outweighs any possible employer justification, the rule at issue will be unlawful and will fit within _Boeing_ Category 3. Finally, “in some instances, it will not be possible to draw any broad conclusions about the legality of a particular rule because the context of the rule and the competing rights and interests involved are specific to that rule and that employer”; such rules will fit within _Boeing_ Category 2. 

[Discussion]{.casesubsection}

The Board has applied _Boeing_ to analyze media-contact rules in two recent cases. In _LA Specialty_, the Board found the following media-contact rule to be lawful:

> Employees approached for interview and/or comments by the news media, cannot provide them with any information. Our President, Michael Glick, is the only person authorized and designated to comment on Company policies or any event that may affect our organization. 

The Board acknowledged that “Section 7 generally protects employees when they speak with the media about working conditions, labor disputes, or other terms and conditions of employment” and that a rule would be facially unlawful if employees would reasonably interpret it to infringe on their Section 7 right to express their personal opinion about those topics to the media. The Board found, however, that employees would have reasonably interpreted the media-contact rule at issue there to provide “only that when employees are approached by the news media for comment, they cannot speak on the employer’s behalf.” “The phrase ‘authorized and designated’ was key” because it signified that the employer’s president was its “spokesperson, i.e., the only person authorized to comment about company matters on the employer’s behalf.” Thus, employees would have reasonably interpreted the media-contact rule merely to prohibit them from speaking to the media on the employer’s behalf. The Board ultimately concluded that because employees do not have a Section 7 right to speak to the media on their employer’s behalf, the media-contact rule at issue did not potentially interfere with the exercise of Section 7 rights and was therefore lawful. The Board placed rules that prohibit employees from speaking to the media on their employer’s behalf in _Boeing_ Category 1(a). 

In _Maine Coast Regional Health Facilities, d/b/a Maine Coast Memorial Hospital_, the Board found the following media policy to be unlawful:

> No EMHS employee may contact or release to news media information about EMHS, its member organizations or their subsidiaries without the direct involvement of the EMHS Community Relations Department or of the chief operating officer responsible for that organization. Any employee receiving an inquiry from the media will direct that inquiry to the EMHS Community Relations Department, or Community Relations staff at that organization for appropriate handling.

The Board agreed with the judge that the media policy above “significantly burdened the employees’ protected rights to communicate with third parties about labor disputes in order to seek improvements in their working conditions, and that the restrictions on Section 7 rights far outweighed the employer’s proffered justifications.” In finding that the media policy significantly burdened the exercise of Section 7 rights, the Board observed that it was “not limited to communications about confidential or proprietary information, or to circumstances when the employees purport to speak on behalf of the employer.” 

In _Maine Coast_, the Board also analyzed the employer’s amended media policy and found that it was lawful because the employer added the following “savings clause” to the unlawful media policy above: “This Policy does not apply to communications by employees, not made on behalf of EMHS or a Member Organization, concerning a labor dispute or other concerted communications for the purpose of mutual aid or protection protected by the National Labor Relations Act.” The Board found that based on the clear language of that “savings clause,” employees would not reasonably interpret the amended media policy to interfere with their Section 7 rights, and it placed the amended media policy in _Boeing_ Category 1(a). 

As to the media-contact provision at issue here, we disagree that employees would reasonably interpret the media-contact provision to apply only to confidential information. The Confidentiality Agreement defines confidential information, in part, as information that is “not already public.” The media-contact provision states that “it is never OK to communicate with the media” about the Respondent “regardless of whether information has already been made public.” Because the express language of the media-contact provision clearly indicates that it applies to information beyond the Confidentiality Agreement’s definition of confidential information, employees would not reasonably interpret the media-contact provision to apply only to communications with the media regarding confidential information. That is so even when the media-contact provision is read in the context of the statement in the first paragraph of the Confidentiality Agreement that it was created “in response to recent leaks of confidential Tesla information.” That general statement does not change the meaning of the plain language of the media-contact provision, which employees would reasonably interpret to apply to communications with the media about any matter regarding the Respondent, including working conditions, labor disputes, or other terms and conditions of employment.

Further, unlike the media-contact rule in _LA Specialty_, the employees here would not reasonably interpret the media-contact provision to apply only to statements made to the media on the Respondent’s behalf because the media-contact provision does not include any language designating a company spokesperson that would logically lead employees to read the provision in that manner. We do not agree with the Respondent that the phrase “unless you have been specifically authorized in writing to do so” would have the same effect as the language designating a company spokesperson in the _LA Specialty_ media-contact rule because employees would not reasonably interpret the authorization language in the media-contact provision here to designate a company spokesperson. Instead, employees would reasonably interpret that language to require that they receive authorization before communicating with the media about any matter regarding the Respondent, including working conditions, labor disputes, or other terms and conditions of employment. The Respondent may not lawfully require its employees to receive preauthorization before engaging in such Section 7 activity. 

Additionally, we reject the Respondent’s argument that employees would understand that the media-contact provision does not apply to Section 7 activity because the first sentence of the paragraph directly following the media-contact provision begins with the phrase “unless otherwise allowed by law.” When read in context, that phrase does not appear to apply to the media-contact provision because it is in a separate paragraph and specifically applies to a list of prohibited activities, which does not mention speaking to the media. In any event, even if employees would interpret the phrase “unless otherwise allowed by law” to apply to the media-contact provision, such vague, generalized language would require employees to meticulously determine the state of the law for themselves, and employees therefore cannot be expected to interpret that language to exclude Section 7 activity from the coverage of the media-contact provision. The media-contact provision simply does not contain any language comparable to the “savings clause” that rendered the amended media policy lawful in _Maine Coast_.

Rather, the media-contact provision here is similar to the other media policy that the Board analyzed--and ultimately found unlawful--in _Maine Coast_. As in _Maine Coast_, because the media-contact provision is not limited to communications regarding confidential information or circumstances in which employees purport to speak on the Respondent’s behalf, the General Counsel met his initial burden by proving that employees would reasonably interpret the media-contact provision to potentially interfere with the exercise of their Section 7 right to communicate with the media concerning working conditions, labor disputes, or other terms and conditions of employment.

We acknowledge that the Respondent has a legitimate and, indeed, weighty interest in protecting its confidential information. However, the right of employees to communicate with the media concerning labor disputes and terms and conditions of employment--and to do so without having to obtain preauthorization from their employer--is “central to the Act,” and employees would reasonably interpret the media-contact provision to wholly preclude them from exercising that right. As in _Maine Coast_, we find that the media-contact provision’s potential impact on Section 7 rights outweighs the Respondent’s justification.

Based on the foregoing, we find that the media-contact provision in the Respondent’s Confidentiality Agreement is unlawful and that the Respondent therefore violated Section 8(a)(1) by maintaining it. Further, we place rules that prohibit employees from communicating with the media regardless of whether the communications concern confidential information or the employees purport to speak on the employer’s behalf in _Boeing_ Category 3.

::: {.callout-note}
In _Lowe's Home Centers_ and _Tesla_, the NLRB evaluated the employers' confidentiality policies under the standard adopted in  @BoeingCompany_NLRB2017 and @SpecialtyProduce_NLRB2019. In @StericycleInc_NLRB2023 (see Chap. 4), the NLRB overruled _Boeing_ and "adopt[ed] a new legal standard to decide whether an employer’s work rule that does not expressly restrict employees’ protected concerted activity under Section 7 of the National Labor Relations Act (Act) is facially unlawful under Section 8(a)(1) of the Act." Because the standard under _Stericycle_ is less deferential to employer interests and more protective of employee rights, the outcome in cases like _Lowe's Home Centers_ and _Tesla_, holding employer rules illegal under _Boeing_, would likely be the same.
:::

## Confidential Settlement Agreements 

### @ZornHillA2BTaxiLLC_SDNY2020

Plaintiff Kenneth Zorn-Hill ("Zorn-Hill") filed a Complaint against A2B Taxi LLC ("A2B"), Everald Gilliard, and Trevonne Gilliard (collectively, "Defendants"), pursuant to the Fair Labor Standards Act of 1938 ("FLSA") and New York Labor Law Article 6 § 190 _et seq_ ("NYLL"). 

Similarly, on November 30, 2018, Plaintiff Christopher Hunlock ("Hunlock") filed a Complaint against A2B and Everald Gilliard, pursuant to the FLSA and NYLL.

The Parties now seek approval of their proposed settlement. For the reasons that follow, the Parties' application is denied without prejudice.

[Background]{.casesection}

According to the Complaints, A2B provides non-emergency medical transportation services. Plaintiffs allege that they were not (1) informed of their right to overtime pay, (2) paid overtime for work in excess of 40 hours per week, or (3) provided with an appropriate wage notice. Plaintiffs seek damages, liquidated damages, pre-and post-judgment interest, further relief available under the FLSA and NYLL, and attorney fees.

[Discussion]{.casesection}

Under Fed. R. Civ. P. 41(a)(1)(A), a plaintiff's ability to dismiss an action without a court order is made "subject to ... any applicable federal statute." "Except as provided in Rule 41(a)(1), an action may be dismissed at the plaintiff's request only by court order, on terms that the court considers proper." The Second Circuit has confirmed that the FLSA is an "applicable federal statute," such that "Rule 41(a)(1)(A)(ii) stipulated dismissals settling FLSA claims with prejudice require the approval of the district court or the Department of Labor to take effect." Consequently, "the Parties must satisfy the Court that their agreement is 'fair and reasonable.'"

As a number of courts have recognized, although a court should consider the totality of the circumstances, the most significant factors include:

> \(1) the plaintiff's range of possible recovery; (2) the extent to which the settlement will enable the parties to avoid anticipated burdens and expenses in establishing their respective claims and defenses; (3) the seriousness of the litigation risks faced by the parties; (4) whether the settlement agreement is the product of arm's-length bargaining between experienced counsel; and (5) the possibility of fraud or collusion.

Conversely, factors which weigh against finding a settlement fair and reasonable include:

> \(1) the presence of other employees situated similarly to the claimant; (2) a likelihood that the claimant's circumstance will recur; (3) a history of FLSA non-compliance by the same employer or others in the same industry or geographic region; and (4) the desirability of a mature record and a pointed determination of the governing factual or legal issue to further the development of the law either in general or in an industry or in a workplace.

[Non-Disparagement Clause]{.casesubsection}

The Court finds that the Proposed Settlement's non-disparagement clause is reasonable. In this clause, the Parties mutually "agree not to say or publicize things that are insulting or disparaging about the other Party." The clause also contains a carve-out: "each of the parties are free to make truthful statements about their experience litigating their case (except as to statements made at the confidential mediation held on July 9, 2020)." Non-disparagement clauses are valid, so long as they contain such a carve-out. Thus, the Court approves the non-disparagement clause.

[Non-Publicity Clause]{.casesubsection}

The Court finds that the Proposed Settlement's non-publicity cause imposes reasonable restrictions on affirmative contact with media, but unreasonable restrictions on use of social media. This clause states that "Plaintiffs, on behalf of themselves and their counsel, agree not to take affirmative steps to contact the media or utilize social media to publicize the Proposed Settlement or its terms." The clause contains two specific carve-outs. First, "if contacted by the media regarding the Proposed Settlement, Plaintiffs and Plaintiffs' Counsel are free to make truthful statements about their experience litigating their case." Second, Plaintiffs' Counsel is permitted to post a brief description of the lawsuit and settlement to its website, including a hyperlink to the case dockets.

"The overwhelming majority of courts reject the proposition that FLSA settlement agreements can be confidential." This is because "a provision that prohibits Plaintiff's right to discuss the settlement is incompatible with the purposes of the FLSA, namely, to ensure that workers are aware of their rights.

Courts are split on whether agreements that limit plaintiffs' ability to contact media are permissible. _Compare_ _Chun Lan Guan v. Long Island Bus. Instute, Inc._ (E.D.N.Y.2020) (approving media restriction because "although these provisions do place some limits on Plaintiffs' ability to discuss the settlements, the limits are not absolute and do not restrict Plaintiffs' general ability to discuss the settlements"); _Pucciarelli v. Lakeview Cars, Inc._ (E.D.N.Y. 2017) ("The confidentiality provision is not highly restrictive because it pertains only to the agreement...."); _Lola v. Skadden, Arps, Meagher, Slate & Flom LLP_ (S.D.N.Y. 2016) (same, and also noting that "since no one can force Plaintiffs to opine on the case in the future anyway, it is by no means irrational or improper for Plaintiffs to compromise words for dollars as part of a global, arms-length settlement"); _with_ _Garcia v. Good for Life by 81, Inc._ (S.D.N.Y. 2018) ("Barring plaintiffs from contacting the media is thus not a trivial infringement on their ability to spread the word to other workers who may then be able to vindicate their statutory rights."). Courts are also split on whether FLSA settlements may limit plaintiffs' ability to post to social media. _Compare_ _Burczyk v. Kemper Corp. Servs., Inc._ (E.D.N.Y. 2017) (rejecting proposed social media restriction because "considering the commonality of which individuals communicate over the internet, preventing Plaintiffs from posting 'on any social media, website, blog or other form or Internet activity' places a substantial burden on their ability to openly discuss their experience"); _Chung v. Brooke's Homecare LLC_ (S.D.N.Y. 2018) (finding "too broad" a provision that applied restrictions to social media); _with_ _Flores v. Studio Castellano Architect, P.C._ (S.D.N.Y. 2017) (approving a non-disclosure provision "limited to an agreement not to publicize the terms of the settlement in news or social media"); _Lola_ (finding restriction on social media "is not absolute" and does not limit "plaintiffs' general ability to discuss the settlement").

Here, the restriction on affirmative steps to communicate with the media is permissible. First, it does not prevent Plaintiffs from discussing the Proposed Settlement with their colleagues and friends who may face similar uncompensated overtime. Second, it limits Plaintiffs' ability to speak with the media only about the Proposed Settlement itself. Plaintiffs may still take affirmative steps to contact the media about matters outside the Proposed Settlement, such as their allegations. Third, the Proposed Settlement allows Plaintiffs to respond to media inquiries with "truthful statements about their experience litigating their case." This restriction is significantly less onerous than no-media restrictions approved by other courts, which in at least two cases required a scripted response to media inquiries. _See_ _Daniels v. Haddad_ (S.D.N.Y. 2018) (requiring the plaintiffs, if contacted by the media, to "simply refer the inquirer to the public dockets"); _Lola_ (requiring the plaintiffs to say "no comment" or "the matter has been resolved").

The Court finds that the restriction on use of social media is impermissible. Since individuals regularly use the internet to communicate with friends, colleagues, and family, restricting Plaintiffs ability to use it "places a substantial burden on their ability to openly discuss their experience litigating the lawsuit and entering into the Proposed Settlement." This is incompatible with the statutory purpose to "ensure that workers are aware of their rights." It is true that the Proposed Settlement restricts only efforts "to publicize" the agreement. However, this provides little comfort "given the broad range of meanings which can be imputed to the word 'publicize.'"

[Conclusion]{.casesection}

For the foregoing reasons, the Parties' request for approval of their Proposed Settlement is denied without prejudice. The Parties may reapply for approval of a settlement that eliminates or tailors the provision restricting use of social media.

### @MaclarenMacomb_NLRB

The main issue presented is whether the Respondent violated Section 8(a)(1) of the National Labor Relations Act (Act) by offering a severance agreement to 11 bargaining unit employees it permanently furloughed. The agreement broadly prohibited them from making statements that could disparage or harm the image of the Respondent and further prohibited them from disclosing the terms of the agreement. Agreements that contain broad proscriptions on employee exercise of Section 7 rights have long been held unlawful because they purport to create an enforceable legal obligation to forfeit those rights. Proffers of such agreements to employee have also been held to be unlawfully coercive. The Board in _Baylor University Medical Center_ and _IGT d/b/a International Game Technology_ reversed this long-settled precedent and replaced it with a test that fails to recognize that unlawful provisions in a severance agreement proffered to employees have a reasonable tendency to interfere with, restrain, or coerce the exercise of employee rights under Section 7 of the Act. We accordingly overrule _Baylor_ and _IGT_ and, upon careful analysis of the terms of the nondisparagement and confidentiality provisions at issue here, we find them to be unlawful, and thus find the severance agreement proffered to employees unlawful.

[I.]{.casesection}

The Respondent operates a hospital in Mt. Clemens, Michigan, where it employs approximately 2300 employees. After an election on August 28, 2019, the Board certified Local 40 RN Staff Council, Office of Professional Employees International Union (OPEIU), AFL-CIO (Union) as the exclusive collective-bargaining representative of a unit of approximately 350 of the Respondent's service employees. Following the onset of the Coronavirus Disease 2019 (Covid-19) pandemic in March 2020, the government issued regulations prohibiting the Respondent from performing elective and outpatient procedures and from allowing nonessential employees to work inside the hospital. The Respondent then terminated its outpatient services, admitted only trauma, emergency, and Covid-19 patients, and temporarily furloughed 11 bargaining unit employees because they were deemed nonessential employees. In June, the Respondent permanently furloughed those 11 employees and contemporaneously presented each of them with a "Severance Agreement, Waiver and Release" that offered to pay differing severance amounts to each furloughed employee if they signed the agreement. All 11 employees signed the agreement. The agreement required the subject employee to release the Respondent from any claims arising out of their employment or termination of employment. The agreement further contained the following provisions broadly prohibiting disparagement of the Respondent and requiring confidentiality about the terms of the agreement:

> 6\. **Confidentiality Agreement.** The Employee acknowledges that the terms of this Agreement are confidential and agrees not to disclose them to any third person, other than spouse, or as necessary to professional advisors for the purposes of obtaining legal counsel or tax advice, or unless legally compelled to do so by a court or administrative agency of competent jurisdiction.
> 
> 7\. **Non-Disclosure.** At all times hereafter, the Employee promises and agrees not to disclose information, knowledge or materials of a confidential, privileged, or proprietary nature of which the Employee has or had knowledge of, or involvement with, by reason of the Employee's employment. At all times hereafter, the Employee agrees not to make statements to Employer's employees or to the general public which could disparage or harm the image of Employer, its parent and affiliated entities and their officers, directors, employees, agents and representatives.

The agreement provided for substantial monetary and injunctive sanctions against the employee in the event the nondisparagement and confidentiality proscriptions were breached:

> 8\. **Injunctive Relief.** In the event that Employee violates the provisions of paragraphs 6 or 7, the Employer is hereby authorized and shall have the right to seek and obtain injunctive relief in any court of competent jurisdiction. If Employee individually or by his/her attorneys or representative(s) shall violate the provisions of paragraph 6 or 7, Employee shall pay Employer actual damages, and any costs and attorney fees that are occasioned by the violation of these paragraphs.

The Respondent neither gave the Union notice that it was permanently furloughing the 11 employees nor an opportunity to bargain regarding that decision and its effects. The Respondent also did not give the Union notice that it presented the severance agreement to the employees, nor did it include the Union in its discussions with the employees regarding their permanent furloughs and the severance agreement. Thus, the Respondent entirely bypassed and excluded the Union from the significant workplace events here: employees' permanent job loss and eligibility for severance benefits.

[III. ]{.casesection}

The gravamen of the General Counsel's amended complaint is that the nondisparagement and confidentiality provisions of the severance agreement unlawfully restrain and coerce the furloughed employees in the exercise of their Section 7 rights. Applying _Baylor_ and _IGT_, the judge found these provisions to be lawful, and thus concluded that the severance agreement was lawful and that the proffer of the agreement to the furloughed employees was lawful. The General Counsel excepts to the dismissal and argues, among other things, that the Board should overrule _Baylor_ and _IGT._ We agree.

Until _Baylor_, when faced with an allegation that a severance agreement violated the Act, Board precedent focused on the language of the severance agreement to determine whether proffering the agreement had a reasonable tendency to interfere with, restrain, or coerce employees' exercise of their Section 7 rights. For example, in _Metro Networks_, the Board specifically analyzed the nonassistance and nondisclosure provisions of the severance agreement at issue and found that "the plain language of the severance agreement would prohibit \[employee\] Brocklehurst from cooperating with the Board in important aspects of the investigation and litigation of unfair labor practice charges." The Board accordingly concluded that the proffer of the severance agreement to Brocklehurst was unlawful. In _Clark Distribution Systems_, the Board like-wise carefully scrutinized the language of the confidentiality provision contained in the severance agreement offered to employees. The Board found that the language of the provision prohibited employees from participating in the Board's investigative process, and thus, that the proffer of the severance agreement was unlawful. More recently, in _Shamrock Foods Co._, the Board found that a separation agreement proffered to an employee that contained confidentiality and non-disparagement provisions was unlawful. The Board, citing and analyzing the specific language of the provisions, found the agreement unlawful because the provisions "broadly required" the employee to whom it was proffered "to waive certain Section 7 rights." Specifically, the separation agreement prevented him from assisting his former co-workers, disclosing information to the Board, and making disparaging remarks which could be detrimental to the employer.

In none of these cases was the presence of additional unlawful conduct by the employer necessary to find that the plain language of the agreement violated the Act. Rather, the Board treated the legality of a severance agreement provision as an entirely independent issue. What mattered was whether the agreement, on its face, restricted the exercise of statutory rights.

In _Baylor_, the Board abandoned examination and analysis of the severance agreement at issue. _Baylor_ shifted focus instead to the circumstances under which the agreement was presented to employees. The _Baylor_ Board held that the Respondent did not violate the Act by the "mere proffer" of a severance agreement that required the signer to agree not to "pursue, assist, or participate in any claim" against Baylor and to keep a broad swath of information confidential. The Board reasoned that the agreement was not mandatory, pertained exclusively to post-employment activities and, therefore, had no impact on terms and conditions of employment, and there was no allegation that anyone offered the agreement had been unlawfully discharged or that the agreement was proffered under circumstances that would tend to infringe on Section 7 rights. The _Baylor_ Board overruled prior decisions to the extent they held to the contrary.

Only a few months later, in _IGT_, the Board again dismissed an allegation that the respondent maintained an unlawful nondisparagement provision in the severance agreement it offered to separated employees. The provision required the signer to agree not to "disparate or discredit IGT or any of its affiliates, officers, directors and employees." Citing _Baylor_, the Board again reasoned that the agreement was "entirely voluntary, does not affect pay or benefits that were established as terms of employment, and has not been proffered coercively." The _IGT_ Board underscored that _Baylor_ had "overruled" _Shamrock Foods_, _Clark Distribution Systems_, and _Metro Networks_.

As discussed below, _Baylor_ and _IGT_ are flawed in multiple respects. We therefore overrule both decisions and return to the prior, well-established principle that a severance agreement is unlawful if its terms have a reasonable tendency to interfere with, restrain, or coerce employees in the exercise of their Section 7 rights, and that employers' proffer of such agreements to employees is unlawful. In making that determination we will examine, as pre-_Baylor_ precedent did, the language of the agreement, including whether any relinquishment of Section 7 rights is narrowly tailored.

Notably absent from either _Baylor_ or _IGT_ was any analysis of the specific language in the challenged provisions of the severance agreements. That is because, under those decisions, an employer's mere proffer to employees of a severance agreement with unlawful provisions cannot be unlawful. Under _Baylor,_ coercive language cannot have a reasonable tendency to coerce employees unless it is also proffered in circumstances deemed coercive, independent of the agreement itself. In this respect the _Baylor_ Board "entirely failed to consider an important aspect of the problem," making its decision arbitrary.

The _Baylor_ test arbitrarily adopts a two-factor analysis for finding that a severance agreement violates Section 8(a)(1) of the Act. First, it requires the employer proffering the severance agreement to have discharged its recipient in violation of the Act, or committed another unfair labor practice discriminating against employees under the Act. _Baylor_ thus held that absent such unlawful coercive circumstances, an employer is entirely free to proffer any provision, even a facially unlawful one. The Board did not explain what legitimate employer interest is served by permitting that step, which reasonably could result in the employee's acceptance of the agreement (and its unlawful provisions) and, in turn, the employee's decision not to violate the agreement by exercising Section 7 rights. Nor did the Board offer a persuasive reason to find that an agreement with an unlawful provision has no reasonable tendency to coerce employees unless the employer has a proclivity to violate the Act otherwise or has violated the Act or infringed on employees' Section 7 rights while carrying out actions surrounding the provision of the severance agreement. The presence of such exacerbating circumstances certainly enhances the coercive potential of the severance agreement. But the absence of such behavior does not and cannot eliminate the potential chilling effect of an unlawful severance agreement on the exercise of Section 7 rights. And yet, the standard set by _Baylor_ does nothing to protect employees confronted with patently coercive severance agreements, if their employer has not otherwise violated the Act.

Second, the _Baylor_ test is incorrectly premised on the contention that employer animus towards the exercise of Section 7 rights is a relevant component of an allegation that provisions of a severance agreement violate Section 8(a)(1) of the Act. The Board in _Baylor_ justified its refusal to find a violation of the Act on grounds that "there is no reason to believe that the Respondent harbors animus against Sec. 7 activity, let alone that it is willing to terminate employees who engage in it. Under these circumstances, the offer of a severance agreement does not _reasonably_ tend to interfere with the free exercise of employee rights under the Act."

But whether an employer harbors animus against Section 7 activity is irrelevant to the long-established objective test for determining whether Section 8(a)(1) of the Act is violated. "It is well settled that the test of interference, restraint, and coercion under Section 8(a) (1) of the Act does not turn on the employer's motive or on whether the coercion succeeded or failed. The test is whether the employer engaged in conduct which, it may reasonably be said, tends to interfere with the free exercise of employee rights under the Act." Consistent with Section 8(a)(1) law generally, evaluation of the tendency of a severance agreement to coerce (and therefore its lawfulness) does not involve inquiring, as did the Board in _Baylor_ and _IGT,_ whether employer animus surrounds or infects the circumstances surrounding the offer of the severance agreement. The _Baylor_ Board offered no justification for its consideration of animus and discrimination apart from the terms of the severance agreement, which altered the long-established construction of Section 8(a)(1) of the Act.

Indeed, neither _Baylor_ nor the _IGT_ majority attempted to articulate any policy considerations that would justify its severely constricted view of Section 7 rights. The _IGT_ majority reasons that because _some_ employee waivers of Section 7 rights are permissible, _no_ waivers can be facially unlawful, but this is a non sequitur. Whether or not employees view employer documents through the prism of Section 7 rights (a proposition questioned by the _IGT_ majority), the Board must do so when the General Counsel issues a complaint alleging that a severance agreement violates employee Section 7 rights. Because both _Baylor_ and the _IGT_ majority fail this test, we overrule them.

[IV. ]{.casesection}

_Baylor_ and the _IGT_ majority ignore well-established precedent concerning waiver of employee rights. The Board does not write on a clean slate regarding employee waiver of Section 7 rights via a severance agreement. There is a backdrop of nearly a century of settled law that employees may not broadly waive their rights under the NLRA. Agreements between employers and employees that restrict employees from engaging in activity protected by the Act, or from filing unfair labor practice charges with the Board, assisting other employees in doing so, or assisting the Board's investigative process, have been consistently deemed unlawful. The "future rights of employees as well as the rights of the public may not be traded away" in a manner which requires "forebearance from future charges and concerted activities." This broad proscription underscores that the Board acts in a public capacity to protect public rights to give effect to the declared public policy of the Act. 

The broad scope and the wide protection afforded employees by Section 7 of the Act bear repeating. "It is axiomatic that discussing terms and conditions of employment with coworkers lies at the heart of protected Section 7 activity. Section 7 rights are not limited to discussions with coworkers, as they do not depend on the existence of an employment relationship between the employee and the employer, and the Board has repeatedly affirmed that such rights extend to former employees. It is further long-established that Section 7 protections extend to employee efforts to improve terms and conditions of employment or otherwise improve their lot as employees through channels outside the immediate employee-employer relationship. These channels include administrative, judicial, legislative, and political forums, newspapers, the media, social media, and communications to the public that are part of and related to an ongoing labor dispute. Accordingly, Section 7 affords protection for employees who engage in communications with a wide range of third parties in circumstances where the communication is related to an ongoing labor dispute and when the communication is not so disloyal, reckless, or maliciously untrue to lose the Act's protection.

The Board is tasked with safeguarding the integrity of its processes for employees exercising their Section 7 rights. "Congress has made it clear that it wishes all persons with information about unfair labor practices to be completely free from coercion against reporting them to the Board." "This complete freedom is necessary . . . 'to prevent the Board's channels of information from being dried up by employer intimidation of prospective complainants and witnesses.'" "It is also consistent with the fact that the Board does not initiate its own proceedings; implementation is dependent 'upon the initiative of individual persons.'" The Board's "'ability to secure vindication of rights protected by the Act depends in large measure upon the ability of its agents to investigate charges fully to obtain relevant information and supporting statements from individuals,'" and "such investigations often rely heavily on the voluntary assistance of individuals in providing information."

It is through the lens of this broad grant of rights and the Board's duty to protect them that the Board scrutinizes a severance agreement containing provisions alleged to violate Section 8(a)(1) of the Act. Inherent in any proffered severance agreement requiring workers not to engage in protected concerted activity is the coercive potential of the overly broad surrender of NLRA rights if they wish to receive the benefits of the agreement. Accordingly, we return to the approach followed by Board precedent before _Baylor_, and hold that an employer violates Section 8(a)(1) of the Act when it proffers a severance agreement with provisions that would restrict employees' exercise of their NLRA rights. Such an agreement has a reasonable tendency to restrain, coerce, or interfere with the exercise of Section 7 rights by employees, regardless of the surrounding circumstances.

Certainly such surrounding circumstances may enhance the reasonable tendency of the severance agreement to coerce employees, but that tendency does not depend on them. Where an agreement unlawfully conditions receipt of severance benefits on the forfeiture of statutory rights, the mere proffer of the agreement itself violates the Act, because it has a reasonable tendency to interfere with or restrain the prospective exercise of Section 7 rights, both by the separating employee and those who remain employed. Whether the employee accepts the agreement is immaterial. As the Board explained in _Metro Networks_, the employer's "proffer of the severance agreement . . . constitutes an attempt to deter the employee from assisting the Board" and the employee's "conduct in _not_ signing the agreement did not render the employer's conduct lawful." If the law were to the contrary, it would create an incentive for employers to proffer severance agreements with unlawful provisions to employees. Only if the employee signed the agreement, subjected herself to its unlawful requirements, and then came to the Board would the Board be able to address the situation, belatedly. No policy of the Act is served by creating this obstacle to the effective protection of Section 7 rights. In fact, under established standards, no showing of actual coercion is required to prove a violation of Section 8(a)(1) of the Act. Rather, it is the high potential that coercive terms in separation agreements may chill the exercise of Section 7 rights that dictates the Board's traditional approach of viewing severance agreements requiring the forfeiture of Section 7 rights--whether accepted or merely proffered--as unlawful unless narrowly tailored.

[V. ]{.casesection}

Examining the language of the severance agreement here, we conclude that the nondisparagement and confidentiality provisions interfere with, restrain, or coerce employees' exercise of Section 7 rights. Because the agreement conditioned the receipt of severance benefits on the employees' acceptance of those unlawful provisions, we find that the Respondent's proffer of the agreement to employees violated Section 8(a)(1) of the Act.

The nondisparagement provision on its face substantially interferes with employees' Section 7 rights. Public statements by employees about the workplace are central to the exercise of employee rights under the Act. Yet the broad provision at issue here prohibits the employee from making any "statements to \[the\] Employer's employees or to the general public which could disparage or harm the image of \[the\] Employer"--including, it would seem, any statement asserting that the Respondent had violated the Act (as by, for example, proffering a settlement agreement with unlawful provisions). This far-reaching proscription--which is not even limited to matters regarding past employment with the Respondent--provides no definition of disparagement that cabins that term to its well-established NLRA definition under _NLRB v. Electrical Workers Local 1229 (Jefferson Standard Broadcasting Co.)_. Instead, the comprehensive ban would encompass employee conduct regarding any labor issue, dispute, or term and condition of employment of the Respondent. As we explained above, however, employee critique of employer policy pursuant to the clear right under the Act to publicize labor disputes is subject only to the requirement that employees' communications not be so "disloyal, reckless or maliciously untrue as to lose the Act's protection."

Further, the ban expansively applies to statements not only toward the Respondent but also to "its parents and affiliated entities and their officers, directors, employees, agents and representatives." The provision further has no temporal limitation but applies "at all times hereafter." The end result is a sweepingly broad bar that has a clear chilling tendency on the exercise of Section 7 rights by the subject employee. This chilling tendency extends to efforts to assist fellow employees, which would include future cooperation with the Board's investigation and litigation of unfair labor practices with regard to any matter arising under the NLRA at any time in the future, for fear of violating the severance agreement's general proscription against disparagement and incurring its very significant sanctions. The same chilling tendency would extend to efforts by furloughed employees to raise or assist complaints about the Respondent with their former coworkers, the Union, the Board, any other government agency, the media, or almost anyone else. In sum, it places a broad restriction on employee protected Section 7 conduct. We accordingly find that the proffer of the nondisparagement provision violates Section 8(a)(1) of the Act.

Our scrutiny of the confidentiality provision of the severance agreement leads to the same conclusion. The provision broadly prohibits the subject employee from disclosing the terms of the agreement "to _any_ third person." The employee is thus precluded from disclosing even the existence of an unlawful provision contained in the agreement. This proscription would reasonably tend to coerce the employee from filing an unfair labor practice charge or assisting a Board investigation into the Respondent's use of the severance agreement, including the nondisparagement provision. Such a broad surrender of Section 7 rights contravenes established public policy that all persons with knowledge of unfair labor practices should be free from coercion in cooperating with the Board. The confidentiality provision has an impermissible chilling tendency on the Section 7 rights of all employees because it bars the subject employee from providing information to the Board concerning the Respondent's unlawful interference with other employees' statutory rights. 

The confidentiality provision would also prohibit the subject employee from discussing the terms of the severance agreement with his former coworkers who could find themselves in a similar predicament facing the decision whether to accept a severance agreement. In this manner, the confidentiality provision impairs the rights of the subject employee's former coworkers to call upon him for support in comparable circumstances. Additionally encompassed by the confidentiality provision is discussion with the Union concerning the terms of the agreement, or such discussion with a union representing employees where the subject employee may gain subsequent employment, or alternatively seek to participate in organizing, or discussion with future co-workers. A severance agreement is unlawful if it precludes an employee from assisting coworkers with workplace issues concerning their employer, and from communicating with others, including a union, and the Board, about his employment. Conditioning the benefits under a severance agreement on the forfeiture of statutory rights plainly has a reasonable tendency to interfere with, restrain, or coerce the exercise of those rights. unless it is narrowly tailored to respect the range of those rights. Our review of the agreement here plainly shows that not to be the case. We accordingly find that the proffer of the confidentiality provision violates Section 8(a)(1) of the Act.

::: {.callout-note}

Two states, California and Washington, have enacted legislation against provisions in settlement agreements that restrict disclosure of factual information related to sexual assault, sexual harassment, and other workplace discrimination and harassment. [Cal. Code of Civil Procedure, § 1001](https://leginfo.legislature.ca.gov/faces/codes_displayText.xhtml?lawCode=CCP&division=&title=14.&part=2.&chapter=3.5.&article=); [Wash, Sess. Laws, Chapter 133, Laws of 2022](https://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1795-S.SL.pdf). The Washington law also applies to settlement agreements related to wage and hour violations. Similar legislation has been introduced in the U.S. Congress. Accountability for [Workplace Misconduct Act](https://www.govinfo.gov/app/details/BILLS-118hr4802ih), H.R. 4802. 
:::

## Trade Secrets 

### @TSGFinishingLLCBollinger_NCApp2014

TSG Finishing, LLC ("plaintiff" or "TSG") appeals from an order denying its motion for a preliminary injunction aimed at preventing its former employee, Keith Bollinger ("defendant"), from breaching a non-competition and confidentiality agreement ("the non-compete agreement") and misappropriating TSG's trade secrets. On appeal, plaintiff contends that the trial court erred by denying its motion for a preliminary injunction because: (1) it has demonstrated a likelihood of success on the merits of its claims for breach of contract and misappropriation of trade secrets; and (2) it would suffer irreparable harm without issuance of the preliminary injunction.

After careful review, we reverse the trial court's order and remand with instructions to issue the preliminary injunction.

[Background]{.casesection}

TSG is in the business of fabric finishing. It has three plants in Catawba County, North Carolina. Rather than manufacturing fabrics, TSG applies chemical coatings to achieve whichever result is desired by the customer, such as coloring, stiffening, deodorizing, and abrasion resistance.

Defendant began working in the field of fabric finishing for Geltman Corporation after graduating from high school in 1982. He has no formal education beyond high school. TSG, Incorporated ("TSG, Inc.") acquired Geltman in 1992, and defendant stayed on to work for TSG, Inc. By the late 1990's, defendant was promoted to Quality Control Manager.

Defendant was responsible for assessing a customer's finishing needs and developing a finishing protocol for that customer. Defendant also helped in the creation of a "style data card" for each customer. The style data cards contained information on each step of the finishing process, such as: (1) the chemical finish compound, 70 percent of which was proprietary to TSG; (2) "cup weight" density; (3) needle punch technique; (4) type of machine needed for the needle punch technique; (5) speed of needle punch; (6) types of needles used; (7) needle punch depths; (8) method of compound application; (9) speed of compound application; (10) blade size; (11) fabric tension; and (12) temperature and type of drying required.

Defendant testified during deposition that some of these factors required trial and error to achieve a customer's desired result. For example, on one of the style data cards used to explain defendant's work-related duties during the deposition, defendant had marked a number of changes to the various factors listed and signed his initials to the changes. He testified that he changed the data entered by the customer because subsequent testing revealed different and more efficient methods to achieve the result. He also testified that the results of the trials he conducted and the knowledge he gained regarding how to achieve these results were not known outside of TSG. Michael Goldman, the Director of Operations at TSG, filed an affidavit in which he asserted that some of the customer projects that defendant worked on required over a year's worth of trial and error to achieve a customer's desired result.

TSG expends great effort to keep its customer and finishing information confidential. Specifically, it uses a code system in its communications with customers that allows the customer to identify the type of finish it wants, but does not reveal the chemicals or processes involved in creating that finish. TSG has confidentiality agreements in place with many of its customers. Third parties must sign confidentiality agreements and receive a temporary identification badge when visiting TSG's facilities. TSG's computers are password protected, with additional passwords being required to access the company's production information.

In 2007, TSG, Inc. and defendant entered into a non-disclosure and non-compete agreement. In exchange for an annual increase in compensation of $1,300.00 and a $3,500.00 signing bonus, defendant agreed not to disclose TSG, Inc.'s confidential or proprietary trade secrets and further assented to employment restrictions after his tenure at the company ended.

TSG, Inc. filed for bankruptcy in 2009. By a plan approved by the United States Bankruptcy Court on 1 May 2011, TSG, Inc. transferred its interests to plaintiff, a wholly owned operating subsidy of TSG, Inc., which remained in operation. According to defendant, every aspect of his day-to-day job remained the same after bankruptcy reorganization.

In July 2013, defendant and a direct competitor of TSG, American Custom Finishing, LLC ("ACF"), began negotiations regarding defendant's potential to leave TSG and work for ACF. According to TSG, defendant resigned from his position on 21 November 2013 and announced that he was leaving to become plant manager for ACF at a plant five miles away from TSG. Defendant claims that he gave TSG two weeks' notice on 21 November 2013 but was terminated immediately and escorted off of the premises. Defendant began working for ACF the following Monday, on 25 November 2013. During his deposition, defendant testified that TSG and ACF shared certain customers, and that defendant is responsible for performing similar customer evaluations for ACF as he did at TSG.

TSG filed suit against defendant on 16 January 2014, alleging claims for breach of contract, misappropriation of trade secrets, and unfair and deceptive practices. TSG also moved for a preliminary injunction to prevent defendant from breaching the non-compete and misappropriating TSG's trade secrets. A confidential hearing was held on plaintiff's motion, and by order entered 20 February 2014, the trial court denied the motion for preliminary injunction. Plaintiff filed timely notice of appeal.

We must first address the interlocutory nature of plaintiff's appeal. Orders granting or denying preliminary injunctions are "interlocutory and thus generally not immediately reviewable. An appeal may be proper, however, in cases, including those involving trade secrets and non-compete agreements, where the denial of the injunction deprives the appellant of a substantial right which he would lose absent review prior to final determination." 

Accordingly, because both a non-compete and the potential misappropriation of trade secrets are implicated by this case, we conclude that plaintiff has succeeded in demonstrating how a substantial right may be lost without immediate appellate review; thus, we will reach the merits of the appeal.

[Discussion]{.casesection}

[Misappropriation of Trade Secrets]{.casesubsection}

Plaintiff first argues that the trial court erred by concluding that it has not demonstrated a likelihood of success on the merits of its claim for trade secret misappropriation. After careful review, we agree.

> As a general rule, a preliminary injunction is an extraordinary measure taken by a court to preserve the status quo of the parties during litigation. It will be issued only (1) if a plaintiff is able to show _likelihood_ of success on the merits of his case and (2) if a plaintiff is likely to sustain irreparable loss unless the injunction is issued, or if, in the opinion of the Court, issuance is necessary for the protection of a plaintiff's rights during the course of litigation.

The [Trade Secrets Protection Act](https://www.ncleg.gov/EnactedLegislation/Statutes/HTML/ByArticle/Chapter_66/Article_24.html) ("TSPA") allows for a private cause of action where a plaintiff can prove the "acquisition, disclosure, or use of a trade secret of another without express or implied authority or consent, unless such trade secret was arrived at by independent development, reverse engineering, or was obtained from another person with a right to disclose the trade secret." 

> "Trade secret" means business or technical information, including but not limited to a formula, pattern, program, device, compilation of information, method, technique, or process that:
> 
> a\. Derives independent actual or potential commercial value from not being generally known or readily ascertainable through independent development or reverse engineering by persons who can obtain economic value from its disclosure or use; and
> 
> b\. Is the subject of efforts that are reasonable under the circumstances to maintain its secrecy.

N.C. Gen.Stat. § 66-152(3) (2013). To determine what information should be treated as a trade secret for the purposes of protection under the TSPA, the Court should consider the following factors:

> (1\) the extent to which the information is known outside the business;
> 
> (2\) the extent to which it is known to employees and others involved in the business;
> 
> (3\) the extent of measures taken to guard secrecy of the information;
> 
> (4\) the value of the information to business and its competitors;
> 
> (5\) the amount of effort or money expended in developing the information; and
> 
> (6\) the ease or difficulty with which the information could properly be acquired or duplicated by others.

"Actual or threatened misappropriation of a trade secret may be preliminarily enjoined during the pendency of the action and shall be permanently enjoined upon judgment finding misappropriation." N.C. Gen. Stat. § 66-154(a).

> Misappropriation of a trade secret is prima facie established by the introduction of substantial evidence that the person against whom relief is sought both:

> (1\) Knows or should have known of the trade secret; and
> 
> (2\) Has had a specific opportunity to acquire it for disclosure or use or has acquired, disclosed, or used it without the express or implied consent or authority of the owner.

N.C. Gen.Stat. § 66-155.

Here, the trial court determined that plaintiff failed to demonstrate likelihood of success on the merits of its misappropriation of trade secrets claim for the following reasons: (1) plaintiff asserted that its finishing process "as a whole" was the trade secret for which it sought protection, and under the holding of _Analog Devices, Inc. v. Michalski,_ 157 N.C.App. 462 (2003), general processes are too vague to receive TSPA protection; and (2) defendant's familiarity with customer preferences was "more akin to general knowledge and skill acquired on the job than any trade secret maintained by plaintiff." For the following reasons, we disagree with the trial court's conclusions.

First, contrary to the trial court's assessment of the preliminary injunction hearing, plaintiff did not "continually assert" that it was the "combination of the components," or the "process as a whole," for which it sought protection. Although TSG's Chief Executive Officer Jack Rosenstein ("Rosenstein") did say that the entire equation of processes was a trade secret in and of itself, he also testified that the particular steps in the process were also trade secrets. As an example, Rosenstein highlighted the needle punch technique on a style data card that defendant had worked on during his time at TSG. The customer initially requested that the fabric be put through the needle punch machine one time at a specific setting. Through trial and error, defendant discovered that the customer's desired result could not be accomplished by running the needle punch machine one time at this setting, so he changed the process after experimenting with varying settings. Rosenstein testified the needle punch research for this client, in addition to the similar types of experimentation done to various processes throughout the finish equation, were trade secrets. Specifically, he testified as follows:

> ROSENSTEIN: That's all part of the trade secrets. That's all part of what defendant, in his own mind when he's looking at a new fabric, needs to determine—which Latex should be used, what density needs to be used, whether it needs to be needle punched or not and then within that which—which needle punch, what depth of penetration—exactly what the parameters are. Then he needs to determine what range it needs to go on, what speed needs to be run, what the finish is.
> 
> Q: And so each one of those variables impacts the other variables in the equation?
> 
> ROSENSTEIN: Yes.

Therefore, it was not just the process as a whole, but the specific knowledge defendant gained as to each discrete step in the process, that TSG sought to protect.

Based on _Analog Devices, Inc.,_ the trial court concluded that plaintiff had failed to "put forward enough facts to support trade secret protection over the process as a whole or any particular component such that the trial court would be justified in granting the injunction sought." However, the _Analog Devices, Inc._ Court upheld the denial of a preliminary injunction in part because the differences between the defendant's former and new employers "rendered the alleged trade secrets largely non-transferable." Furthermore, the Court determined that the plaintiff did not carry its burden of producing evidence specifically identifying the trade secrets it sought to protect. The evidence before the Court showed that some of the plaintiff's production techniques were "easily and readily reverse engineered," while others were "either generally known in the industry, are process dependent so as to preclude misappropriation, or are readily ascertainable by reverse engineering." Finally, regarding the processes used by the plaintiff, the Court found that there was substantial differences between the products of the two companies that would "require new experimentation and development of new ways to effectively identify efforts that will lead to successful development." Thus, the Court affirmed the trial court's denial of the preliminary injunction.

The facts of this case are readily distinguishable from _Analog Devices, Inc.,_ and they demonstrate that TSG would likely prevail on the merits of its claim for misappropriation of trade secrets. Using the factors enunciated by _Area Landscaping, L.L.C. v. Glaxo-Welcome, Inc.,_ 586 S.E.2d 507 (N.C. Ct. App. 2003), TSG presented sufficient evidence on its specific trade secrets to warrant protection. First, Rosenstein testified that the company spends $500,000.00 per year on research and development in order to create unique finishes and applications for his customers. Defendant testified that the results of his experimentation at TSG regarding specific process refinements were not known outside of TSG. Rosenstein also testified that defendant's work was not something that anyone else in the industry would know without years of trial and error by experienced technicians. Security measures were in place such that only top-level employees were familiar with the proprietary information defendant was in charge of developing. The trial court acknowledged in its order that TSG "maintains significant security measures over its finishing process." Indeed, TSG made its employees, customers, and facility visitors sign confidentiality forms to protect this information. Additionally, Rosenstein testified that defendant's disclosure of the trade secrets would give ACF the opportunity to save "untold amounts of hours, days, weeks, and months to come up with these finishes and these applications." Rosenstein testified that defendant could help ACF achieve their customers' desired results, which they sometimes shared with TSG, without spending the money on research and development that TSG invested. Defendant admitted as much in his deposition when he testified that he performs many of the same duties for ACF for some of the same customers that he formerly served at TSG. Therefore, unlike in _Analog Devices, Inc.,_ there was significant evidence showing that TSG's trade secrets were transferrable to ACF. Over the past two decades, TSG invested millions of dollars to develop and protect the information defendant compiled through his years of employment. The director of operations at TSG testified in deposition that defendant would sometimes work for more than a year on a process in order to achieve a desired result. There is no indication in the record that these process are able to be "reverse engineered" like those in _Analog Devices, Inc.,_ and it is undisputed that they are not generally known throughout the industry.

In sum, each of the factors identified by the _Area Landscaping, L.L.C._ Court weigh in plaintiff's favor. Plaintiff specifically identified the production factors for which it claims trade secret protection. Defendant acknowledged during his deposition that he performed research and development for these factors during his time at TSG and was responsible for keeping customer- and fabric-specific proprietary information regarding these processes on the style data cards. Therefore, we conclude that plaintiff has carried its burden of presenting evidence sufficient to identify the specific trade secrets protected by the TSPA.

Additionally, we hold that plaintiff presented _prima facie_ evidence of misappropriation of its trade secrets. "Direct evidence is not necessary to establish a claim for misappropriation of trade secrets; rather, such a claim may be proven through circumstantial evidence." Defendant testified that he is being asked to perform similar duties for ACF that he did at TSG, including evaluating customer needs and organizing production processes. Defendant acknowledged that TSG and ACF share customers and that he is currently working with multiple customers for ACF that he served at TSG. Specifically, he admitted that he had done independent research and experimentation for TSG on the needle punch, finish, and heating processes for one specific customer that he now serves at ACF, and that he talks about the various components of the TSG style data cards with ACF management personnel. This is precisely the type of threatened misappropriation, if not actual misappropriation, that the TSPA aims to prevent through issuance of a preliminary injunction. 

Based on the foregoing, we conclude that plaintiff demonstrated a likelihood of success on the merits of his claim for trade secret misappropriation.

## Employee Disloyalty

### @MiklinEnterprisesIncNLRB_8thCircuit2016

MikLin Enterprises, Inc. ("MikLin") petitions for review of a National Labor Relations Board ("Board") Order holding that MikLin violated Sections 8(a)(1) and 8(a)(3) of the National Labor Relations Act ("NLRA" or "the Act") when it (i) discharged and disciplined employees who publicly distributed posters suggesting that MikLin's "Jimmy John's" sandwiches posed a health risk to consumers; (ii) solicited employees to aid in removing the posters; (iii) encouraged employees to disparage a union supporter; and (iv) removed union literature from in-store bulletin boards. MikLin argues that the Board misapplied governing law and its decision is not supported by substantial evidence. The Board cross-petitions for enforcement of its Order. A divided panel enforced the Order in its entirety. We granted rehearing en banc and vacated the panel decision. We now conclude that the means the disciplined employees used in their poster attack were so disloyal as to exceed their right to engage in concerted activities protected by the NLRA, as construed in a controlling Supreme Court precedent, _NLRB v. Local Union No. 1229, IBEW_, 346 U.S. 464 (1953) ("Jefferson Standard"). We therefore decline to enforce the determination that MikLin violated the Act by disciplining and discharging those employees and by soliciting removal of the unprotected posters. We enforce the remainder of the Order, as so modified.

[Background.]{.casesection}

[The "Sick Day Posters" Campaign.]{.casesubsection}

MikLin is a family enterprise that owns and operates ten Jimmy John's sandwich-shop franchises in the Minneapolis-St. Paul area. Michael Mulligan is president and co-owner; Robert Mulligan, his son, is vice-president. In 2007, several MikLin workers began an organizing campaign seeking representation by the Industrial Workers of the World ("IWW") union. The IWW lost a Board-conducted election in October 2010, filed unfair labor practice charges and objections to the election with the Board, and continued its organizing campaign by urging MikLin to provide employees holiday pay in late 2010. On January 10, 2011, MikLin and the IWW settled the IWW's objections. MikLin admitted no wrongdoing but agreed to a Board-conducted rerun election if the IWW filed for the election after sixty days but not later than after eighteen months.

With the holiday season passed, the IWW decided its next "march on the boss" group action would be to demand paid sick leave. The IWW concluded that the approach of flu season was a good time to raise the issue. At this time, MikLin's handbook required any employee who would be absent from a shift to find a replacement and notify the store manager. Rule 11 of Jimmy John's Rules for Employment, which employees received when hired, stated: "Find your own replacement if you are not going to be at work. We do not allow people to simply call in sick! We require our employees and managers to find their own replacement! NO EXCEPTIONS!" Failure to follow this procedure resulted in termination. MikLin did not offer paid leave for sick employees, though an employee with sufficient tenure was entitled to paid leave to care for a sick child.

Organizers of the IWW sick leave campaign began their attack in late January and early February 2011 by designing and posting on community bulletin boards in MikLin stores posters that prominently featured two identical images of a Jimmy John's sandwich. Above the first image were the words, "YOUR SANDWICH MADE BY A HEALTHY JIMMY JOHN'S WORKER." The text above the second image said, "YOUR SANDWICH MADE BY A SICK JIMMY JOHN'S WORKER." "HEALTHY" and "SICK" were in red letters, larger than the surrounding text in white. Below the pictures, white text asked: "CAN'T TELL THE DIFFERENCE?" The response, in red and slightly smaller: "THAT'S TOO BAD BECAUSE JIMMY JOHN'S WORKERS DON'T GET PAID SICK DAYS. SHOOT, WE CAN'T EVEN CALL IN SICK." Below, in slightly smaller white text, was the warning, "WE HOPE YOUR IMMUNE SYSTEM IS READY BECAUSE YOU'RE ABOUT TO TAKE THE SANDWICH TEST." Text at the bottom of the poster asked readers to help the workers win paid sick days by going to their website.

MikLin managers quickly removed the posters from store bulletin boards. On the morning of March 10—the day before the IWW could request a rerun election—IWW supporters distributed a press release, letter, and the sandwich poster to more than one hundred media contacts, including local newspapers and major news outlets such as the Associated Press, Reuters, Bloomberg, and NBC News. The press release highlighted "unhealthy company behavior." Its second sentence framed the message: "As flu season continues, the sandwich makers at this 10-store franchise are sick and tired of putting their health and the health of their customers at risk." The release declared: "According to findings of a union survey, Jimmy John's workers have reported having to work with strep throat, colds and even the flu." The release ended with a threat: if Robert and Michael Mulligan would not talk with IWW supporters about their demands for paid sick leave, the supporters would proceed with "dramatic action" by "plastering the city with thousands of Sick Day posters."

Employees attached to the press release a "sick leave letter" to the Mulligans which asserted that health code violations occur at MikLin stores nearly every day. The employees complained: "By working sick, we are jeopardizing the entirety of the company's image and risking public safety." The letter accused MikLin of refusing to put customers first, risking customers' health, and "shoving customers to the bottom of the well of importance." Like the press release, the letter concluded with a threat: if the Mulligans would not meet the employees' demands, the campaign would "move forward with its Sick Day posters by posting them not only in stores, but on the University's Campus, in hospitals, on street corners, and any other place where postings are common, citywide."

Also on March 10, four organizers met with Robert Mulligan. They told Mulligan that MikLin's attendance policy and low wages pressured employees to work while sick. Mulligan said MikLin was in the process of reforming its policies. The organizers provided Mulligan a printed version of their letter and press release and warned that, unless MikLin took action to fix the sick day policy within ten days, employees would display sandwich posters throughout the area. Employees who attended felt they had achieved some "common ground."

MikLin posted a new sick leave policy in each store on March 16. The new policy provided a sliding scale of disciplinary points for absences. An employee who did not report but found a replacement would receive no points. An absent employee who could not find a replacement but notified the store manager at least one hour before shift start would receive one point. An absent employee without a replacement who called less than one hour prior to shift start would receive two points. An absent employee who did not call the manager and did not find a replacement would receive three points. An employee who received four disciplinary points within a twelve-month period would be terminated. The policy emphasized: "With regard to absenteeism due to flu like symptoms, Team Members are not allowed to work unless and until those symptoms have subsided for 24 hours." Between March 10 and March 20, MikLin posted a notice in its stores reminding workers: "for those who 'don't feel good' we have a policy that expects them to find a replacement for their shift. The record clearly shows that we have demonstrated flexibility with regard to excusing those who cannot find replacements."

On March 20, IWW supporters implemented their threat to plaster the city with a new version of the Sick Day posters they had placed in MikLin stores in January and February. The bottom of the publicly distributed posters incorporated one change: rather than asking for support of the employees' request for paid sick leave, the public posters listed Robert Mulligan's personal telephone number and instructed customers to call him to "LET HIM KNOW YOU WANT HEALTHY WORKERS MAKING YOUR SANDWICH!" A copy of the publicly distributed posters appears as Appendix A to this opinion. Organizers placed posters in various locations near MikLin stores, including lampposts, trash cans, and mailboxes. Robert Mulligan testified that he was "bombarded by phone calls" for close to a month from people who thought it was unsafe to eat at Jimmy John's. Concerned about the effect on MikLin's business, Mulligan and some managers took down the public posters. On March 22, MikLin fired six employees who coordinated the attack and issued written warnings to three who assisted.

The IWW continued its sick leave attack. In a press release issued a day after the terminations, a discharged employee stated: "It just isn't safe—customers are getting their sandwiches made by people with the flu, and they have no idea. Rather than safeguard public health and do the right thing for their employees and their customers, Jimmy John's owners Mike and Rob Mulligan are trying to silence us." On March 30, the IWW issued another press release stating that "customers have a right to know that their sandwich could be filled with germs," that IWW members have a duty to speak out on this "public health issue," and that employees "blew the whistle by posting 3000 copies of a poster advising the public of health risks at the sandwich chain." The release quoted one employee as stating: "The unfettered greed of franchise owner Mike Mulligan and Jimmy John Liautaud himself jeopardizes the health of thousands of customers and workers almost every day. We will speak out until they realize that no one wants to eat a sandwich filled with cold and flu germs."

[The NLRB Proceedings.]{.casesubsection}

Following a two-day evidentiary hearing, the Board's Administrative Law Judge ("ALJ") concluded that MikLin violated Sections 8(a)(1) and 8(a)(3) of the Act. Citing prior Board decisions, the ALJ ruled that "Section 7 29 U.S.C. § 157 protects employee communications to the public that are part of and related to an ongoing labor dispute," such as the Sick Day posters and related press releases, unless they are "so disloyal, reckless, or maliciously untrue as to lose the Act's protections." To lose Section 7 protection, "an employee's public criticism must evidence 'a malicious motive'" or be made with knowledge of the statements' falsity or with reckless disregard for their truth or falsity.

The ALJ found that the Sick Day posters were not maliciously untrue. While "it is not literally true that employees could not call in sick," the ALJ observed, employees "are subject to discipline if they call in sick without finding a replacement." Thus, the assertion, "SHOOT, WE CAN'T EVEN CALL IN SICK," was "protected hyperbole." The ALJ acknowledged record evidence that MikLin had served more than six million sandwiches over its ten-year existence and had been investigated by the Minnesota Department of Health only two times for food borne disease—once in 2006 and once in 2007, when the investigating sanitarian "noted overall compliance with food code requirements and no critical violations." The ALJ found, however, "it is at least arguable that MikLin's sick leave policy subjects the public to an increased risk of food borne disease," and MikLin "could have waged its own publicity campaign" to attract consumers. The ALJ made no mention of the false assertion in the open letter accompanying the IWW press release that health code violations occurred at MikLin stores nearly every day. Nor did the ALJ even attempt to analyze and apply the disloyalty principle of Jefferson Standard.

A divided panel of the Board affirmed the ALJ's findings and conclusions. The majority concluded "that neither the posters nor the press release were shown to be so disloyal, reckless, or maliciously untrue as to lose the Act's protection." The public communications "were clearly related to the ongoing labor dispute concerning the employees' desire for paid sick leave. Indeed, any person viewing the posters and press release would reasonably understand that the motive for the communications was to garner support for the campaign to improve the employees' terms and conditions of employment by obtaining paid sick leave rather than to disparage MikLin or its product." Nor were any of the statements maliciously untrue.

Turning to the question of disloyalty, the majority noted that "Board law has developed considerably in its approach to the question of employee disloyalty." "To lose the Act's protection as an act of disloyalty, an employee's public criticism of an employer must evidence a malicious motive," even if the public communication "raises highly sensitive issues such as public safety." Accepting the majority's summary of prior Board decisions, the dissenting Member would nonetheless have held the Sick Day posters and press release unprotected, because "it is well established that employees lose the Act's protection if their means of protest are 'flagrantly disloyal, wholly incommensurate with any grievances which they may have, and manifested by public disparagement of the employer's product or undermining of its reputation,'".

["Sick Day" Poster Issues.]{.casesection}

It is well established that an employer commits an unfair labor practice if it discharges employees for engaging in concerted activities that are protected by Section 7 of the NLRA, including communications to third parties or to the public that seek to "improve their lot as employees through channels outside the immediate employee-employer relationship." Section 10(c) of the Act, however, expressly limits the Board's broad authority to remedy unlawful employee discharges: "No order of the Board shall require the reinstatement of any individual as an employee if such individual was suspended or discharged for cause." The interplay between Section 7 and Section 10(c) was the critical question the Supreme Court addressed in Jefferson Standard.

A\. In Jefferson Standard, the Court upheld the Board's decision that a broadcasting station did not violate the Act when it fired technicians who distributed handbills "making a sharp, public, disparaging attack upon the quality of the company's product and its business policies, in a manner reasonably calculated to harm the company's reputation and reduce its income." After bargaining negotiations broke down, employees first picketed the station for treating its employees unfairly. When this tactic failed, the employees distributed thousands of handbills, signed "WBT Technicians," criticizing the station's poor programming quality and asserting that Jefferson Standard did not value its customers and considered the local city to be a "second-class community." The Board found the employee handbills unprotected because the technicians "deliberately undertook to alienate their employer's customers by impugning the technical quality of his product." Though the technicians' purpose was "to extract a concession from the employer with respect to the terms of their employment," the Board found that they lost the Act's protection when they failed to disclose their interests as employees. The Board reasoned that the technicians lost the Act's protection because "the gist of the technicians' appeal to the public was that the employer ought to be boycotted because he offered a shoddy product to the consuming public—not because he was 'unfair' to the employees who worked on that product." The Board declined to decide whether the product disparagement in the handbills would justify discharge "had it been uttered in the context of a conventional appeal for support of the union in the labor dispute."

The Supreme Court, in affirming the Board, decided the case on broader grounds. After quoting the "for cause" language of Section 10(c), the Court declared that "there is no more elemental cause for discharge of an employee than disloyalty to his employer." Congress in the NLRA "did not weaken the underlying contractual bonds and loyalties of employer and employee." Absent a labor controversy, the technicians' conduct "unquestionably would have provided adequate cause for their disciplinary discharge within the meaning of § 10(c). The fortuity of the coexistence of a labor dispute affords these technicians no substantial defense." Thus, the handbill attack targeting "the quality of the company's product was as adequate a cause for the discharge of its sponsors as if the labor controversy had not been pending." Though the Court noted several times that the technicians failed to disclose a connection between their labor dispute and the handbill attack, the Court declined to remand for further consideration of whether the handbills were an "appeal for support in the pending dispute," rather than "a concerted separable attack," because the attack would be unprotected either way:

> Even if the attack were to be treated, as the Board has not treated it, as a concerted activity wholly or partly within the scope of those mentioned in § 7, the means used by the technicians in conducting the attack have deprived the attackers of the protection of that section, when read in the light and context of the purpose of the Act.

The Supreme Court's decision not to remand in Jefferson Standard made clear that the Court's disloyalty ruling includes communications that otherwise would fall within Section 7 protection, if those communications "make a sharp, public, disparaging attack upon the quality of the company's product and its business policies, in a manner reasonably calculated to harm the company's reputation and reduce its income." In _NLRB v. Washington Aluminum Co._, 370 U.S. 9 (1962), the Court confirmed that Section 10(c) "cannot mean that an employer is at liberty to punish a man by discharging him for engaging in concerted activities which § 7 of the Act protects." But the Court explained that Jefferson Standard "denied the protection of § 7 to activities characterized as 'indefensible' because they were there found to show a disloyalty to the workers' employer which the Court deemed unnecessary to carry on the workers' legitimate concerted activities." Thus, we reject the dissent's suggestion that Jefferson Standard does not apply in this case because the employees' disparaging communications "expressly referenced ongoing labor disputes." 

B\. Board decisions applying Jefferson Standard initially recognized that employers may protect their businesses from detrimental product disparagement whether or not an employee attack referenced a labor dispute. _See_ _Patterson-Sargent Co_., 115 N.L.R.B. 1627 (1956) (employees' handbill asserting replacement workers produced defective paint was unprotected "public disparagement of the quality of the employer's product"); _Coca Cola Bottling Works, Inc_., 186 N.L.R.B. 1050 (1970) (employees' leaflet warning that inexperienced workers could leave objects such as roaches, bugs, and dead mice in the company's bottles was "the very type of disparaging conduct" held unprotected in Jefferson Standard).

Though the Supreme Court's interpretation of the NLRA in Jefferson Standard remains unchanged, "Board law has developed considerably in its approach to the question of employee disloyalty." In 1987, the Board articulated its modern interpretation: "Jefferson Standard held that employees may engage in communications with third parties in circumstances where the communication is related to an ongoing labor dispute and when the communication is not so disloyal, reckless, or maliciously untrue to lose the Act's protection." Although Jefferson Standard did not involve employee public communications that were reckless or maliciously untrue, we do not question the Board's view that such communications are not entitled to the protection of Section 7 as limited by Section 10(c).

The issue in this case is the Jefferson Standard disloyalty principle—Section 10(c) permits an employer to fire an employee for "making a sharp, public, disparaging attack upon the quality of the company's product and its business policies, in a manner reasonably calculated to harm the company's reputation and reduce its income." On this issue, while always purporting to apply Jefferson Standard's holding, the Board has migrated to a severely constrained interpretation of that decision. "To lose the Act's protection as an act of disloyalty, an employee's public criticism of an employer must evidence a malicious motive." "Even communications that raise highly sensitive issues such as public safety are protected where they are sufficiently linked to a legitimate labor dispute and are not maliciously motivated to harm the employer."

In our view, the Board fundamentally misconstrued Jefferson Standard in two ways. First, while an employee's subjective intent is of course relevant to the disloyalty inquiry—"sharp, public, disparaging attack" suggests an intent to harm—the Jefferson Standard principle includes an objective component that focuses, not on the employee's _purpose,_ but on the _means_ used—whether the disparaging attack was "reasonably calculated to harm the company's reputation and reduce its income," to such an extent that it was harmful, indefensible disparagement of the employer or its product. By holding that _no_ act of employee disparagement is unprotected disloyalty unless it is "maliciously motivated to harm the employer," the Board has not interpreted Jefferson Standard—it has overruled it.

Second, the Board's definition of "malicious motive" for these purposes excludes from Jefferson Standard's interpretation of Section 10(c) all employee disparagement that is part of or directly related to an ongoing labor dispute. While the employees "may have anticipated that some members of the public might choose not to patronize MikLin's restaurants after reading the posters or press release," the Board ruled, their public communications were protected activity because "there is no evidence that their purpose was to inflict harm on MikLin." Rather, "they were motivated by a sincere desire to improve their terms and conditions of employment." In other words, the Board refuses to treat as "disloyal" any public communication intended to advance employees' aims in a labor dispute, regardless of the manner in which, and the extent to which, it harms the employer. As the Court held in Jefferson Standard that its disloyalty principle would apply even if the employees had explicitly related their public disparagement to their ongoing labor dispute, once again the Board has not interpreted Jefferson Standard—it has overruled it.

By requiring an employer to show that employees had a subjective intent to harm, and burdening that requirement with an overly restrictive need to show "malicious motive," the Board has effectively removed from the Jefferson Standard inquiry the central Section 10(c) issue as defined by the Supreme Court—whether the means used reflect indefensible employee disloyalty. This is an error of law. Our prior cases confirm that an employee's disloyal statements can lose Section 7 protection without a showing of actual malice. In _St. Luke's_, we expressly rejected the contention that public disparagement of an employer "was protected activity unless maliciously false." We explained that cases interpreting Jefferson Standard "establish that an employee exceeds the boundaries of protected activity when she falsely and publicly disparages her employer or its products and services." By requiring proof that disloyal conduct was the product of a malicious motive, the Board fundamentally misinterpreted both Jefferson Standard and our decisions construing and applying Jefferson Standard.

Rather than employee motive, the critical question in the Jefferson Standard disloyalty inquiry is whether employee public communications reasonably targeted the employer's labor practices, or indefensibly disparaged the quality of the employer's product or services. The former furthers the policy of the NLRA; the latter does not. This distinction focuses on the type of harm employees' methods cause. When employees convince customers not to patronize an employer because its labor practices are unfair, subsequent settlement of the labor dispute brings the customers back, to the benefit of both employer and employee. By contrast, sharply disparaging the employer's product or services as unsafe, unhealthy, or of shoddy quality causes harm that outlasts the labor dispute, to the detriment of all employees as well as the employer. 

D\. Turning to the merits of this case, we review the Board's factual findings for "substantial evidence on the record as a whole." Substantial evidence supports the Board's findings that the employees' Sick Day posters and press releases were related to their protected concerted effort to improve the terms and conditions of their employ by obtaining paid sick leave. Communications asking the public to support this effort may be within the protection of Section 7 even though they address a sensitive issue, like sick leave in the food service industry. Delineating the boundaries of "indefensible" third-party communications is more difficult when this connection is present. But as a matter of law, the Board erred in concluding that the employees' product disparagement was protected Section 7 activity simply because its purpose was to obtain paid sick days. Even communications connected to a labor dispute are unprotected when they constitute a "sharp, public, disparaging attack upon the quality of the company's product and its business policies." 

The attack was "sharp," proceeding "in a manner reasonably calculated to harm the company's reputation and reduce its income." The posters, press releases, and letter were an effective campaign to convince customers that eating Jimmy John's sandwiches might cause them to become sick. The Sick Day poster warned that the reader was "about to take the sandwich test." Its enduring image was a MikLin-made Jimmy John's sandwich that, although appearing like any other, was filled with cold and flu germs. As in Jefferson Standard, the employees were not on strike, but continued to work and collect wages as they attempted to scare customers away from their employer and its products. "Nothing could be further from the purpose of the Act than to require an employer to finance such activities." 

Allegations that a food industry employer is selling unhealthy food are likely to have a devastating impact on its business, what the D.C. Circuit called the "equivalent of a nuclear bomb" in a labor-relations dispute. MikLin's employees maximized this effect, choosing March as a "good time" to launch their attack "because it was flu season." The employees understood that MikLin's business was dependent on its "clean" public image, yet directly attacked that image. Like the technicians in Jefferson Standard, the MikLin employees accused their employer of not valuing its customers. By targeting the food product itself, employees disparaged MikLin in a manner likely to outlive, and also unnecessary to aid, the labor dispute. Even if MikLin granted paid sick leave, the image of contaminated sandwiches made by employees who chose to work while sick was not one that would easily dissipate.

The employees' public claims about their employer's product were also "materially false and misleading." The Sick Day poster graphically told customers that sandwich makers were working when sick by falsely stating, "Shoot, we can't even call in sick." The press release and open letter claimed that MikLin jeopardized customers' health by the almost daily health code violations occurring at MikLin's stores. Yet the IWW supporters knew MikLin complied with Minnesota Department of Health regulations by requiring employees to call in sick if they had experienced flu-like symptoms in the last 24 hours. As the ALJ noted: "Given MikLin's record over a 10-year period one could regard the risk of becoming ill by eating at one of its shops to be infinitesimal." This factor made the MikLin employees' attack even more "indefensible" than that at issue in Jefferson Standard, where the technicians "did not misrepresent, at least willfully, the facts they cited to support their disparaging report." As dissenting Board Member Johnson stated, "Any employee who is willing to make up allegations out of whole cloth against his or her employer is obviously far more disloyal, in any meaningful sense of that word, than one who acts upon a reasonable but mistaken belief." 

From the array of possible tactics, the employees selected public communications that were sure "to harm MikLin's reputation and reduce its income." This was a "continuing attack upon the very interests which the attackers were being paid to conserve and develop." The Act does not protect such calculated, devastating attacks upon an employer's reputation and products. Although applying Jefferson Standard's disloyalty principle is often difficult, the employees' third-party communications demonstrated "such detrimental disloyalty as to provide 'cause'" for MikLin to discharge and discipline those responsible for the campaign. We decline to enforce the Board's contrary Order.

E\. After learning that IWW supporters were about to "plaster" the area surrounding MikLin stores with Sick Day posters, Robert Mulligan posted this message on an employee-created "Jimmy John's Anti-Union" Facebook page:

> The IWW are threatening to put up thousands of posters that threaten our business and your jobs. They plan on doing this if we don't meet with them which we will not do. I encourage anyone to take down any posters they may see around the twin cities. These posters are defamatory.

The ALJ concluded this post violated Section 8(a)(1) because its target, the sandwich posters, was concerted activity protected by Section 7. The Board affirmed the ALJ, one member dissenting. Section 8(a)(1) forbids employers to "interfere with, restrain, or coerce" employees in the exercise of their Section 7 rights. Because we conclude the posters were not protected Section 7 activity, substantial evidence does not support the Board's decision. Soliciting employees to remove unprotected public communications did not "interfere with, restrain or coerce" employees in their exercise of Section 7 rights. We decline to enforce this portion of the Board's Order.

### @FoodLionIncCapital_MDNC1996

This matter is before the Court on Defendants' Renewed Motion to Dismiss Plaintiff's Claims of Breach of Fiduciary Duty/Constructive Fraud and Unfair or Deceptive Trade Practices, or in the Alternative, for Summary Judgment For the reasons stated below, Defendants' Motion is DENIED.

[I.]{.casesection}

Defendants Lynne Litt and Susan Barnett are both employed by the ABC news program _Prime Time Live._ The television show at some point determined that it would prepare and broadcast a story on Food Lion stores. In an attempt to gain access to parts of Food Lion stores not generally open to the public, Litt and Barnett applied for positions of employment with Food Lion. Both provided false information to Food Lion in order to obtain a position. Barnett was eventually employed as a deli clerk in a store in South Carolina. Litt was employed as a meat wrapper in North Carolina. During the brief period of their employment, each wore a hidden camera, secreted in a wig, into work areas and recorded video footage. Some of this footage was ultimately used in a _Prime Time Live_ broadcast which was highly critical of Food Lion. This lawsuit arises as a result of these actions.

Two of Food Lion's claims are at issue here. Food Lion claims that Litt and Barnett, as Food Lion employees, owed Food Lion a duty of loyalty and that they violated that duty by serving another, undisclosed, master while "working" for Food Lion. In addition, Food Lion claims that the actions of Defendants were unfair and deceptive acts which violated the North Carolina Unfair Trade Practices Act.

[III.]{.casesection}

[A. Fiduciary Duty]{.casesubsection}

Defendants maintain that there can be no violation of fiduciary duty because there never was a fiduciary relationship for Litt and Barnett to violate. For a fiduciary relationship to exist, according to Defendants, there must be a relationship of special confidence or access to confidential information. In some contexts, Defendants' contentions might be correct. To the contrary, however, it appears both the North Carolina and South Carolina Supreme Courts likely would recognize a broader claim.

In its Amended Complaint, Plaintiffs state that Litt and Barnett "owed Food Lion a fiduciary duty of unselfish and undivided loyalty." The complaint goes on to list poor job performance, as well as the appropriation of information, as possible violations of that duty. Under the liberal notice pleading requirements of the Federal Rules of Civil Procedure, Plaintiff's complaint can be fairly read as stating a claim for relief not confined to violation of a duty based on a confidential relationship.

Both the North Carolina and South Carolina courts seem to recognize a duty of loyalty in the employment context which is not confined to maintaining employer confidences. _See, e.g.,_ _McKnight v. Simpson's Beauty Supply, Inc.,_ 358 S.E.2d 107 (N.C.Ct.App. 1987) (stating that "the law implies a promise on the part of every employee to serve his employer faithfully and discharge his duties with reasonable care and attention."); _Long v. Vertical Technologies, Inc.,_ 113 N.C.App. 598, 439 S.E.2d 797 (1994) (stating that disloyalty of employees was a violation of "their fiduciary duty of good faith, fair dealing and loyalty"); _Lowndes Prods., Inc. v. Brower,_ 259 S.C. 322 (stating that "an employee has a duty of fidelity to his employer apart from the question whether he has an obligation to maintain the employer's processes and systems of operation in confidence."). There is a cause of action for violation of the duty of loyalty. Since the courts recognize the existence of a duty of loyalty, it follows that they would recognize a claim for breach of that duty and that Food Lion's claim should not be dismissed under Rule 12(b)(6).

As discussed, an employee has a duty to use her efforts, while working, for the service of her employer. The potential violation of that duty here lies in Litt and Barnett being employed by Food Lion and ABC at the same time. Food Lion did not know of their affiliation with ABC. Meanwhile, ABC not only knew of the affiliation with Food Lion but in fact sent the two to work in Food Lion stores in order to serve the objectives of ABC.

The Restatement (Second) of Agency provides that "a person may be the servant of two masters at one time as to one act, if the service to one does not involve abandonment of the service to the other." A reasonable jury could find that, because of Litt's and Barnett's affiliation with and allegiance to ABC, they did not adequately perform their duties while working with Food Lion. This is a genuine issue of material fact which precludes summary judgment on this issue.

Defendants further argue that the remedy when an employee does not use her best efforts in the service of her employer is to discharge that employee. While this is one remedy, it is not the only one in this situation. The North Carolina Court of Appeals has allowed an employer to recover the fair value of the services that the plaintiffs supplied to another venture while the plaintiffs were employees of the defendant. If the jury finds that Litt and Barnett did not adequately perform their Food Lion jobs because of a motivation to serve the interests of ABC, then Defendants could be liable, at least, for the fair value of the services Litt and Barnett deprived Food Lion while serving the interests of their undisclosed master, ABC.

Plaintiff seems to contemplate a very broad duty of loyalty. For instance, Plaintiff states that "this duty applies not only to information denominated as confidential, but also to information which the employee should know that the employer would not want revealed to others." If this language were applied to the facts of this case, the result would be more far reaching than is reasonable.

In addition to the claims that Litt and Barnett were substandard employees because of their loyalty to ABC and that they disclosed information learned during the time they held their Food Lion positions, Food Lion also claims that Litt and Barnett "staged" many of the scenes which appear in the hidden camera tapes and which subsequently were broadcast on the _PrimeTime Live_ broadcast. Plaintiff claims that such "staging" was a further breach of the duty of loyalty. The essence of the duty of loyalty contemplated here is that an employee has a duty to use her efforts, while on the job, in the furtherance of her employer's objectives and that a factual question may be created if the employee is attempting to serve two masters at the same time. Evidence of "staging" may be relevant to the jury's determination of whether Litt and Barnett were devoting their best efforts to Food Lion or were in fact more interested in serving the interests of ABC. Examples of conduct where Litt or Barnett disobeyed instructions or failed to adequately perform the duties of their Food Lion jobs, if they occurred, could show a breach of the duty of loyalty owed to Food Lion. Further, if these episodes were subsequently broadcast, then the jury could find part of the damage Food Lion suffered as a result of the _PrimeTime Live_ story resulted from Litt's and Barnett's violation of fiduciary duty.

::: {.callout-note}

In addition to breach of their duty of loyalty as employees, Litt and Barnett were also found liable for trespass. Food Lion was awarded a total of $2 in damages for those claims. See @FoodLionIncCapital_4thCircuit1999 (affirming in part and reversing in part). 

:::

### @DaltonCamp_NC2001

This case arises out of an employer's allegations of unfair competitive activity by former employees and a new corporation formed by them. Plaintiff Robert Earl Dalton d/b/a B. Dalton & Company ("Dalton") produced, under a thirty-six month contract, an employee newspaper for Klaussner Furniture Industries ("KFI"). Dalton hired defendant David Camp ("Camp") to produce the publication and subsequently hired Nancy Menius ("Menius") to assist in the production of the employee newspaper. Near the conclusion of the contract period, Dalton began negotiations with KFI to continue publication. After the contract had expired, Dalton continued to publish the employee newspaper without benefit of a contract while talks between the parties continued. During this period, Camp, who was contemplating leaving Dalton's employ, established a competing publications entity, Millennium Communication Concepts, Inc. ("MCC"), and discussed with KFI officials the possibility of replacing Dalton as publisher of KFI's employee newspaper. Soon thereafter, Camp entered into a contract with KFI to produce the newspaper. He resigned from Dalton's employment approximately two weeks later.

In the wake of Camp's resignation, Dalton sued Camp, Menius, and MCC for breach of the fiduciary duty of loyalty, conspiracy to appropriate customers, tortious interference with contract, interference with prospective advantage, and unfair and deceptive acts or practices under chapter 75 of the North Carolina General Statutes. The trial court first dismissed Dalton's claim for tortious interference with contract and subsequently granted Camp's motion for summary judgment against Dalton for the remaining claims. In its initial review of the case, the Court of Appeals held that the trial court had properly granted summary judgment for all defendants as to the claim for unfair and deceptive trade practices. As for the claim for breach of duty of loyalty, the Court of Appeals held that summary judgment was proper for defendant Menius and improper for defendant Camp. As for Dalton's claim of tortious interference with prospective advantage, the Court of Appeals again held that summary judgment was properly granted for defendant Menius and improperly granted for defendant Camp. After this Court remanded the case to the Court of Appeals for further review, the Court of Appeals ultimately concluded that summary judgment was properly granted for: (1) all claims against Menius, and (2) the conspiracy to appropriate customers claim against Camp and MCC. The court also held that summary judgment was improperly granted for: (1) the breach of duty of loyalty claim against Camp, (2) the interference with prospective advantage claim against Camp and MCC, and (3) the unfair and deceptive trade practices claim against Camp and MCC.

For the reasons set forth below, we hold that the trial court properly granted summary judgment for all applicable claims, and we reverse those portions of the Court of Appeals opinion that hold otherwise. Thus, in sum, none of plaintiff Dalton's claims survive.

[I.]{.casesection}

We begin our analysis with an examination of Dalton's first claim against Camp which, as described in Dalton's complaint, constituted a breach of fiduciary duty, including a duty of loyalty. From the outset, we note that Dalton argues this claim from two distinct vantage points. First, he alleges that Camp breached his fiduciary duty by being disloyal. Second, he argues that a separate and distinct action for breach of duty of loyalty exists and that Camp's conduct constituted a breach of that duty. We disagree with both contentions, holding that Dalton has failed to establish: (1) facts supporting a breach of fiduciary duty, and (2) that any independent tort for breach of duty of loyalty exists under state law.

The question before us is whether the Court of Appeals properly concluded that genuine issues of material fact existed as to Dalton's claims against Camp for breach of fiduciary duty and/or breach of duty of loyalty. We address the specifics of Dalton's arguments supporting the Court of Appeals decision in successive order.

For a breach of fiduciary duty to exist, there must first be a fiduciary relationship between the parties. Such a relationship has been broadly defined by this Court as one in which "there has been a special confidence reposed in one who in equity and good conscience is bound to act in good faith and with due regard to the interests of the one reposing confidence, and 'it extends to any possible case in which a fiduciary relationship exists in fact, and in which there is confidence reposed on one side, and _resulting domination and influence on the other_.'" However, the broad parameters accorded the term have been specifically limited in the context of employment situations. Under the general rule, "the relation of employer and employee is not one of those regarded as confidential." _King v. Atlantic Coast Line R.R. Co.,_ 157 N.C. 44 (1911); _see also_ _Hiatt v. Burlington Indus., Inc.,_ 55 N.C.App. 523 (1982).

In applying this Court's definition of fiduciary relationship to the facts and circumstances of the instant case—in which employee Camp served as production manager for a division of employer Dalton's publishing business—we note the following: (1) the managerial duties of Camp were such that a certain level of confidence was reposed in him by Dalton; and (2) as a confidant of his employer, Camp was therefore bound to act in good faith and with due regard to the interests of Dalton. In our view, such circumstances, as shown here, merely serve to define the nature of virtually all employer-employee relationships; without more, they are inadequate to establish Camp's obligations as fiduciary in nature. No evidence suggests that his position in the workplace resulted in "domination and influence on the other Dalton," an essential component of any fiduciary relationship. Camp was hired as an at-will employee to manage the production of a publication. His duties were those delegated to him by his employer, such as overseeing the business's day-to-day operations by ordering parts and supplies, operating within budgetary constraints, and meeting production deadlines. In sum, his responsibilities were not unlike those of employees in other businesses and can hardly be construed as uniquely positioning him to exercise dominion over Dalton. Thus, absent a finding that the employer in the instant case was somehow subjugated to the improper influences or domination of his employee—an unlikely scenario as a general proposition and one not evidenced by these facts in particular—we cannot conclude that a fiduciary relationship existed between the two. As a result, we hold that the trial court properly granted defendant Camp's motion for summary judgment as to Dalton's claim alleging a breach of fiduciary duty and reverse the Court of Appeals on this issue.

As for any claim asserted by Dalton for breach of a duty of loyalty (in an employment-related circumstance) outside the purview of a fiduciary relationship, we note from the outset that: (1) no case cited by plaintiff recognizes or supports the existence of such an independent claim, and (2) no pattern jury instruction exists for any such separate action. We additionally note that Dalton relies on cases he views as defining an independent duty of loyalty, even though those cases were devoid of claims or counterclaims alleging a breach of such duty. In _McKnight v. Simpson's Beauty Supply,_ 86 N.C.App. 451 (1987), the Court of Appeals held that every employee was obliged to "serve his employer faithfully and discharge his duties with reasonable diligence, care and attention." However, the rule's role in deciding the case was limited; it was but a factor in determining whether an employer was justified in terminating an employee. The circumstance and conclusion reached in _In re Burris,_ 263 N.C. 793, 140 S.E.2d 408 (1965) are strikingly similar. At issue in that case was whether a civil service employee was properly discharged after he "knowingly brought about a conflict of interest between himself and his employer." In deciding the case, this Court wrote "where an employee deliberately acquires an interest adverse to his employer, he is disloyal, _and his discharge is justified_." Conspicuously absent from the _Burris_ Court's consideration was any claim or counterclaim seeking damages resulting from an alleged breach of a duty of loyalty.

In our view, if _McKnight_ and _Burris_ indeed serve to define an employee's duty of loyalty to his employer, the net effect of their respective holdings is limited to providing an employer with a defense to a claim of wrongful termination. No such circumstance is at issue in the instant case, in which Camp resigned from Dalton's employ. Thus, we hold that: (1) there is no basis for recognizing an independent tort claim for a breach of duty of loyalty; and (2) since there was no genuine issue as to any material fact surrounding the claim as stated in the complaint (breach of fiduciary duty, including a duty of loyalty), the trial court properly concluded as a matter of law that summary judgment was appropriate for Camp.

To the extent that the holding in _Food Lion, Inc. v. Capital Cities/ABC, Inc.,_ 951 F.Supp. 1224 (M.D.N.C.1996), can be read to sanction an independent action for breach of duty of loyalty, we conclude that the federal district court incorrectly interpreted our state case law by assuming that: (1) "since the state's courts recognize the existence of the duty of loyalty, it follows that they _would_ recognize a claim for breach of that duty,"; and (2) the "North Carolina Supreme Court _likely would_ recognize a broader claim" for a breach of fiduciary duty. As previously explained, although our state courts recognize the existence of an employee's duty of loyalty, we do not recognize its breach as an independent claim. Evidence of such a breach serves only as a justification for a defendant-employer in a wrongful termination action by an employee. Moreover, an examination of our state's case law fails to reveal support for the federal district court's contention that this Court would broaden the scope of fiduciary duty to include food-counter clerks employed by a grocery store chain.

As for the holding in _Long v. Vertical Technologies, Inc.,_, 439 S.E.2d 797 (N.C. Ct. App. 1994) we note that the corporate employer in that case was awarded damages for "a material breach of fiduciary duty of good faith, fair dealing and loyalty" by its employees. Essentially, the _Long_ court determined that the employees, who originally founded the company in question and served respectively as its president and senior vice president, owed a fiduciary duty to the parent firm and that they breached that duty by taking actions contrary to the parent firm's best interests. Thus, the claim and damages awarded in _Long_ resulted from: (1) a showing of a fiduciary relationship, (2) thereby establishing a fiduciary duty, and (3) a breach of that duty. No such fiduciary relationship or duty is evidenced by the circumstances of the instant case.

[II.]{.casesection}

As for Dalton's claim against Camp and MCC for tortious interference with prospective advantage, this Court has held that "interference with a man's business, trade or occupation by maliciously inducing a person not to enter a contract with a third person, which he would have entered into but for the interference, is actionable if damage proximately ensues." 

In applying the law to the circumstances of the instant case, we note the following: (1) under contract, Dalton had published a newsletter to the expressed satisfaction of KFI for thirty-six months; (2) at or about the time that the original contract expired, Dalton and KFI discussed renewing the deal; (3) such negotiations reached an impasse over two key terms (duration of the new contract and price); (4) in the aftermath of the expired original contract, the parties agreed that Dalton would continue to publish the newsletter on a month-to-month basis; (5) during this negotiating period, Camp formed a rival publishing company (MCC); and (6) while still in the employ of Dalton, Camp (representing MCC) entered into a contract with KFI to publish its newsletter. Approximately two weeks after signing the KFI deal, Camp resigned his position with Dalton, presumably in order to run MCC with his partner, Menius.

Although the facts confirm that Camp joined the negotiating fray at a time when Dalton and KFI were still considering a contract between themselves, thereby establishing a proper time frame for tortious interference, two other obstacles undermine Dalton's claim. First, there is no evidence suggesting that Camp induced, no less maliciously induced, KFI into entering a contract. According to testimony from the deposition of Mark Walker, KFI's human resources director, it was he who approached Camp about assuming the newsletter contract, not vice versa. Moreover, Dalton admitted in his own deposition that he had no personal knowledge as to the specifics of who offered what amid conversations between Camp and Walker. Thus, nothing in the record reflects an improper inducement on the part of Camp.

Second, while Dalton may have had an expectation of a continuing business relationship with KFI, at least in the short term, he offers no evidence showing that but for Camp's alleged interference a contract would have ensued. After Dalton's original contract expired, he met with KFI to discuss terms for a possible renewal. During the negotiation period, the parties agreed that Dalton would continue publishing the newsletter on an interim basis. However, with regard to a new contract, KFI said it wanted a discount from the original contract price. In response, Dalton said he could not reduce the price as he was not making any profit on the publication. KFI, through Walker, then urged Dalton to consider the matter further and get back to the company, which, by his own admission, Dalton never did. In our view, such circumstances fail to demonstrate that a Dalton KFI contract would have ensued.

The absence of evidence supporting two essential elements of a party's allegation of interference with prospective advantage—intervenor's inducement of a third party and a showing that a contract would have ensued—exposes a fatal weakness in that claim. As a result, we hold that the trial court properly granted summary judgment for both Camp and his company, MCC, and thus reverse the Court of Appeals on this issue.

[III.]{.casesection}

Dalton additionally argues that he has presented a genuine question of material fact as to alleged unfair and deceptive trade practices of Camp and MCC. Again, we disagree.

The extent of trade practices deemed as unfair and deceptive is summarized in N.C.G.S. § 75-1.1(a) ("the Act"), which provides: "Unfair methods of competition in or affecting commerce, and unfair or deceptive acts or practices in or affecting commerce, are declared unlawful." The Act was intended to benefit consumers, but its protections extend to businesses in appropriate situations. 

Although this Court has held that the Act does not normally extend to run-of-the-mill employment disputes, we note that the mere existence of an employer-employee relationship does not in and of itself serve to exclude a party from pursuing an unfair trade or practice claim. For example, employers have successfully sought damages under the Act when an employee's conduct: (1) involved egregious activities outside the scope of his assigned employment duties, and (2) otherwise qualified as unfair or deceptive practices that were in or affecting commerce. 

In order to establish a _prima facie_ claim for unfair trade practices, a plaintiff must show: (1) defendant committed an unfair or deceptive act or practice, (2) the action in question was in or affecting commerce, and (3) the act proximately caused injury to the plaintiff. A practice is unfair if it is unethical or unscrupulous, and it is deceptive if it has a tendency to deceive. The determination as to whether an act is unfair or deceptive is a question of law for the court. As for whether a particular act was one "in or affecting commerce," we note that N.C.G.S. § 75-1.1(b) defines "commerce" inclusively as "business activity, however denominated." We also note that while the statutory definition of commerce crosses expansive parameters, it is not intended to apply to all wrongs in a business setting. Examples of business activity beyond the scope of the statutory definition include: professional services; most employer-employee disputes; and securities transactions. Moreover, "some type of _egregious_ or _aggravating_ circumstances must be alleged and proved before the Act's provisions may take effect." 

Application of the aforementioned law to the circumstances underlying the dispute between Dalton and Camp serves a two-fold purpose. By helping to illustrate the distinguishing characteristics between the instant case and _Sara Lee Corp. v. Carter,_ 351 N.C. 27 (1999)—a case in which an employer successfully pursued an unfair and deceptive trade practices claim against an employee—the analysis simultaneously demonstrates why Camp's actions did not amount to unfair or deceptive trade practices.

In _Sara Lee_, this Court concluded that "defendant's relationship to plaintiff as an employee, _under these facts,_ does not preclude applicability of N.C.G.S. § 75-1.1." In the Court's view, the defendant: (1) had fiduciary duties, and (2) was entrenched in buyer-seller transactions that fell squarely within the Act's intended reach. While serving as a purchasing agent for Sara Lee, defendant was simultaneously selling parts to his employer at inflated prices, a scheme characterized by the Court as self-dealing conduct "in or affecting commerce." As a consequence, the Court held that it would not permit the defendant to use his employment status as a _de facto_ defense against his employer's unfair and deceptive trade practices claim.

In contrast, the two parties in the instant case were not in a fiduciary relationship. Thus, employee Camp was unencumbered by fiduciary duties, a significant distinction between him and the employee-defendant in _Sara Lee._ Camp's duties as a production manager for Dalton were limited to those commonly associated with any employee. He simply produced a magazine—designing layouts, editing content, printing copies, etc. Unlike the _Sara Lee_ defendant, who worked as a purchasing agent, Camp did not serve his employer in the capacity of either a buyer or a seller. Nor did he serve in any alternative capacity suggesting that his employment was such that it otherwise qualified as "in or affecting commerce."

We also find no evidence of attendant circumstances to indicate that Camp's conduct was especially egregious or aggravating. Camp met with a KFI representative and raised the possibility of forming his own publishing company. He and the KFI representative later discussed having Camp's new company publish KFI's magazine, talks that ultimately culminated in an exclusive publishing agreement between Camp and KFI. However, during this period, we note that Camp also continued his best efforts to publish Dalton's final issue. That he failed to inform his employer of the ongoing negotiations and resigned after signing the KFI deal may be an unfortunate circumstance; however, in our view, such business-related conduct, without more, is neither unlawful in itself, nor aggravating or egregious enough to overcome the longstanding presumption against unfair and deceptive practices claims as between employers and employees.

As a consequence of concluding that employee Camp was without fiduciary duty, that his position was not one "in or affecting commerce," and that his business actions were neither aggravating nor egregious, we conclude that the trial court properly granted summary judgment as to employer Dalton's claim under N.C.G.S. § 75-1.1. Therefore, with regard to both appellants Camp and MCC, we reverse the Court of Appeals on this issue.

### @NCPropertyProtection2016

::: {.legalcode}

**Recovery of Damages for Exceeding the Scope of Authorized Access to Property.**

- (a) Any person who intentionally gains access to the nonpublic areas of another's premises and engages in an act that exceeds the person's authority to enter those areas is liable to the owner or operator of the premises for any damages sustained. For the purposes of this section, "nonpublic areas" shall mean those areas not accessible to or not intended to be accessed by the general public.
- (b) For the purposes of this section, an act that exceeds a person's authority to enter the nonpublic areas of another's premises is any of the following:
	- (1) An employee who enters the nonpublic areas of an employer's premises for a reason other than a bona fide intent of seeking or holding employment or doing business with the employer and thereafter without authorization captures or removes the employer's data, paper, records, or any other documents and uses the information to breach the person's duty of loyalty to the employer.
	- (2) An employee who intentionally enters the nonpublic areas of an employer's premises for a reason other than a bona fide intent of seeking or holding employment or doing business with the employer and thereafter without authorization records images or sound occurring within an employer's premises and uses the recording to breach the person's duty of loyalty to the employer.
	- (3) Knowingly or intentionally placing on the employer's premises an unattended camera or electronic surveillance device and using that device to record images or data.
	- (4) Conspiring in organized retail theft, as defined in Article 16A of Chapter 14 of the General Statutes.
	- (5) An act that substantially interferes with the ownership or possession of real property.
- (c) Any person who intentionally directs, assists, compensates, or induces another person to violate this section shall be jointly liable.
- (d) A court may award to a party who prevails in an action brought pursuant to this section one or more of the following remedies:
	- (1) Equitable relief.
	- (2) Compensatory damages as otherwise allowed by State or federal law.
	- (3) Costs and fees, including reasonable attorneys' fees.
	- (4) Exemplary damages as otherwise allowed by State or federal law in the amount of five thousand dollars ($5,000) for each day, or portion thereof, that a defendant has acted in violation of subsection (a) of this section.
- (e) Nothing in this section shall be construed to diminish the protections provided to employees under Article 21 of Chapter 95 or Article 14 of Chapter 126 of the General Statutes, nor may any party who is covered by these Articles be liable under this section.
- (f) This section shall not apply to any governmental agency or law enforcement officer engaged in a lawful investigation of the premises or the owner or operator of the premises.
- (g) Nothing in this section shall be construed to limit any other remedy available at common law or provided by the General Statutes. 

::: 

::: {.callout-note}

1\. The sponsors of N.C.G.S. § 99-A-2 explained that the purpose of the statute is to codify the holding in _Food Lion v. Capital Cities/ABC, Inc._. A lawsuit by animal rights, environmental, and whistleblower advocates challenged the statute on 1st Amendment grounds. @PeopleEthicalTreatmentAnimals_4thCir2023. In that suit, the court held that the statute is unconstitutional and enjoined its enforcement "insofar as it applies to bar protected newsgathering activities", but "reserve[d] all other applications for future case-by-case adjudication."

2\. Recall that in _Dalton v. Camp_, the North Carolina Supreme Court stated that "the federal district court in _Food Lion_ incorrectly interpreted our state case law" and held that, absent a fiduciary relationship between an employer and employee, "there is no basis for recognizing an independent tort claim for a breach of duty of loyalty". What implications does this have for claims under §§ 99-A-2(b)(1) & (2), which impose liability on employees who use information collected or recordings made without authorization "to breach the person's duty of loyalty to the employer"?

3\. § 99-A-2(e) excludes employee conduct that is protected under certain other state statutes from liability under § 99-A-2. N.C.G.S. chap. 95, art. 21 prohibits retaliation or discrimination against employees for filing claims, providing evidence, or other activity under N.C.G.S. chap. 97 (Workers' Compensation Act), N.C.G.S. chap. 95, art. 2A (Wage and Hour Act), N.C.G.S. chap 95, art. 16 (Occupational Safety and Health Act); N.C.G.S. chap. 74, art. 2A (Mine Safety and Health Act), (National Guard Reemployment Rights Act), N.C.G.S. art. 143, chap. 52 (Pesticide Board); N.C.G.S. chap. 90, art. 5F (Control of Potential Drug Paraphernalia Products); and N.C.G.S. §§ 95-28.1 & 95-28.1A (prohibiting discrimination based on certain medical traits and genetic information or testing). N.C.G.S. chap 126, art. 14 prohibits retaliation or discrimination against state employees for reporting illegal, fraudulent, or certain other improper activity by state agencies or employees. 

However, the statute does not exempt employee conduct that is protected under federal law. The National Labor Relations Act protects concerted activity by employees regarding their terms and conditions of employment. This protection may apply to unauthorized recording of workplace conditions and communications, and to sharing the information recorded with co-workers and the public. Other federal laws also sometimes protect the use of unauthorized recordings to document illegal workplace conditions or activity, for example in connection with a complaint to a federal agency with investigatory or enforcement authority, or as evidence in an employee's lawsuit. 

The NLRA generally preempts state law (criminal and civil) regulating or imposing liability for employee or employer conduct that is “arguably subject” to the NLRA.@SanDiegoBuildingTrades_US1959. This means that if an employer sues an employee or labor union for conduct that is arguably protected under Section 7, the court (state or federal) must normally dismiss the claim for lack of subject matter jurisdiction.There is an exception for claims involving matters of special state interest, such as trespassing or "conduct marked by violence and imminent threats to the public order". _Garmon_, 359 U.S. at 247. It is an unfair labor practice under § 8(a)(1) for an employer to bring such a preempted suit against an employee or union. @CanAmPlumbingIncNLRB_DCCir2003.

Consider how labor preemtion might apply to suits under N.C.G.S. § 99-A-2 against employees for workplace recording or other activity arguably protected under the NLRA. 

:::

## Non-Compete Agreements 

### @TSGFinishingLLCBollinger_NCApp2014

TSG Finishing, LLC ("plaintiff" or "TSG") appeals from an order denying its motion for a preliminary injunction aimed at preventing its former employee, Keith Bollinger ("defendant"), from breaching a non-competition and confidentiality agreement ("the non-compete agreement") and misappropriating TSG's trade secrets. On appeal, plaintiff contends that the trial court erred by denying its motion for a preliminary injunction because: (1) it has demonstrated a likelihood of success on the merits of its claims for breach of contract and misappropriation of trade secrets; and (2) it would suffer irreparable harm without issuance of the preliminary injunction.

After careful review, we reverse the trial court's order and remand with instructions to issue the preliminary injunction.

[Background]{.casesection}

TSG is in the business of fabric finishing. It has three plants in Catawba County, North Carolina. Rather than manufacturing fabrics, TSG applies chemical coatings to achieve whichever result is desired by the customer, such as coloring, stiffening, deodorizing, and abrasion resistance.

Defendant began working in the field of fabric finishing for Geltman Corporation after graduating from high school in 1982. He has no formal education beyond high school. TSG, Incorporated ("TSG, Inc.") acquired Geltman in 1992, and defendant stayed on to work for TSG, Inc. By the late 1990's, defendant was promoted to Quality Control Manager.

Defendant was responsible for assessing a customer's finishing needs and developing a finishing protocol for that customer. Defendant also helped in the creation of a "style data card" for each customer. The style data cards contained information on each step of the finishing process, such as: (1) the chemical finish compound, 70 percent of which was proprietary to TSG; (2) "cup weight" density; (3) needle punch technique; (4) type of machine needed for the needle punch technique; (5) speed of needle punch; (6) types of needles used; (7) needle punch depths; (8) method of compound application; (9) speed of compound application; (10) blade size; (11) fabric tension; and (12) temperature and type of drying required.

Defendant testified during deposition that some of these factors required trial and error to achieve a customer's desired result. For example, on one of the style data cards used to explain defendant's work-related duties during the deposition, defendant had marked a number of changes to the various factors listed and signed his initials to the changes. He testified that he changed the data entered by the customer because subsequent testing revealed different and more efficient methods to achieve the result. He also testified that the results of the trials he conducted and the knowledge he gained regarding how to achieve these results were not known outside of TSG. Michael Goldman, the Director of Operations at TSG, filed an affidavit in which he asserted that some of the customer projects that defendant worked on required over a year's worth of trial and error to achieve a customer's desired result.

TSG expends great effort to keep its customer and finishing information confidential. Specifically, it uses a code system in its communications with customers that allows the customer to identify the type of finish it wants, but does not reveal the chemicals or processes involved in creating that finish. TSG has confidentiality agreements in place with many of its customers. Third parties must sign confidentiality agreements and receive a temporary identification badge when visiting TSG's facilities. TSG's computers are password protected, with additional passwords being required to access the company's production information.

In 2007, TSG, Inc. and defendant entered into a non-disclosure and non-compete agreement. In exchange for an annual increase in compensation of $1,300.00 and a $3,500.00 signing bonus, defendant agreed not to disclose TSG, Inc.'s confidential or proprietary trade secrets and further assented to employment restrictions after his tenure at the company ended.

TSG, Inc. filed for bankruptcy in 2009. By a plan approved by the United States Bankruptcy Court on 1 May 2011, TSG, Inc. transferred its interests to plaintiff, a wholly owned operating subsidy of TSG, Inc., which remained in operation. According to defendant, every aspect of his day-to-day job remained the same after bankruptcy reorganization.

In July 2013, defendant and a direct competitor of TSG, American Custom Finishing, LLC ("ACF"), began negotiations regarding defendant's potential to leave TSG and work for ACF. According to TSG, defendant resigned from his position on 21 November 2013 and announced that he was leaving to become plant manager for ACF at a plant five miles away from TSG. Defendant claims that he gave TSG two weeks' notice on 21 November 2013 but was terminated immediately and escorted off of the premises. Defendant began working for ACF the following Monday, on 25 November 2013. During his deposition, defendant testified that TSG and ACF shared certain customers, and that defendant is responsible for performing similar customer evaluations for ACF as he did at TSG.

TSG filed suit against defendant on 16 January 2014, alleging claims for breach of contract, misappropriation of trade secrets, and unfair and deceptive practices. TSG also moved for a preliminary injunction to prevent defendant from breaching the non-compete and misappropriating TSG's trade secrets. A confidential hearing was held on plaintiff's motion, and by order entered 20 February 2014, the trial court denied the motion for preliminary injunction. Plaintiff filed timely notice of appeal.

We must first address the interlocutory nature of plaintiff's appeal. Orders granting or denying preliminary injunctions are "interlocutory and thus generally not immediately reviewable. An appeal may be proper, however, in cases, including those involving trade secrets and non-compete agreements, where the denial of the injunction deprives the appellant of a substantial right which he would lose absent review prior to final determination." 

Accordingly, because both a non-compete and the potential misappropriation of trade secrets are implicated by this case, we conclude that plaintiff has succeeded in demonstrating how a substantial right may be lost without immediate appellate review; thus, we will reach the merits of the appeal.

[Discussion]{.casesection}

[Breach of Contract]{.casesubsection}

Plaintiff next argues that the trial court erred by concluding that it failed to present a likelihood of success on the merits of its claim for breach of the non-compete. We agree.

Due to a choice of law provision in the agreement, Pennsylvania law governs enforcement of the non-compete. "Restrictive covenants are not favored in Pennsylvania and have been historically viewed as a trade restraint that prevents a former employee from earning a living." However, "restrictive covenants are enforceable if they are incident to an employment relationship between the parties; the restrictions imposed by the covenant are reasonably necessary for the protection of the employer; and the restrictions imposed are reasonably limited in duration and geographic extent." Thus, in assessing whether to enforce a non-compete agreement, Pennsylvania law requires the court to balance "the employer's protectable business interests against the interest of the employee in earning a living in his or her chosen profession, trade or occupation, and then balancee the result against the interest of the public.

We believe that the restrictions imposed in the non-compete are reasonable. Under Pennsylvania law, the burden is on the employee to show how a non-compete is unreasonable in order to prevent its enforcement. The non-compete provided that upon termination, defendant would be prevented from participating in the field of "textile finishing" for two years in the prohibited territory, which was defined, in part, as all of North America. Specifically, the non-compete prevents defendant from:

> Engaging, as an employee or contractor, in the performance of Textile Finishing, engaging in the manufacture of Textile Finishing machinery or equipment, including but not limited to a jobber, reseller, or dealers of used textile machinery or equipment or engaging in sales, marketing or managerial services for any individual or entity that competes with TSG directly or indirectly within the Prohibited Territory.

In contrast to unenforceable non-competes restricting "any work" competitive to the employer, the non-compete here permissibly restricts defendant from engaging in the specific industrial practices that could harm the legitimate business interests TSG seeks to protect.

Furthermore, defendant has failed to carry his burden of demonstrating that the time and geographic restrictions are unreasonable and render the non-compete unenforceable. Pennsylvania courts have consistently enforced non-compete agreements restricting employment for two or more years. Additionally, Pennsylvania courts have established a correlation between reasonableness of a geographic restriction and the employer's verifiable market. Specifically, Pennsylvania federal courts have upheld covenants restricting competition nationwide or throughout the region of North America, where appropriate. TSG presented evidence that it serves customers throughout at least 38 states, in addition to Canada and Mexico. Defendant claims that TSG failed to explain how the geographic restrictions are reasonable, and also argues that the cases TSG cites in support of the time restriction are inapposite. However, the burden is not on TSG to establish that the restrictions in the non-compete are reasonable; rather, the burden rests with defendant to show that they are unreasonable and that the contract he signed is unenforceable. Defendant has failed to carry that burden here.

Finally, we turn to the trial court's determination that the equities weighed against enforcing the non-compete. "Fundamental to any enforcement determination is the threshold assessment that there is a legitimate interest of the employer to be protected as a condition precedent to the validity of a covenant not to compete." "Generally, interests that can be protected through covenants include trade secrets, confidential information, good will, and unique or extraordinary skills." "The issue of enforceability is one to be determined on a case-by-case basis," wherein the Court is to consider all relevant facts and circumstances.

Among the important factors that Pennsylvania courts consider in assessing the enforceability of a non-compete are: (1) the circumstance under which the employment relationship was terminated; (2) the employee's skills and capacity; (3) the length of time of the previous employment; (4) the type of consideration paid to the employee; (5) the effect of restraint on the employee's life; and (6) circumstantial economic conditions.

> It bears noting that there is a significant factual distinction between the hardship imposed by the enforcement of a restrictive covenant on an employee who voluntarily leaves his employer and that imposed upon an employee who is terminated for failing to do his job. The salesman discharged for poor sales performance cannot reasonably be perceived to pose the same competitive threat to his employer's business interests as the salesman whose performance is not questioned, but who voluntarily resigns to join another business in direct competition with the employer. Only when the novice has developed a certain expertise, which could possibly injure the employer if unleashed competitively, will the employer begin to think in terms of a restrictive covenant.

Based on the record before us, we believe that these notions weigh in favor of enforcement of the non-compete. Defendant worked at TSG for 27 years and became one of its most trusted and skilled managers. Throughout his tenure he developed valuable expertise in the field of textile finishing through trial-and-error and industrial experimentation that was highly guarded by TSG and not known throughout the industry. In exchange for his assent to the non-compete, defendant was offered an annual increase of $1,300.00 to his regular salary and a signing bonus of $3,500.00; defendant considered TSG's offer for at least two weeks before eventually agreeing to the non-compete and accepting this increase in compensation. Rather than being terminated for poor work, defendant was specifically recruited and voluntarily left TSG to work for a direct competitor at a plant five miles away without giving prior notice or asking for a raise from TSG. ACF did not require defendant to provide a resume or interview for the position; defendant was hired after meeting with an ACF representative one time. Given that defendant possessed advanced expertise in the field of textile finishing and abruptly and voluntarily left his position at TSG after 27 years of service to work for a direct competitor, we find that he poses a significant competitive threat to TSG's legitimate business interests should the non-compete be unenforceable.

Despite these factors, defendant argues, and the trial court agreed, that enforcement of the non-compete essentially renders him unemployable for two years because he has "no experience outside of textile finishing, rudimentary computer skills, and no college education." We are unpersuaded. Defendant argued in his brief that ACF hired him for "his management skills in dealing with employees, human resources issues, equipment dealers, customer complaints and suppliers, not for any trade secrets or other confidential information which he might know from his time at TSG." Skill in management and human resources is desirable in many fields, not just textile finishing. Although the non-compete does restrict defendant from working as an employee for any company that competes with TSG "in sales, marketing or managerial services," TSG's competitors only comprise a small subset of companies and industries where such skills are valuable. Defendant admitted that before leaving TSG for ACF, he did not look for other employment. TSG presented evidence of multiple job openings within 25 miles of Hickory, N.C., that were not competitive to TSG and listed experience in plant management and manufacturing as desirable traits. Therefore, we disagree with the trial court's conclusion that enforcement of the non-compete would effectively prevent defendant from attaining employment anywhere in North America.

We also find TSG's policy arguments in this case persuasive. TSG employs around 160 people. According to Rosenstein, the customers that defendant now serves at ACF could account for up to forty percent of TSG's business, and some of the customer relationships that TSG has had for many years are now "strained" due to defendant's transition from TSG to ACF. In weighing the equities, we are permitted to consider the effect that breach of a non-compete may have on an employer's protectable business interests. Among these, we consider the potential harm done to other TSG employees should defendant be permitted to retain employment at ACF in contravention of the non-compete. The significant risk that defendant's actions pose to TSG's competitive advantage indirectly threaten the job security of many others who work for TSG. Thus, in balance, we find that the equities favor enforcement of the non-compete.

In sum, we hold that the non-compete was validly assigned to plaintiff through bankruptcy reorganization, the non-compete itself is reasonable to protect TSG's legitimate business interests, and the equities weigh in favor of enforcement under these facts. Therefore, because it is undisputed that defendant is in breach of the non-compete by working for ACF, a direct competitor of TSG, we hold that TSG has demonstrated a likelihood of success on the merits of its claim for breach of contract.

### @ContractsRestraintTrade_nd

::: {.legalcode}

#### § 16600

- (a) Except as provided in this chapter, every contract by which anyone is restrained from engaging in a lawful profession, trade, or business of any kind is to that extent void.
- (b) (1) This section shall be read broadly, in accordance with [_Edwards v. Arthur Andersen LLP_](https://scholar.google.com/scholar_case?case=969445912817466674) (2008) 44 Cal.4th 937, to void the application of any noncompete agreement in an employment context, or any noncompete clause in an employment contract, no matter how narrowly tailored, that does not satisfy an exception in this chapter.
	- (2) This subdivision does not constitute a change in, but is declaratory of, existing law.
- (c) This section shall not be limited to contracts where the person being restrained from engaging in a lawful profession, trade, or business is a party to the contract.

#### § 16600.1

- (a) It shall be unlawful to include a noncompete clause in an employment contract, or to require an employee to enter a noncompete agreement, that does not satisfy an exception in this chapter.
- (b) (1) For current employees, and for former employees who were employed after January 1, 2022, whose contracts include a noncompete clause, or who were required to enter a noncompete agreement, that does not satisfy an exception to this chapter, the employer shall, by February 14, 2024, notify the employee that the noncompete clause or noncompete agreement is void.
	- (2) Notice made under this subdivision shall be in the form of a written individualized communication to the employee or former employee, and shall be delivered to the last known address and the email address of the employee or former employee.
- (c) A violation of this section constitutes an act of unfair competition within the meaning of [Chapter 5](https://leginfo.legislature.ca.gov/faces/codes_displayText.xhtml?lawCode=BPC&division=7.&title=&part=2.&chapter=5.&article=) (commencing with Section 17200).

#### § 16600.5

- (a) Any contract that is void under this chapter is unenforceable regardless of where and when the contract was signed.
- (b) An employer or former employer shall not attempt to enforce a contract that is void under this chapter regardless of whether the contract was signed and the employment was maintained outside of California.
- (c) An employer shall not enter into a contract with an employee or prospective employee that includes a provision that is void under this chapter.
- (d) An employer that enters into a contract that is void under this chapter or attempts to enforce a contract that is void under this chapter commits a civil violation.
- (e) (1) An employee, former employee, or prospective employee may bring a private action to enforce this chapter for injunctive relief or the recovery of actual damages, or both.
	- (2) In addition to the remedies described in paragraph (1), a prevailing employee, former employee, or prospective employee in an action based on a violation of this chapter shall be entitled to recover reasonable attorney’s fees and costs.

:::

### @MassachusettsNoncompetitionAgreement_nd

::: {.legalcode}

- (a) As used in this section, the following words shall have the following meanings:-
- "Business entity", any person or group of persons performing or engaging in any activity, enterprise, profession or occupation for gain, benefit, advantage or livelihood, whether for profit or not for profit, including but not limited to corporations, limited liability companies, limited partnerships or limited liability partnerships.
- "Employee", an individual who is considered an employee under section 148B of this chapter; provided, however, that the term "employee", as used in this section, shall also include independent contractors under section 148B.
- "Forfeiture agreement", an agreement that imposes adverse financial consequences on a former employee as a result of the termination of an employment relationship, regardless of whether the employee engages in competitive activities following cessation of the employment relationship. Forfeiture agreements do not include forfeiture for competition agreements.
- "Forfeiture for competition agreement", an agreement that by its terms or through the manner in which it is enforced imposes adverse financial consequences on a former employee as a result of the termination of an employment relationship if the employee engages in competitive activities.
- "Garden leave clause", a provision within a noncompetition agreement by which an employer agrees to pay the employee during the restricted period, provided that such provision shall become effective upon termination of employment unless the restriction upon post-employment activities are waived by the employer or ineffective under subsection (c)(iii).
- "Noncompetition agreement", an agreement between an employer and an employee, or otherwise arising out of an existing or anticipated employment relationship, under which the employee or expected employee agrees that he or she will not engage in certain specified activities competitive with his or her employer after the employment relationship has ended. Noncompetition agreements include forfeiture for competition agreements, but do not include: (i) covenants not to solicit or hire employees of the employer; (ii) covenants not to solicit or transact business with customers, clients, or vendors of the employer; (iii) noncompetition agreements made in connection with the sale of a business entity or substantially all of the operating assets of a business entity or partnership, or otherwise disposing of the ownership interest of a business entity or partnership, or division or subsidiary thereof, when the party restricted by the noncompetition agreement is a significant owner of, or member or partner in, the business entity who will receive significant consideration or benefit from the sale or disposal; (iv) noncompetition agreements outside of an employment relationship; (v) forfeiture agreements; (vi) nondisclosure or confidentiality agreements; (vii) invention assignment agreements; (viii) garden leave clauses; (ix) noncompetition agreements made in connection with the cessation of or separation from employment if the employee is expressly given seven business days to rescind acceptance; or (x) agreements by which an employee agrees to not reapply for employment to the same employer after termination of the employee.
- "Restricted period", the period of time after the date of cessation of employment during which an employee is restricted by a noncompetition agreement from engaging in activities competitive with his or her employer.
- (b) To be valid and enforceable, a noncompetition agreement must meet the minimum requirements of paragraphs (i) through (viii).
	- (i) If the agreement is entered into in connection with the commencement of employment, it must be in writing and signed by both the employer and employee and expressly state that the employee has the right to consult with counsel prior to signing. The agreement must be provided to the employee by the earlier of a formal offer of employment or 10 business days before the commencement of the employee's employment.
	- (ii) If the agreement is entered into after commencement of employment but not in connection with the separation from employment, it must be supported by fair and reasonable consideration independent from the continuation of employment, and notice of the agreement must be provided at least 10 business days before the agreement is to be effective. Moreover, the agreement must be in writing and signed by both the employer and employee and expressly state that the employee has the right to consult with counsel prior to signing.
	- (iii) The agreement must be no broader than necessary to protect one or more of the following legitimate business interests of the employer: (A) the employer's trade secrets; (B) the employer's confidential information that otherwise would not qualify as a trade secret; or (C) the employer's goodwill. A noncompetition agreement may be presumed necessary where the legitimate business interest cannot be adequately protected through an alternative restrictive covenant, including but not limited to a non-solicitation agreement or a non-disclosure or confidentiality agreement.
	- (iv) In no event may the stated restricted period exceed 12 months from the date of cessation of employment, unless the employee has breached his or her fiduciary duty to the employer or the employee has unlawfully taken, physically or electronically, property belonging to the employer, in which case the duration may not exceed 2 years from the date of cessation of employment.
	- (v) The agreement must be reasonable in geographic reach in relation to the interests protected. A geographic reach that is limited to only the geographic areas in which the employee, during any time within the last 2 years of employment, provided services or had a material presence or influence is presumptively reasonable.
	- (vi) The agreement must be reasonable in the scope of proscribed activities in relation to the interests protected. A restriction on activities that protects a legitimate business interest and is limited to only the specific types of services provided by the employee at any time during the last 2 years of employment is presumptively reasonable.
	- (vii) The noncompetition agreement shall be supported by a garden leave clause or other mutually-agreed upon consideration between the employer and the employee, provided that such consideration is specified in the noncompetition agreement. To constitute a garden leave clause within the meaning of this section, the agreement must (i) provide for the payment, consistent with the requirements for the payment of wages under section 148 of chapter 149 of the general laws, on a pro-rata basis during the entirety of the restricted period, of at least 50 percent of the employee's highest annualized base salary paid by the employer within the 2 years preceding the employee's termination; and (ii) except in the event of a breach by the employee, not permit an employer to unilaterally discontinue or otherwise fail or refuse to make the payments; provided, however, if the restricted period has been increased beyond 12 months as a result of the employee's breach of a fiduciary duty to the employer or the employee has unlawfully taken, physically or electronically, property belonging to the employer, the employer shall not be required to provide payments to the employee during the extension of the restricted period.
	- (viii) The agreement must be consonant with public policy.
- (c) A noncompetition agreement shall not be enforceable against the following types of workers: (i) an employee who is classified as nonexempt under the Fair Labor Standards Act, 29 U.S.C. 201-219; (ii) undergraduate or graduate students that partake in an internship or otherwise enter a short-term employment relationship with an employer, whether paid or unpaid, while enrolled in a full-time or part-time undergraduate or graduate educational institution; (iii) employees that have been terminated without cause or laid off; or (iv) employees age 18 or younger. This section does not render void or unenforceable the remainder of the contract or agreement containing the unenforceable noncompetition agreement, nor does it preclude the imposition of a noncompetition restriction by a court, whether through preliminary or permanent injunctive relief or otherwise, as a remedy for a breach of another agreement or a statutory or common law duty.
- (d) A court may, in its discretion, reform or otherwise revise a noncompetition agreement so as to render it valid and enforceable to the extent necessary to protect the applicable legitimate business interests.
- (e) No choice of law provision that would have the effect of avoiding the requirements of this section will be enforceable if the employee is, and has been for at least 30 days immediately preceding his or her cessation of employment, a resident of or employed in Massachusetts at the time of his or her termination of employment.
- (f) All civil actions relating to employee noncompetition agreements subject to this section shall be brought in the county where the employee resides or, if mutually agreed upon by the employer and employee, in Suffolk county; provided that, in any such action brought in Suffolk county, the superior court or the business litigation session of the superior court shall have exclusive jurisdiction.

:::

### @DraftkingsIncHermalyn_1stCir2024

Massachusetts and California aren't exactly on the same page when it comes to noncompete agreements.

Massachusetts generally _allows_ noncompetes if they comply with certain restrictions (for example, employers can't require all employees to sign them (excluded employees include persons aged 18 or younger) and the noncompete period can't last more than a year (except if the employee breached a fiduciary duty to the employer or stole the employer's property, in which case a 2-year cap applies)). _See, e.g._, Mass. Gen. Laws ch. 149, § 24L(b)(iv), (c). California generally _bans_ noncompetes unless they squeeze within one of the few narrow exceptions (like for noncompetes in a business sale or a partnership breakup). _See, e.g._, Cal. Bus. & Prof. Code §§ 16600(a), 16601, 16602. And that's true "regardless of where and when the contract was signed" and "whether ... the employment was maintained outside of California." See id. § 16600.5(a), (b).

Today's case plays out against the backdrop of these different policy choices. We streamline the facts and procedural history (rather aggressively) to lay bare the nature of the disputes before us, adding more details later as needed for specific issues (an example of streamlining is our ignoring a California state-court lawsuit involving some of the same parties as here, because that suit doesn't affect our analysis).

As recently as the beginning of this year, then-New Jersey resident Michael Hermalyn had a plum job with Massachusetts-headquartered DraftKings. But he quit to take a similar job with rival Fanatics's California-based subsidiary, a position (he says) that requires him to live and work in Los Angeles. DraftKings and Fanatics (for anyone who hasn't seen their ads) are sports betting and online gaming companies (a description that simplifies things a bit but is enough for now).

DraftKings thought (among other concerns) that Hermalyn's new post violated a noncompete he had signed before quitting—an agreement that had a Massachusetts choice-of-law proviso and a one-year noncompete clause. So DraftKings sued him in Massachusetts federal court for breach of the noncompete (along with other claims not relevant here).

Everyone seems to agree (at least for present purposes) that if the noncompete is enforceable, Hermalyn breached it by joining Fanatics. Not surprisingly then, DraftKings asked the district judge to use Massachusetts law and Hermalyn asked her to use California law. Siding with DraftKings, the judge—after using Massachusetts law—ruled the noncompete enforceable and preliminarily enjoined Hermalyn from competing against DraftKings in the United States for one year (she did reject DraftKings's request for a worldwide injunction, however).

Hermalyn then filed this interlocutory appeal, making two alternative arguments. The first is that the judge wrongly held that Massachusetts law governed the enforceability of the noncompete. The second is that if Massachusetts law does govern, then the judge should've excluded California from the preliminary injunction's scope.

[Choice of Law]{.casesection}

[Massachusetts Law]{.casesubsection}

Because—as the parties agree—diversity jurisdiction exists over the breach-of-noncompete claim, the "forum" of Massachusetts (where DraftKings sued Hermalyn) sets the rules for which state's law decides the noncompete's enforceability (even though the noncompete itself picked Massachusetts). So on to Bay State law then.

Massachusetts usually respects the parties' choice of law. But exceptions exist, each driven by public-policy concerns (the term "usually" in the last sentence was a tipoff about exceptions). And the exception Hermalyn invokes requires him to show that (i) "application of" Massachusetts law "would be contrary to a fundamental policy of" California; (ii) California "has a materially greater interest than" Massachusetts "in the determination of the . . . issue"; and (iii) California is the state whose law would control "in the absence of an effective choice of law by the parties"—_i.e.,_ that California has "the most significant relationship to the transaction and the parties."

The word linking the above-listed requisites is "and," _not_ "or." Which means Hermalyn must satisfy _all_ of them to get anywhere. But he can't satisfy the materially-greater-interest requisite (as we explain next), thus dashing his hopes of winning the issue (even assuming _without deciding_ that he could satisfy the others). 

[Arguments and Analysis]{.casesubsection}

The centerpiece of Hermalyn's argument is that Oxford—an opinion by the Massachusetts Supreme Judicial Court ("SJC")—makes the materially-greater-interest issue open-and-shut in _his_ favor. That's because, he continues, Oxford held that a Massachusetts choice-of-law clause there couldn't "survive" since California's interest in not enforcing the contract—a "Confidentiality, Non-Solicitation and Non-Competition Agreement,"—_was_ "materially greater" than Massachusetts's interest in enforcing it. And applying Oxford evenhandedly, he submits, entitles him to a victory here.

Unfortunately for Hermalyn, Oxford can't do the work that he asks of it.

In pressing his Oxford-centric arguments, Hermalyn mentions how "California" is "where he currently resides, works, and allegedly breached the non-compete covenant." But Oxford held that "California had a materially greater interest than Massachusetts" there "_because_" the employee Hernandez had "executed" _and_ "performed" the contract with his Massachusetts-based former employer Oxford "in California," _and_ had "allegedly committed a breach of the agreement in California" after he quit and joined a California competitor—Hernandez (you see) lived and worked in California before and after he "allegedly violated" the agreement's "nonsolicitation and confidentiality provisions." Plus Oxford also noted that the "subject matter of the contract—_Hernandez's employment with Oxford_—had been located _exclusively_ in California." Hermalyn's facts are not like Hernandez's. According to what the judge here found—and we see no convincingly developed argument contesting her findings as reversible error—(i) while "Hermalyn primarily worked for Massachusetts-headquartered DraftKings from New Jersey and New York, he traveled to Massachusetts for work at least 25 times" during a 2½-year stretch before leaving for Fanatics—which roughly comes to "once every 6 weeks"; (ii) "Hermalyn does not contend, nor is there evidence, that he performed any of his work responsibilities for DraftKings from California"; and (iii) "any harms flowing from Hermalyn's likely" noncompete breach "will be felt by DraftKings in Massachusetts, not California." Given the dissimilarities between Oxford and our case, Hermalyn's Oxford-based arguments sputter out.

Hermalyn is right about one thing, however. Oxford did say that California's "legislatively" declared "policy" interest "in favor of open competition and employee mobility" was "materially greater" than Massachusetts's—a state, Oxford added, that lacked a "statute akin" to California's. But "a paradigm shift" occurred when Massachusetts passed a law—the Massachusetts Noncompetition Agreement Act ("MNAA")—that "dramatically reduced the number of Massachusetts employees who can be subjected to ... enforceable" noncompetes, while giving those exposed to them "stronger substantive and procedural protections than in the past" and also "limiting" employers "to substantially reduced post-employment restrictions."

The MNAA was no off-the-cuff, spur-of-the-moment bit of legislating either. Far from it. The law "gestated" during a _decade's_ worth of legislative study and debate. See id. Interestingly—and we think tellingly—a Massachusetts legislator actually "proposed a bill to _completely ban_" noncompetes back "in 2009," a bill "modeled" after "_California_" law. Concerned Bay State business leaders then stressed how "essential" noncompetes are "for protecting the ideas that they had developed through great effort." And they "promised to leave the state if his legislation passed." That bill ultimately went nowhere, however. But after years and _years_ of legislative give-and-take, "a _hard fought compromise_" emerged that "banned" noncompetes "for lower level workers, limited them for higher level workers, and provided procedural protections to assure that workers know what they are getting into when they sign them."

The MNAA became law in August 2018, just days before the SJC's September 2018 Oxford ruling. But the MNAA applies only to noncompetes "entered into on or after _October 1, 2018._" Which explains why Oxford never even hinted that the MNAA played _any_ role there. And which also shows that Oxford had in mind the state of law _before_ the MNAA when it talked about California's interest being "materially greater" than Massachusetts's—_not_ the state of the law _after_ the MNAA.

Perhaps anticipating some of these points, Hermalyn notes that Oxford "predates" California's 2024 passage of laws reinforcing its deep-rooted policy against restraint of trade. But the fact still remains that Oxford—which (as we said) acknowledged California's "_settled_ legislative policy" of promoting "open competition and employee mobility"—ran the materially-greater-interest analysis _without_ having to factor in the MNAA (because (again) the MNAA wasn't in play there).

Still looking for a winning argument, Hermalyn writes that "the MNAA did not purport to abrogate Massachusetts law as discussed and understood in Oxford," quoting for support this snippet from the Massachusetts Law Review article mentioned above: the MNAA "codified aspects of the common law that will continue to require case-by-case exposition." Hermalyn's point seems to be that the MNAA didn't change Bay State "law or policy of limited tolerance towards non-compete covenants." But the article's animating thesis—revealed in the following excerpts (we quoted some of them a few paragraphs back)—couldn't be any clearer: the MNAA "represents a _paradigm shift_ in _favor_ of _employees_" that "dramatically reduced the number of Massachusetts employees who can be subjected to ... enforceable" noncompetes, while offering those covered by them "stronger substantive and procedural protections than in the past" and likewise "limiting" employers "to substantially reduced post-employment restrictions." Which scotches Hermalyn's attempt to downplay the MNAA's significance.

Given this tableau—involving (among other features) two states passing laws reflecting different but careful balances of conflicting forces in the noncompete area (after the usual push-and-pull of politics), with Massachusetts opting _not_ to mimic California's ban and instead generally allowing noncompetes for higher-level employees like Hermalyn (who unlike lower-level employees often have business-sensitive info and deep ties with company customers)—we can't say that Hermalyn has shown (as he was required to do) that California's "interest" in pursuing its policy is not just "greater" than Massachusetts's, but is "materially" so. Or to put it differently but with the same result, he hasn't shown that "California's public policy" eclipses "the parties' clear and unambiguous agreement to apply Massachusetts law."

::: {.callout-note}

**Federal Agency Regulation of Non-Compete Agreements**

In 2023, the NLRB General Counsel issued a Memorandum declaring that non-compete "agreements interfere with employees' exercise of rights under Section 7 of the National Labor Relations Act" and that, "[e]xcept in limited circumstances, ... the proffer, maintenance, and enforcement of such agreements violate Section 8(a)(1) of the Act." [Memorandum GC 23-08](../exhibits/GC-23-08.pdf), (May 30, 2023). In February 2025, the new Acting General Counsel rescinded that Memorandum (among many others). [Memorandum GC 25-05](../exhibits/GC-25-05.pdf) (February 14, 2025). 

In 2024, the Federal Trade Commission published a [final rule](https://www.federalregister.gov/documents/2024/05/07/2024-09171/non-compete-clause-rule) prohibiting most non-compete provisions as "unfair methods of competition" under Section 5 of the FTC Act, 15 U.S.C. § 45(a). In [Ryan, LLC v. FTC](https://scholar.google.com/scholar_case?case=7255993935182189521), Civil Action No. 3:24-CV-00986-E (N.D. Tex. Aug. 20, 2024) and Properties of the Villages v. FTC, Case No. 5:24-cv-316-TJC-PRL (M.D. Fla. Aug. 15, 2024), the courts held that the FTC lacked the statutory authority to issue the rule and blocked its enforcement. In September 2025, the FTC voluntarily dismissed its appeals of those two decisions and agreed to vacate the Non-Compete Rule. [Federal Trade Commission Files to Accede to Vacatur of Non-Compete Clause Rule](https://www.ftc.gov/news-events/news/press-releases/2025/09/federal-trade-commission-files-accede-vacatur-non-compete-clause-rule) (FTC Sept. 9, 2025). 

:::